hack/devtools/deploy-shared-env.sh, pkg/deploy/assets/aks-development.json
Brings the ARM template in line with the changes made in the AKS EV2 production deploy pipeline.
1. Assign the required permissions for the MDSD pods to fetch their certificate from the service keyvault.
1. Assign the required MSI access for fetching kubeconfig on-the-fly.
1. Lower the number of nodes in the cluster to 2 to save resources.
1. Sync the Kubernetes version.
1. Change the AKS network address allocation to match production.
1. Add the Ev2 Shell Containers subnet, so that we can test container deployments like they would run in production.
1. Remove the *-aks Keyvault that we don't have in Production.
Tested by manually creating AKS clusters in the dev environment.
No.
=> Sync AKS Dev deployment with production

pkg/frontend/frontend.go, pkg/frontend/openshiftcluster_delete.go, pkg/frontend/openshiftcluster_get.go, pkg/frontend/openshiftcluster_putorpatch.go
Fixes https://issues.redhat.com/browse/ARO-1899
Added frontendResultLog for enrichment
Currently frontend logs do not give out much information for QoS. The returned frontend response says "sent response" with not much detail if there was an error, and if there is, it's just an error code. This PR creates a separate result log that will look similar to the one created for backend. It sends a message stating "Succeeded" or "Failed", and marks it as a QoS log. It also sends the error information as well as the operation type being done from the http request method. For now, this is only being used on openshiftcluster put/patch, get, and delete. Potentially other places in the future. With these changes, we can easily measure the health by checking what's succeeding and what's failing.
=> logs added for frontend enrichment

.dockerignore
Fixes https://redhat-internal.slack.com/archives/C03F6AA3HDH/p1673556523236649?thread_ts=1673462743.994619&cid=C03F6AA3HDH
Found another `.dockerignore` pattern that's removing files that are in the git repo; this causes container builds to have a `-dirty` version tag.
=> dockerignore: remove /env* files since they're in the git repo

docs/deploy-development-rp.md, pkg/frontend/admin_openshiftcluster_stopvm.go, pkg/frontend/admin_openshiftcluster_stopvm_test.go, pkg/frontend/adminactions/azureactions.go, pkg/util/azureclient/mgmt/compute/virtualmachines_addons.go, pkg/util/mocks/adminactions/adminactions.go, pkg/util/mocks/azureclient/mgmt/compute/compute.go
Fixes: https://issues.redhat.com/browse/ARO-1884
Covers circumstances where a Virtual machine has to be stop-deallocated and started again in order to be deployed on next generation hardware in Azure.
1. Deploy a test cluster.
2. Login to the OpenShift cluster's console.
3. Open Azure Portal to watch VM status.
4. Select a master node and perform the steps below
```bash
make runlocal-rp
curl -X POST -k "https://localhost:8443/admin/subscriptions/$SUB_ID/resourceGroups/$RG/providers/Microsoft.RedHatOpenShift/openShiftClusters/$CLUSTER/stoptvm?vmName=$VMNAME&deallocateVM=true" --header "Content-Type: application/json" -d "{}"
```
You will see the VM goes into a Stopped (deallocated) state.
Start the VM once again and watch status in Azure Portal as well as the OpenShift console.
```bash …
```
=> Optionally deallocate a VM after performing a graceful stop VM action

cmd/aro/operator.go, pkg/operator/controllers/checkers/clusterdnschecker/controller.go, pkg/operator/controllers/checkers/clusterdnschecker/controller_test.go, pkg/operator/controllers/checkers/ingresscertificatechecker/controller.go, pkg/operator/controllers/checkers/ingresscertificatechecker/controller_test.go, pkg/operator/controllers/checkers/internetchecker/controller.go, pkg/operator/controllers/checkers/internetchecker/controller_test.go, pkg/operator/controllers/checkers/serviceprincipalchecker/controller.go, pkg/operator/controllers/checkers/serviceprincipalchecker/controller_test.go, pkg/operator/controllers/genevalogging/genevalogging_test.go, pkg/operator/controllers/machine/machine_controller.go, pkg/operator/controllers/machine/machine_controller_test.go, pkg/util/conditions/condition.go, pkg/util/conditions/condition_test.go
Operator is not longer dependant on a version client for ARO objects and is now using a split client.
This continues the rafactoring started in #2605
=> Removes dependency on a versioned ARO client from the operator

pkg/dbtoken/refresher.go
Fixes https://issues.redhat.com/browse/ARO-1714
Removes existing unused Gateway db token timestamp metric. Adds new heartbeat type metric for token refresh monitoring. This will allow us to create a monitor that detects lapses in token refresh.
Check that the new metric is correctly emitted.
No
=> added token refresh heartbeat. removed lastrefresh

cmd/aro/operator.go, pkg/operator/controllers/alertwebhook/alertwebhook_controller.go, pkg/operator/controllers/autosizednodes/autosizednodes_controller.go, pkg/operator/controllers/banner/banner_controller.go, pkg/operator/controllers/checkers/clusterdnschecker/controller.go, pkg/operator/controllers/checkers/ingresscertificatechecker/controller.go, pkg/operator/controllers/checkers/internetchecker/controller.go, pkg/operator/controllers/checkers/serviceprincipalchecker/controller.go, pkg/operator/controllers/clusteroperatoraro/clusteroperatoraro_controller.go, pkg/operator/controllers/dnsmasq/cluster_controller.go, pkg/operator/controllers/dnsmasq/machineconfig_controller.go, pkg/operator/controllers/dnsmasq/machineconfigpool_controller.go, pkg/operator/controllers/genevalogging/genevalogging_controller.go, pkg/operator/controllers/imageconfig/image_controller.go, pkg/operator/controllers/ingress/ingress_controller.go, pkg/operator/controllers/machine/machine_controller.go, pkg/operator/controllers/machinehealthcheck/machinehealthcheck_controller.go, pkg/operator/controllers/machineset/machineset_controller.go, pkg/operator/controllers/monitoring/monitoring_controller.go, pkg/operator/controllers/muo/muo_controller.go, pkg/operator/controllers/node/node_controller.go, pkg/operator/controllers/previewfeature/previewfeature_controller.go, pkg/operator/controllers/pullsecret/pullsecret_controller.go, pkg/operator/controllers/rbac/rbac_controller.go, pkg/operator/controllers/routefix/routefix_controller.go, pkg/operator/controllers/storageaccounts/storageaccount_controller.go, pkg/operator/controllers/subnets/subnets_controller.go, pkg/operator/controllers/workaround/workaround_controller.go
Follow up for https://github.com/Azure/ARO-RP/pull/2605#discussion_r1062897865
Makes injection of the controller-runtime explicit. Previous implicit behaviour described [here](https://github.com/Azure/ARO-RP/pull/2605#discussion_r1062897865).
Will help with refactoring of some of the controllers where we need a client in a constructor (so we can pass to other constructors).
=> Makes split client injection explicit

cmd/aro/operator.go, hack/gendiscoverycache/main.go, pkg/cluster/removeprivatednszone.go, pkg/operator/controllers/checkers/ingresscertificatechecker/checker.go, pkg/operator/controllers/checkers/ingresscertificatechecker/checker_test.go, pkg/operator/controllers/checkers/ingresscertificatechecker/controller.go, pkg/operator/controllers/clusteroperatoraro/clusteroperatoraro_controller.go, pkg/operator/controllers/imageconfig/image_controller.go, pkg/operator/controllers/imageconfig/image_controller_test.go, pkg/operator/controllers/routefix/routefix_controller.go, pkg/operator/controllers/workaround/workaround_controller.go, pkg/operator/controllers/workaround/workaround_controller_test.go, pkg/util/version/clusterversion.go
#2641 needs to be merged first
Operator is not longer dependant on a version config client and is now using a split client.
=> Removes dependency on a versioned config client from the operator

hack/portalauth/portalauth.go, pkg/portal/middleware/aad.go, pkg/portal/middleware/aad_test.go, pkg/portal/security_test.go, test/e2e/setup.go
simplifies the session timeout process. Instead of storing a whole struct into the session cookies, now only store an integer which avoids to use `gob` and sending whole struct in cookies
=> aad session expiration simplification

cmd/aro/operator.go, pkg/operator/controllers/checkers/clusterdnschecker/checker.go, pkg/operator/controllers/checkers/clusterdnschecker/checker_test.go, pkg/operator/controllers/checkers/clusterdnschecker/controller.go, pkg/operator/controllers/checkers/ingresscertificatechecker/checker.go, pkg/operator/controllers/checkers/ingresscertificatechecker/checker_test.go, pkg/operator/controllers/checkers/ingresscertificatechecker/controller.go, pkg/operator/controllers/ingress/ingress_controller.go, pkg/operator/controllers/ingress/ingress_controller_test.go
Operator is not longer dependant on a version config client and is now using a split client.
=> Removes dependency on a versioned operator client

test/e2e/adminapi_cluster_get.go, test/e2e/adminapi_cluster_getlogs.go, test/e2e/adminapi_cluster_list.go, test/e2e/adminapi_cluster_update.go, test/e2e/adminapi_csr.go, test/e2e/adminapi_drainnode.go, test/e2e/adminapi_kubernetesobjects.go, test/e2e/adminapi_redeployvm.go, test/e2e/adminapi_resources.go, test/e2e/hive.go, test/e2e/setup.go
https://issues.redhat.com/browse/ARO-1602
This PR adds new e2e tests that run only when the test cluster is managed by Hive. The tests attempt to validate that the installation/adoption of the test cluster went as expected by comparing some data values stored in the test cluster's corresponding `ClusterDeployment` object (retrieved from the AKS/Hive cluster) to the expected values (the values that the RP would have set at the time that it told Hive to install/adopt the cluster).
I ran the new e2e test locally using my dev RP instance. When using a test cluster created by Hive, the new tests all pass. When using a test cluster *not* created by Hive, the tests are skipped (the desired behavior).
Not to my knowledge, but please let me know if there is any documentation I'll need to update.
I …
=> e2e test for Hive-managed ARO clusters

pkg/operator/controllers/machinehealthcheck/staticresources/machinehealthcheck.yaml
https://issues.redhat.com/browse/ARO-1814
Fixes
Added a new field to the file: `pkg/operator/controllers/machinehealthcheck/staticresources/machinehealthcheck.yaml `- 
`nodeStartupTimeout: "20m"` - to specify the timeout duration that a machine health check must wait for a node to join the cluster before a machine is determined to be unhealthy.
The current issue is that the alert is received, then it gets auto-mitigated at some point and SREs don't really take any action on it. So trying to reduce the number of auto-mitigating alerts
Will monitor how frequently the auto-mitigating alerts are being generated after the change and whether it is affecting other MHC alert scenarios
Yes, past three months MHC alert data is uploaded in the Jira ticket mentioned above.
=> Increase nodeStartupTimeout for the Machine Health Check

test/e2e/operator.go
Fixes [Implement an E2E test confirming that MUO deployment gets recreated by ARO operator in case of deletion](https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/15689363)
ARO operator reconciles MUO deployment on customer clusters and must restore MUO resources in case of deletion.
We already have a test that proves that MUO is deployed by default on the customer clusters, but no test that proves that the deployment is being reconciled. So the task is to create that last missing test.
Created the new E2E test (the task is itself to write an E2E test).
N/A
=> add MUO reconciliation E2E test

pkg/util/cluster/cluster.go
Since the introduction of aks-vnet and dev-vpn-vnet. Dev-vnet has /16 address space here https://github.com/Azure/ARO-RP/pull/2238.
Development clusters use address space of dev-vnet to create subnets, changing the generatesubnets function to allow clusters to be created within the /16 address space. This limits the number of clusters we can create to 128
=> Update subnet generation for local dev

python/az/aro/HISTORY.rst, python/az/aro/azext_aro/_help.py, python/az/aro/azext_aro/_params.py, python/az/aro/azext_aro/_validators.py, python/az/aro/azext_aro/custom.py
Changes the `az aro create` CLI argument for multi-version from `install-version` to `version`.
This change was requested from product management to ensure a consistent experience for end-users, because we list the versions as simply `Version` and also the ARM template cluster creation accepts `version`.
Tested cluster creation and version validation manually.
Yes. The documentation for multi-version should specify `version` and not `install-version`.
=> Change az aro create install-version argument to version

test/e2e/aks.go, test/e2e/hive.go, test/e2e/hive_manager.go
Fixes
The Hive tests are not runable in prod environment.
=> Hide Hive behind localdev check

docs/prepare-your-dev-environment.md, docs/testing.md
The documentation for testing has been updated with the fix to the issue
=> Added fix for diff issue in MacOS

test/e2e/setup.go
Fixes
Hides the hive config behind localdev flag. The managed identity is not yet supported in the prod e2e, which renders these tests unusable. 
=> Hide hive config behind localdev flag

.pipelines/onebranch/templates/template-buildrp-buildaro.yml, Makefile
Fixes a case mismatch in PR #2574 that causes the tag checking to never happen.
=> Always use lowercase "true" for the Official Release flag

pkg/frontend/clustermanager_putorpatch.go
N/A
Fixes a build error introduced by #2671
```
pkg/frontend/clustermanager_putorpatch.go:39:18: no new variables on left side of :=
```
=> Fix build error

pkg/util/cluster/cluster.go
During cluster creation via hack script/e2e tests, if the cluster already exists we return nil, instead we should also check for the provisioning state of the cluster and return nil only if its not Failed.
Background:
For a failed e2e test case, due to resource quota limitation, on re-run e2e was still using the failed cluster and panicking. 
Instead, give a better error message.
Fixes
=> While create if cluster exists check provisioning state

pkg/frontend/admin_openshiftcluster_approvecsr.go, pkg/frontend/admin_openshiftcluster_cordonnode.go, pkg/frontend/admin_openshiftcluster_drainnode.go, pkg/frontend/admin_openshiftcluster_kubernetesobjects.go, pkg/frontend/admin_openshiftcluster_kubernetesobjects_test.go, pkg/frontend/adminactions/kubeactions.go, pkg/frontend/frontend.go, pkg/frontend/validate.go, pkg/frontend/validate_test.go, pkg/util/dynamichelper/gvrresolver.go, pkg/util/dynamichelper/gvrresolver_test.go, pkg/util/mocks/adminactions/adminactions.go, test/e2e/adminapi_kubernetesobjects.go
Fixes ARO-2148
Updates `getAdminKubernetesObjects` to only work for system level objects (specific clusterwide objects, and openshift system namespaces). Adds a `getAdminKubernetesObjectsUnrestricted` method and route to allow us to bypass this in specific circumstances.
This also moves us to use standard client-go restmapper libraries instead of custom ones to resolve cluster objects.
=> Add validation and unrestricted endpoint for kubernetes objects

pkg/cluster/fixssh.go, pkg/cluster/fixssh_test.go
Fixes: https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/14539058/
Fixes: https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/16195191/
This PR will fix SSH to the new node did not work after the master node replacement  and a PUCM was performed to reconcile the NIC and restore ssh access (as PUCM will call fixssh to do that reconciliation). Also this PR  fixes the issue whether the new NIC  is not being added to Internal LoadBalancer API Backend Address Pool after the master is replaced even after running the Admin Update or PUCM.
Added unit tests. Also tested manually by replacing the master nodes in test clusters.
<!--
Added new Go Mock Testcases.
https://msazure.visualstudio.com/AzureRedHatOpenShift/_wiki/wikis/ …
=> Ensure SSH access and LB backend pool for Master Node replacement

docs/dbtoken-service.md, docs/prepare-a-shared-rp-development-environment.md
Fixes old dbtoken-service docs that aren't relevant.
=> Update old dbtoken-service documentation

pkg/api/admin/openshiftcluster_convert.go
Removes SystemData from being returned in the admin API "GET" response.  
It is no longer needed and to comply with MAG requirements.
testing in INT tomorrow
nope
=> Remove systemdata from admin API

go.mod, go.sum, vendor/modules.txt
Fixes #2687
Bump github.com/opencontainers/runc from 1.1.1 to 1.1.2 to pull in CVE fixes
Details: https://github.com/advisories/GHSA-f3fp-gc8g-vw66
=> Bump github.com/opencontainers/runc from 1.1.1 to 1.1.2

pkg/cluster/install.go
With this commit, mdsd certs renewal will be run during the update task (so az aro update) so that customers can self-serve and fix expired Certs themselves.
Work-Item: https://issues.redhat.com/browse/ARO-2145
Fixes: https://issues.redhat.com/browse/ARO-2145
- Create a dev cluster and test update process
- Add a Wiki Page for SRE Troubleshooting and update CEE on the process.
Todo:
Added unit test cases if applicable.
=> Renew MDSD certs on az-aro-update

pkg/api/admin/openshiftcluster.go
Removes SystemData from API, was previously removed from converter.  
#2686 was previous implementation, but missed this in that one.
=> Remove the systemdata field from Admin API, not just the converter

cmd/aro/operator.go, pkg/operator/controllers/machine/machine.go, pkg/operator/controllers/machine/machine_controller.go, pkg/operator/controllers/machine/machine_controller_test.go, pkg/operator/controllers/machineset/machineset_controller.go, pkg/operator/controllers/machineset/machineset_controller_test.go, pkg/operator/controllers/previewfeature/previewfeature_controller.go, pkg/operator/controllers/storageaccounts/storageaccount_controller.go, pkg/operator/controllers/subnets/subnets_controller.go, pkg/util/subnet/cluster_subnets.go, pkg/util/subnet/cluster_subnets_test.go
Operator is not longer dependant on a versioned machine client and is now using a split client which uses cache for read operations.
=> Removes dependency on a versioned machine client

cmd/aro/operator.go, pkg/operator/controllers/genevalogging/genevalogging.go, pkg/operator/controllers/genevalogging/genevalogging_controller.go, pkg/operator/controllers/routefix/routefix.go, pkg/operator/controllers/routefix/routefix_controller.go
Operator is not longer dependant on a versioned security client and is now using a split client which uses cache for read operations.
=> Removes dependency on a versioned security client

pkg/util/version/const.go
Part of https://issues.redhat.com/browse/ARO-1384 so we're not jumping too far
Updates to the fluentbit 1.9.9 that we're using on the RP/
This was tested on a prod cluster and appears to work.
N/A
=> Update the default fluentbit image to 1.9.9

cmd/aro/operator.go, pkg/operator/controllers/autosizednodes/autosizednodes_controller.go, pkg/operator/controllers/dnsmasq/cluster_controller.go, pkg/operator/controllers/dnsmasq/machineconfig_controller.go, pkg/operator/controllers/dnsmasq/machineconfigpool_controller.go, pkg/operator/controllers/workaround/systemreserved.go, pkg/operator/controllers/workaround/systemreserved_test.go, pkg/operator/controllers/workaround/workaround_controller.go
Operator is not longer dependant on a versioned MCO client and is now using a split client which uses cache for read operations.
=> Removes dependency on a versioned MCO client

pkg/cluster/fixssh.go, pkg/cluster/fixssh_test.go
**Which issue this PR addresses:**
Fixes: https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/14539058/
Fixes: https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/16195191/
**What this PR does / why we need it:**
This PR fixes the Internal Load Balancer BackendAddressPool Name mismatch in the older architecture clusters.
**Test plan for issue:**
Added unit tests. Also tested manually by replacing the master nodes in test clusters.
=> Fixing ILB BackendPool Name in Old Architecture

pkg/frontend/admin_openshiftcluster_kubernetesobjects.go, pkg/frontend/frontend.go
Fixes
Simplifies and DRYs out some of the `getAdminKubernetesObjects` code
End to end should validate it
No, just a refactor
=> Simplify validation code on getAdminKubernetesObjects

test/util/listener/listener.go
[Fix race conditions in test functions](https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/16201104)
Help requested 👀 
I have used the [data race detector](https://go.dev/doc/articles/race_detector) and have detected some race conditions.
If you run 
```sh
go test -race -tags=aro,containers_image_openpgp ./… 
```
with a fresh pull of master, you will see that there are some race conditions/data races ([not the same](https://cronokirby.github.io/posts/data-races-vs-race-conditions) BTW).
Those race conditions are just affecting some unit tests and not production code (AFAIK):
- there is a data race in the test/util/listener/listener.go Close method because we try to read “l.closed” which can be accessed by more than one go routine at a time, causing a data race. The …
=> Fix race conditions in Test functions

test/e2e/adminapi_redeployvm.go, test/e2e/adminapi_resources.go, test/e2e/disk_encryption.go, test/e2e/fips.go, test/e2e/get.go, test/e2e/list.go, test/e2e/operations.go, test/e2e/operator.go, test/e2e/setup.go, test/e2e/update.go
Fixes
Updates the e2e tests to all use the latest API client version
The e2e test it self will show any issues
=> Move all e2e tests to use latest API version

pkg/frontend/admin_openshiftcluster_kubernetesobjects.go
Fixes
This reverts commit 9b19c7641763fcf5cfee943411596918d3572c4c.
This debug logging is no longer needed.
=> Revert "Add debug logging for _getAdminKubernetesObjects"

pkg/api/featureflags.go, pkg/frontend/openshiftclusterkubeconfigcredentials_post.go, pkg/frontend/openshiftclusterkubeconfigcredentials_post_test.go
Fixes `ADO work item link`
This PR removes the check for the AdminKubeconfig feature flag on the get-admin-kubeconfig operation, allowing all subscriptions to access the Admin Kubeconfig without manually registering the feature. 
The frontend unit tests for this feature ([pkg/frontend/openshiftclusterkubeconfigcredentials_post.go](https://github.com/Azure/ARO-RP/compare/master...tsatam:ARO-RP:remove-adminkubeconfig-feature-flag?expand=1#diff-2a13e63cc85a024293b8d88211109a265e73de6e38072c1eaaa7b4d2dd81a478)) were modified to remove the expectation that this feature flag must be set in order for the request to succeed.
=> Remove adminkubeconfig feature flag

cmd/aro/operator.go, pkg/operator/controllers/alertwebhook/alertwebhook_controller.go, pkg/operator/controllers/alertwebhook/alertwebhook_controller_test.go, pkg/operator/controllers/autosizednodes/autosizednodes_controller.go, pkg/operator/controllers/checkers/serviceprincipalchecker/checker.go, pkg/operator/controllers/checkers/serviceprincipalchecker/controller.go, pkg/operator/controllers/genevalogging/genevalogging_controller.go, pkg/operator/controllers/monitoring/monitoring_controller.go, pkg/operator/controllers/monitoring/monitoring_controller_test.go, pkg/operator/controllers/muo/muo_controller.go, pkg/operator/controllers/muo/muo_controller_test.go, pkg/operator/controllers/muo/template_test.go, pkg/operator/controllers/node/node_controller.go, pkg/operator/controllers/node/node_controller_test.go, pkg/operator/controllers/previewfeature/previewfeature_controller.go, pkg/operator/controllers/pullsecret/pullsecret_controller.go, pkg/operator/controllers/pullsecret/pullsecret_controller_test.go, pkg/operator/controllers/routefix/routefix_controller.go, pkg/operator/controllers/storageaccounts/storageaccount_controller.go, pkg/operator/controllers/subnets/subnets_controller.go, pkg/operator/controllers/workaround/ifreload.go, pkg/operator/controllers/workaround/workaround_controller.go, pkg/util/clusterauthorizer/authorizer.go, pkg/util/clusterauthorizer/authorizer_test.go, pkg/util/deployer/deploy_test.go, pkg/util/deployer/deployer.go
Operator is not longer dependant on a versioned kube client and is now using a split client which uses cache for read operations.
=> Removes dependency on a versioned kube client

cmd/aro/operator.go, pkg/operator/controllers/genevalogging/genevalogging_controller.go, pkg/operator/controllers/routefix/routefix_controller.go
Previously `dynamichelper` was sometimes passed into other constructors, sometimes created inside the controllers. This PR standardises on passing it into the constructors.
=> Operator standardise dynamichelper

pkg/api/validate/dynamic/dynamic.go, pkg/api/validate/dynamic/dynamic_test.go
Fixes: Retried cluster installs that have already attached our expected NSG to the subnets.
If an installation process gets past the attachNSG step and then restarts, either due to an RP restart from an upgrade, panic, or CosmoDB lease expiry, the install fails due to a false positive check for any NSG being attached to the master or worker subnets.
This PR adds the same [check that already takes place during install](https://github.com/Azure/ARO-RP/blob/a3c9e536a3b509c99f5961b35168a1fdd3467b26/pkg/cluster/deploystorage.go#L194-L209) "forward" into the dynamic validation.
Create test clusters using a shared environment.
Nope.
=> Detect expected NSG's during install retries

pkg/deploy/assets/rp-production.json, pkg/deploy/generator/templates_rp.go
Fixes: Incorrect comma placement in https://github.com/Azure/ARO-RP/pull/2721 
To fix CosmoDB VNET rule allocation during RP deploy.
Deployed to Public INT.
No
=> Put the comma in the correct place for CosmoDB VNET rule allocation

pkg/deploy/assets/rp-production.json, pkg/deploy/generator/templates.go, pkg/deploy/generator/templates_rp.go
Fixes: The root cause behind the deploy failures introduced in https://github.com/Azure/ARO-RP/pull/2721 (for realz this time).
Deploying the RP is borked without it.
Manually tested the changes in a dedicated RP, although it's not directly possible because a dedicated RP instance is a sortof dev not pure production.
No.
=> Use VirtualNetworkRule structs and not strings for the CosmoDB VNET rules

pkg/installer/generateconfig.go
in `pkg/frontend/openshiftcluster_putorpatch.go`, we set defaults `api.SetDefaults` which always ensures that the SDN is set on cluster creation or cluster update.  This if statement is no longer necessary as the SDN will always be set on a cluster during installconfig generation.
=> Remove unnecessary checking of SDN for install config generation

pkg/cluster/delete.go
Slackthread: https://redhat-internal.slack.com/archives/C02ULBRS68M/p1676340311290279
Current Scenario:
azcli delete only ensures if ARO SP has NETWORK_CONTRIBUTOR_ROLE on the VNET and adds it if missing, if OWNER Permission is missing on ARO SP for CRG, the deletion fails and only AdminUpdate can fix such missing permission which will be tricky if the cluster is in ProvisioningFailed state.
With this PR:
We fix any missing permission on ARO SP so that deletion works without failure.
Fixes
=> Run ensureResourceGroup for ARO delete

cmd/aro/operator.go, pkg/operator/controllers/workaround/systemreserved.go, pkg/operator/controllers/workaround/systemreserved_test.go, pkg/operator/controllers/workaround/workaround_controller.go
Changes:
* Removes dynamichelper. Using dynamichelper to create just one object looks like overkill here. The same can be done with the client.
* Updates `Remove`: we previously were removing the label from `MachineConfigPool`, but keeping `KubeletConfig` handing around. Now we remove both
* Extra unit test coverage
Existing and new unit tests.
No, refactoring
=> systemreserved: Fixes `Remove`, eleminates dependency on dynamichelper & adds more test coverage

python/az/aro/azext_aro/_params.py, python/az/aro/azext_aro/_validators.py, python/az/aro/azext_aro/custom.py, python/az/aro/azext_aro/tests/latest/unit/test_validators.py
Removes an unused field that doesn't take any effect in cluster creation using `az aro` command module.  
@tony-schndr tested an `az aro create --version 4.11.x` and even though this field was present, it still defaulted to OVNKubernetes as it should.  
Nope
=> Remove SDN in Python as field no longer used in v2022-09-04 or later 

pkg/api/defaults.go, pkg/api/defaults_test.go, pkg/cluster/ipaddresses.go, pkg/frontend/openshiftcluster_putorpatch_test.go, pkg/installer/generateconfig.go
Fixes ARO-1476
The aro-installer will now set SDN if it's not set.  It will change based on which aro-installer is invoked.  4.11 will be OVNK8s and 4.10 will be OpenShiftSDN.  Relevant PR in aro-installer: https://github.com/openshift/ARO-Installer/pull/16/files
=> Support OVNKubernetes in OpenShift 4.11

cmd/aro/mirror.go, cmd/aro/update_ocp_versions.go, docs/deploy-full-rp-service-in-dev.md, pkg/api/v20191231preview/openshiftcluster_validatestatic_test.go, pkg/api/v20200430/openshiftcluster_validatestatic_test.go, pkg/api/v20210901preview/openshiftcluster_validatestatic_test.go, pkg/api/v20220401/openshiftcluster_validatestatic_test.go, pkg/api/v20220904/openshiftcluster_validatestatic_test.go, pkg/cluster/install_version_test.go, pkg/cluster/storageclass_test.go, pkg/cluster/version.go, pkg/frontend/admin_openshiftversion_put.go, pkg/frontend/admin_openshiftversion_put_test.go, pkg/frontend/frontend.go, pkg/frontend/openshiftversions_list.go, pkg/frontend/openshiftversions_list_test.go, pkg/frontend/validate.go, pkg/monitor/cluster/clusterversions.go, pkg/monitor/cluster/clusterversions_test.go, pkg/util/dynamichelper/discovery/cache_fallback_discovery_client_test.go, pkg/util/version/const.go
Refactors hive install streams used in `update_ocp_versions`.  We're currently using a map but there is no need.  Additionally, we shouldn't be hardcoding minor version strings for installer pull spec in case default changes for some reason.  
Run the pipeline against INT.
=> Refactor hive install streams

pkg/api/v20230401/openshiftcluster_validatestatic_test.go
There was a change introduced in #2706 that was missed in #2742 because 2742 CI ran before 2706 was merged in.  This fixes any issues with referenced variable that doesn't exist.
=> Reconcile conflict between refactor and previously merged PR

pkg/api/validate/vm.go, pkg/frontend/admin_openshiftcluster_vmresize.go, pkg/frontend/validate.go, pkg/frontend/validate_test.go
Fixes
Resizing masters to unsupported/untested VM sizes could have unintended negative consequences for a cluster. This adds validating logic to the master resize action so that SRE doesn't have to go and check the list manually.
Unit tests
No
=> Validate master resize target is a supported master vmSize

Dockerfile.fluentbit, Makefile, cmd/aro/mirror.go
Fixes https://issues.redhat.com/browse/ARO-1384
This builds fluentbit from source in a Mariner build container and then places it in a Mariner runtime container.
The build is minimised to include as little functionality as possible, removing all available features except ones required by ARO for use in conjunction with MDSD.
Build portion at https://msazure.visualstudio.com/AzureRedHatOpenShift/_git/ARO.Pipelines/pullrequest/7089561 (merged)
Needs to be manually tested in a cluster.
N/A
=> Add a Fluentbit image build using Mariner containers

pkg/api/validate/dynamic/serviceprincipal.go, pkg/api/validate/dynamic/serviceprincipal_test.go, pkg/util/clusterauthorizer/authorizer.go, pkg/util/clusterauthorizer/authorizer_test.go, pkg/util/instancemetadata/prod.go, pkg/util/instancemetadata/prod_test.go
Fixes https://issues.redhat.com/browse/ARO-1577
This PR updates all cases when `ParseUnverified` is called and returns a cloud error, which will then be converted to a `UserError`. This prevents the generic `InternalServerError` status code from being the only error.
Updated existing unit tests.
I don't believe so.
=> Fix failure to parse token errors as Cloud Errors - ARO-1577

pkg/util/aad/aad.go, pkg/util/aad/aad_test.go, pkg/util/mocks/refreshable/refreshable.go, pkg/util/refreshable/refreshable.go
https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/14588871
Fixes
Return the error if error is captured instead of nil
Customer wants to identify the error instead generic error(Internal Server Error)
=> Returning the error if error is captured instead of nil

.gdn/.gdnsuppress
Fixes gdn warnings, before they turn into errors and block the build on 03/15/2023
Add the references for the two offending files from the output of a recent build run as per https://onebranch.visualstudio.com/OneBranch/_wiki/wikis/OneBranch.wiki/4640/Suppress-SDL-issues?anchor=download-.gdnsuppress-or-.gdnbaselines-file-from-the-failed-build
Build from PR successful
see: https://msazure.visualstudio.com/AzureRedHatOpenShift/_build/results?buildId=69655759&view=results
n/a
=> Fix gdn warnings

pkg/api/error.go, pkg/cluster/delete.go
Fixes https://issues.redhat.com/browse/ARO-2298
Client was having an issue deleting a cluster and was getting internal server error. When digging into the logs, the issue was shown to be InUseSubnet, which is marked as an internalServerError with error code 400. This change will change the error to a userError and the user will be able to see more details surrounding the failure and be able to correct it.
=> Add new clouderror for inUseSubnet

pkg/monitor/cluster/cluster.go, pkg/monitor/cluster/debugpods.go, pkg/monitor/cluster/debugpods_test.go, pkg/util/stringutils/stringutils.go
[Detect customer debug pod activity](https://issues.redhat.com/browse/ARO-1697)
We want to have this metric to track debug pod activity
Unit tests
TBD
=> Track debug pods

pkg/deploy/deploy.go, pkg/deploy/vmsscleaner/clean.go, pkg/util/azureclient/mgmt/compute/virtualmachinesscalesets_addons.go, pkg/util/mocks/azureclient/mgmt/compute/compute.go, pkg/util/mocks/vmsscleaner/vmsscleaner.go
When updating the gateway to have a separate probe for the probe, it blocks the update of the deployment because the vmss is still using the probe. This deletes the vmss first in case it happens so we can update the probe and then recreate the vmss
Fixes
=> now recreates the gateway vmss if there is a change in the probe

pkg/deploy/vmsscleaner/clean.go, pkg/deploy/vmsscleaner/clean_test.go
fixes the wrong return value in the cleaner which prevented the deployer to redeploy the vmss
Fixes
=> fixes wrong return value for retry in vmss cleaner in deployer

pkg/operator/controllers/checkers/ingresscertificatechecker/checker.go, pkg/util/dns/manageddomains.go, pkg/util/dns/manageddomains_test.go, pkg/util/net/net.go
Refactor: move IsManagedDomain() function to the dns package.
I got a [request](https://github.com/Azure/ARO-RP/pull/2608#pullrequestreview-1345797720) to move the function _IsManagedDomain()_ to the dns package, so doing it now.
Already covered by unit tests.
N/A
=> refactor: move IsManagedDomain function to dns package

pkg/api/admin/openshiftcluster.go, pkg/api/openshiftcluster.go, pkg/api/validate/dynamic/encryptionathost_test.go, pkg/api/validate/vm.go
Fixes https://issues.redhat.com/browse/ARO-1344
Adds new generation instance types, also adds some customer-requested types from CEE. Adds some that were previously only supported on worker to be supported on master also. Cleans up some formatting and adds recently added SKUs to admin API.
Also, we want to remove support for certain deprecated sizes that don't support premium disk.
Yes, we will need to submit a docs change to `azure-docs-pr` once we have released this.
=> Add newer gen instance types, remove deprecated and non-s types

pkg/deploy/assets/databases-development.json, pkg/deploy/assets/rp-production.json, pkg/deploy/generator/resources_rp.go
Fixes [ARO-2615](https://issues.redhat.com/browse/ARO-2615)
Increases the default throughput for the RP cosmosdb from 500 to 1000. 
None (config change)
No
=> Increase cosmosdb default throughput to 1000

pkg/operator/controllers/checkers/ingresscertificatechecker/controller.go
The IngressCertificateChecker are emitted under the controller name SPChecker, although this doesn't have any impact and only creates misleading logging in the ARO operator.
This PR fixes this, by using a unique name IngressCertificateChecker
Slack thread: https://redhat-internal.slack.com/archives/C02ULBRS68M/p1679406933440319
Tested the change using https://github.com/Azure/ARO-RP/blob/master/docs/operators.md#how-to-run-the-operator-locally-out-of-cluster
Fixes
=> Replace SPChecker with IngressCertificateChecker

pkg/dbtoken/server.go, pkg/dbtoken/server_test.go
When replacing `gorilla/mux` with the standard library we lost the access logging. Using `chi` instead of the standard library will add the access logging back
Fixes
=> replaced standard library with chi in dbtoken

pkg/deploy/assets/gateway-production.json, pkg/deploy/generator/resources_gateway.go, pkg/gateway/gateway.go, pkg/gateway/http.go
replaces the standard library with go-chi since we apparently lost the access logs with it. Standard library returned 404 for requests which should have been found. 
also put the probe back to the port 80 where it used to be so we don't run into the problem of `ProbeInUSeByVMSS` 
Fixes
=> replaces the standard library mux with chi in the gateway

docs/deploy-development-rp.md, pkg/api/validate/vm.go, pkg/frontend/admin_supportvmsizes_list.go, pkg/frontend/frontend.go
Jira: https://issues.redhat.com/browse/ARO-2566
A new GA which takes instanceType as input and lists all the supportedVMSizes by taking pkg/api/validate/vm.go as the source of truth
Fixes
=> GenevaAction to list Supported VM Sizes

Dockerfile.fluentbit
Fixes https://issues.redhat.com/browse/ARO-1384
Docker is a bit more restrictive than Podman in terms of args. For building, we'll need this.
Will test in CI/building
N/A
=> Add the registry arg for the fluentbit dockerfile

Dockerfile.fluentbit, Makefile, cmd/aro/mirror.go
Part of https://issues.redhat.com/browse/ARO-1384
We don't need to clone from MCR for Mariner images/etc that are needed in EV2, since they are fine to pull directly. We still need to clone images that might be used in clusters or are on registry.redhat (e.g. go-toolset, or azure-cli from MCR), but for base images from MSFT the first party repo is supposed to be used.
Will be testing by building
N/A
=> Change mariner to pull from MCR

.pipelines/e2e.yml, Makefile
Adding SHELLFLAGS and switch to double dollar signs to prevent make from expanding bash variables
No current issues.
Currently unset variables are allowed in Makefile. I don't believe there should be a case where we need/want unset variables, I believe this a safer option.  
`.SHELLFLAGS := -o nounset -c` sets `nounset` and variables are expanded by bash by escaping with double dollar signs.
Existing tests that utilize make
No
=> Update Makefile to not allow unset variables

test/e2e/operator.go
removes the manual timeout as we set it to 5 minutes [here](https://github.com/Azure/ARO-RP/blob/master/test/e2e/setup.go#L512) and 3 seconds caused flakes
=> remove mhc test timeout

pkg/cluster/install.go, pkg/cluster/install_test.go, pkg/metrics/metrics.go, pkg/metrics/noop/noop.go, pkg/metrics/statsd/metrics.go, pkg/metrics/statsd/metrics_test.go, pkg/metrics/statsd/statsd.go, pkg/util/steps/action.go, pkg/util/steps/condition.go, pkg/util/steps/refreshing.go, pkg/util/steps/runner.go, pkg/util/steps/runner_test.go
Improve naming: add parameter names to Emitter's interface methods and unify the naming of metrics and monitor.
In the codebase, we refer to the same concepts regarding metrics with different names in different places ("metric", "topic", etc.). This PR unifies the usage of those names following the [statsd Protocol Reference of MSFT](https://eng.ms/docs/products/geneva/collect/metrics/statsdref). It also adds names to the parameters of the methods of metrics.Emitter interface as those methods has two unnamed parameters of the same type, which makes it impossible to know which param is what without looking at the interface implementation.
Already covered by unit tests/E2E test. Most of the refactoring was done using the IDE renaming feature.
N/A
=> add param names to Emitter's interface methods and unify naming

.pipelines/clean-subscription.yml, .pipelines/templates/template-clean-subscription.yml
Fixes the pipeline because some library needs 1.18 to run after and so pipeline wouldn't compile anymore
https://redhat-internal.slack.com/archives/CCV9YF9PD/p1680851340018869
=> bumped go version

pkg/util/clusterdata/clusterdata.go, pkg/util/clusterdata/clusterdata_test.go
https://redhat-internal.slack.com/archives/C02ULBRS68M/p1681167150885559
This fixes a race condition in testing that would make the test fail because the metrics emission is async
Fixes
=> fixed race condition in testing

docs/deploy-development-rp.md
Note
This pull request updates "Deploy development RP" documentation clarifying setup of local ARO-RP with Hive instance and fixes example of "Stop and deallocate a VM" REST call.
I manually tested that both `stopvm?vmName=$VMNAME` and `stopvm?vmName=$VMNAME&deallocateVM=True` works [as expected](https://learn.microsoft.com/en-us/azure/virtual-machines/states-billing).
=> fix minor doc issues

.pipelines/e2e.yml
`clean_e2e_db` is responsible for cleaning up the cluster database from `e2e-eastus`, but because it was [only being executed in cases of succeeded e2e](https://msazure.visualstudio.com/AzureRedHatOpenShift/_build/results?buildId=71317109&view=logs&j=10f66467-59e5-53bc-0c8a-42cc89770de4&t=f00aaa95-0643-5e60-2886-48bbeb9c10f0), it was causing failed e2e runs to leak databases. This eventually resulted in a full CosmosDB quota which was fixed by manually deleting cluster databases using `az`.
Ensures that `clean_e2e_db` always runs.
e2e passes, cluster database is deleted. e2e fails, cluster database is also deleted.
=> Fix `clean_e2e_db` not running in CI when e2e fails

test/e2e/cluster.go, test/e2e/disk_encryption.go
none
The default storage class on 4.12 cluster is the same as on 4.11, but  the correct default storage class is used on 4.11 clusters only,  which will make  2 test cases fail on 4.12 cluster.
When the current condition was created, we [were not sure what the default for 4.12 will be](https://github.com/Azure/ARO-RP/pull/2739/files#r1114609783), but now we [have this assumption in the code already](https://github.com/Azure/ARO-RP/pull/2585/files#diff-288bcd4df3d10098fe8b909ead3bf744c5e0e9fd5849623157d3046d11025c87R45).
For this reason, we need to update the version check so that the new storage classes are used with >= 4.11.
I run the e2e tests on 4.12 cluster during upgrade testing.
No documentation needs update.
=> fix e2e tests when running against 4.12 clusters

pkg/cluster/fixssh.go, pkg/cluster/fixssh_test.go
https://issues.redhat.com/browse/ARO-2321
This PR fixes the issue when the master node in the cluster is replaced, the newly replaced master's network interface is not automatically being added the External Load Balancer Address Pool in the old architecture version(V1) clusters. Also in the clusters with newer architecture(V2) when the network interface is removed manually from the External Load Balancer for any reason then its not automatically being  added to the External  Load Balancer Backend Address Pool again. This issue can be fixed when we run PUCM/Admin Update after the master node is replaced in the cluster.
Test manually by replacing the master nodes in test clusters in both new and old version architectures. Also add unit test cases.
=> Fixing External LoadBalancer Backend Address Pool after Master node replacement

pkg/operator/deploy/staticresources/master/deployment.yaml.tmpl, pkg/operator/deploy/staticresources/worker/deployment.yaml.tmpl
Fixes an issue where the customer marked all nodes as unschedulable and the ARO operator wouldn't run 
Above
Manually added it on the shared cluster and it ran successfully when all nodes were tainted with unschedulable.  
Nope
=> Allow aro operator to tolerate noschedule and noexecute

cmd/aro/mirror.go
Fixes broken mirroring pipeline since we're trying to mirror versions that are old.  
Bump the default mirror starting at 4.8 since the other versions are out of support https://access.redhat.com/support/policy/updates/openshift
Run it
=> Start mirroring from 4.8 as below versions are no longer getting updates

cmd/aro/deploy.go, pkg/deploy/deploy.go
Fixes a regression from https://github.com/Azure/ARO-RP/pull/2667
Unlike its ADAL-based predecessor [NewAuthorizerFromEnvironment](https://pkg.go.dev/github.com/Azure/go-autorest/autorest/azure/auth#NewAuthorizerFromEnvironment), [azidentity.NewEnvironmentCredential](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azidentity#NewEnvironmentCredential) does not attempt to use MSI, and ARO uses MSI when deploying to production environments.
Work around this by having the caller provide an appropriate TokenCredential when creating a Deployer instance.
=> pkg/deploy: Caller provides an appropriate TokenCredential

hack/ssh-agent.sh
Fixes `hack/ssh-agent.sh`
It seems that since this script was written the name of the NIC attribute `privateIpAddress` has changed to `privateIPAddress`.
Script was not working when I tried to run it for my first time, and I ended up tracing it to the line I've updated in this PR. It worked after my change.
No
=> Update privateIpAddress -> privateIPAddress in hack/ssh-agent.sh

pkg/api/admin/openshiftcluster.go, pkg/api/openshiftcluster.go, pkg/api/validate/vm.go
These `v4` instances don't exist in Azure documentation yet:
https://learn.microsoft.com/en-us/azure/virtual-machines/dv4-dsv4-series
https://learn.microsoft.com/en-us/azure/virtual-machines/ev4-esv4-series
If customers want to install with these instances, they can go to the v5 versions (Standard_D96s_v5, Standard_E96s_v5).
=> Remove Standard_D96s_v4 and Standard_E96s_v4

pkg/api/validate/vm.go, pkg/frontend/admin_supportvmsizes_list.go, pkg/frontend/validate.go
This PR creates a new function SupportedVMSizesByRole to provide supportedMasterVmSizes and supportedWorkerVmSizes thus preventing accidental changes to the variables by changing the scope of these variables from public.
Jira: https://issues.redhat.com/browse/ARO-2882
=> Func to list SupportedVMSizesByRole

cmd/aro/mirror.go
Fixes P0s on the hive image vulnerability
We have vulnerabilities against hive in production.  We are bumping the image to the latest commit to mirror that image and then test it in INT -> to production.  
Merge this in, deploy hive in INT, run e2e against INT, proceed to production. 
nope.  There are associated ADO PRs for this though in RP config, and ARO.Pipelines.
=> Bump the hive image to latest to addresss vulns

pkg/deploy/assets/databases-development.json, pkg/deploy/assets/rp-development.json, pkg/deploy/assets/rp-production-parameters.json, pkg/deploy/assets/rp-production.json, pkg/deploy/config.go, pkg/deploy/deploy_rp.go, pkg/deploy/devconfig.go, pkg/deploy/generator/resources_rp.go, pkg/deploy/generator/templates.go, pkg/deploy/generator/templates_rp.go
Fixes [ARO-2655](https://issues.redhat.com/browse/ARO-2655)
This PR extracts the previously hardcoded throughput values for the CosmosDB deployment into ARM template parameters, overrideable via deployment configuration. 
This PR also enables autoscaling for dev database instances. 
- Existing unit tests for validating deployment assets continue to pass as expected. 
- Manually deployed [full-service RP](https://github.com/Azure/ARO-RP/blob/master/docs/deploy-full-rp-service-in-dev.md) with new configuration and ensured the deployment was successful and changed the configured CosmosDB throughput values for the database, and portal/gateway containers
No
- Providing the `cosmosDB` block in configuration is optional; but if it is provided, all throughputs (database-level, portal, gateway) …
=> Extract CosmosDB throughput configuration to ARM template parameters

pkg/frontend/adminactions/azureactions.go, pkg/util/azureclient/applens/applens.go, pkg/util/azureclient/applens/applens_client.go
Fix a problem where the json.Marshal(resp.Body) was returning an {} instead of the expected Json string
=> Fix reading the AppLens resp to return Json string

cmd/aro/mirror.go
There was a regression in hive latest versions which watch a CRD which isn't present in non-ocp clusters.  Drop the commit to one that doesn't show any vulnerabilities.  
Run mirror
Nope
=> Update hive image in use in prod

.github/workflows/npm-audit.yml
None
Currently, we store the portal's build artifacts in the repository. If these are invalid, either out-of-sync with itself or with the corresponding source, this can cause issues when deploying the portal. 
This PR adds a step to the `node-lint` GitHub action to validate that the build artifacts are up-to-date with source, by simply running the build and checking if the files have changed. 
See the `npm_build_check` check on this very PR. We can play with pushing temp changes to the portal on this branch and view failing checks. 
N/A
=> Validate portal build assets are up-to-date in PRs

Dockerfile.autorest, Makefile, hack/build-client.sh
[JIRA LINK](https://issues.redhat.com/browse/ARO-2902)
Client generation is broken with the current Dockerfile.
We are using a nodejs image that is no longer updated for security nor is it LTS. -18 is the new LTS.
Debugging client generation is an effort without some form of blockd logging.
1. Updated autorest version to 3.6.3
2. Updated nodejs image from deprecated nodejs-14 to nodejs-18
```
nodejs-14 EOL: APRIL 2021 (no security updates)
nodejs-16 EOL: September 2023 (very soon)
nodejs-18 EOL: April 2025
```
3. Removed USER 1001 from Dockerfile (fixing permissions issue for successful client generation)
4. Added print statements to client generation for readability/debugging
5. Updated comments for clarity
Manual testing of client generation with current clients to make sure there are …
=> Fix client generation

.github/generate_release_note.sh, .github/workflows/release-note.yml
Fixes https://issues.redhat.com/browse/ARO-1682
This PR enables to create release page by pushing an annotated tag.
It uses github actions and https://github.com/softprops/action-gh-release
It's hard to write a automated test because it is a part of github actions and totally dependent on github actions behaviour and git itself.
I tested it manually. Below is the example.
```bash
git tag -a v3014 -m "This is annotation."
```
https://github.com/bitoku/ARO-RP/releases/tag/v3014
no
=> Auto-generate release note

pkg/cluster/cluster.go, pkg/cluster/install.go, pkg/util/refreshable/refreshable.go, pkg/util/steps/refreshing.go
Fixes https://issues.redhat.com/browse/ARO-2978 maybe
Force refreshes the token if we hit the authorization errors that are due to caches. We no longer need to refresh the token ourselves for normal uses, but since the first token might have a lifetime of 3600s and there's no external interface to force a token refresh, we just rebuild the authoriser to try again.
I'm not sure?
fixes have docs in them
=> Attempt to refresh credentials if we get access exceptions

cmd/aro/mirror.go
There's an issue in hive in production where there appears to be memory leaks.  We also have to take into account older versions of hive have vulnerabilities.  
This hive image is a hotfix image rebuilt at the commit we were using which was good, but should have red hat update packages so no P0s :+1: 
Test in INT + roll to prod.  
Nope
=> Ad-hoc Hive Image with Red Hat Package Updates at Old Commit

python/az/aro/azext_aro/_help.py
This is to simplify the help output for az aro create --help. An @ symbol is no longer required before the pull secret file.
None
Fixes
The pull secret file path no longer needs to be prefixed with @ for the `az aro` command to parse the file. This is to remove the @ symbol from the help output.
N/A
=> Update az aro --pull-secret help example output

cmd/aro/mirror.go
The previous hive image had more vulnerabilities reported on it.  This one is based on ubi/ubi8-minimal which doesn't show any vulnerabilties as of today.  
Follow SDP
will need an update in RP config, and ARO.Pipelines.
=> Use less vulnerable container image based on ubi8

pkg/operator/controllers/dnsmasq/cluster_controller.go, pkg/operator/controllers/dnsmasq/cluster_controller_test.go, pkg/operator/controllers/dnsmasq/machineconfig_controller.go, pkg/operator/controllers/dnsmasq/machineconfig_controller_test.go, pkg/operator/controllers/dnsmasq/machineconfigpool_controller.go, pkg/operator/controllers/dnsmasq/machineconfigpool_controller_test.go, test/e2e/operator.go
Fixes: https://issues.redhat.com/browse/ARO-1490
Deletes the `99-%s-aro-dns` MachineConfig made by the operator for each MachineConfigPool when that MachineConfigPool is deleted. This will prevent alerts firing for these MachineConfigs when they do not apply to any MachineConfigPool. 
Unit tests and an E2E test were added for the overall MachineConfig creation as well as the delete case.
No.
=> Clean up dnsmasq machineconfig when machineconfigpool is deleted

pkg/api/validate/dynamic/dynamic.go, pkg/api/validate/dynamic/serviceprincipal_test.go, pkg/api/validate/openshiftcluster_validatedynamic.go, pkg/operator/controllers/checkers/serviceprincipalchecker/checker.go, pkg/operator/controllers/checkers/serviceprincipalchecker/checker_test.go
When we initialize validators, they will never return an error.  So remove the errors they claim to return and remove some code.  
e2e
Nope
=> Remove unnecessary error return

pkg/operator/controllers/clusteroperatoraro/clusteroperatoraro_controller.go
Fixes operator version not updating
Currently, the operator sets it's version when it's first installed, but then never updates it even if the operator is updated.
=> Update operator version when version.GitCommit changes

Makefile
`make validate-go` generates an error when it runs `go vet` because there is only nolint directive for `golangci-lint` not for `go vet`.
```
❯ make validate-go
gofmt -s -w cmd hack pkg test
go run ./vendor/golang.org/x/tools/cmd/goimports -w -local=github.com/Azure/ARO-RP cmd hack pkg test
go run ./hack/validate-imports cmd hack pkg test
go run ./hack/licenses
go vet -tags containers_image_openpgp ./...
pkg/backend/openshiftcluster.go:264:15: assignment copies lock value to ocCopy: github.com/Azure/ARO-RP/pkg/api.OpenShiftCluster contains sync.Mutex
make: *** [validate-go] Error 1
```
https://github.com/Azure/ARO-RP/blob/be4bae3d0ce01c2c9ba3cc7fe7bf30b0a1cd78c2/pkg/backend/openshiftcluster.go#L262-L264
`go vet` is now included in `golangci-lint`, and `golangci-lint` can be run already by …
=> Remove go vet from validate-go in Makefile

pkg/cluster/fixssh.go
Fixes an issue where PUCM will fail when outboundType is UserDefinedRouting, because it attempts to `Get` an external load balancer, which doesn't appear to be created in a prod install when UDR is enabled.
PUCM should pass for clusters where [our preview feature to not create a public IP](https://learn.microsoft.com/en-us/azure/openshift/howto-create-private-cluster-4x#create-a-private-cluster-without-a-public-ip-address-preview) is enabled. This PR skips the external load balancer portion of `checkandUpdateNIC()` if the UserDefinedRouting feature is enabled.
- Create a dev cluster as private, using the [public document](https://learn.microsoft.com/en-us/azure/openshift/howto-create-private-cluster-4x)
- Remove the public load balancer of the dev cluster
- Mimic the prod setup by …
=> Fix PUCM failure when outboundType is UserDefinedRouting

test/e2e/operator.go
Fixes https://issues.redhat.com/browse/ARO-3084
Reduces the complexity around checking if the annotation is added properly after nsg reconciliation.
e2e tests run for the PR
N/A
=> simplifies subnet reconcile annotation check to avoid flaky timestamps

.github/workflows/yamllint.yml, .gitignore, .mega-linter.yml
Chore from warnings in github
Fixes up deprecation warnings
It is tests :)
N/A
=> Update the mega linter because of GitHub Action deprecations

python/az/aro/azext_aro/_dynamic_validators.py, python/az/aro/azext_aro/custom.py, python/az/aro/azext_aro/tests/latest/unit/test_dynamic_validators.py
https://issues.redhat.com/browse/ARO-2887
This provides a better experience for customers.  By pre checking certain common issues it means the `aro_create`  does not fail half way through creation but immediately after running the `az_validate` "ready for creation tests".  Saving the customer time and poor user experiance.
1. When I run a validate with no warnings or errors. The command should exit with a return status of 0 and no tables.
1. When I run a validate with a warning. The command should exit with a return status of 0 and a warning table (yellow) with 1 row
2. When I run a validate with an single error in it. The command should exit with a return status of >0 and a error table(red) with 1 row
3. When I run a validate with an single error and a single warning in it. The command …
=> ARO-2887 - Add az aro validate functionality to az aro create

pkg/cluster/clusterserviceprincipal.go, pkg/cluster/clusterserviceprincipal_test.go
Fixes [ARO-2898](https://issues.redhat.com/browse/ARO-2898)
Fixes
Unit tests updated for new functionality.
Manual tests performed on locally running RP.
1. Create a new cluster and get admin kubeconfig
1. Save existing secret `oc get secret -n kube-system azure-credentials -o yaml > azure-credentials-old.yaml`
1. Delete secret from cluster `oc delete secret -n kube-system azure-credentials`
1. Run `az aro update` on cluster
1. Get newly created secret `oc get secret -n kube-system azure-credentials -o yaml > azure-credentials-new.yaml`
1. Compare secret contents `diff --color azure-credentials-old.yaml azure-credentials-new.yaml`
None
=> Fix failure in az aro update when missing azure-credentials object

pkg/monitor/cluster/debugpods.go, pkg/monitor/cluster/debugpods_test.go
Debug pods can be spawned not only in the default namespace.
This PR updated the part that fetches debug pods.
Update unit tests
=> fixing an issue with debug pods namespace

Dockerfile.gatekeeper
Fixes https://issues.redhat.com/browse/ARO-3201
Ensure the gatekeeper image is FIPs compliant
```
$ go tool nm ./manager | grep -i dlopen
401bb0 T _cgo_522b112ea4b5_Cfunc__goboringcrypto_DLOPEN_OPENSSL
543960 T crypto/internal/boring._Cfunc__goboringcrypto_DLOPEN_OPENSSL.abi0
389ee88 D crypto/internal/boring._cgo_522b112ea4b5_Cfunc__goboringcrypto_DLOPEN_OPENSSL
U dlopen
```
No
=> Update gatekeeper dockerfile to ensure cgo is enabled

pkg/monitor/cluster/debugpods.go
fixes a bug introduced by the new version of the event object. For some reasons in some cases the event time is 0 and we should look at the deprecated field instead 
Fixes
=> now check if time is not set in event object in monitor

pkg/deploy/deploy.go
Came up in Slack thread about most recent RP release. When I updated this error handling code a few months ago, I forgot to ensure that the error on failed deployments is always logged regardless of what type of error it is.
Prior to this PR, errors on failed deployments would only be logged if it was the last deployment attempt or the error was known (specifically the known error related to the RP LB). This PR makes it so that the error is always logged for any failed deployment.
N/A
N/A
=> Always log error (if applicable) on failed deployment attempts

pkg/deploy/assets/rp-production.json, pkg/deploy/generator/resources_rp.go
https://issues.redhat.com/browse/ARO-2927
PR updates the production RP template generator code and also updates the corresponding assets.
Update is done to template such that, a new CosmosDB Alert is added to fire an IcM  in case of throttling.
It is done to monitor CosmosDB experiencing an abnormal or problematic level of rate limiting.
Additional information and analysis:- https://docs.google.com/document/d/1gcYyhjlXIFMWTGDGDz5tNvnoRqeQLj73SqBhxV17Aq8/edit?usp=sharing
Tested the functionality by successfully deploying a full RP and checking if the alerts are getting fired on the azure portal.
Test the INT deployment pipeline (Still Needed)
Yes, On Call Monitors and Alert docs.
I will need help to make sure what documentations need this update.
=> add cosmosdb throttling azure alerting rule

pkg/frontend/admin_openshiftcluster_vmresize.go, pkg/frontend/admin_openshiftcluster_vmresize_test.go, pkg/frontend/adminactions/azureactions.go, pkg/util/mocks/adminactions/adminactions.go
With this PR, a new option to Force resize a master node GA is added, this parameter prevents nodeName check, this will be helpful if the API server is unavailable or the control plane is under extreme load.
jira: https://issues.redhat.com/browse/ARO-2797
=> Force Resize option in Master Resize GA

go.mod, pkg/operator/controllers/dnsmasq/cluster_controller.go, pkg/operator/controllers/dnsmasq/dnsmasq.go
Fixes https://issues.redhat.com/browse/ARO-3194 
To remove the installer dependency, we need to vendor in the dnsmasq config code.
E2E
N/A
=> [ARO-3194] Vendor dnsmasq into the operator

cmd/aro/mirror.go
[ARO-3011](https://issues.redhat.com/browse/ARO-3011)
Updates Hive image to 32e143a294
N/A
N/A
=> Update Hive image to 32e143a294

pkg/operator/controllers/imageconfig/image_controller.go, pkg/operator/controllers/imageconfig/image_controller_test.go
JIRA: https://issues.redhat.com/browse/ARO-3272
Fixes
Based on changes of: https://github.com/Azure/ARO-RP/pull/2899
=> Propagate errors of ARO ImageConfig controller to ARO Operator

pkg/api/error.go, pkg/cluster/deploybaseresources.go
This issue is solution to [ARO-2506](https://issues.redhat.com/browse/ARO-2506). 
This PR Adds a new CloudErr for RequestDisallowedByPolicy.
It will help customer know the faulty/incorrect policy attached to subnet and fix it without need for any support
Tested manually by reproducing the issue by assigning a deny policy to master subnet
No
=> Adding RequestDisallowedByPolicy cloud error

pkg/monitor/cluster/cluster.go, pkg/monitor/cluster/hiveregistrationstatus_panics_test.go
Co-authored by: @dbizau and @gvanderpotte
Fixes https://portal.microsofticm.com/imp/v3/incidents/details/399924373/home
Prevents the monitor from crashing when client.New() returns an error, without changing the current behavior of the monitor to not have any unexpected impact in prod.
General showcase of the nil interface: 
https://go.dev/play/p/W63APGm-Aik
Created unit tests to show the panic that we had in production + tests for the fix showing it does not panic anymore.
The unit tests also serve as documentation for this type of issue. 
Unit Tests are provided with explanations and I am finishing an RCA that I will share soon.
=> fix monitoring panic when client.New() returns an error and provide unit tests

pkg/operator/controllers/autosizednodes/autosizednodes_controller.go, pkg/operator/controllers/autosizednodes/autosizednodes_controller_test.go
https://issues.redhat.com/browse/ARO-3501
Align managed services + allow autonode sizing on masters.  
https://github.com/openshift/managed-cluster-config/blob/master/deploy/kubelet-config/01-kubelet-config.yaml
Create cluster, enable autonode sizing, ensure it applies to masters & workers.  Profit
no
=> AutoSized Nodes now reference both masters and workers

cmd/aro/update_ocp_versions.go, pkg/cluster/install_version_test.go, pkg/cluster/version.go, pkg/frontend/frontend.go, pkg/frontend/openshiftcluster_preflightvalidation_test.go, pkg/frontend/openshiftcluster_putorpatch_test.go, pkg/frontend/validate.go, pkg/util/cluster/cluster.go, pkg/util/liveconfig/hive.go, pkg/util/version/const.go, pkg/util/version/version.go, pkg/util/version/version_test.go
Fixes https://issues.redhat.com/browse/ARO-3276
Allows us to push installer images without having them affect the entire fleet at once and in an inconsistent manner.  
Right now here's how it happens:
1. Push a new installer image
2. imagePullPolicy on hive is `IfNotPresent`
3. If the node has the image cached, it will use the older installer image
4. if the node does not have the image cached, it will use the new installer image
our e2e will be inconsistent after an installer image push, and there's no guarantee around which image is used and when only the newer images are used. 
1. Roll out this change via `update_ocp_versions`
2. Run an e2e
3. Check the installer image being used is being pulled with image digest
Yes. TBD
High level:
1. Push new image to all ACRs
5. Update the SHAs …
=> Installer images use sha256

pkg/monitor/cluster/cluster.go, pkg/monitor/cluster/healthz.go
Fixes https://issues.redhat.com/browse/ARO-3330
1. Scrape metric for API server ping health. This will be used as a signal for Azure Resource Health check.
2. Use API server ping check to determine if other metrics should be scraped. This replaces the current logic of using the API server healthz status code. That status code is now checked after the ping health check.
INT deployment
Yes:  https://msazure.visualstudio.com/AzureRedHatOpenShift/_wiki/wikis/AzureRedHatOpenShift.wiki/484208/API-Server-Unreachable
=> Add API Server Reachability Check

docs/deploy-development-rp.md
None
Fixes
None
Add logging aliases for viewing rp logs in a friendly manner. Fix spelling
Fix/Improve markdown formatting for readability
Update "Create your own RP Database" step to only redirect stdout, in case there's an error it's best to print to the screen. Update Azure Red Hat OpenShift Cluster creation documentation to reference version 4.
NA
NA
=> Minor Updates to deploy-development-rp documentation

pkg/monitor/cluster/cluster.go, pkg/monitor/cluster/healthz.go
Fixes https://issues.redhat.com/browse/ARO-3330
1. Scrape metric for API server ping health if the healthz check returns a non 200. This will be used as a signal for Azure Resource Health check.
INT deployment
Yes:  https://msazure.visualstudio.com/AzureRedHatOpenShift/_wiki/wikis/AzureRedHatOpenShift.wiki/484208/API-Server-Unreachable
=> Ping after healthz

.pipelines/e2e.yml
=> Try and fix the e2e mustgather

.gdn/.gdnsuppress, pkg/util/pullsecret/extract_test.go
Note that the .gdnsuppress file generated by the pipeline now is "hydrated" with all identifying information removed, including the file location by default.
Fixes
[Vendored docker swagger api document causing errors.](https://msazure.visualstudio.com/AzureRedHatOpenShift/_build/results?buildId=76389191&view=logs&j=096205eb-4599-56da-affa-13246cc49eac&t=7e5c3140-9b2b-5395-0e58-9e02fe0de382&l=89) 
Updates unit test to not trigger guardian credscan.
[New guardian rules are causing an old test to throw an error](https://msazure.visualstudio.com/AzureRedHatOpenShift/_build/results?buildId=76389191&view=logs&j=096205eb-4599-56da-affa-13246cc49eac&t=7e5c3140-9b2b-5395-0e58-9e02fe0de382&l=83)
=> Update guardian suppression rules

docs/prepare-your-dev-environment.md
Fixes https://issues.redhat.com/browse/ARO-3710
Adds documentation for starting podman in your development environment
Tested commands locally 
Docs update
=> Add podman container install docs

pkg/util/steps/condition.go, pkg/util/steps/runner_test.go
Does not fix [ARO-1558](https://issues.redhat.com/browse/ARO-1558), but provides further clarity in log messages when the below issue is encountered
This change will wrap all `ErrWaitTimeout` errors (`"timed out waiting for the condition"`) returned within our steps runner. 
The `wait.PollImmediateUntil()` function used within our Condition checker returns an `ErrWaitTimeout` of its own when the condition is not met within the specified timeout, leading internal errors within the conditions that match `ErrWaitTimeout` to appear identical to conditions that legitimately time out. 
A unit test was added to the runner tests to handle this specific case. 
No.
- The wrapped error will still match `ErrWaitTimeout` (e.g. `errors.Is(err, wait.ErrWaitTimeout)` returns `true`). If we would like to …
=> Wrap Timeout errors within Condition steps

pkg/operator/controllers/dnsmasq/machineconfig_controller.go, pkg/operator/controllers/dnsmasq/machineconfig_controller_test.go
JIRA: https://issues.redhat.com/browse/ARO-3254
Fixes
=> Propagate errors of ARO DNSMasqMachineConfig controller

python/az/aro/azext_aro/_client_factory.py, python/az/aro/azext_aro/_params.py, python/az/aro/azext_aro/_validators.py, python/az/aro/azext_aro/commands.py, python/az/aro/azext_aro/custom.py, python/az/aro/azext_aro/tests/latest/unit/test_validators.py
Fixes https://issues.redhat.com/browse/ARO-1478
Bumps api version used and adds parameter `--outbound-type` to az aro cli extension for public IP removal.  OutboundType can be Loadbalancer in all cases of apiserver/ingress visibility but OutboundType of UserDefinedRouting is only valid if both apiserver and ingress are private.  This should probably not not be merged until the next stable API is released.
Added unit tests and created clusters with OutboundType of UserDefinedRouting and Loadbalancer.
Yes, the [Azure Doc](https://learn.microsoft.com/en-us/azure/openshift/howto-create-private-cluster-4x#create-a-private-cluster-without-a-public-ip-address-preview) will need to be updated though that will be a separate effort.
=> add outbound-type param to az cli extension

pkg/util/steps/condition.go, pkg/util/steps/condition_test.go
Currently, all conditions steps return InternalServerError and only looking at the RP logs will give detailed understanding on the failure, this PR attempts to change this by adding a wrapper function to exiting poll function to return readable error.
Fixes: https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/9224646
Add Unit tests for AdminUpdate and Test_Runner
This PR is based on implementation done by David here: https://github.com/Azure/ARO-RP/pull/1863
=> Refactor conditions to return error

pkg/frontend/admin_openshiftcluster_etcdrecovery.go, pkg/frontend/admin_openshiftcluster_etcdrecovery_test.go, pkg/frontend/admin_openshiftcluster_kubernetesobjects.go, pkg/frontend/admin_openshiftcluster_kubernetesobjects_test.go, pkg/frontend/adminactions/kubeactions.go, pkg/frontend/fixetcd.go, pkg/frontend/fixetcd_test.go, pkg/frontend/frontend.go, pkg/frontend/scripts.go, pkg/frontend/scripts/backupandfixetcd.sh, pkg/util/mocks/adminactions/adminactions.go
Fixes
https://issues.redhat.com/browse/ARO-1534
In the event that a master node changes IP addresses (or NIC's) the etcd quorum will become degraded. The node with the change will then have it's etcd pod in a crashloop. This is due to the hardcoded etcd spec.
This PR adds the remediation type EtcdRecovery maintenance task to remediate this issue.
1. Verify this is the issue by comparing etcd's env variables to the node's IP address. a degradedEtcd object is returned with relevant information.
1. Create a batch job to backup etcd's data directory and move the etcd manifest to stop the pod from crash looping.
1. A batch job is created to run a pod that ssh's into the peer etcd container's to remove the failing node from it's member list.
1. Secret's for the failing pod are deleted
1. Etcd …
=> Recover etcd master endpoint

pkg/operator/controllers/clusteroperatoraro/clusteroperatoraro_controller_test.go
None
Add additional test coverage for the clusteroperatoraro controller, responsible for populating the ARO Cluster Operator resource. 
The tests specifically cover the issue found and fixed in #2903 by validating that the version remains set on the resource on all Reconcile scenarios.  
The PR is just tests
No.
=> Add tests for clusteroperatoraro controller

pkg/util/steps/condition.go, pkg/util/steps/condition_test.go
N/A (fixes broken unit test)
Update error enrichment in Condition step to return original error if condition function is unknown. 
1. Run unit tests
2. Ensure they pass
No
=> Fix condition step tests

docs/az-aro-python-development.md, docs/deploy-development-rp.md, docs/prepare-your-dev-environment.md
Day of Learning activity
Clarifies various confusion points around our usage of and contribution to the Azure CLI. 
Additionally, removes specific instructions for upstreaming changes to the Azure CLI as these instructions will be contained within internal product release documentation. 
Documentation changes only, no tests
Yes
I have not made any functional changes or changes to any processes as a part of this pull request, however there are opportunities for them:
- Change our python requirements.txt to install the Azure CLI via pip, rather than expecting it be available system-wide
- Outright require the usage of the pyenv for development setup
- This would help avoid incompatibilities with specific versions of Python, the Azure CLI, etc, and ensure development is done with a …
=> Improve Documentation on Azure CLI and `az aro` command

hack/cluster/cluster.go, pkg/env/env.go
https://issues.redhat.com/browse/ARO-3536
Fixes
Error handling when env variable "CLUSTER" is blank. 
Running hack create script throws a mem issue if it's just an empty "CLUSTER" env variable.
Run hack create script.
No
=> ARO-3536: Add error handling when "CLUSTER" env variable is empty.

pkg/operator/controllers/checkers/ingresscertificatechecker/controller.go
N/A
This PR removes a redundant if statement.
err is already checked on L59 and err doesn't change till L70.
existing tests verify the functionality.
tech debt cleanup
=> remove redundant if statement

pkg/containerinstall/install.go, pkg/containerinstall/install_test.go, pkg/containerinstall/podman.go
Fixes the need for further docs in https://issues.redhat.com/browse/ARO-3710
It doesn't matter if this runs as 0, since rootless podman should do it fine.
CI/E2E
N/A
=> Don't use the uid in containerinstall code

pkg/deploy/predeploy.go, pkg/deploy/predeploy_test.go
Jira - https://issues.redhat.com/browse/ARO-3240
Fixes
Remove the gateway restart during the predeploy which was added as part of PR https://github.com/Azure/ARO-RP/pull/2946 because the rotated encryptions secrets are not used by gateway and the gateway service doesn't need the restart during predeploy
Updated Unit Test Cases
No
=> remove gateway restart during rp predeploy

pkg/cluster/ipaddresses.go
Will help identify issues with cluster errors for linkId conflicts.
https://issues.redhat.com/browse/ARO-3750
This will have more verbose error logging for us to be able to connect if a linkId is being reused on cluster installation failures, or if Azure has a bug with linkId reuse.  
We're still seeing cluster installations fail because of this error message, and we don't log the linkId anywhere so we don't know which cluster it is conflicting with.  This will explicitly error out which cluster has the conflict and what the linkID is, so we can go in and examine if there's a race condition in our code, or if we need to file a bug with the NRP team.
=> Add more information to on conflict for gateway PE linkId

pkg/cluster/deploybaseresources.go, pkg/cluster/deploybaseresources_test.go
Cleans up some unnecessary code & checks on installs.  
Also ensures the location and managedBy fields are as expected, otherwise fails out.
https://issues.redhat.com/browse/ARO-3749
When this was implemented, the [FPSP Service Role](https://msazure.visualstudio.com/One/_git/AD-RBAC-RoleDefinitions?path=/MICROSOFT.REDHATOPENSHIFT/PROD/AzureRedHatOpenShiftRP%20Service%20Role.json) did not contain the ResourceGroup Read permissions when a customer registered for our resource provider.  The RBAC has since been updated.  
Only place to test this is in prod or INT.  
Will update with testing notes afterwards.  
```bash
$ az group show -n bvesel
{
"id": "/subscriptions/<sub>/resourceGroups/bvesel",
"location": "eastus",
"managedBy": null,
"name": "bvesel",
"properties": {
"provisioningState": …
```
=> Remove the provisioning state check around ensure managed rg

.golangci.yml, pkg/api/util/subnet/const.go, pkg/api/util/subnet/subnet.go, pkg/api/util/subnet/subnet_test.go, pkg/api/v20191231preview/openshiftcluster_validatestatic.go, pkg/api/v20200430/openshiftcluster_validatestatic.go, pkg/api/v20210901preview/openshiftcluster_validatestatic.go, pkg/api/v20220401/openshiftcluster_validatestatic.go, pkg/api/v20220401/openshiftcluster_validatestatic_test.go, pkg/api/v20220904/openshiftcluster_validatestatic.go, pkg/api/v20220904/openshiftcluster_validatestatic_test.go, pkg/api/v20230401/openshiftcluster_validatestatic.go, pkg/api/v20230401/openshiftcluster_validatestatic_test.go, pkg/api/v20230701preview/openshiftcluster_validatestatic.go, pkg/api/v20230701preview/openshiftcluster_validatestatic_test.go, pkg/api/v20230904/openshiftcluster_validatestatic.go, pkg/cluster/deploybaseresources.go, pkg/cluster/nsg.go, pkg/frontend/adminactions/resources_list.go, pkg/operator/controllers/subnets/subnet_controller_test.go, pkg/operator/controllers/subnets/subnet_nsg.go, pkg/operator/deploy/deploy.go, pkg/util/subnet/cluster_subnets.go, pkg/util/subnet/subnet.go, pkg/util/subnet/subnet_test.go, pkg/validate/dynamic/dynamic.go, test/e2e/adminapi_resources.go, test/e2e/operator.go
Fixes https://issues.redhat.com/browse/ARO-3574
Moves `pkg/api/` dependencies of `pkg/util/subnet/` into `pkg/api/util/subnet` so that `pkg/api` does not have cross-package dependencies.
Unit tests should continue to pass
N/A, refactor
=> Move pkg/api dependencies on util/subnet to api/util/subnet

hack/e2e/run-rp-and-e2e.sh
Fixes e2e on master
Pins Selenium Grid to a known working version
E2E
N/A
=> Pin to selenium grid 4.10

pkg/operator/controllers/checkers/ingresscertificatechecker/controller.go, pkg/operator/controllers/monitoring/monitoring_controller.go, pkg/operator/controllers/monitoring/monitoring_controller_test.go
https://issues.redhat.com/browse/ARO-2998
Aggregate errors of the monitoring controller through the aro controller. Precedent and reference here:
https://github.com/SrinivasAtmakuri/ARO-RP/blob/b025e278676744aeea0a01095c7854bf2f[…]9c/pkg/operator/controllers/dnsmasq/machineconfig_controller.go
10:31
https://github.com/Azure/ARO-RP/pull/2965/files
Local tests pass, error propagation will happen and be checked in INT
No
=> Aro 2998 monitoring errors

pkg/util/version/const.go
[ARO-3789](https://issues.redhat.com/browse/ARO-3789): Add 4.12 stream to RP
This change enables 4.12.25 to be rolled out with Official Update Version pipelines.
- 4.12.25 smoke tests:
- https://docs.google.com/document/d/111lzrW_IgwQkPYLRWEEC45KPT2mA47yhapl2v2F7-dQ/edit
- https://docs.google.com/document/d/1YnZ93drfaPjg0uW0Kvrau67eTGskhK7akKBaSLTfdmk/edit
- Temporary draft PR used to test E2E: https://github.com/Azure/ARO-RP/pull/3063
No
=> Adding 4.12 install streams

.github/workflows/codeql-analysis.yml, .pipelines/ci.yml
Fixes ARO-3957
* Removes Golang CodeQL check from ADO CI pipeline
* Adds Golang CodeQL check to the existing GitHub Action, but uses a hosted 1ES pool for golang
This is a presubmit CI job, so a green test here means :shipit: 
Yes, will need to document the 1ES pool
=> Fix CodeQL GitHub Action

.github/workflows/ci-go.yml, .github/workflows/codeql-analysis.yml, .github/workflows/golint.yml, .github/workflows/maintenance.yml, .github/workflows/npm-audit.yml, .github/workflows/release-note.yml, .github/workflows/yamllint.yml
Follow up related to ARO-3957
This updates the formatting/permissions/triggers for our existing GitHub Actions to ensure they are secure and only have the minimum permissions they need.
The existing external GH actions we use are all allow-listed here: https://github.com/Azure/ARO-RP/settings/actions
No
=> Update formatting/permissions/triggers for GH Actions

pkg/cluster/delete.go
Fixes deletion of Microsoft.Compute/galleries resources 
Related to hard-ticket: 408127395
Tested locally, we don't have a mock-setup for this, we'd have to integration or e2e test it in order to ensure it works as expected, but it's in the deletion code path.  
nope
=> Add priority deletion ordering of nested Microsoft.Compute/galleries resources

pkg/frontend/admin_openshiftcluster_approvecsr.go, pkg/frontend/admin_openshiftcluster_cordonnode.go, pkg/frontend/admin_openshiftcluster_drainnode.go, pkg/frontend/admin_openshiftcluster_etcdrecovery.go, pkg/frontend/admin_openshiftcluster_etcdrecovery_test.go, pkg/frontend/admin_openshiftcluster_kubernetesobjects.go, pkg/frontend/admin_openshiftcluster_kubernetesobjects_test.go, pkg/frontend/adminactions/kubeactions.go, pkg/frontend/validate.go, pkg/frontend/validate_test.go, pkg/util/mocks/adminactions/adminactions.go
Part of cleanups for https://issues.redhat.com/browse/ARO-3812
Gets rid of one usage of our custom GVRResolver, and instead uses the one from controller-runtime which is capable of doing the refreshing we need.
This means we don't use the cache, but in situations where that matters we often didn't have much luck getting the APIServer to do anything.
E2E?
N/A
=> Remove gvrresolver use in the frontend

pkg/util/steps/condition.go, pkg/util/steps/condition_test.go
With PR: https://github.com/Azure/ARO-RP/pull/2450 merged, I have added cluster installation failed in the error message and step hiveClusterDeploymentReady will also be run during the Update path, the existing error message will confuse customers.
This PR modifies the error message by removing the install word in the error.
Fixes
=> Remove install word in Condition error messages

pkg/api/defaults.go, pkg/operator/controllers/dnsmasq/cluster_controller.go, pkg/operator/controllers/dnsmasq/dnsmasq.go, pkg/operator/controllers/dnsmasq/dnsmasq_restart.go, pkg/operator/controllers/dnsmasq/machineconfig_controller.go, pkg/operator/controllers/dnsmasq/machineconfigpool_controller.go, pkg/operator/controllers/dnsmasq/scripts.go, pkg/operator/controllers/dnsmasq/scripts/99-dnsmasq-restart.gotmpl, pkg/operator/controllers/dnsmasq/scripts/aro-dnsmasq-pre.sh.gotmpl, pkg/operator/controllers/dnsmasq/scripts/dnsmasq.conf.gotmpl, pkg/operator/controllers/dnsmasq/scripts/dnsmasq.service.gotmpl
Fixes
https://issues.redhat.com/browse/ARO-3474
https://issues.redhat.com/browse/ARO-3468
If the network interfaces are brought up/down without restarting NetworkManager, our resolv.conf will be overwritten by NetworkManager. This can occur during [Azure Host Servicing](https://learn.microsoft.com/en-us/azure/developer/intro/hosting-apps-on-azure) events.
See [NetworkManager-dispatcher](https://networkmanager.dev/docs/api/latest/NetworkManager-dispatcher.html) documentation for more information, such as available actions.  
The second commit cleans up the dnsmasq controller package by embedding all Go templates, and moving them into their own files within `pkg/operators/controllers/dnsmasq/scripts`.
**Operator flag has been set to true**
Tested on a dev cluster with, I have created a …
=> Fix resolv.conf during Azure host servicing

go.mod, vendor/modules.txt
Followup from https://github.com/Azure/ARO-RP/pull/3119
We don't actually need this anymore since we moved to controller-runtime
N/A
=> Remove the unneeded replace for hive

cmd/aro/operator.go, pkg/api/defaults.go, pkg/operator/controllers/cloudproviderconfig/cloudproviderconfig_controller.go, pkg/operator/controllers/cloudproviderconfig/cloudproviderconfig_controller_test.go, test/e2e/operator.go
Fixes ARO-3112
Adds a controller the ARO operator to watch and maintain the `cloud-provider-config` in the `openshift-config` namespace.
As a part of the roll out Public IP functionality changes we need to set the setting disableOutboundSNAT to true on load balancers. This can be managed using the `cloud-provider-config`.
Unit tests and e2e tests were added for this controller.
Functional testing was done by doing the following:
1. Created a new ARO cluster in Azure
2. Ran the operator locally against this new cluster with different settings in `cloud-provider-config`
Tested the following scenarios:
- cloud-provider-config has `disableOutboundSNAT: null` -> Set to true
- cloud-provider-config has `disableOutboundSNAT: false` -> Set to true
- cloud-provider-config has `disableOutboundSNAT: …
=> ARO-3112: Set DisableOutbound SNAT to true on Load Balancers

pkg/cluster/clusterserviceprincipal.go, pkg/cluster/clusterserviceprincipal_test.go
Fixes [ARO-2898](https://issues.redhat.com/browse/ARO-2898)
Recreates the `azure-credentials` secret if it has been deleted.
The implementation uses [server-side apply](https://kubernetes.io/docs/reference/using-api/server-side-apply/) to accomplish this task. Since SSA as a concept is new to the code base I am going to annotate the PR a bit more than normal.
Unit tests in `clusterserviceprincipal_test.go` updated for new behavior.
Previous code failed because of missing `Force` parameter in apply action (see annotations).
=> Fix credential rotation failure

pkg/util/azureclient/mgmt/network/loadbalancers.go
Fixes broken validateResources call in FF.
[ARO-4090](https://issues.redhat.com/browse/ARO-4090)
The previous client did not specify the Resource Manager endpoint, which results in it defaulting to Azure public cloud.  Change the client to be Cloud-aware.
FF INT e2e test. 
No
=> Specify the resource manager endpoint for the lb backend pool client

pkg/util/namespace/namespace.go, pkg/util/namespace/namespace_test.go
allow GetKubernetesObjects GA to retrieve deployment status of Guardrails
add openshift-azure-guardrails to openshift ns to allow GetKubernetesObjects GA to retrieve deployment status of Guardrails
NA
NA
=> added guardrails namespace

.gitignore
Right now our .gitignore just ignores *.kubeconfig (such as `aks.kubeconfig`) but not `kubeconfig`. If you run `az aro get-admin-kubeconfig` in the repo against a local or prod RP, the kubeconfig that's generated is not ignored.
- touch aks.kubeconfig (confirm no git changes)
- touch kubeconfig (confirm no git changes)
No
=> Fix .gitignore for kubeconfigs

.github/workflows/ci-go.yml, .github/workflows/codeql-analysis.yml, .github/workflows/golint.yml
N/A
When setting up go in our GitHub Actions, always use the go version from the go.mod file. One less thing to bump :)
No
=> Use go version from go.mod

pkg/operator/controllers/machinehealthcheck/doc.go, pkg/operator/controllers/machinehealthcheck/staticresources/machinehealthcheck.yaml
Fixes https://issues.redhat.com/browse/ARO-4040
=> increase machine health check node unready timeout to 15m

cmd/aro/mirror.go
Partially fixes https://issues.redhat.com/browse/ARO-3850 
- Removes `quay.io/bvesel/hive:fec14dcf0-20230623`
- Adds `quay.io/app-sre/hive:70b666ec89`
- Hive smoke testing done by QE (see https://redhat-internal.slack.com/archives/C02ULBRS68M/p1692714810403069). Applying a `hold` label until we have a green light.
No, just an internal change.
=> Mirror the hive version we intend to upgrade to

pkg/operator/controllers/genevalogging/const.go
Fixes https://issues.redhat.com/browse/ARO-1414
Reduces logging by removing more customer-owned openshift- namespaces that we don't need to collect.
E2E should tell us if it breaks things :)
N/A
=> Exclude some more log namespaces

go.mod, vendor/modules.txt
Follow up to #3143 
There's a few versions in the require section of go.mod that show incorrect/incompatible versions that are then being overridden by replace.. but because they are incorrect in the require section, our code vuln tools aren't showing that they have been updated.
This change should be strictly cosmetic.
Green CI == :shipit:
No
=> Fix kube versions in go.mod

test/database/openshiftclusters.go
Fixes:
https://github.com/Azure/ARO-RP/security/code-scanning/1
https://github.com/Azure/ARO-RP/security/code-scanning/2
Fixes an incorrect and unnecessary string to int64 to int conversion.
No
=> Fix string to int conversion

cmd/aro/mirror.go
This updates the mirroring to be 4.10+ and includes UBI9 base images, as well as Mariner azure-cli.
It also updates the MUO mirroring to the latest promoted release.
merge, see if int works?
=> Update mirroring targets to 4.10+ and add UBI9

Dockerfile.aro-e2e, Dockerfile.aro-multistage, Dockerfile.ci, Dockerfile.proxy, pkg/containerinstall/install_test.go
Fixes E2E, oops
Updates us  to use Go 1.18.10 rather than 1.18.4 that I deleted from arointsvc thinking it wasn't used :thinking: 
CI/E2E
N/A
=> update to go 1.18.10

pkg/deploy/assets/cluster-development-predeploy.json, pkg/deploy/generator/resources_cluster.go, pkg/validate/dynamic/dynamic.go, pkg/validate/dynamic/dynamic_test.go
Fixes a nil pointer dereference in cluster creation due to addressPrefix not being set during cluster creation.  
Switch between addressPrefix and addressPrefixes on subnets.  
e2e & green ci 
nope
=> Fix nil pointer dereference in subnet validation

pkg/operator/controllers/muo/muo_controller_test.go, pkg/util/version/const.go, test/e2e/operator.go
https://issues.redhat.com/browse/ARO-4088
This PR follows PR #3147
Bump up MUO image to include recent bugfixes
**NOTE** E2E tests for the PR have passed (see [here](https://msazure.visualstudio.com/AzureRedHatOpenShift/_build/results?buildId=79463173&view=logs&j=10f66467-59e5-53bc-0c8a-42cc89770de4&t=8530e8d4-fb46-5697-903b-6bef07c9756d)), however the pipeline was cancelled by Azure during cleanup phase.
Smoke test run manually:
- Create new 4.11.44 cluster (no upgrade history), which runs **aro-b4** MUO image
- Create UpgradeConfig aiming for 4.12.25 and confirm MUO pods CrashLoopBackoff
- Upgrade MUO to **v0.1.952** and confirm pods get into Running and upgrade starts
- Wait for Upgrade completion and check pods are Running and history shows in UpgradeConfig
- Create UpgradeConfig …
=> Bumping up MUO to v0.1.952

pkg/cluster/loadbalancerprofile.go, pkg/cluster/loadbalancerprofile_test.go
Skips reconciling when architecture is version 1 as this feature is only needed/tested against v2.
Unit Tests
=> skip lb profile reconcile when arch is v1

test/e2e/adminapi_cluster_getlogs.go
Fixes
Currently this test isn't passing in e2e. Looking at the pod definition for the test the quay image probably doesn't exist anymore. Trying switching it to the local stream as a public image or image off cluster is not required for this test.
E2E should become green again. If this test passes we win.
No
=> Update adminapi_cluster_getlogs.go with new pod image to fix e2e

pkg/util/version/const.go
https://issues.redhat.com/browse/ARO-2720
Make 4.12 the default install stream in ARO
=> Default to 4.12 for new installations

pkg/monitor/cluster/certificateexpirationstatuses.go, pkg/monitor/cluster/certificateexpirationstatuses_test.go, pkg/monitor/cluster/cluster.go
Fixes [ARO-2916](https://issues.redhat.com/browse/ARO-2916)
Creates a monitor to report expiration dates of certificates that are managed by the RP. The Geneva certificate is always monitored, ingress and API certificates are only monitored if the cluster's domain is not custom.
Unit tests for both managed and unmanaged domains.
=> create monitor for certificate expirations

.github/dependabot.yml
N/A
Adds dependabot config specific to GH actions to open auto-bump PRs when needed
No
=> Add dependabot to auto-bump GH actions versions when needed

pkg/monitor/cluster/certificateexpirationstatuses.go, pkg/monitor/cluster/certificateexpirationstatuses_test.go, pkg/monitor/cluster/cluster.go, pkg/util/cert/cert.go
For clusters running version <4.9, emit daysUntilExpiration metric for etcd peer, serving, serving-metrics certificates present in openshift-etcd namespace when close to expiry (when less than 20% of duration is remaining) so SRE can be alerted
JIRA: https://issues.redhat.com/browse/ARO-3994
=> New Monitor to emit ETCD certificates expiration

.github/workflows/ci-go.yml, Dockerfile.ci
Hopefully fixes ADO pipeline software supply chain warnings
Dynamically take the dockerfile registry as a build argument. 
ci + e2e green + no longer alerting on build arg issue :shipit: 
no
=> Update Dockerfile.ci to use buildarg for registry name

pkg/util/azureclient/applens/applens_client_test.go, pkg/util/azureclient/applens/applens_error_test.go, pkg/util/azureclient/authz/remotepdp/client_test.go, test/util/http/server/server_mock.go, test/util/http/server/server_mock_test.go
Fixes https://issues.redhat.com/browse/ARO-4264 (partial)
This is an initial refactor to make subsequent changes that allow tests to mock HTTP client calls via mocking httpTransport. This refactor changes the name of this package to reflect its directory name, and also allows us to extend the changes to have a `test/util/http/client` library alongside it.
Current build and tests should pass to prove this rename works. This is only a refactor of current test related code.
N/A
=> Refactor /test/util/applens package names/directories

pkg/cluster/delete.go
This will now fail deletion if we fail to clean up hive resources.  This will ensure we don't leave orphaned hive resources in the hive cluster.
=> Return error if we fail to delete hive resources during deletion

pkg/cluster/ipaddresses.go
Fixes an incorrect check against the resourceId vs the linkIdentifier, resulting in a failed cluster creation and ServerError
[Fixes an incorrect install error.  ](https://issues.redhat.com/browse/ARO-4246)
=> Fix bad logic comparison against an already existing gateway record

python/az/aro/azext_aro/_client_factory.py, python/az/aro/azext_aro/_dynamic_validators.py, python/az/aro/azext_aro/_params.py, python/az/aro/azext_aro/_validators.py, python/az/aro/azext_aro/commands.py, python/az/aro/azext_aro/custom.py, python/az/aro/azext_aro/tests/latest/unit/test_dynamic_validators.py, python/az/aro/azext_aro/tests/latest/unit/test_validators.py, python/az/aro/linter_exclusions.yml
Fixes [ARO-3103](https://issues.redhat.com/browse/ARO-3103)
Implicitly fixes [ARO-2467](https://issues.redhat.com/browse/ARO-2467) as well
Implements support within the `az aro update` command in the ARO extension for the managedOutboundIps.Count property on the cluster load balancer profile, implemented in the 2023-07-01 preview API. 
On a provisioned ARO cluster, managed by an RP with the 2023-07-01 preview API (e.g. local dev):
- Run `az aro update --help` and validate that the `--load-balancer-managed-outbound-ip-count` flag and information is present
- Run `az aro update --load-balancer-managed-outbound-ip-count $NUMBER` for numbers != 1 and ensure that the resulting cluster document has property `openShiftCluster.properties.networkProfile.loadBalancerProfile.managedOutboundIps.count` …
=> `az aro update` `--load-balancer-managed-outbound-ip-count` flag support

pkg/api/admin/openshiftcluster_convert.go, pkg/api/v20230904/openshiftcluster_convert.go, test/e2e/adminapi_cluster_update.go
Fixes the following bugs:
* PUCM failing due to a bug in converting workerProfilesStatus
* Ensures in our e2e we check for a successful PUCM, instead of PUCM finishing
* Fixes (by fixing the PUCM failure) the e2e portal test, since PUCM succeeds, we now expect 10 columns to be present (since `lastAdminUpdateError` isn't present if PUCM succeeds).  
Poem about debugging ARO portal tests: 
```
In the ARO Portal's digital expanse so wide,
A bug did lurk, in the e2e test it did hide,
A challenge to conquer, a puzzle to unfold,
In the realm of code, where mysteries are bold.
With browsers as allies, and scripts as their sword,
Testers embarked on a mission, united and assured,
To hunt down the bug, that elusive foe,
In the ARO Portal's world, where the issues grow.
They scrutinized each line, …
```
=> Fix WorkerProfilesStatus PUCM Bug

pkg/cluster/acrtoken.go, pkg/util/clusterdata/worker_profile.go
Fixes https://issues.redhat.com/browse/ARO-4304
Due to the nature of acr token passwords, this will be tested manually
=> rotate the openshift-config pull-secret on acr token rotation

pkg/util/version/const.go
Reverts Azure/ARO-RP#3171
Due to install success effecting Error: https://issues.redhat.com/browse/ARO-4306
=> Revert "Default to 4.12 for new installations"

pkg/cluster/acrtoken.go
Fixes a bug where the update doesn't proceed if the pull-secret has been modified.
=> retry operations on pull-secret when receiving a conflict

pkg/frontend/openshiftcluster_putorpatch.go, pkg/frontend/openshiftcluster_putorpatch_test.go
Fixes bug that causes customer confusion when they randomly get update message.
Prevent customer confusion.
INT testing
https://msazure.visualstudio.com/AzureRedHatOpenShift/_wiki/wikis/AzureRedHatOpenShift.wiki/457767/ARO-Signals-for-Azure-Monitor
=> Don't Put Cluster in Update State after PUCM Pending

pkg/api/admin/openshiftcluster_convert.go, pkg/frontend/openshiftcluster_putorpatch_test.go
Fixes an issue where our powershell scripts rely on a field that will never be unmarshalled.  
Powershell relies on it
green e2e
=> Convert the pucm pending boolean in the AdminAPI

pkg/util/restconfig/restconfig.go
In client-go 0.26.0+, every time you create a new client, there is a new entry created in TLS cache.  The memory leak is described by https://github.com/kubernetes/kubernetes/issues/118703. That issue has not been resolved at the time of this writing, but describes a couple of workarounds. Try the one described in https://github.com/kubernetes/kubernetes/issues/118703#issuecomment-1595072383:
For now, I would probably just set the Proxy func to
utilnet.NewProxierWithNoProxyCIDR(http.ProxyFromEnvironment) so that
the TLS cache is skipped for your code. This isn't guaranteed behavior
and may stop working at any time, but it will at least solve the issue
for you for now (by restoring the old behavior).
We don't use client-go v0.26.0, but while this issue is fresh in our minds we will set …
=> Prevent memory leaks with DialContext usage and new k8s client creation

pkg/api/v20230904/openshiftcluster_validatestatic.go, pkg/api/v20230904/openshiftcluster_validatestatic_test.go
Fixes: https://issues.redhat.com/browse/ARO-4391
Check workerProfilesStatus is nil only during cluster creation. 
Updated existing unit test to confirm the workerProfilesStatus is validated to be nil during cluster creation.
Bug fix, N/A
=> workerProfilesStatus static validate

pkg/cluster/delete.go, pkg/cluster/delete_test.go
Fixes [ARO-4436](https://issues.redhat.com/browse/ARO-4436)
Currently, during cluster deletion, the RP will silently succeed if it does not have the permissions to delete the ARO-managed resource group for the cluster. This PR changes the behavior to fail the delete operation. 
The PR also refactors the deletion logic to be simpler, taking advantage of new permissions added to the RP FPSP to read resource groups. 
Unit tests have been added for some of the logic around deciding when to delete, and how to handle deletion errors, though the entire deletion flow is not unit tested. 
N/A
=> Fail cluster deletion if RP is not authorized to delete managed resource group

pkg/api/openshiftversion.go
Split off from https://github.com/Azure/ARO-RP/pull/3094, related to [[ARO-3896] Read default OCP version from CosmosDB](https://issues.redhat.com/browse/ARO-3896)
See my [comment in #3094](https://github.com/Azure/ARO-RP/pull/3094#issuecomment-1749002036).  This is phase 1 of the deployment.  The RP needs to be aware of the default version flag before the default version flag can be rolled out to CosmosDB.
Manual testing.
No.
=> api: Add Default field to OpenShiftVersionProperties

pkg/api/openshiftversion.go
Follow-up to https://github.com/Azure/ARO-RP/pull/3202, related to [[ARO-3896] Read default OCP version from CosmosDB](https://issues.redhat.com/browse/ARO-3896)
Discovered the culprit behind the [complications to default OpenShift version deployment](https://github.com/Azure/ARO-RP/pull/3094#issuecomment-1749002036) was `OpenShiftVersionProperties` lacking a `MissingFields` field, which would have absorbed the initially-unknown `Default` flag from CosmosDB and obviated the need for two RP releases.
No need for testing, this is just correcting an oversight so we don't encounter this situation again.
No, internal change only.
=> api: Add MissingFields to OpenShiftVersionProperties

pkg/cluster/deploybaseresources.go, pkg/cluster/deploybaseresources_additional.go, pkg/cluster/deploybaseresources_test.go, pkg/cluster/storageaccounts.go, pkg/operator/controllers/storageaccounts/storageaccount_controller.go, pkg/operator/controllers/storageaccounts/storageaccounts.go, pkg/operator/controllers/storageaccounts/storageaccounts_test.go, test/e2e/cluster.go, test/e2e/setup.go, test/util/project/project.go
Fixes [ARO-4450](https://issues.redhat.com/browse/ARO-4450)
to properly use `azurefile-csi` storage class that comes out of the box in openshift, the worker / master virtual machine must be able to talk to the cluster storage account.  
Set Network ACLs on the cluster storage account during Creation & AdminUpdate only if the Microsoft.Storage service endpoint is set on the subnets.  
There will be an e2e test that will run against production clusters to ensure this works based on the storage account controller.  
We can test this as follows though: 
- Disable the storage account controller
- Disable the service endpoints controller
- Disable `ensureServiceEndpoints` step in RP for dev clusters only
- Remove NACLs from cluster storage account
- Set service endpoints on one or all cluster …
=> Network acl fix for storageaccounts on Create or AdminUpdate

test/e2e/adminapi_cluster_getlogs.go, test/e2e/adminapi_cluster_update.go, test/e2e/adminapi_kubernetesobjects.go, test/e2e/adminapi_redeployvm.go, test/e2e/cluster.go, test/e2e/operator.go, test/e2e/setup.go
N/A
When we use `Eventually().WithContext()`, the default Eventually timeout doesn't apply. We could either strip the context out, or explicitly add a timeout to any eventually calls that use WithContext. This goes for the latter.
https://onsi.github.io/gomega/#eventually
Green CI == :shipit:
=> Add eventually timeout when we use contexts

.github/workflows/maintenance.yml
N/A
Removes the `ready-for-review` label when a rebase is required.
No
=> Remove ready-for-review when rebase is required

python/az/aro/azext_aro/custom.py
N/A
GraphError doesn't have `message` attribute and az tries to access it which causes another error when it gets a GraphError.
https://github.com/Azure/azure-cli/blob/41927496c3c682e35b7f436b6f44c8d10b752387/src/azure-cli/azure/cli/command_modules/role/_msgrpah/_graph_client.py#L375
example
```
❯ az aro update -n shared-cluster -g shared-cluster --refresh-credentials
The behavior of this command has been altered by the following extension: aro
The command failed with an unexpected error. Here is the traceback:
'GraphError' object has no attribute 'message'
Traceback (most recent call last):
File "/usr/local/Cellar/azure-cli/2.50.0_1/libexec/lib/python3.10/site-packages/azure/cli/command_modules/role/_msgrpah/_graph_client.py", line 52, in _send
r = send_raw_request(self._cli_ctx, method, …
```
=> fix graph error handling

pkg/cluster/deploybaseresources_additional.go, pkg/deploy/assets/gateway-production.json, pkg/deploy/assets/rp-production-global.json, pkg/deploy/assets/rp-production.json, pkg/util/azureclient/apiversions.go
Fixes [ARO-4403](https://issues.redhat.com/browse/ARO-4403)
Enables infrastructure encryption on the ARO-provisioned cluster and imageregistry storage accounts, by updating to the Azure Storage 2019-06-01 API which supports the `requireInfrastructureEncryption` boolean. 
- Tested manual cluster creation with the change successfully
- E2E
No
=> Enable Double (infrastructure) Encryption on ARO-provisioned storage accounts 

pkg/deploy/assets/aks-development.json
Matches our AKS development version with production version defined in ARO-Pipelines bicept templates.
Deploy AKS in development mode
Nope.
=> Match AKS development version with production

cmd/aro/operator.go, pkg/operator/controllers/machinehealthcheck/machinehealthcheck_controller.go, pkg/operator/controllers/machinehealthcheck/machinehealthcheck_controller_test.go
Fixes - https://issues.redhat.com/browse/ARO-3256
Aggregates errors from the MachineHealthCheck controller and propagates to the ARO Operator.
As of now I think it must pass the local test cases after spinning up a test cluster and if case scenarios falls under the test conditions defined in code then error propagation will happen.
None that I'm aware of.
=> Propagate errors of ARO MachineHealthCheckController to ARO Operator

pkg/operator/controllers/machinehealthcheck/machinehealthcheck_controller.go, pkg/operator/controllers/machinehealthcheck/machinehealthcheck_controller_test.go, pkg/util/dynamichelper/dynamichelper.go, pkg/util/dynamichelper/dynamichelper_test.go
Fixes [ARO-4041](https://issues.redhat.com/browse/ARO-4041)
Adds the `cluster.x-k8s.io/paused=""` annotation to the `aro-machinehealthcheck` resource during cluster upgrades, and ensures the MachineHealthCheck controlle responsible for this resource requeues (every hour) during a cluster upgrade, in order to ensure the annotation is removed after the upgrade is complete. 
Updates DynamicHelper to preserve the Status when updating MachineHealthChecks. This fixes an existing bug where the MachineHealthCheck controller would delete the Status on the aro-machinehealthcheck on every reconciliation. 
- Unit tests were updated to ensure the controller requeues during cluster upgrades
- Due to limitations in the mock DynamicHelper used in the unit tests, it is not possible to ensure the …
=> Pause ARO MachineHealthCheck during cluster upgrades

pkg/api/admin/openshiftcluster.go, pkg/api/admin/openshiftcluster_convert.go, pkg/api/openshiftcluster.go, pkg/api/register.go, pkg/api/util/immutable/immutable.go, pkg/api/v20191231preview/openshiftcluster_convert.go, pkg/api/v20200430/openshiftcluster_convert.go, pkg/api/v20210901preview/openshiftcluster_convert.go, pkg/api/v20220401/openshiftcluster_convert.go, pkg/api/v20220904/openshiftcluster_convert.go, pkg/api/v20230401/openshiftcluster_convert.go, pkg/api/v20230701preview/openshiftcluster.go, pkg/api/v20230701preview/openshiftcluster_convert.go, pkg/api/v20230701preview/openshiftcluster_validatestatic_test.go, pkg/api/v20230904/openshiftcluster.go, pkg/api/v20230904/openshiftcluster_convert.go, pkg/frontend/openshiftcluster_putorpatch.go, pkg/swagger/typewalker.go, test/e2e/update.go
Fixes [[ARO-4223] BUG: Fix golang client PUT for GA](https://issues.redhat.com/browse/ARO-4223)
This pull request allows clients to successfully make PUT requests to update a cluster's `properties.networkProfile.loadBalancerProfile.managedOutboundIps` value.
The bug has to do with the `effectiveOutboundIps` field, also in the `loadBalancerProfile`.  This field is tagged as "read-only" in the API's Swagger specification, which means generated API clients will omit this field when making POST or PUT requests.  But due to its omission, the request was failing static validation because the comparison logic treated this as an attempt to modify the read-only field.
This pull request presents a generalized method for handling "read-only" API fields by using a `swagger:"readOnly"` tag in the …
=> BUG: Fix golang client PUT for GA

pkg/util/subnet/subnet.go, pkg/util/subnet/subnet_test.go
ARO-4516
We currently panic & dequeue 6 times when trying to fetch an IP address in a subnet where AddressPrefixes is used.  
Unit tests cover this case in the future.  
nope
=> Fix panic on addressPrefix vs addressPrefixes on subnet

pkg/cluster/deploybaseresources.go, pkg/cluster/deploybaseresources_additional.go
Fixes https://issues.redhat.com/browse/ARO-3102
This PR adds ability to specify multiple outbound IPs during a cluster creation.  Additional OutboundIPs are added to the "storage" arm template.  The API Server IP is reused when the API Server is public and using Managed Outbound IPs.
Manually created cluster with public and private API Server and validated load balancer frontend IP configuration is correct.
Yes, to be done by doc writer.
=> multiple ARO managed public IPs per Load balancer during cluster create

pkg/util/steps/refreshing.go, pkg/validate/openshiftcluster_validatedynamic.go
Continuation of PR #3222 and ARO-4024
- Reverts the change previously made in #3222 to ensureAccessTokenClaims(), since we need the raw Azure error for `AuthorizationRetryingAction` to do the error matching and work as intended.
- Returns the actionable errors related to service principal credentials to the user as CloudError, rather than `timed out waiting for condition` in the RP and Internal Server Error
- We can test it by ensuring that if provided with invalid client ID or client secret values, `az aro create` will return them to the user
=> Return actionable service principal errors to the user

docs/operators.md
No issue/task related to this problem.
Makefile targets `publish-image-aro*` are using env variable `ARO_IMAGE` as a destination, so setting just `DST_QUAY` variable (as currently explained in the docs) is not enough. Updating `ARO_IMAGE`  accordingly fixed the problem.
No further testing needed, I just followed the procedure to push my locally build aro image to quay.
=> fix docs: puslish aro operator to quay

pkg/util/version/const.go
[ARO-2720](https://issues.redhat.com/browse/ARO-2720)
[ARO-4306](https://issues.redhat.com/browse/ARO-4306)
Since we merged a fix for #3220, we can now change the default install target to 4.12.  
e2e + we've already tested this in production and it's available as an installation target.  
No
=> Default installation target to 4.12

pkg/util/azureclient/authz/remotepdp/client.go, pkg/util/azureclient/authz/remotepdp/types.go
From the schema, the status code returned is an integer.
Fixes: https://msazure.visualstudio.com/One/_workitems/edit/15937293#26804649
Currently there's an error when unmarshaling the body of the error payload returned by CheckAccess.  The schema of the error indicates that the field is an integer while the current struct uses a string.
N/A This fixes the unmarshal error returned with message *"Unexpected error when calling CheckAccessV2: json: cannot unmarshal number into Go struct field CheckAccessErrorResponse.statusCode of type string"*
N/A
=> Fix CheckAccess unmarshal bug

pkg/util/pki/pki_test.go
CI is failing because the PKI tests call an external webservice which is presently down.
Should fix CI.
don't know?
=> Skip failing pki test for now

cmd/aro/mirror.go
Since we're removing 4.10 as an installation target and support has fallen off from OCP, we're removing mirroring of 4.10 installation images.  
Less mirroring, faster pipelines, wow!
Run mirroring
nope
=> Only mirror images from 4.11+

pkg/hive/install.go
Use hive minimal install mode (or set ourselves up for).
https://github.com/openshift/hive/pull/2157
As part of installation through hive, the following is done:
1. Hive pulls the ocp-release images
2. Hive pulls the oc-cli image (discovers this from the ocp-release image)
- this is used for must-gather, which we' don't configure
3. Hive pulls the installer image (discovers from the ocp-release image unless `installerImageOverride` is set)
- we set `installerImageOverride` in ARO. 
That means that if we allow the installation of older versions, older images are pulled down, which we don't necessarily want.  
This will have no affect until we get to a hive version which has https://github.com/openshift/hive/pull/2157/files merged in. 
Testing will be manual and in INT environment. 
no
=> Hive Minimal Install Annotation on ClusterDeployment

pkg/hive/install.go
Until we're on a version of hive which supports minimal installs, we need the annotation to pull the cli-image from arosvc, not quay.io
test in INT.  
Nope
=> bug: Keep cli-domain-from-installer-image until we use minimal hive version

pkg/hive/manager.go
Fixes [ARO-4175](https://issues.redhat.com/browse/ARO-4175)
Replaces our use of Update to set annotations on ClusterDeployments with Patch. This ensures that we do not run into errors when unrelated parts of our known schema for the CRD conflict with Hive's webhook (e.g. when versions do not match). 
- Existing unit tests continue to pass
- Cluster installations via Hive continue to work as expected (`hive.openshift.io/additional-log-fields` annotation has the log fields set by ARO removed)
No
=> Patch Hive ClusterDeployment rather than Update it

pkg/util/cluster/cluster.go, test/e2e/cluster.go
https://issues.redhat.com/browse/ARO-4488
This is a follow-up PR on the hotfix because we had trouble getting the test working before the hotfix release. We want this test to work so we have continuous validation that our code can handle this situation properly.
**Edit:** I unfortunately found that the reason that the reason the test wasn't working in CI is because CI clusters are FIPS-enabled, and Azure File storage does not work on FIPS-enabled clusters. So the plan for this PR is changing from fixing the test -> leaving the test pending but leaving comments saying it should be enabled when/if FIPS becomes toggleable post-install.
If you look at the E2E run for commit [8e39971](https://github.com/Azure/ARO-RP/pull/3226/commits/8e399716140d6389762320f1428b5dd561e40518), you can see that …
=> Fix e2e test for azurefile-csi storage class that uses ARO-managed storage account on OCP 4.11

cmd/aro/mirror.go, hack/hive-config/hive-config.yaml, hack/hive-generate-config.sh, pkg/hive/install.go
ARO-4545
Bumps the hive version to resolve vulns as well as moves us to a hive minimal version which allows us not to pull ocp-release and oc-cli images.
Full int environment
Nope
=> Bump Hive Version + Minimal Install

cmd/aro/update_ocp_versions.go
Deletes to OpenShiftVersions are updating the database, but the frontend does not see the change and must be restarted for the deletions to be effective. Delete the docs via the changefeed mechanism so that the frontend notices.
Tested with a local RP, and running `./aro update-versions`. Next test is to push this to INT, create a dummy version in the database then delete it, and confirm that `az aro get-versions` does not return the dummy version.
=> Delete OpenShiftVersions via change-feed

pkg/operator/controllers/muo/staticresources/muo_alerts.yaml, pkg/operator/controllers/muo/template_test.go
Fixes https://issues.redhat.com/browse/ARO-4338
Adds muo alerts to aro operator that will be picked up by RP monitor process and shipped to Geneva.  Alerts are based on the set of [metrics](https://github.com/openshift/managed-upgrade-operator/blob/4efa725c960b07674c0cd4952898439f3b27a2db/docs/metrics.md?plain=1#L7-L13) exposed by the MUO operator and OSD/ROSAs  [current alerting configuration]( https://github.com/openshift/managed-cluster-config/blob/master/deploy/sre-prometheus/100-managed-upgrade-operator.PrometheusRule.yaml)
I opted to not add an alert for the metric  `upgradeoperator_scaling_failed` because the inability of scaling does not block cluster upgrades so the alert would be invalid, see [OSD-10740](https://issues.redhat.com//browse/OSD-10740).
I created a cluster, started …
=> add muo alerts

pkg/operator/controllers/genevalogging/genevalogging.go, pkg/operator/controllers/genevalogging/genevalogging_controller.go, pkg/operator/controllers/genevalogging/genevalogging_test.go
[[ARO-2994] Propagate errors of GenevaLogging controller](https://issues.redhat.com/browse/ARO-2994)
under epic [[ARO-1627] Propagate Errors and Statuses of ARO Controllers to ARO Cluster Operator](https://issues.redhat.com/browse/ARO-1627)
Adds a `GenevaLoggingReady` "check" condition to the `cluster.aro.openshift.io/v1alpha1` singleton object that exposes controller errors.
Manual testing using a custom operator image.
None that I'm aware of.
=> Propagate errors of GenevaLogging controller

go.mod, pkg/util/graph/adapter.go
I recently reconstructed how I originally enabled HTTP tracing for MS Graph requests when porting the RP from Azure Active Directory Graph last year.  I'm offering this up as a permanent debugging feature, enabled by defining an environment variable named `ARO_MSGRAPH_TRACE`.  It might come in handy again in the future.
=> graph: Add HTTP tracing option for MS Graph requests

test/e2e/setup.go
Errors returned from MS Graph APIs are useless as an `error` type.  They just use a [hard-coded message](https://github.com/microsoft/kiota-abstractions-go/blob/main/api_error.go#L16):
```
error status code received from the API
```
To get to the real information requires casting the `error` as an `ODataError` and unpacking the details, which I usually just "spew" to a log.
This is to help debug such errors we're currently seeing in E2E tests.
=> e2e: Spew ODataError details before panicing

pkg/hive/install.go
Attempt to fix current E2E issues.
deploy and run E2E in int
=> add back cli-domain-from-installer-image

pkg/cluster/deploybaseresources.go, pkg/cluster/deploybaseresources_test.go
Adds unit tests for adding multiple managed IPs to the public load balancer during arm template generation
Refactored public load balancer ARM template generation by isolating it into a separate function.  Added unit tests for the new function that tests the changes in #3110 
Unit tests
Manual test: 5 managed IPs, API server public
Manual test: 5 managed IPs, API Server private
Manual test: 1 managed IP, API Server private
E2E cluster creation: 1 managed IP, API Server public
No
=> add unit tests for multiple IP aro create

hack/genhiveconfig/genhiveconfig.go, hack/genhiveconfig/genhiveconfig_test.go, hack/hive-config/generate.go, hack/hive-config/hive-additional-install-log-regexes.yaml, pkg/hive/failure/handler.go, pkg/hive/failure/reasons.go, pkg/hive/failure/reasons_test.go, pkg/hive/manager.go, pkg/hive/manager_test.go
Part of [ARO-3220](https://issues.redhat.com/browse/ARO-3220)
Implements a pattern for handling Hive install failures in the RP, and handles one specific case (Azure RequestDisallowedByPolicy) by passing the policy errors along to the requester. 
This PR also handles the generic Azure "InvalidTemplateDeployment" error, as this error contains many potential underlying errors including the above RequestDisallowedByPolicy error. The intent here is to cascade these generic errors to customers, but also alert SREs that a more specific error case ought to be implemented and handled as well. The ordering of patterns in the Hive ConfigMap ensures that more specific errors will take precedence over this generic one. 
With this code running on e.g. a local RP setup that installs via Hive, with the …
=> Handle Hive ProvisionFailed=True conditions within RP and pass errors in API response

python/az/aro/azext_aro/_params.py, python/az/aro/azext_aro/azext_metadata.json, python/az/aro/azext_aro/custom.py, python/az/aro/setup.py
HOLD until #3073 is merged and the v20230701preview API release contains the corresponding create functionality 
Fixes [ARO-3829](https://issues.redhat.com/browse/ARO-3829)
Implements support within the `az aro create` command in the ARO extension for the managedOutboundIps.Count property on the cluster load balancer profile, implemented in the 2023-07-01 preview API. 
On an RP with the 2023-07-01 preview API (e.g. local dev):
- Run `az aro create --help` and validate that the `--load-balancer-managed-outbound-ip-count` flag and information is present
- Run `az aro create` with the `--load-balancer-managed-outbound-ip-count` flag set to `$NUMBER` for numbers != 1 and ensure that the resulting cluster document has property `openShiftCluster.properties.networkProfile.loadBalancerProfile.mana …
=> `az aro create` `--load-balancer-managed-outbound-ip-count` flag support

pkg/operator/controllers/storageaccounts/storageaccount_controller.go, pkg/operator/controllers/storageaccounts/storageaccounts.go, pkg/operator/controllers/storageaccounts/storageaccounts_test.go, pkg/operator/controllers/subnets/subnet_controller_test.go, pkg/operator/controllers/subnets/subnet_nsg.go, pkg/operator/controllers/subnets/subnet_serviceendpoint.go, pkg/operator/controllers/subnets/subnets_controller.go, pkg/util/azureerrors/error.go, pkg/util/subnet/cluster_subnets.go, pkg/util/subnet/cluster_subnets_test.go, test/e2e/operator.go
- Potential fix for [ARO-4632](https://issues.redhat.com/browse/ARO-4632)
- Fixes [ARO-4468](https://issues.redhat.com/browse/ARO-4468) as the test flakiness blocks merge of this PR
- Updates the ARO Operator Subnets and StorageAccounts controller to only watch master Machines, and to watch worker MachineSets instead
- Updates the underlying cluster_subnets List() function to also retrieve worker subnets via MachineSets rather than Machines
- Updates the e2e test for subnet NSG reconciliation, as it was previously dependent on the subnet controller reconciling frequently and unnecessarily in order to pass. 
This should (hopefully) cut down on Reconcile loops for the above two controllers when individual worker nodes change but their underlying definition and therefore subnet do not. 
- …
=> Watch MachineSets for worker subnet changes instead of Machines

pkg/util/version/const.go
[ARO-3748](https://issues.redhat.com/browse/ARO-3748)
Remove 4.11.26 as an installation target
N/A
See Jira.
=> Remove version 4.11.26 due to installation issues

cmd/aro/mirror.go
Fixes ARO-4779
This mirrors the new Hive image so it can be deployed in production.
N/A 
N/A
=> ARO-4779: Mirror new hive image to close vulns

docs/deploy-development-rp.md, pkg/frontend/admin_openshiftcluster_delete_managedresource.go, pkg/frontend/admin_openshiftcluster_delete_managedresource_test.go, pkg/frontend/adminactions/azureactions.go, pkg/frontend/adminactions/delete_managedresource.go, pkg/frontend/adminactions/delete_managedresource_test.go, pkg/frontend/frontend.go, pkg/util/azureclient/mgmt/features/resources_addons.go, pkg/util/loadbalancer/loadbalancer.go, pkg/util/loadbalancer/loadbalancer_test.go, pkg/util/mocks/adminactions/adminactions.go, pkg/util/mocks/azureclient/mgmt/features/features.go, test/e2e/adminapi_delete_managedresource.go, test/e2e/update.go
Fixes https://issues.redhat.com/browse/ARO-4425
This PR adds an admin action to delete cluster managed resources. All resources are deleted using DeleteByIDAndWait except for FrontendIPConfiguration.  FrontendIPConfiguration cannot be deleted via http DELETE, instead loadbalancer config is retrieved, manipulated to not include the FrontendIPConfiguration and applied with `CreateOrUpdateAndWait`.
Unit tests
E2E tests added verifying that LoadBalancer loadbalancingrules, frontendIPConfiguration, and PublicIPAddresses can be deleted.
Yes, will add command example to `docs/deploy-development-rp.md`.
=> Admin action to delete a cluster managed resource

pkg/frontend/admin_openshiftcluster_etcdcertificaterenew.go, pkg/frontend/admin_openshiftcluster_etcdcertificaterenew_test.go, pkg/monitor/cluster/certificateexpirationstatuses.go, pkg/util/cert/cert.go
Added extra validation to verify if etcd certificates are renewed Also, removed isLessThanMinDuration code block so we can even renew clusters whose expiry is more than 6 months duration
Fixes
=> etcd-renew - Add extra validation and remove IsLessThanMinDuration

Dockerfile.fluentbit
Fixes fluentbit builds.  I pushed over the INT ACR image so e2es will pass.  We will need to rebuild and push over the existing tags for the images we broke.  **But we should not push over production images & tags**
In the latest builds of fluentbit, there is a requirement for the shared object library `libstdz.so.1`, which isn't copied into the fluentbit image.  As a result, we get an crashloopbackoff when running fluentbit and e2es fail.  
```bash
[bvesel@fedora ARO-RP]$ oc -n openshift-azure-logging logs mdsd-b9krb -c fluentbit
/opt/td-agent-bit/bin/td-agent-bit: error while loading shared libraries: libzstd.so.1: cannot open shared object file: No such file or directory
```
`podman build -f Dockerfile.fluentbit --build-arg MARINER_VERSION=<xyz>`
Nope.  We should really be using image …
=> Add libzstd.so.1 to fluentbit container build

pkg/util/version/const.go
4.13.16 has been tombstoned, use latest 4.13 instead
https://github.com/openshift/cincinnati-graph-data/pull/4259
=> Enable 4.13.23 as an install target instead of 4.13.16

hack/clean/clean.go
Fixes https://issues.redhat.com/browse/ARO-4856
- Delete clusters with a managedBy field
- Our purge script is not deleting resource groups that have the managedBy field. Previously, we were assuming that any resource group with a managedBy field was a prod cluster, but dev clusters can/do have that field, and we should be deleting them.
- From now on, we use `purge:true` only as the source of truth for which clusters are dev
- Add `shared-cluster` to the deny list, so it doesn't get wiped out by this change
- Prod clusters that we want to persist should already be tagged `persist: true` and not have the `purge` tag, so they shouldn't get deleted. 
- Move to infof in the script, so we see these messages during a pipeline run (if something isn't getting deleted, we want to know why)
- Run …
=> Update purge script (hack/clean/clean.go)

pkg/cluster/arooperator.go, pkg/cluster/condition.go, pkg/cluster/condition_test.go, pkg/cluster/install.go, pkg/operator/deploy/deploy.go, pkg/util/mocks/operator/deploy/deploy.go, test/e2e/setup.go, test/e2e/update.go
Issue where `az aro update --refresh-credentials` fails because `credentialsrequest/openshift-azure-operator` doesn't exist   (for clusters not yet updated to use the new ARO operator Azure auth scheme; see https://github.com/Azure/ARO-RP/pull/3274)
- Adds a step that reconciles the CredentialsRequest upon every `az aro update` regardless of the auth scheme the operator is using or whether the update is a CSP refreshing update
- Fixes the `aroCredentialsRequestReconciled` function to retry until the timeout if the CredentialsRequest is not found (as opposed to erroring out immediately)
- On a dev cluster, manually tested the code changes by deleting the CredentialsRequest and then running a successful `az aro update --refresh-credentials`
- Added an E2E test that tests whether `az aro …
=> `az aro update` CredentialsRequest hotfix

.pipelines/e2e.yml
The current must-gather we use on failed CI runs doesn't collect ARO-specific data such as MDSD, ARO operator deployments, and the ARO CR. I've added a [custom image of must-gather](https://github.com/cadenmarchese/must-gather/tree/add-aro) and pushed it to quay so that we can evaluate using that must-gather instead.
A lot of e2e tests rely on ARO-specific functionality, so debugging them in CI often relies on having this data before the cluster is deleted by the pipeline.
The must-gather image itself was tested by running `oc adm must-gather --image quay.io/cmarches/aro-must-gather:20231030.00` and then validating that the gather contains the info we need:
```
~/omc get pods -n openshift-azure-operator
NAME                                   READY   STATUS    RESTARTS   AGE …
```
=> Use aro-must-gather for CI instead of base client

pkg/api/error.go, pkg/api/v20191231preview/openshiftcluster_validatestatic.go, pkg/api/v20191231preview/openshiftcluster_validatestatic_test.go, pkg/api/v20200430/openshiftcluster_validatestatic.go, pkg/api/v20200430/openshiftcluster_validatestatic_test.go, pkg/api/v20210901preview/openshiftcluster_validatestatic.go, pkg/api/v20210901preview/openshiftcluster_validatestatic_test.go, pkg/api/v20220401/openshiftcluster_validatestatic.go, pkg/api/v20220401/openshiftcluster_validatestatic_test.go, pkg/api/v20220904/openshiftcluster_validatestatic.go, pkg/api/v20220904/openshiftcluster_validatestatic_test.go, pkg/api/v20230401/openshiftcluster_validatestatic.go, pkg/api/v20230401/openshiftcluster_validatestatic_test.go, pkg/api/v20230701preview/openshiftcluster_validatestatic.go, pkg/api/v20230701preview/openshiftcluster_validatestatic_test.go, pkg/api/v20230904/openshiftcluster_validatestatic.go, pkg/api/v20230904/openshiftcluster_validatestatic_test.go
[ARO-3219](https://issues.redhat.com/browse/ARO-3219)
The failure of cluster provisioning occurs when an invalid network address is supplied for the CIDR. This code will introduce dynamic validation for both the cluster network (pod) CIDR range and service CIDR.
None
=> Dynamic validation on CIDR

pkg/cluster/deploybaseresources.go, pkg/cluster/deploybaseresources_test.go, pkg/cluster/install.go, pkg/util/steps/condition.go, pkg/util/steps/condition_test.go
https://issues.redhat.com/browse/ARO-4773
I used Kusto to search for this error, and there are quite a few just in the US regions even within the past week. Fortunately, they are all the same, and I think I see how we can fix them.
All of the failures are occurring at the attachNSGs bootstrap step, specifically on this line: https://github.com/Azure/ARO-RP/blob/91fd9d00ac7573a71d78852c85e5d68cbb6fd030/pkg/cluster/deploybaseresources.go#L300.
Given that the code, as currently written, attempts to attach the NSG immediately after it gets created by the previous bootstrap step, I'll bet that what's happening is that there's just a little bit of lag in Azure where the NSG is not ready to be referenced in a subnet attachment yet. My proposed fix is to make attachNSGs a retrying step to allow …
=> ARO-4773 cluster install failure fix

docs/upstream-differences.md
https://issues.redhat.com/browse/ARO-3542: Update installer documentation
Updates to installer documentation:
* References to new ARO installer repos in openshift org
* Replace references to ARO-RP codebase with Wrapper codebase where appropriate
* Link to image release process
n/a
=> References to new repos and steps to update wrapper instead of RP

cmd/aro/operator.go, pkg/operator/controllers/guardrails/guardrails_config.go, pkg/operator/controllers/guardrails/guardrails_controller.go, pkg/operator/controllers/guardrails/guardrails_controller_test.go, pkg/operator/controllers/guardrails/policies/gktemplates-src/library/common.rego, pkg/operator/controllers/guardrails/policies/gktemplates/aro-deny-delete-pull-secret.yaml, pkg/operator/controllers/guardrails/policies/gktemplates/aro-deny-machine-config.yaml, pkg/operator/controllers/guardrails/policies/gktemplates/aro-deny-master-toleration-taints.yaml, pkg/operator/controllers/guardrails/policies/gktemplates/aro-deny-privileged-namespace.yaml
Fixes 
[ARO-4861](https://issues.redhat.com/browse/ARO-4861)
[ARO-4862](https://issues.redhat.com/browse/ARO-4862)
https://redhat-internal.slack.com/archives/C02ULBRS68M/p1702007716321979
find a way to not deploy guardrails onto clusters that already installed gatekeeper
fix the Guardrails problem that turning off managed did not delete the gatekeeper deployment
add one  more exempted user for guardrails policy
passed basic tests on my environment
$ go test -v
=== RUN   TestGuardRailsReconciler
=== RUN   TestGuardRailsReconciler/disabled
=== RUN   TestGuardRailsReconciler/managed
=== RUN   TestGuardRailsReconciler/managed,_no_pullspec_&_namespace_(uses_default)
=== RUN   TestGuardRailsReconciler/managed,_GuardRails_does_not_become_ready
=== RUN …
=> added exempted user to guardrails

.github/workflows/ci-go.yml, .github/workflows/codeql-analysis.yml, Makefile
Removes unnecessary build tag. 
The build tag is set in the installer, not in the RP anymore.  
e2e, ci
no-
=> Remove aro build tag as it's not needed for the ARO-RP

cmd/aro/mirror.go
chore
Updates the images so we can use 1.20
N/A
N/A
=> Add Go 1.20 images (and ose-tools-rhel8 for 4.14)

pkg/monitor/azure/nsg/nsg.go, pkg/monitor/azure/nsg/nsg_test.go
Fixes ARO-4892 and ARO-4967
Currently the new NSG monitor makes a GET call to NRP for each workerprofile configured on the cluster.  It could be that different profiles can have the same subnet configured.  If that's the case, the subnet can then be looked up more than once.
This PR makes sure that the subnets will only be retrieved once by maintaining a set of subnetID and looking it up before making the actual call.  If the subnet has been retrieved before, the code will skip it.
Unit tests, E2E
N/A
=> Improve NSG monitoring by retrieving subnet only once

cmd/aro/dbtoken.go, cmd/aro/deploy.go, cmd/aro/gateway.go, cmd/aro/monitor.go, cmd/aro/portal.go, cmd/aro/rp.go, cmd/aro/update_ocp_versions.go, hack/aead/aead.go, hack/cluster/cluster.go, hack/db/db.go, hack/gendevconfig/gendevconfig.go, hack/portalauth/portalauth.go, pkg/cluster/cluster.go, pkg/env/core.go, pkg/env/dev.go, pkg/env/env.go, pkg/env/msiauthorizer.go, pkg/env/prod.go, pkg/util/mocks/env/core.go, pkg/util/mocks/env/env.go
Part of https://issues.redhat.com/browse/ARO-4595
Makes env/ understand what service it is running for, which allows us to standardise some of the "what" about the service running (e.g. knowing what dbtoken permission we're asking for, what logger we want to use, etc)
CI/E2E
N/A, cleanup
=> Make env know what the service component its running is

cmd/aro/const.go, cmd/aro/dbtoken.go, cmd/aro/gateway.go, cmd/aro/main.go, cmd/aro/monitor.go, cmd/aro/portal.go, cmd/aro/rp.go, cmd/aro/update_ocp_versions.go, pkg/api/v20191231preview/openshiftcluster_validatestatic_test.go, pkg/api/v20200430/openshiftcluster_validatestatic_test.go, pkg/api/v20210901preview/openshiftcluster_validatestatic_test.go, pkg/api/v20230904/openshiftcluster_validatestatic_test.go, pkg/frontend/admin_openshiftversion_put.go, pkg/frontend/admin_openshiftversion_put_test.go, pkg/frontend/changefeed.go, pkg/frontend/frontend.go, pkg/frontend/openshiftcluster_preflightvalidation_test.go, pkg/frontend/openshiftcluster_putorpatch_test.go, pkg/frontend/openshiftversions_list.go, pkg/frontend/openshiftversions_list_test.go, pkg/frontend/validate.go, pkg/monitor/cluster/clusterversions.go, pkg/monitor/cluster/clusterversions_test.go, pkg/util/dynamichelper/discovery/cache_fallback_discovery_client_test.go, pkg/util/version/const.go, test/e2e/setup.go
[[ARO-3896] Read default OCP version from CosmosDB](https://issues.redhat.com/browse/ARO-3896)
Depends on a couple ADO pull requests:
- [RP-Config: Add openShiftVersions data](https://msazure.visualstudio.com/AzureRedHatOpenShift/_git/RP-Config/pullrequest/8603646) :heavy_check_mark: _merged_
- [ARO.Pipelines: Read OpenShiftVersions from YAML configuration](https://msazure.visualstudio.com/AzureRedHatOpenShift/_git/ARO.Pipelines/pullrequest/8603681) :heavy_check_mark: _merged_
Make CosmosDB the single source of truth for available OpenShift versions, including the default version.  Currently it's a mix: CosmosDB has the available versions but only ARO RP knows the default version.
Local development mode has been a subject of discussion within my functional team (Loki).  Initially I had …
=> Move default openshift version

docs/deploy-development-rp.md
This is to give a heads up that this podman issue can occur if the podman user socket is not enabled.
=> Update deploy-development-rp.md to include a heads up.

.github/workflows/yamllint.yml
Fixes https://docs.opensource.microsoft.com/github/apps/permission-changes/#tldr
Adds a permissions stanza to the yamllint action
Green run of this action on this PR == :shipit: 
No
=> Add permissions stanza to yamllint GH action

Dockerfile.aro, Makefile, docs/operators.md
Breaking up some of the Go 1.20 changes that aren't strictly related.
Fixes https://issues.redhat.com/browse/ARO-5135
Removes the image-aro makefile target and the Dockerfile. This build target is legacy and does the wrong thing in general, and could lead to inconsistent results depending on the host Golang.
CI, E2E, should validate it's not used anywhere
Updated the remaining reference
=> Remove Dockerfile.aro and the image-aro Makefile

Dockerfile.aro-e2e, Dockerfile.aro-multistage, Dockerfile.ci, Dockerfile.proxy
https://issues.redhat.com/browse/ARO-5137
Having things in GOPATH confuses the build process sometimes, so move it out.
CI, E2E 
N/A
=> Move Dockerfile build paths outside of GOPATH

pkg/monitor/cluster/certificateexpirationstatuses.go, pkg/monitor/cluster/certificateexpirationstatuses_test.go
Fixes [ARO-5227](https://issues.redhat.com/browse/ARO-5227)
The ARO Monitor's certificateexpirationstatus monitor expects the IngressController resource on-cluster to be well-formed, namely it requires a default certificate name to be present within `.spec.defaultCertificate.name`. 
The Go type definition for IngressController allows the `DefaultCertificate` property to be nil, and we do not currently perform a nil check here.
This causes the monitor service to panic and terminate when evaluating a cluster that has such an invalid IngressController resource. 
- Unit test added for this specific case
- All existing unit and e2e tests continue to pass
No
=> Return error on certificateexpirationstatus monitor when IngressController is invalid rather than panic

test/e2e/adminapi_delete_managedresource.go
https://issues.redhat.com/browse/ARO-4956
I encountered a test failure in a different PR where E2E errored out on the line of the call to delete the Service. This PR attempts to fix that error by handling the Service deletion in a (hopefully) more robust way.
N/A
N/A
=> Hopefully fix E2E flake related to deletion of a test Service

test/e2e/dns.go, test/e2e/setup.go
https://issues.redhat.com/browse/ARO-4824
The test simulates host servicing on all three worker nodes based on [instructions from Azure docs on how to do so](https://learn.microsoft.com/en-us/azure/virtual-network/accelerated-networking-how-it-works#disabling-or-enabling-accelerated-networking-in-a-nonrunning-vm). It then waits for the worker nodes to become Ready again and reads each worker node's `resolv.conf` to confirm that the contents are still correct after the "host servicing" has taken place.
A concern that the team should provide feedback on: I did my best to do only what's necessary, but the test takes > 10 minutes just because of the nature of what we have to do. Is this unreasonably long considering that we will likely only continue to add to the length of E2E in the future? …
=> Add E2E test for host servicing

.pipelines/ci.yml, Dockerfile.aro-e2e, Dockerfile.aro-multistage, Makefile, hack/fips/validate-fips.sh
Fixes https://issues.redhat.com/browse/ARO-5136
Use an alternative method (fips-detect) which validates the binary directly.
Should be covered by CI?
N/A
=> Use another method of FIPS validation (fips-detect)

pkg/monitor/azure/nsg/nsg.go
Proposed behavioral change for the refactor performed in #3358 
Original Jiras for feature: [ARO-4892](https://issues.redhat.com/browse/ARO-4892) and [ARO-4967](https://issues.redhat.com/browse/ARO-4967)
In the NSG monitor, we currently exit early if we encounter an error when trying to retrieve a subnet. This PR changes the behavior to continue trying to evaluate the subnets and to ignore ones with errors. 
The implementation as-is was causing flaky test failures, as the order of subnet evaluation was not consistent, leading to mocked Subnet GET calls not always occurring as expected. 
- Existing unit tests continue to pass
- were also run multiple times to ensure the flake is gone
no
=> Do not exit NSG monitor when unable to get subnet

pkg/operator/controllers/genevalogging/genevalogging.go, pkg/operator/controllers/muo/staticresources/deployment.yaml, pkg/operator/deploy/deploy_test.go, pkg/operator/deploy/staticresources/master/deployment.yaml.tmpl, pkg/operator/deploy/staticresources/worker/deployment.yaml.tmpl, pkg/operator/helpers_test.go
Fixes https://issues.redhat.com/browse/ARO-3955
in 4.15 pods will fail to be created unless they correctly satisfy the securitycontext labels on either the namespace or pod(s) themselves.  
Create a cluster, update the deployment, check the pod security admission to determine if it's still throwing an error on `AdminUpdate`
>looking for things like pod-security.kubernetes.io/audit-violations in the annotations section of audit logs
All clusters will need a round of PUCM
=>  Add securityContext to ARO worker and master operator deployments as required by k8s v1.27.x

pkg/backend/openshiftcluster.go, pkg/validate/openshiftcluster_validatedynamic.go
Fixes https://issues.redhat.com/browse/ARO-4734
Users are getting "Internal Server Error" when they have a deleted ServicePrincipal, and we want to give them a better and more detailed response. We noticed that the SP validation checks happen that would catch this and return the right error, but FP doesn't so we are doing the same validation step for FP as well.
Looking into ways to test this as it would require removing a SP on this branch in an INT env.
=> Added FP Check for validation

pkg/cluster/adminupdate_test.go, pkg/cluster/hive.go, pkg/cluster/hive_test.go, pkg/hive/manager.go, pkg/hive/manager_test.go, pkg/util/mocks/hive/hive.go, test/e2e/hive_manager.go
HiveNamespace currently uses aro-"uuid", this change is an effort to unify UUIDs across cluster doc instead of having multiple, by pointing HiveNamespace to docID so this can be leveraged later.
More Details: https://redhat-internal.slack.com/archives/C02ULBRS68M/p1686806655273309
Fixes
=> HiveNamespace to use docID/clusterID for new Installs

pkg/portal/kubeconfig/proxy_test.go, pkg/portal/prometheus/proxy_test.go
Part of the fixes in [issues.redhat.com/browse/ARO-5320](https://issues.redhat.com/browse/ARO-5320)
Fixes unit tests that fail in Go 1.20 (because the behaviour of User-Agents when not provided in the HTTP proxy functionality changed)
Unit tests should continue passing
N/A
=> Fix Go 1.20 change around proxy and default user agents

hack/hive-dev-install.sh, hack/hive-generate-config.sh
cleanup
- Updates coordinates to dev hive image to match the version we use in prod (as of the time of this PR)
- Backports recent changes from our production Hive deployment to ensure the Hive deployment is running successfully before exiting the script (see https://msazure.visualstudio.com/AzureRedHatOpenShift/_git/ARO-Pipelines/pullrequest/9524243 for details) 
- Ran Hive dev deployment (against eastus shared dev env) and ensured it ran successfully. 
Internal Hive deployment documentation ought to be updated to ensure our dev deployment stays up to date in prod (or better yet, is updated beforehand in order to test out that Hive deployment before releasing in prod)
=> Update Hive dev install

pkg/api/v20230701preview/openshiftcluster_validatestatic.go, pkg/api/v20230701preview/openshiftcluster_validatestatic_test.go, pkg/api/v20231122/openshiftcluster_validatestatic.go, pkg/api/v20231122/openshiftcluster_validatestatic_test.go
Fixes https://issues.redhat.com/browse/ARO-5484
Adds a check to api v2023-11-22 static validation to prevent updating managedOutboundIPs.count to anything greater than 1 for architecture v1 clusters.
Unit tests
No
=> add archv1 check to multiple ip static validation

pkg/cluster/cluster.go, pkg/cluster/install.go, pkg/operator/controllers/genevalogging/genevalogging.go, pkg/operator/controllers/genevalogging/genevalogging_test.go, pkg/operator/controllers/muo/config/config.go, pkg/operator/controllers/muo/muo_controller.go, pkg/operator/controllers/muo/muo_controller_test.go, pkg/operator/controllers/muo/staticresources/deployment.yaml.tmpl, pkg/operator/deploy/deploy.go, pkg/operator/deploy/deploy_test.go, pkg/operator/deploy/staticresources/master/deployment.yaml.tmpl, pkg/operator/deploy/staticresources/worker/deployment.yaml.tmpl, pkg/operator/helpers.go, pkg/operator/helpers_test.go, pkg/util/version/clusterversion.go, pkg/util/version/clusterversion_test.go
In <4.11, the SCCs don't align with the secCompProfile set on the pods, which result in the pods with the added `secCompProfile` failing to schedule / run.  
Unit tests + manual testing of 4.10 version
Testing instructions:
1. Create a 4.10 cluster at this aro operator version + RP version
2. Make sure MUO, aro-operator (worker and master), and geneva logging pods are working as intended.
3. Check the presence of: aro-worker and aro-master operators (secCompProfile), geneva logging namespace (should not have labels), and MUO deployment (secCompProfile)
4. Upgrade to 4.11
5. AdminUpdate the cluster
6. All the items in step 3 should have the appropriate things now
**Changes**
- Namespace: 
```
"pod-security.kubernetes.io/enforce": "privileged",
"pod-security.kubernetes.io/audit": …
```
=>  Don't add security context on <4.11 as OpenShift restricted SCCs do not tolerate it

python/az/aro/azext_aro/_dynamic_validators.py, python/az/aro/azext_aro/tests/latest/unit/test_dynamic_validators.py
Fixes [ARO-5075](https://issues.redhat.com/browse/ARO-5075)
Updates the dynamic validation performed by the Azure CLI `az aro` command to mirror the validation performed by the RP itself. This also fixes incorrect behavior in the CLI handling of the `not_actions` list on permissions, which were previously being treated as full deny permissions, rather than negations on only the sibling `actions` list of its parent permission. 
Note that this will change the error reported to users - previously users would see a `${ACTION} permission is disabled` error message, which is untrue (since permissions cannot be "disabled"). The only error message from this validation will be `${ACTION} permission is missing`. 
Unit tests were added for the dynamic validator's `can_do_action` function. These …
=> Update `az aro` permissions validation to mirror RP frontend validation

pkg/monitor/azure/nsg/nsg.go, pkg/monitor/azure/nsg/nsg_test.go, pkg/monitor/monitor.go, pkg/monitor/worker.go
Fixes ARO-4854
This makes the NSG Monitor run every 10 minutes instead of every hour.  It accomplishes this by maintaining a time.Ticker of 10*time.Minute duration in the ~~monitor object~~ workOne function and using the tick as a signal to monitor during the main monitoring loop.
Unit tests 
N/A
=> Make NSG Monitor run every 10 minutes

pkg/util/azureclient/mgmt/redhatopenshift/2023-09-04/redhatopenshift/openshiftclusters.go, pkg/util/azureclient/mgmt/redhatopenshift/2023-09-04/redhatopenshift/openshiftclusters_addons.go, pkg/util/azureclient/mgmt/redhatopenshift/2023-09-04/redhatopenshift/operations.go, pkg/util/azureclient/mgmt/redhatopenshift/2023-09-04/redhatopenshift/operations_addons.go, pkg/util/cluster/cluster.go
Fixes ongoing release
As part of the effort to eventually release the ARO 20231122 API, we had previously updated `pkg/util/cluster` to use this new API. Unfortunately, this breaks e2e tests against production regions, as this API does not yet officially exist. 
This PR temporarily updates pkg/util/cluster to use the 20230904 API, until we are able to update. 
This is intended to be a "hotfix" patch for the ongoing release, and as such the change is intended to be as small as possible. I think there is an opportunity for a more involved refactor to `pkg/util/cluster` to make changes like this easier, which I will evaluate separately. 
- No (existing docs on API release process already call out the correct order of operations here)
When merging this PR, please squash this so we can cherry …
=> Revert pkg/util/cluster creation to use 20230904 API

pkg/backend/openshiftcluster.go, pkg/backend/openshiftcluster_test.go, pkg/frontend/frontend.go, pkg/frontend/frontend_test.go
Fixes [ARO-5112](https://issues.redhat.com/browse/ARO-5112)
As of now, all CloudErrors are termed as UserError.  This PR will check upon the statusCode of the error and provide resultType accordingly. 
Done : Manually Tested mapping of CloudError `StatusCode` with `ResultType`.
Also, included test coverage for the functions
No
=> Adding segregation of resultType for CloudError

test/e2e/dns.go
Fixes ongoing rollout
Skips the Azure Host Servicing E2E test when not in development environments. This is required as this test performs direct actions on the cluster VMs, which are protected by ARO's deny assignment in production regions. This causes this E2E test to fail when used e.g. to validate a production region during our deployment process. 
Note that this is intended to be a temporary fix - we should evaluate a more permanent solution that allows us to validate this behavior in all regions during our rollout.  
No.
=> Do not run Azure Host Servicing test in non-development environments

Makefile
This PR simplifies the `shared-cluster-loging` target by using az directly rather than using secrets we cache and share. More context [here](https://redhat-internal.slack.com/archives/C02ULBRS68M/p1708442218652829?thread_ts=1708427098.104239&cid=C02ULBRS68M). 
Note: An upside of this is that the re-creation of the shared cluster leads to zero changes in the secrets with these changes... automated shared-cluster rebuilds anyone??
I think we can do the following:
- Remove `secrets/shared-cluster.kubeconfig`
- This file is old and very out of data
- AFAIK nothing is using it
- Remove from `secrets/env`:
- SHARED_CLUSTER_API
- SHARED_CLUSTER_KUBEADMIN_PASSWORD
If people agree I'll implement the above.
=> Update shared cluster login

python/az/aro/azext_aro/_client_factory.py, python/az/aro/azext_aro/_params.py, python/az/aro/azext_aro/_validators.py, python/az/aro/azext_aro/azext_metadata.json, python/az/aro/azext_aro/commands.py, python/az/aro/azext_aro/custom.py, python/az/aro/azext_aro/tests/latest/unit/test_validators.py, python/az/aro/setup.py
Fixes [ARO-4616](https://issues.redhat.com/browse/ARO-4616)
Implements the `--load-balancer-managed-outbound-ip-count` flag on `az aro create` and `az aro update`. This functionality is equivalent to what is contained on the `azext-aro-v20230701preview` branch, just dependent on the stable ARO v20231122 API instead. Commits have been manually recreated and/or cherry-picked from the `azext-aro-v20230701preview` depending on applicability. 
None in this PR.
=> `az aro`: Implement the multiple public IPs functionality against the ARO stable API

.github/CODEOWNERS
Following existing process for FLs to get added to codeowners:
https://docs.google.com/document/d/1Ay_jbHP69LLHK7BIgeFwGNRoOQvs0oPD7qGYtwV2iCc/edit#heading=h.n32czpbwk4qa
n/a
n/a
=> Adding my username to codeowners

docs/disk-encryption-set.md
None
The RP is addressing:
- difference between des naming scheme used in e2e tests and the disk-encryption-set.md document
- issues with `az keyvault show` reporting just created keyvault as not found
No
No further edits needed.
=> Fixes in disk-encryption-set.md

pkg/operator/controllers/checkers/clusterdnschecker/checker.go, pkg/operator/controllers/checkers/clusterdnschecker/checker_test.go, pkg/operator/controllers/checkers/clusterdnschecker/controller.go, pkg/operator/controllers/checkers/clusterdnschecker/controller_test.go
Which issue this PR addresses:
Fixes https://issues.redhat.com/browse/ARO-5445
What this PR does / why we need it:
Customer reported ARO operator errors in the logs when custom DNS servers are configured in forward plugin:
https://portal.microsofticm.com/imp/v3/incidents/incident/469705806/summary
This is a [supported setup as per our docs](https://learn.microsoft.com/en-us/azure/openshift/dns-forwarding) and should not be logged as an error.
The DNS checks had been setup initially to be included as cluster conditions for SRE awareness (this did not log the status conditions as errors):
https://github.com/Azure/ARO-RP/blob/3e69b7e742af5aeee471a8d781d518c72fd235dd/pkg/operator/controllers/checker/clusterdns.go
A refactoring was done [in this …
=> [ARO-5445] DNS checker logging custom DNS server as an error

pkg/cluster/cluster.go, pkg/cluster/graph/manager.go, pkg/cluster/graph/manager_test.go
Fixes https://issues.redhat.com/browse/ARO-4249
reload aead when encountering CIF chacha20poly1305 error
manually modified code to test it:
INFO[2024-03-12T13:52:06+13:00]pkg/cluster/graph/manager.go:60 graph.(*manager).LoadPersisted() Jeff failed to load persisted with current aead &{0xc00065d080 [0xc00024e6e0 0xc0002b70c0]}  client_principal_name= client_request_id= component=backend correlation_id= request_id=ff0aad89-b360-48ce-bfe1-607fff22a651 resource_group=v4-australiaeast resource_id=/subscriptions/fe16a035-e540-4ab7-80d9-373fa9a3d6ae/resourcegroups/v4-australiaeast/providers/microsoft.redhatopenshift/openshiftclusters/jeff-412x resource_name=jeff-412x subscription_id=fe16a035-e540-4ab7-80d9-373fa9a3d6ae version=4.12.25
INFO[2024-03-12T13:52:06+13:00]pkg/cluster/graph/manager.go:73 …
=> reload aead when encountering CIF chacha20poly1305 error

pkg/api/error.go, pkg/util/storage/manager.go
https://issues.redhat.com/browse/ARO-3804
Fixes
To report the cluster installation failure error related to storage.AccountsClient#ListAccountSAS: Failure responding to request: StatusCode=429
=> CIF - ServerError: storage.AccountsClient#ListAccountSAS: TooManyRequests

Dockerfile.ci-portal, Makefile, env.example
Fixes https://issues.redhat.com/browse/ARO-5089
In short, this PR creates a new `make` target that takes all these diverging bits and pieces of build code related to the SRE portal and 1.) makes `podman` the only build dependency 2.) consolidates them into a single location that's easier to maintain 3.) guarantees that you don't skip any steps locally or in CI, and 4.) improves build time performance through caching:
- [portal lint (ci)](https://github.com/Azure/ARO-RP/blob/master/.pipelines/ci.yml#L107-L115)
- [make lint-admin-portal](https://github.com/Azure/ARO-RP/blob/6ed5f52e0f264529734e436e11d9c096876a8149/Makefile#L232)
- [Dockerfile for portal linting](https://github.com/Azure/ARO-RP/blob/6ed5f52e0f264529734e436e11d9c096876a8149/Dockerfile.portal_lint#L1-L9)
- [portal audit …
=> Add CI containerfile for portal javascript build

cmd/aro/dbtoken.go, cmd/aro/monitor.go, cmd/aro/portal.go, cmd/aro/rp.go, cmd/aro/update_ocp_versions.go, docs/dbtoken-service.md, hack/db/db.go, pkg/database/database.go, pkg/database/database_test.go
~~This is blocked until the keys are rotated in prod~~
Rollout is now underway and this can be merged.
Full context is [here](https://docs.google.com/document/d/1ectS3jrOAR6Y7dBF2S0zuSlH8DeqHOuL2cdRTIhm5q4/edit?usp=sharing) but it implements https://issues.redhat.com/browse/ARO-5491
Change RP to use Secondary RO/RW Cosmos DB Tokens
This will get tested correctly as part of the release.
Done as part of this PR
=> Switch to using the secondary key

docs/deploy-full-rp-service-in-dev.md
None.
Improves "Deploy an Entire RP Development Service" guide so that one can avoid problems caused by misunderstanding of the procedure.
Changes are based on my experience with this procedure. No further testing expected beyond review.
=> clarify deploy-full-rp-service-in-dev.md guide

Makefile, README.md, docs/prepare-your-dev-environment.md, hack/git/hooks/pre-commit
Fixes [ARO-6316](https://issues.redhat.com/browse/ARO-6316) - moved from #3477 
See [ARO Branching Strategy](https://docs.google.com/document/d/1wDe1vBCyzjul6ZXJM5ZFMa8a7-qmiSuWueis4S0tyA0/edit). Now that branching is required over forks, we need to keep our repo organized. This PR introduces strict naming conventions of branches to:
1. Minimize risk of development efforts getting squashed via --force pushing
2. Make CODEOWNER lives a bit easier while managing branches in rare situations like branches going stale, employees leaving the company, etc.
Local git - attempted to use "bad" branch names and ensured they failed to create commits locally. `git branch --move some-bad-name some-good-name` works and passes the pre-commit hooks.
Yes, included in this PR. I will send notifications to …
=> Add git hooks for branch name validation

hack/devtools/deploy-shared-env.sh, pkg/deploy/assets/rp-oic.json, pkg/deploy/generator/resources_oic.go, pkg/deploy/generator/templates_oic.go
I've had to re-open this PR a few times due to e2e failures resulting from invalid tenant. I've moved over to the main trunk repo and hopefully e2e will succeed.
https://msazure.visualstudio.com/AzureRedHatOpenShift/_git/ARO-Pipelines/pullrequest/9703384?_a=files changed the way that the prod storage accounts are named (using storageAccountDomain + "oic" rather than prefix + "oidc" + region). This PR is meant to align our dev storage accounts to that as much as possible so that they follow the same naming convention.
In the case of the shared dev environments (v4-eastus, v4-westeurope, etc) those will likely have to stay as-is using the resource group name since in a local or shared dev environment there is no storageAccountDomain or RP-config defined for those environments.
=> Consistent storage account naming between dev and prod

cmd/aro/mirror.go
No Jira
Updates our image reference for the Azure CLI to a known working version
- mirroring pipeline works
No
N/A (image only used ad-hoc)
=> Update azure-cli coordinates in mirror

.gitignore, .pipelines/e2e.yml, docs/deploy-development-rp.md, hack/cluster/cluster.go, hack/e2e/run-rp-and-e2e.sh, pkg/env/env.go, pkg/util/cluster/cluster.go
Part of ARO-5822
Loads the application and SP secret from the env, instead of automatically creating it. This allows us to load them from a fixed pool in the e2e process, instead of creating new ones each time.
Manually tested creating a cluster locally with the steps updated in the docs
Updated dev RP docs
Purely CI/E2E/dev changes -- more will need to happen for prod e2e
=> Load the app/SP from the environment instead of automatically creating it

pkg/deploy/assets/gateway-production.json, pkg/deploy/assets/rp-production.json, pkg/deploy/generator/resources_gateway.go, pkg/deploy/generator/resources_rp.go
Fixes ARO6610
To remove SkipAzSecPack=true tag during the next release for security sprint.
N/A
N/A
VMSSes will no longer have the tag.
=> Remove SkipLinuxAzSecPack from RP and Gateway VMSS

pkg/operator/controllers/genevalogging/genevalogging.go, pkg/operator/controllers/genevalogging/genevalogging_test.go
No JIRA yet
If the Fluentbit/MDSD operator flags are set to the empty string, assume the default version for these images (defined in pkg/util/version/const.go). 
This follows the same behavior as our MUO deployment: https://github.com/Azure/ARO-RP/blob/master/pkg/operator/controllers/muo/muo_controller.go#L100 
- Unit test was added to handle this specific case 
No
We can validate this in local dev/int/canary, by either utilizing our admin action to patch cluster flags, or by editing the in-cluster `cluster` resource directly
=> Ensure Fluentbit/MDSD spec operatorflags assume default version when set to empty string

cmd/aro/mirror.go
This PR specifies the correct image for mirroring that we use. 
I think with all the bumps we missed it in here: https://github.com/Azure/ARO-RP/pull/3493
=> Specify the correct MDSD image

cmd/aro/mirror.go
Part of https://issues.redhat.com/browse/ARO-6651
Sync go-toolset 1.20.12 so we can use it
N/A
N/A
updating a target, should work :)
=> Sync go-toolset 1.20.12

pkg/util/cluster/cluster.go
N/A
The [doc](https://github.com/Azure/ARO-RP/blob/master/docs/deploy-development-rp.md#run-the-rp-and-create-a-cluster) says we need to run `source clusterapp.env` but it doesn't work because `clusterapp.env` doesn't have `export` with each env, and the env variables aren't passed to `hack/cluster create`.
Test it locally
N/A
Change the code according to the doc.
=> add export in createapp.env

pkg/api/admin/platformworkloadidentityroleset.go, pkg/api/admin/platformworkloadidentityroleset_convert.go, pkg/api/admin/platformworkloadidentityroleset_validatestatic.go, pkg/api/platformworkloadidentityroleset.go, pkg/api/platformworkloadidentityrolesetdocument.go, pkg/api/platformworkloadidentityrolesetdocument_example.go, pkg/api/v20240812preview/platformworkloadidentityroleset.go, pkg/api/v20240812preview/platformworkloadidentityroleset_convert.go, pkg/api/v20240812preview/platformworkloadidentityroleset_example.go
https://issues.redhat.com/browse/ARO-6082
This PR adds API types, converters, and validators for the new `PlatformWorkloadIdentityRoleSet` proxy resource that's being added to support the MIWI feature.
**Note:** I commented out the admin API converter and validator because the linter didn't like them to exist without being used... is it okay to merge them like this for now? This PR is going to grow very large if we add in all of the stuff that will use this converter and validator.
These API changes will have to be tested once we have created a Cosmos DB container to store the new proxy resources.
N/A
Unit tests and other tests as applicable will be implemented or performed as part of later tickets once the actual new functionality has been added to the RP.
=> MIWI preview API - Add PlatformWorkloadIdentityRoleSet proxy resource type 

pkg/deploy/assets/env-development.json, pkg/deploy/assets/gateway-production.json, pkg/deploy/assets/rp-production.json, pkg/deploy/generator/resources_dev.go, pkg/deploy/generator/resources_gateway.go, pkg/deploy/generator/resources_rp.go
Fixes: ARO-6610 (Upgrade Policy Mode part)
AzSecPack team policy requires that we don't use `Manual` upgrade policy.  Automatic shouldn't be used as it can introduce disruption and is not suitable for production workload.  Changing this to rolling also means accepting the default values of the [RollingUpgradePolicy](https://learn.microsoft.com/en-us/azure/templates/microsoft.compute/2020-12-01/virtualmachinescalesets?pivots=deployment-language-arm-template#rollingupgradepolicy-1), namely 20% maxBatchInstancePercent, maxUnhealthyInstancePercent, maxUnhealthyUpgradeInstancePercent and 0 pauseTimeBetweenBatches.
VMSSes (rp, gateway) can still be created and have upgradepolicy set to `rolling`
N/A
VMSSes (rp, gateway) can still be created and have upgradepolicy set to `rolling`
=> Change the upgrademode of VMSS to rolling

env-int.example
We have set the char limit to 20 in our deployment template. Hence this env's value should also be atmost 20 char. It exceeds with a region with big name is chosed like australiaeast.
=> Limiting KEYVAULT_PREFIX to 20 Chars

pkg/api/pretty.go, pkg/database/database.go, pkg/frontend/subscriptions_put.go
This PR drops the use of the ErrorIfNoField flag for our decoding. This flag: ` If true, returns an error if a map in the stream has a key which does not map to any field; else read and discard the key and value in the stream and proceed to the next.` (http://ugorji.net/blog/go-codec-primer)
The principal behind this is that we shouldn't error if we receive more data than expected.
=> Drop ErrorIfNoField

pkg/deploy/assets/databases-development.json, pkg/deploy/assets/rp-development.json, pkg/deploy/assets/rp-production.json, pkg/deploy/generator/resources_rp.go, pkg/util/arm/marshal.go, pkg/util/azureclient/apiversions.go
Fixes [ARO-6842](https://issues.redhat.com/browse/ARO-6842)
This PR set TLS 1.2 as minimum requirement for cosmodb as required by Microsoft Compliance 
Tested using full-rp-dev-setup. Details added in JIRA ticket. 
NA
Tested using full-rp-dev-setup. Details added in JIRA ticket.
=> Setting TLS1.2 as min for cosmoDB

pkg/util/azureclient/mgmt/compute/virtualmachines.go
Fixes https://issues.redhat.com/browse/ARO-3807
Polling duration for virtual machine is increased to 30 minutes to give more time for process to finish and avoid timing out.
No test plan. Unable to reproduce a wait time of more than 15 minutes.
No, tech debt. 
Existing implementation that overrides default polling duration exists in
pkg/util/azureclient/mgmt/features/deployments.go
=> ARO-7160: Increase polling duration for virtual machine to 30mins

pkg/api/v20231122/openshiftcluster_convert.go, pkg/api/v20240812preview/openshiftcluster_convert.go, pkg/frontend/openshiftcluster_putorpatch.go
Fixes https://issues.redhat.com/browse/ARO-7192
Clears the ReadOnly fields on PUT or PATCH requests in 2023-11-22 and 2024-08-12-preview APIs.  The addition of clearing the fields on PUT requests is due to the frontend prepopulating fields it "thinks" are expected, toInternal() preserves these fields.
Ran e2e against api 2023-11-22
Existing unit tests
created cluster and ran az aro update against 2023-11-22
=> Bug fix - clear ReadOnly fields on PUT or PATCH for 2023-11-22 and 2024-08-12-preview APIs

pkg/deploy/assets/databases-development.json, pkg/deploy/assets/rp-production.json, pkg/util/arm/marshal.go
Fixes:-
e2e pipeline failure due to cosmos db deployment failure, related failed e2e runs:- https://msazure.visualstudio.com/AzureRedHatOpenShift/_build/results?buildId=92491280&view=results
Issue was caused after following PR was merged:- https://github.com/Azure/ARO-RP/pull/3520
Adds the dependsOn wherever needed, that was removed as part of the PR that caused issue.
e2e should succeed. (In Progress)
No
=> add dependsOn for cosmosdb container deployment templates

pkg/util/cluster/cluster.go
Fixes no Jira yet
Along the same lines as #3513, this PR skips explicit roleassignment deletion during cluster cleanup when we are going to delete the resources within the roleassignment scope anyways. 
If the resource within the scope of a roleassignment is deleted, or any parent resources are deleted (e.g. resource group, or top-level resource of a sub-resource scope), the role assignments get cleaned up as well. 
This change avoids "failing" E2E in scenarios where we fail to perform explicit roleassignment deletion, but the roleassignments get cleaned up anyways through implicit deletion alongside their resources.
- PR E2E succeeds and no roleassignments are left behind on the service principal
- Prod E2E succeeds and no roleassignments are left behind on the service principal
N/A 
See …
=> Do not perform explicit CSP roleassignment deletion in prod e2e

Makefile, docs/deploy-development-rp.md, docs/prepare-your-dev-environment.md, env.example
[ARO-7278](https://issues.redhat.com/browse/ARO-7278)
- Fix the `github.user` doc
- Fix the `az` cli doc for setting envvar rather than ~/.config
This PR updates the developer onboarding documentation.
Documented how to manually test and verify the feature
N/A
N/A
=>  Modified the content to set up the dev env  : ARO-7278

docs/deploy-full-rp-service-in-dev.md
In the steps where we need to white list the local ISP IP by creating a NSG rule, it fails because `$(curl --silent ipecho.net/plain)/32` gives ipv6 IP. Fixed that by adding the option to give ipv4 IP.
=> Added option to only give ipv4 as output.

.github/workflows/ci-go.yml, .pipelines/ci.yml, .pipelines/onebranch/pipeline.buildrp.official.yml, .pipelines/onebranch/pipeline.buildrp.pullrequest.yml, pkg/containerinstall/install_test.go
**Which issue this PR addresses:**
https://issues.redhat.com/browse/ARO-6716
**Fixes**
What this PR does / why we need it:
This fixes some CVEs in the standard library which govulncheck notes:
https://pkg.go.dev/vuln/GO-2023-2382
https://pkg.go.dev/vuln/GO-2023-2186
among others patched in go-toolset
**Test plan for issue:**
local go unit test with `/pkg/containerinstall/install_test.go` and E2E
**Is there any documentation that needs to be updated for this PR?**
N/A
**How do you know this will function as expected in production?**
should be fine as long as E2E passes
=> update go version to 1.20.12

Dockerfile.aro-e2e, Dockerfile.aro-multistage, Dockerfile.gatekeeper, Dockerfile.proxy
https://issues.redhat.com/browse/ARO-6717
Fixes
This fixes some CVEs in the standard library which govulncheck notes:
https://pkg.go.dev/vuln/GO-2023-2382
https://pkg.go.dev/vuln/GO-2023-2186
among others patched in go-toolset
basic checks plus ci & e2e
NA
should be fine as long as e2e passes
=> upgrade to go1.20.12

pkg/cluster/adminupdate_test.go, pkg/cluster/install.go, pkg/util/generics/helpers.go
A refactor to lay the groundwork for: https://issues.redhat.com/browse/ARO-5327
I've smashed all the various `if` blocks to give us another view on what this is doing and hopefully, this is clearer. I've preserved the step execution order (mostly) because it's not clear to me what exactly what dependencies are involved.   Functionally, I believe this is identical to what we had before but now there is some extra repeats of certain idempotent steps. 
Note: I noticed that in the `everything` path weren't actually running the `m.renewMDSDCertificate` step. This PR fixes this.
Some questions:
- ~~Is it valid to run this with all flags set to false? Technically, it would have done bootstrap 0 & 1 and step 0 but here I set it to panic.~~
It is valid according to the unit tests.
- ~~Is the hive …
=> Fix adminUpdate steps

pkg/util/cluster/cluster.go
This is the same PR as #3360 but it was made from a branch not a fork to pass the E2E.
There is no way to specify pull-secret when we use the hack script to create a cluster.
When testing the installer, if the installer image is hosted in quay.io, hive doesn't changes the domains of other images required during installation to ACR domain and it causes Authentication error if it doesn't have the pull-secret.
This pull-secret enables us to access to those images in quay.io and make the installer test convenient.
I was able to create a cluster with ACR domain installer and quay.io domain installer.
=> accept pull-secret when we use hack script to create a clsuter

docs/deploy-development-rp.md
None 
Related to #3486 
This PR adds document about how to create a cluster with custom installer.
N/A document update
updated
N/A
=> Update document about custom installer

Dockerfile.ci-rp, Dockerfile.ci-rp.dockerignore, Makefile, docs/prepare-your-dev-environment.md
Fixes [ARO-5087](https://issues.redhat.com/browse/ARO-5087). Special shout-out to #tony-schndr for his amazing work in getting the massive initial hurdles out of the way!
* Adds a Makefile target `make ci-rp` that issues a `podman build` command to consolidate 100% of required validation steps into a container build process (read: in the containerfile) so that it runs anywhere (local, pr, and on trunk commits in CI).
* Creates a clear line of logic and removes complex inter-dependencies during the build process. I hope I have clarified the exact build requirements by only moving commands in one direction flow: Makefile >> docker build >> shell commands. There are no longer complex chains of logic to parse out (e.g. "what env vars do I need to set for this command to work?" "what does …
=> `make ci` support for golang (RP) components

pkg/frontend/asyncoperationresult_get.go, pkg/frontend/openshiftcluster_get.go, pkg/frontend/openshiftcluster_list.go, pkg/frontend/openshiftclustercredentials_post.go, pkg/frontend/openshiftclusterkubeconfigcredentials_post.go
Additional changes for https://issues.redhat.com/browse/ARO-6623
Previous PR:- https://github.com/Azure/ARO-RP/pull/3529
Adds a condition on ServicePrincipalProfile before setting the client secret. This required for the MIWI clusters which will have the ServicePrincipalProfile as nil, and setting ClientSecret on the nil pointer would cause an error.
e2e and CI should pass
No
Additional checks on already tested and working flow.
=> Add nil check on ServicePrincipalProfile before populating clientsecrets for different frontend routes

hack/devtools/deploy-shared-env.sh
Development VPN connection issues across the team
Currently, at least on my Mac, the `genkey` hack generates the VPN client private key in one format, while the `vpn_configuration` function tries to read the private key in a different format. Since `vpn_configuration` generates an OpenVPN config file and places the improperly formatted private key into this file, this issue results in some confusing problems when you're trying to connect to any of our shared dev VPNs or a VPN that you have set up for your own full service RP.
This PR updates the `vpn_configuration` function to use the same key format as the `genkey` hack.
You can read about the two different private key formats in this Stack Overflow post that I found helpful: https://stackoverflow.com/questions/40822328/openssl-rsa-key-pe …
=> VPN client cert fix

pkg/api/v20240812preview/openshiftcluster_convert.go, pkg/api/v20240812preview/openshiftcluster_validatestatic.go, pkg/api/v20240812preview/openshiftcluster_validatestatic_test.go, pkg/util/arm/resources.go, pkg/util/arm/resources_test.go, pkg/util/stringutils/stringutils.go, pkg/util/stringutils/stringutils_test.go
For ARO-6425
Adds static validation for new API fields added in v20240812preview
Includes unit tests for the new static validation features.
No, this is just static validation to ensure inputs are as expected.
Unit test data has been written to match expected inputs but nonetheless this should be tested in a lower environment before being pushed to production
=> ARO-6425 v20240812preview validation

pkg/deploy/assets/rp-oic.json, pkg/deploy/assets/rp-production-global.json, pkg/deploy/generator/const.go, pkg/deploy/generator/resources.go, pkg/deploy/generator/resources_gateway.go, pkg/deploy/generator/resources_oic.go, pkg/deploy/generator/resources_rp.go
Fixes https://issues.redhat.com/browse/ARO-7388
- Add exempt tags to storage accounts that have public blob anonymous access. This prevents an s360 violation.
- The two storage accounts are dev OIDC and RP version. These are meant to have public access
These are infra changes - will test via rollout in INT
https://msazure.visualstudio.com/AzureRedHatOpenShift/_wiki/wikis/AzureRedHatOpenShift.wiki/675077/S360-Disable-anonymous-public-blob-access
We're going to test in INT and cross fingers the exemption goes through. Also, this change just adds a tag - it's not affecting the configuration of the storage accounts.
=> Add exemption tags for OIDC dev and RP version storage accounts

Dockerfile.proxy, pkg/deploy/assets/env-development.json, pkg/deploy/generator/resources_dev.go, pkg/deploy/generator/scripts/devProxyVMSS.sh, pkg/deploy/generator/templates_dev.go, pkg/proxy/proxy.go
Fixes: ARO-7329
Security Sprint/Waves requires that 1p apps start using Azure Linux as its base OS and enable VMSS auto image upgrade.
To enable VMSS rolling upgrades, we need an LB with a healthcheck.  Dev proxy doesn't have a healthcheck endpoint so I added a simple one on port 8080.
Ensure the deployment is done and e2e runs successfully in INT.  The changes will not be applied to Prod.
No
N/A
=> Migrate dev-proxy-vmss to Azure Linux and enable rolling OS update

pkg/api/admin/openshiftcluster_convert.go, pkg/api/v20230904/openshiftcluster_convert.go, pkg/api/v20231122/openshiftcluster_convert.go, pkg/api/v20240812preview/openshiftcluster_convert.go, pkg/util/mocks/env/core.go
Recently saw a customer where the cluster installation for them was failing when they are using the `--enable-preconfigured-nsg` option to install the cluster.
When digged more into it, I found that the cluster object was correctly sent to the RP but at frontend, the PreconfiguredNSG field gets modified to Disabled.
Fixes [ARO-7419](https://issues.redhat.com/browse/ARO-7419)
=> [BUGFIX] This is to fix the cluster installation failure when preconfigured NSGs used

pkg/util/version/const.go
Fixes ARO-2783
Sets 4.13.40 as default openshift version
Installed a dev cluster succesfully.
No
This has been tested under ARO-4750
=> Making 4.13.40 as default version for local dev

Dockerfile.ci-rp, Makefile
Fixes no Jira
The `go-toolset` image used to build the ARO binary in `make ci-rp` sets its own `VERSION` environment variable, overriding the `VERSION` arg we pass in. This results in the `version.GitCommit` ldflag being set to an incorrect value (version of Go in the go-toolset image). 
This PR changes the name of this argument to `ARO_VERSION` to avoid this naming conflict, and additionally explicitly sets this arg on the RP build stage, since all ARGs are set to nil at the completion of each stage in a multi-stage build. 
- Ran `make ci-rp` with this change in place, and ensured the resulting binary has the correct ldflags set for `version.GitCommit`. 
No
N/A (output of `make ci-rp` not yet used in production)
=> Add explicit `ARG ARO_VERSION` to RP build stage in ci-rp

pkg/api/admin/openshiftcluster.go, pkg/api/openshiftcluster.go, pkg/frontend/openshiftcluster_putorpatch.go, pkg/frontend/openshiftcluster_putorpatch_test.go
Fixes ARO-6086
The cluster doc needs to persist identityURL in order for Cluster MSI (CUAMSI) token refreshing to work. The identityURL is a header that is provided by ARM to the RP and is used for token refreshing purposes. For more info, see the design doc: https://docs.google.com/document/d/1dtgp6B-VYyXUmPsMX9f9MdlAE9sON4OuH1Cw9Ij0mmg/edit that @rajdeep wrote.
API calls should succeed in persisting identityURL header when a put or patch call to RP is made.
=> Add identityURL to internal apis for CMSI usage

pkg/util/arm/deploy.go, pkg/util/azureerrors/error.go, pkg/util/azureerrors/error_test.go, pkg/util/steps/refreshing.go
Fixes [ARO-7598](https://issues.redhat.com/browse/ARO-7598)
Handle ARM deployment preflight errors containing `"Authorization failed for template resource"` as authorization errors within our `AuthorizationRetryingAction` step. 
These errors occur in local development environments, where we fake the behavior of the first-party service principal automatically being granted Owner permissions over a cluster's managed resource group, by explicitly and manually granting this role assignment after MRG creation. This role assignment can take time to propagate, and may not be recognized by the time we apply ARM templates to the managed resource group.
ARM returns an InvalidTemplateDeployment error (HTTP 400), which was not previously considered to be an authorization error and we would thus fail …
=> Retry failed ARM template deployments during cluster installation when FPSP is missing roleassignments

Dockerfile.ci-rp, env.example, pkg/util/pki/pki_test.go
Fixes N/A
Currently to skip the pki tests, which always fail in dev env, you have to set `ARO_RUN_PKI_TESTS`.
Contrary to the name, if you set it, it **skips** the tests.
This PR changes the name to the more appropriate and understandable name, and also adds the envvar to env.example because it should be set in the dev env.
Run `make unit-test-go` in the devenv and confirm that the pki tests are skipped.
Confirm that CI succeeds.
N/A
N/A
=> change envvar name to skip pki unit tests

pkg/util/cluster/cluster.go
Fixes no Jira
Updates pkg/util/cluster/cluster.go to use a single ARO API version and client, replacing the 4 different API versions previously in use. 
This version is currently set to the v20230904 API - the latest public-facing API as of now. This allows the functionality in pkg/util/cluster to continue to be used against production RP instances, e.g. in production E2E contexts. 
No. 
N/A (this functionality is only used during local development and when running E2E)
=> Use single ARO API/client version in pkg/util/cluster

Dockerfile.ci-rp, Makefile
Fixes https://issues.redhat.com/browse/ARO-7189
This PR helps us automatically prune local container images generated by `make ci`, so that we as developers do not run out of local disk space in our machines. Additionally it also does labeling for all the intermediate images in a multistage Docker file which could help us at the time of pruning.
Run `make ci-rp` to produce `aro-*` images and later run `make ci-clean` to verify and validate whether it is pruning those images to free up our local disk space.
None that I'm aware of.
=> Automate Local Image Pruning

pkg/deploy/assets/gateway-production.json, pkg/deploy/assets/rp-production.json, pkg/deploy/generator/resources_gateway.go, pkg/deploy/generator/resources_rp.go
Fixes https://issues.redhat.com/browse/ARO-7792 and https://issues.redhat.com/browse/ARO-7791
- We are making Gateway and RP Boot Diagnostics use managed storage accounts instead of the previously used custom storage accounts, which will be deleted.
- Before, we needed to disable SAS for such storage accounts. As they will be deleted, we no longer need that, just migrating to managed Boot Diagnostics is sufficient.
✅ 1. Local test: I ran `make generate` and `rp-production.json` and `gateway-production.json` had the desired change on the storage account resource. I also ran `make unit-test-go` and `make build-all` to be sure I hadn't broken anything and it was compiling fine. All these commands were executed in the root of `ARO-RP`.
✅  2. INT test: deployment to int was successful, and …
=> Making Gateway and RP Managed Boot Diagnostics

pkg/deploy/assets/env-development.json, pkg/deploy/assets/gateway-production.json, pkg/deploy/assets/rp-production.json, pkg/deploy/generator/resources_dev.go, pkg/deploy/generator/resources_gateway.go, pkg/deploy/generator/resources_rp.go
Fixes: ARO-8414
S360/Security Waves flagged all our VMSSes that they need to enable Automatic OS Upgrade.  We will request an exception for RP and Gateway VMSSes, and we will fix only dev-proxy by turning on the option.  This PR also removes the no longer needed storage account parameters for the previously deleted boot diagnostics SA so that the deployment can continue.
Will test in INT with E2E.
N/A
The full INT deployment should be enough.
=> EnableAutomaticOSUpgrade for dev-proxy-vmss and remove the no longer needed SA params

.github/workflows/ci-guardrailpolicies.yml
as part of ARO-1457
Integrate gator to our CI pipeline to test guardrail policies
the gator cli uses the `test.sh` script in [`ARO-RP/pkg/operator/controllers/guardrails/policies/scripts/`](https://github.com/azure/ARO-RP/blob/master/pkg/operator/controllers/guardrails/policies/scripts/test.sh)
=> added github actions CI for guardrail policies

pkg/operator/controllers/pullsecret/pullsecret_controller.go, pkg/operator/controllers/pullsecret/pullsecret_controller_test.go
[https://issues.redhat.com/browse/ARO-6600](https://issues.redhat.com/browse/ARO-6600) 
This PR adds logging statements for the ARO Operator pullsecret controller to understand what it's updating and when, without surfacing any explicit secret data.
First, create an OpenShift cluster and [run the ARO Operator locally](https://github.com/Azure/ARO-RP/blob/master/docs/operators.md#how-to-run-the-operator-locally-out-of-cluster). 
* To test recreation of the pullsecret- In a seperate terminal, backup the pullsecret `oc get secret/pull-secret -n openshift-config > backup.yaml` and delete it `oc delete secret/pull-secret -n openshift-config`. "Global pull secret deleted, creating again" and "Global pull secret created" will be logged. 
* To test updating of the pullsecret- 
1. Retrieve the …
=> Adding logging statements for pullsecret controller

.github/workflows/ci-go.yml, Makefile, docs/updating-dependencies.md, hack/update-go-module-dependencies.sh
None. It is a small enhancement. Duplicate of #3492.
Run 'go mod' functions to search for [tidy](https://go.dev/ref/mod#go-mod-tidy), and [vendor](https://go.dev/ref/mod#go-mod-vendor) package changes and then [verify](https://go.dev/ref/mod#go-mod-verify) it.
Yes, in the second commit
=> Add new makefile targets for go mod verification

cmd/aro/mirror.go
Add mirroring of ose-tools-rhel8 for 4.15.
ose-tools image is used for troubleshooting scenarios in the wiki, as it comes with the oc client and a few handy tools for investigations.
BTW this week OCP 4.16 will be released and we might want to add 4.16 image of ose-tools-rhel8.
=> Add mirroring of ose-tools-rhel8 for 4.15

docs/deploy-full-rp-service-in-dev.md
1. Update [int like RP deployment ](https://github.com/Azure/ARO-RP/blob/master/docs/deploy-full-rp-service-in-dev.md)with a step on mirroring two distroless Microsoft Geneva images to your ACR. Follow up to [ARO-7837](https://issues.redhat.com/browse/ARO-7837) & https://github.com/openshift/installer-aro-wrapper/pull/122
2. Add two workarounds for installing `devmapper` and `btrfs` packages or ignoring them while mirroring images using Golang.
Fix two issues when following https://github.com/Azure/ARO-RP/blob/master/docs/deploy-full-rp-service-in-dev.md tutorial on a fresh new RHEL 8.10.
Yes - https://github.com/Azure/ARO-RP/blob/master/docs/deploy-full-rp-service-in-dev.md
I have followed https://github.com/Azure/ARO-RP/blob/master/docs/deploy-full-rp-service-in-dev.md and I have …
=> Mirror two Microsoft Geneva images

pkg/cluster/cluster.go, pkg/cluster/ipaddresses.go, pkg/cluster/ipaddresses_test.go
Fixes https://issues.redhat.com/browse/ARO-7316
This has the same change as https://github.com/Azure/ARO-RP/pull/3579 , but changed tenant ID.
This will fix the failure e2e in canary.
cluster creation in local dev.
cluster creation in canary.
N/A
cluster creation success
=> use track2 SDK in updateAPIIPEarly

.pipelines/ci.yml, .pipelines/e2e.yml
Fixes our e2e/CI not running automatically
it is tests :)
n/a
tests only
=> Fix automatic triggering of CI + E2E

.github/CODEOWNERS
Srini has recently become FL for Firefly. Added him as codeowner as is appropriate.
=> feat: Add srini as codeowner

pkg/api/error.go, pkg/api/openshiftcluster.go, pkg/api/v20191231preview/openshiftcluster_validatestatic.go, pkg/api/v20191231preview/openshiftcluster_validatestatic_test.go, pkg/api/v20200430/openshiftcluster_validatestatic.go, pkg/api/v20200430/openshiftcluster_validatestatic_test.go, pkg/api/v20210901preview/openshiftcluster_validatestatic.go, pkg/api/v20210901preview/openshiftcluster_validatestatic_test.go, pkg/api/v20220401/openshiftcluster_validatestatic.go, pkg/api/v20220401/openshiftcluster_validatestatic_test.go, pkg/api/v20220904/openshiftcluster_validatestatic.go, pkg/api/v20220904/openshiftcluster_validatestatic_test.go, pkg/api/v20230401/openshiftcluster_validatestatic.go, pkg/api/v20230401/openshiftcluster_validatestatic_test.go, pkg/api/v20230701preview/openshiftcluster_validatestatic.go, pkg/api/v20230701preview/openshiftcluster_validatestatic_test.go, pkg/api/v20230904/openshiftcluster_validatestatic.go, pkg/api/v20230904/openshiftcluster_validatestatic_test.go, pkg/api/v20231122/openshiftcluster_validatestatic.go, pkg/api/v20231122/openshiftcluster_validatestatic_test.go, pkg/api/v20240812preview/openshiftcluster_validatestatic.go, pkg/api/v20240812preview/openshiftcluster_validatestatic_test.go
[CIF - Prevent creating OVNKubernetes Clusters with VNET ranges of 100.64.0.0/16](https://issues.redhat.com/browse/ARO-4743)
OVN-Kubernetes, the default network provider in OpenShift Container Platform 4.11 and later, uses the _100.64.0.0/16_ IP address range internally. Added validation that Pod and Service CIDR must not use above IP address.
**Reference Documentation:** https://docs.openshift.com/container-platform/4.14/networking/cidr-range-definitions.html
- Unit test added for this specific case
- All existing unit and e2e tests continue to pass
No
=> Add validation for default CIDR range

.github/CODEOWNERS
- Maitiu is backup FL for EMEA. 
- Aldo has gotten widespread head nodding for code owner status
Adding then as codeowners.
Note: 
I know I'm adding myself and it feels weird but we're stretched a bit atm and I have some time today to just do this PR.
=> Add myself and Aldo as codeowners

docs/deploy-development-rp.md
Fixes: https://issues.redhat.com/browse/ARO-8862
Using a local RP to create a cluster requires registering the subscription to the RP. Following the local development RP docs however yields in this error when trying to spin up a new cluster:
```
(InvalidSubscriptionState) Request is not allowed in unregistered subscription '...'.
```
This PR makes sure that registering the subscription to the local RP is explicitly mentioned.
=> [ARO-8862] local-rp dev docs should mention registering the sub

pkg/api/admin/openshiftcluster.go, pkg/api/openshiftcluster.go, pkg/cluster/adminupdate_test.go, pkg/cluster/arooperator.go, pkg/cluster/arooperator_test.go, pkg/cluster/install.go, pkg/operator/deploy/deploy.go, pkg/util/mocks/operator/deploy/deploy.go
Fixes ARO-7181
Fixes a potential bug (and something that affects #6660) where a flag change *and* an ARO Operator upgrade would cause the flag to take effect on the old operator, rather than the new one.
Unit tests should cover the AdminUpdate behaviour, E2E tests should cover the installation behaviour. It will also undergo QA as a part of #6660.
N/A
Testing :)
=> [ARO-7181] Upgrade the ARO Operator, then update the Cluster object

pkg/deploy/assets/env-development.json, pkg/deploy/generator/resources_dev.go
Fixes no Jira
In #3562, we migrated our dev-proxy-vmss from a RHEL image to Mariner. This caused the OSDisk that we provision for these VM instances to shrink from 64GB to 5GB (RHEL -> Mariner image defaults). 
This PR explicitly sets the OSDisk size to 64GB. 
No
dev-proxy-vmss is not used in production.
=> Increase dev-proxy-vmss OSDisk to 64GB

docs/hive.md, hack/hive-generate-config.sh, hack/util.sh
[ARO-8852](https://issues.redhat.com/browse/ARO-8852)
Fixes
This allows for easier testing of hive images prior to the actual hive deployments.
The script has also been reworked for improved readability, debugging information, and code reuse.
The new `hack/util.sh` script can be sourced by all scripts under `hack/` for shared usage in follow up pull requests.
Previously `kustomize` was left in `/tmp` and not installed. Now `kustomize` is installed to the user's bin directory at `~/bin`.
Tested locally while bumping hive images in [PR #3662](https://github.com/Azure/ARO-RP/pull/3662)
`docs/hive.md` has been updated in this pull request.
Local testing output:
```bash
main: Using hive commit: b1ac27b248
install_kustomize: starting
hive_repo_clone: starting
hive_repo_clone: Cloning …
```
=> Update hive-generate-config.sh to accept differing versions

python/az/aro/azext_aro/tests/latest/unit/test_dynamic_validators.py, python/az/aro/azext_aro/tests/latest/unit/test_validators.py, requirements.txt
Fixes N/A
With Python 3.12.3, `make az` fail returning the error below
<details><summary>Error</summary>
```
python3 -m venv pyenv
. pyenv/bin/activate && \
pip install -U pip && \
pip install -r requirements.txt && \
azdev setup -r . && \
sed -i -e "s|^dev_sources = /Users/atokubi/ARO-RP$|dev_sources = /Users/atokubi/ARO-RP/python|" ~/.azure/config
Requirement already satisfied: pip in ./pyenv/lib/python3.12/site-packages (24.0)
Collecting pip
Using cached pip-24.1.1-py3-none-any.whl.metadata (3.6 kB)
Using cached pip-24.1.1-py3-none-any.whl (1.8 MB)
Installing collected packages: pip
Attempting uninstall: pip
Found existing installation: pip 24.0
Uninstalling pip-24.0:
Successfully uninstalled pip-24.0
Successfully installed pip-24.1.1
Collecting autopep8==1.6.0 (from -r …
```
=> bump azdev

pkg/backend/metrics.go, pkg/backend/metrics_const.go, pkg/backend/metrics_provisioning.go, pkg/backend/metrics_test.go, pkg/backend/openshiftcluster.go, pkg/backend/openshiftcluster_test.go
[ARO-7839](https://issues.redhat.com/browse/ARO-7839)
Fixes
Emit metrics for all RP operation types, creating, updating, adminupdating, and deleting.
Covered by unit tests.
No
=> Emit Cluster Feature Metrics for Cluster Operations

.github/CODEOWNERS
Adds new NASA codeowners proposed last week.
=> Add new NASA codeowners to ARO-RP

pkg/util/cluster/cluster.go
Reopened https://github.com/Azure/ARO-RP/pull/3668 with branch in the correct repository.
Fixes https://issues.redhat.com/browse/ARO-7788
Currently, the dev cluster creation tooling always makes sure that the default openshift version together with the default installer image is written to the cosmos db before creating the cluster. This however makes it impossible to use a custom installer image with the default openshift version, as any modifications to the installer image are overwritten.
This PR changes this behaviour so that the default version and installer image is only written when it is not already present.
- testing was performed according to instructions in jira ticket.
- No
- 
- this doesn't affect production.
=> [ARO-7788] Don't overwrite default installer version in local dev

pkg/operator/controllers/autosizednodes/autosizednodes_controller.go, pkg/operator/controllers/banner/banner_controller.go, pkg/operator/controllers/checkers/clusterdnschecker/controller.go, pkg/operator/controllers/checkers/ingresscertificatechecker/controller.go, pkg/operator/controllers/checkers/internetchecker/controller.go, pkg/operator/controllers/checkers/serviceprincipalchecker/controller.go, pkg/operator/controllers/cloudproviderconfig/cloudproviderconfig_controller.go, pkg/operator/controllers/clusteroperatoraro/clusteroperatoraro_controller.go, pkg/operator/controllers/dnsmasq/cluster_controller.go, pkg/operator/controllers/genevalogging/genevalogging_controller.go, pkg/operator/controllers/guardrails/guardrails_controller.go, pkg/operator/controllers/ingress/ingress_controller.go, pkg/operator/controllers/machinehealthcheck/machinehealthcheck_controller.go, pkg/operator/controllers/machineset/machineset_controller.go, pkg/operator/controllers/monitoring/monitoring_controller.go, pkg/operator/controllers/muo/muo_controller.go, pkg/operator/controllers/pullsecret/pullsecret_controller.go, pkg/operator/controllers/rbac/rbac_controller.go, pkg/operator/controllers/routefix/routefix_controller.go, pkg/operator/controllers/storageaccounts/storageaccount_controller.go, pkg/operator/controllers/subnets/subnets_controller.go, pkg/operator/controllers/workaround/workaround_controller.go, pkg/operator/predicates/predicates.go
Another proposed fix for [ARO-4632](https://issues.redhat.com/browse/ARO-4632)
May help with [ARO-5216](https://issues.redhat.com/browse/ARO-5216) as well
Various changes to how the ARO operator watches resources:
- Extract all common predicates used by controllers to shared package
- Only watch for generation change in ARO cluster resource on most controllers (avoid Reconciles when just status changes)
- Unit tests continue to pass
- E2E tests continue to pass
- Operator functionality not covered by existing tests but likely to be impacted by the change have new tests (TODO)
Note - I am expecting some E2E tests to become _more_ flaky because of this change, as we have many E2E tests that are dependent on the operator reconciling more often than is necessary, and expecting an operator …
=> ARO Operator - Reduce unnecessary reconciles by limiting watched resources/changes

go.mod, hack/gendevconfig/gendevconfig.go, hack/genhiveconfig/genhiveconfig.go, hack/validate-imports/validate-imports.go, pkg/cluster/clusterserviceprincipal.go, pkg/cluster/clusterserviceprincipal_test.go, pkg/cluster/kubeconfig.go, pkg/cluster/kubeconfig_test.go, pkg/deploy/config.go, pkg/operator/controllers/alertwebhook/alertwebhook_controller.go, pkg/operator/controllers/monitoring/monitoring_controller.go, pkg/operator/controllers/muo/template_test.go, pkg/portal/kubeconfig/proxy.go, pkg/util/dynamichelper/unstructuredobj.go, test/e2e/operator.go
Splitting out of the work in https://issues.redhat.com/browse/ARO-1420 
Replaces github.com/ghodss/yaml with the maintained k8s fork.
CI, E2E
N/A
CI should validate behaviour, plus it is not (much, any?) of an underlying behavioural change.
=> Move to maintained yaml lib

pkg/util/azureclient/mgmt/redhatopenshift/2023-09-04/redhatopenshift/openshiftclusters_addons.go, pkg/util/azureclient/mgmt/redhatopenshift/2023-11-22/redhatopenshift/openshiftclusters_addons.go, pkg/util/azureclient/mgmt/redhatopenshift/2024-08-12-preview/redhatopenshift/openshiftclusters_addons.go, pkg/util/cluster/cluster.go, test/e2e/adminapi_delete_managedresource.go, test/e2e/cluster.go, test/e2e/setup.go, test/e2e/update.go
Fixes https://issues.redhat.com/browse/ARO-4618
This PR updates our e2e test suite to use the new GA API version `20231122`, instead of the `20230701preview` version of the API. Plus it also focuses to update our internal, manually-written wrappers around Azure SDK clients and adds back the missing `UpdateAndWait()` functionality to `20231122` and `20240812preview`. This will help us to create clusters with this new GA API version. 
N/A.
None that I'm aware of.
=> Updates Test Suite To Use New GA API Plus Adds Missing Functionality To Our Internal Utility Clients

Dockerfile.ci-tunnel, Makefile
Fixes [ARO-8549](https://issues.redhat.com/browse/ARO-8549)
Builds `./hack/tunnel` into a runnable container. This will allow it to eventually be used within CI contexts to make requests using dev tooling (e.g. `az aro` extension) to a running full-service RP. 
```sh
for f in "localhost.crt" "localhost.key" "dev-client.crt" "dev-client.key"; do
podman secret create $f ./secrets/$f;
done
podman run -it \
-p 8443:8443 \
--secret localhost.crt,target=/opt/secrets/localhost.crt \
--secret localhost.key,target=/opt/secrets/localhost.key \
--secret dev-client.crt,target=/opt/secrets/dev-client.crt \
--secret dev-client.key,target=/opt/secrets/dev-client.key \
aro-tunnel:${VERSION} \
--certFile /opt/secrets/localhost.crt \
--keyFile /opt/secrets/localhost.key \
--clientCertFile …
```
=> Containerize `./hack/tunnel`

cmd/aro/const.go, cmd/aro/main.go, cmd/aro/update_role_sets.go, pkg/env/core.go, pkg/util/cluster/cluster.go, pkg/util/rolesets/const.go
Fixes https://issues.redhat.com/browse/ARO-6449
Adds a new cmd for populating our new proxy resource (PlatformWorkloadIdentityRoleSetDocument) with role sets in prod, and adds the hack code to populate it in dev too. This resource is used to determine identity requirements for supported OCP versions.
- Steps to test:
1) `export PLATFORM_WORKLOAD_IDENTITY_ROLE_SETS='[{"openShiftVersion":"4.14","platformWorkloadIdentityRoles":[{"operatorName":"CloudControllerManager","roleDefinitionName":"Azure RedHat OpenShift Cloud Controller Manager Role","roleDefinitionId":"/providers/Microsoft.Authorization/roleDefinitions/a1f96423-95ce-4224-ab27-4e3dc72facd4","serviceAccounts":["openshift-cloud-controller-manager:cloud-controller-manager"]},{"operatorName":"ClusterIngressOperator","roleDefinitionName": …
=> New cmd to populate PlatformWorkloadIdentityRoleSets in dev and prod

Makefile
Fixes `make ci-rp` locally
- eliminated TCP errors during builds attempting to hit localhost:443 as a registry domain
- eliminated build failures caused by incorrect final tag name with unset envvars
`make ci-rp` now runs locally without TCP and/or build errors.
No.
Only affects local development and image tag names used locally.
=> HOTFIX: correct local image names

test/e2e/disk_encryption.go
Fixes N/A
When I ran e2e to the local dev cluster without encryption, I got this error and it panics.
```
STEP: getting the test cluster resource @ 07/15/24 13:05:49.935
STEP: checking that disk encryption at rest is enabled for masters @ 07/15/24 13:05:50.148
[PANICKED] in [It] - /usr/local/Cellar/go/1.22.2/libexec/src/runtime/panic.go:261 @ 07/15/24 13:05:50.148
• [PANICKED] [0.429 seconds]
Disk encryption at rest [It] must be enabled with customer managed key for the cluster and each disk must have it enabled
/Users/atokubi/ARO-RP/test/e2e/disk_encryption.go:70
[PANICKED] Test Panicked
In [It] at: /usr/local/Cellar/go/1.22.2/libexec/src/runtime/panic.go:261 @ 07/15/24 13:05:50.148
runtime error: invalid memory address or nil pointer dereference
Full Stack Trace …
```
=> fix dev env panic in e2e

pkg/backend/metrics.go, pkg/backend/metrics_test.go
[ARO-9146](https://issues.redhat.com/browse/ARO-9146)
Fixes
If the `doc.OpenShiftCluster.Properties.NetworkProfile.LoadBalancerProfile ` is nil, checking for a nil `doc.OpenShiftCluster.Properties.NetworkProfile.LoadBalancerProfile.ManagedOutboundIPs` will cause a panic.
Relevant line from stack trace:
```go
(*openShiftClusterBackend).gatherNetworkMetrics(0xc000a0cff0, 0x5c35fa0?, 0xc00109c600, 0x6?)\n\t/app/pkg/backend/metrics.go:221 +0x930\ngithub.com/Azure/ARO-RP/pkg/backend.
```
Checking for `doc.OpenShiftCluster.Properties.NetworkProfile.LoadBalancerProfile` first will stop a nil `doc.OpenShiftCluster.Properties.NetworkProfile.LoadBalancerProfile.ManagedOutboundIPs` from being de referenced.
Covered by unit tests.
Will also create a UDR cluster with this document: …
=> Bug fix - Add nil pointer check for LoadBalancerProfile in cluster metrics

pkg/deploy/assets/cluster-development-predeploy.json, pkg/deploy/assets/env-development.json, pkg/deploy/assets/gateway-production.json, pkg/deploy/assets/rp-production.json, pkg/deploy/generator/resources_cluster.go, pkg/deploy/generator/resources_dev.go, pkg/util/azureclient/apiversions.go
No Jira ticket; small thing I encountered doing some other work.
While I was working on deploying our shared dev infra in the Red Hat tenant I encountered an error indicating that the API version specified for the compute RP didn't seem to exist. I traced it back to this commit: https://github.com/Azure/ARO-RP/pull/3600/commits/de3f34242f1c31b8d9762fd364a16df3b63b5e73. You can see the exact error message if you check out my commit messages on this PR.
My PR switches our ARM templates to use the latest stable compute API version.
If the current API version, 2021-12-01, is truly no longer available, I expect that this issue will block any upcoming RP deployments in any environments.
Validated that I no longer encounter issues locally. E2E will validate it in CI as well.
N/A
E2E in CI + E2E …
=> Hotfix: compute API version used in ARM templates

pkg/cluster/adminupdate_test.go, pkg/cluster/install.go
Picking up from @mbarnes  https://github.com/Azure/ARO-RP/pull/2961
[[ARO-1919] AAD: Migrate ARO-RP Azure AD Graph -> Microsoft Graph](https://issues.redhat.com/browse/ARO-1919)
Minor follow-up to #1970 where @bennerv requested this in his review.
The fixupClusterSPObjectID step in PUCM uses only the MS Graph client (no ARM calls), and the client already handles HTTP 401 Unauthorized errors by refreshing its authorization token. So there's no need to use the AuthorizationRetryingAction wrapper.
The 401 Unauthorized error handling logic for the MS Graph client is in the github.com/microsoft/kiota-http-go module.
Create an ARO cluster.
Run az aro update --refresh-credentials on it.
Verify it completes successfully.
No, this is just an internal change.
=> pkg/cluster: Use Action for fixupClusterSPObjectID

pkg/api/preflight.go, pkg/api/subscriptiondocument_example.go, pkg/frontend/openshiftcluster_preflightvalidation.go, pkg/frontend/openshiftcluster_preflightvalidation_test.go
Fixes https://issues.redhat.com/browse/ARO-3854
Currently we have preflight set up for create operations but also need it for update. These changes allow for both put/patch operations on preflight. This PR also cleans up the way we validate for preflight and adds new checks for it as well. There was a previous PR for this here: https://github.com/Azure/ARO-RP/pull/3365 but it was getting messy, and needed to move off the forked branch so that E2E tests would work correctly. 
Created additional unit tests that are similar to put/patch tests. Kusto logs also show preflight success and failures with more details than before. Preflight is also marked for testing and won't hit live until another PR in the future sets that value.
=> Preflight update and tests

pkg/util/dynamichelper/dynamichelper.go, pkg/util/dynamichelper/dynamichelper_test.go
Fixes TODO
On OCP 4.15, the MUO reconciler is running into an endless loop, constantly updating the `trusted-ca-bundle` ConfigMap.
Reason is that since OCP 4.15 the controller, which inserts the certificates into that ConfigMap, is also adding a new annotation: `"openshift.io/owning-component": "Networking / cluster-network-operator"`.
So we need to copy that over to the new ConfigMap in case of updates.
The issue was discovered by very flake MUO deletion test on OCP 4.15. With this change, the test succeeds.
Also the corresponding unit test was extended for the new annotation.
No, this just is a not user facing implementation detail.
Trusting the e2e test.
=> Fix Managed Upgrade Operator reconciler

.gitignore, .pipelines/e2e.yml, docs/deploy-development-rp.md, hack/cluster/cluster.go, hack/e2e/run-rp-and-e2e.sh, pkg/util/cluster/cluster.go, test/e2e/setup.go
[Ticket](https://issues.redhat.com/browse/ARO-8854)
This PR:
- reverts the contents of https://github.com/Azure/ARO-RP/pull/3498/files so we can run E2E in the new tenant.
- makes the deletion flow more explicit and attempts to clean up everything at the end.
=> Create sp for each e2e run

pkg/util/azureclient/authz/remotepdp/const.go, pkg/util/azureclient/authz/remotepdp/types.go, pkg/validate/dynamic/dynamic.go
Fixes: ARO-9261
Refer to the IcM in JIRA, CheckAccess team informed that we need to send an additional field to give hints to CheckAccess that "group expansion" is needed.
Without group expansion, CheckAccess will not take into account what groups the principal belongs to.  That is, if a service principal A is a member of group B, and group B allows writing to a VNet, calling CheckAccess without the group expansion field will return a response that A is not allowed to write to a VNet.  With the group expansion hint, CheckAccess will return an allowed response, which is the behavior we want.
I reproduced this by creating a Deny Assignment on a VNet resource from Azure Blueprint and made a group excluded from it.  The testing app principal is then added to the group.  After that I verified …
=> Always do group expansion for CheckAccess subjects

pkg/api/openshiftcluster.go, pkg/portal/cluster/nodes.go, pkg/util/azureclient/applens/applens_client.go
Fixes some lint failures on master for me
Fixes some linting errors that golangci-lint 1.59.1 picks up.
CI, E2E 
N/A
E2E
=> Clean up some lint errors found on golangci-lint 1.59.1

hack/hive-config/hive-additional-install-log-regexes.yaml, pkg/hive/failure/handler.go, pkg/hive/failure/reasons.go, pkg/hive/failure/reasons_test.go
[ARO-4867](https://issues.redhat.com/browse/ARO-4867)
Following the pattern established in the old PR [#3116](https://github.com/Azure/ARO-RP/pull/3116) for handling Hive installation failures in the RP, this PR addresses a specific case (Azure ZonalAllocationFailed) by forwarding the policy errors to the requester. The sequence of patterns in the Hive ConfigMap ensures that specific errors take precedence over this general one.
With this code running on e.g. a local RP setup that installs via Hive, with the included additional-install-log-regexes ConfigMap applied in the Hive cluster:
Create a policy that blocks e.g. creation of the bootstrap/master VMs created by the installer
Attempt a cluster creation
Unit tests have been added for the specific Hive install failure cases implemented …
=> CIF - ServerError: ZonalAllocationFailed

pkg/hive/manager.go, pkg/hive/manager_test.go, pkg/monitor/cluster/hiveregistrationstatus.go, pkg/monitor/cluster/hiveregistrationstatus_test.go
Fixes: https://issues.redhat.com/browse/ARO-7787
This PR drops the sync sets check from `IsClusterDeploymentReady`.
Monitoring of SyncSets will come as part of it's own monitoring in the future and since we have no SyncSets at present there is no temporary gap.
Tested locally using the dev Hive
=> Drop SyncSets check

pkg/operator/controllers/node/node_controller.go, pkg/operator/controllers/node/node_controller_test.go
Fixes N/A
In a part of other work, I found when I scale machinesets up and down, node controller starts to complain:
```
time="2024-07-24T17:16:45Z" level=error msg="Node \"sre-shared-cluster-ltnmx-worker-eastus1-cl8zj\" not found" func="node.(*Reconciler).Reconcile()" file="pkg/operator/controllers/node/node_controller.go:67" controller=Node
```
This happens because the node is deleted before the request is handled.
Current implementation returns nil if the node is not found and retries, which causes the repeated reconciliation.
Test in local dev cluster.
N/A, bug fix
Try scaling machinesets and check whether there is node controller error logs in aro-operator logs.
=> fix repeated reconciliation in node controller

pkg/util/cluster/aroclient.go, pkg/util/cluster/cluster.go
Fixes [ARO-8003](https://issues.redhat.com/browse/ARO-8003)
This PR updates `pkg/util/cluster/cluster.go` to use the latest in-progress API (v20240812preview) when environment variable `RP_MODE` is set to `development`, and the latest released API that's routable in ARM otherwise (v20231122). 
This allows local development cluster creation, as well as E2E runs against a locally running RP (e.g. the E2E PR pipeline) to test cluster creation/deletion against our in-progress API, while still ensuring that we utilize the latest ARM-routable API during production contexts (e.g. prod E2E). 
The implementation here is generic, and could be expanded in the future to allow us to arbitrarily select which ARO API version we would like to use. 
- Our internal API release documentation should be …
=> Use latest "in-progress" ARO API for local/E2E cluster creation

test/e2e/operator.go
Fixes https://issues.redhat.com/browse/ARO-7345
This PR adds smoke test that confirms there is no error log in aro-operator logs.
This is labelled as "smoke", so it doesn't run automatically in CI.
Run `E2E_LABEL=smoke make test-e2e` locally.
N/A
This is a part of tests.
=> [ARO-7345] smoke test automation for aro-operator log 

Makefile
Fixes no Jira
We previously added the Azure Extension dev_sources property the user's global Azure configuration file, but with #3554 this is no longer necessary, as we set this property via environment variable within the RP development context instead.
No. Documentation was already updated to use the env var instead of configuration (see https://github.com/Azure/ARO-RP/blob/master/docs/deploy-development-rp.md#installing-the-extension) 
Non-production change
=> Do not modify user's Azure CLI config in make pyenv target 

pkg/util/azureclient/azuresdk/errors/errors.go, pkg/util/dns/dns.go, pkg/util/dns/dns_test.go
Fixes N/A
In a part of other task, I found it failed to delete a cluster when dns records are already deleted.
This was caused by the update of the sdk to track2.
Since track2, autorest has been deprecated, we needed to change it to ResponseError.
cf. https://github.com/Azure/go-autorest
https://github.com/Azure/azure-sdk-for-go/blob/e302bb60ef995455b0eaabf590a75c8396e32834/sdk/azcore/internal/exported/response_error.go#L112
I found https://pkg.go.dev/github.com/Azure/azure-sdk-for-go-extensions/pkg/errors#IsNotFoundErr this repository but we can't use it, because the error we get is `NotFound`, but it checks if the error is `ResourceNotFound`.
Probably this discrepancy might come from the Azure API server, but anyway we can't use it.
Delete a dev cluster with dns records already deleted. …
=> Fix NotFound error in DNS isn't handled properly

pkg/deploy/assets/gateway-production.json, pkg/deploy/assets/rp-production.json, pkg/deploy/generator/resources_gateway.go, pkg/deploy/generator/resources_rp.go
To ensure that the vmss instances do not become unavalaible due to storage usage.
[ARO-9421](https://issues.redhat.com/browse/ARO-9421)
Fixes
Increase RP and Gateway VMSS instance disk sizes to prevent full disks from bringing down the instances.
No
=> Increase RP and VMSS disk size from 256GB to 1024GB

cmd/aro/rp.go, pkg/env/prod.go
Fixes deployment failures related to aro-monitor service
IcM:- https://portal.microsofticm.com/imp/v5/incidents/details/527703987/summary
Moves the validation check for variable OIDC_STORAGE_ACCOUNT_NAME from the prod env object setup(that aro-monitor also uses) to rp.go codebase.
Doesn't change the functionality for the RP service, just removal of validation from a general codebase.
Must pass local cluster creation, e2e and canary.
aro-rp was running previously so there's no impact on the aro-rp service.
aro-monitor doesn't need OIDC_STORAGE_ACCOUNT_NAME variable, which was previously checked but not after this PR.
=> ARO-4373 fix oidcstorageaccount variable validation error in aro-monitor

pkg/api/v20240812preview/openshiftcluster_convert.go, pkg/frontend/middleware/msi.go, pkg/frontend/middleware/msi_test.go, pkg/frontend/openshiftcluster_putorpatch.go, pkg/frontend/openshiftcluster_putorpatch_test.go
This issue came up while I was working on https://issues.redhat.com/browse/ARO-4360
- Updates the unit tests for `putOrPatchOpenShiftCluster` to use the latest API version
- Fixes a nil pointer dereference in the converter for the new preview API
- Shifts the code to persist the identity headers further down in the code to ensure that the headers don't get lost during the repeated conversions between external and internal API types
New unit test case
N/A
MIWI feature will be tested extensively when development is done
=> Ensure identity headers are persisted in requests to create MIWI clusters

pkg/util/azureclient/mgmt/network/subnets.go, pkg/util/cluster/cluster.go, pkg/util/mocks/azureclient/mgmt/network/network.go
This PR fixes errors like:
```
Subnet 'maschulz-master' is not valid because its IP address range overlaps with that of an existing subnet in virtual network 'dev-vnet'
```
when creating a cluster using `go run ./hack/cluster create`.
Instead of just randomly generating the subnet cidrs, `generateSubnets` now first retrieves all subnets in the `dev-vnet` and makes sure that the subnet cidrs don't overlap with any of the preexisting ones.
- No
- This change doesn't affect production.
=> [Dev Tooling] generateSubnets should check if subnets are already taken

.pipelines/ci.yml
Allows the Loki team to swarm today on updates to the CI pipeline via a new "trunk" branch for this purpose (allows `/azp run ci` on this alternative branch)
=> Allow the Loki swarming session for day-of-learning

pkg/util/version/const.go
[ARO-5049](https://issues.redhat.com/browse/ARO-5049)
Fixes
Correct the sha checksum for mdsd image to distroless version.
No
=> Correct mdsd image sha to distroless checksum

docs/deploy-development-rp.md, docs/deploy-full-rp-service-in-dev.md
Non-clarity of when to use local dev RP, or when to use the full RP service.
Make it more clear when to build a local dev RP, or when to use the full RP service.
And a added a Known Issues session for common errors situations.
Not needed
=> Added known issues and a session of when to use

.pipelines/ci.yml, Makefile
This PR addresses the issue of inconsistent and error-prone manual build processes by implementing the `make ci `command.
Fixes: [ARO-9563](https://issues.redhat.com/browse/ARO-9563)
This PR automates the build process by using `make ci` instead of manual make commands, ensuring consistency and reducing the potential for human error in the build steps.
The pipeline tests to ensure that the make ci command produces the expected build outputs. Additional manual tests were conducted to verify consistency with previous manual build processes.
N/A
=> This is the new CI-RP stage for the pipline

pkg/util/version/const.go
Fixes [ARO-5049](https://issues.redhat.com/browse/ARO-5049)
Fluentbit Production pipeline has been updated to push the same build to all environments.
This pull request updates the checksum to match what is in the container registries.
```bash
steven@rh-thinkpad-p1:~$ podman pull --authfile .containers/arosvc.dockerconfig arosvc.azurecr.io/fluentbit:1.9.10-cm20240628@sha256:dbf5304bd98cd51c72e4ae0ee8511d3bbcdbcb7e72e65e7d1495a50d7ac33b8d
Trying to pull arosvc.azurecr.io/fluentbit@sha256:dbf5304bd98cd51c72e4ae0ee8511d3bbcdbcb7e72e65e7d1495a50d7ac33b8d...
Getting image source signatures
Copying blob 8af89cb9a3cd skipped: already exists  
Copying blob 5c0d6db3cb16 skipped: already exists  
Copying blob bbeff14dd44c skipped: already exists  
Copying blob 13f9584a5f5b skipped: already exists …
```
=> Sync fluentbit image with correct checksum seen in arosvc registry

pkg/api/v20240812preview/openshiftcluster_convert.go, python/az/aro/azext_aro/_params.py, python/az/aro/azext_aro/_validators.py, python/az/aro/azext_aro/custom.py, python/az/aro/azext_aro/tests/latest/unit/test_validators.py
Fixes [ARO-6451](https://issues.redhat.com/browse/ARO-6451)
Implements the ability to set additional platform workload identities on a managed identity-enabled cluster via `az aro update`. 
- Example invocation: 
```sh
az aro update \
--subscription "${SUBSCRIPTION_ID}" \
--resource-group "${CLUSTER_RESOURCE_GROUP}" \
--name azcli-testcluster \
--assign-platform-workload-identity bar qwert \
--assign-platform-workload-identity baz zxcvb
```
- Against cluster w/ document:
<details>
<summary>Open</summary>
```json
{
"id": "/subscriptions/${SUBSCRIPTION_ID}/resourceGroups/${CLUSTER_RESOURCE_GROUP}/providers/Microsoft.RedHatOpenShift/openShiftClusters/azcli-testcluster",
"location": "eastus",
"identity": {
"type": "UserAssigned",
"userAssignedIdentities": { …
```
=> WI/MI CLI Phase 1 - Base Update Functionality

Makefile, docs/deploy-development-rp.md, env.example, hack/setup_resources.sh, pkg/env/dev.go, setup_resources.sh
We created new Makefile targets to streamline the process of launching containers. This allowed developers to test locally more thoroughly, reducing development cycle time and decreasing failures rate of cluster creation process.
- Fixes [ARO-7435](https://issues.redhat.com/browse/ARO-7435)
- This PR adds new Makefile targets for building, running, and testing the RP container image locally using Podman.
- This enables local development and testing workflows
**Steps for validating on Mac (need to validate on Linux):**
1. Mount your local MacOS filesystem into the podman machine:
`podman machine init --now --cpus=4 --memory=4096 -v $HOME:$HOME`
2. Use the openvpn config file (which is now mounted inside the podman machine) to start the VPN connection:
`podman machine ssh`
`sudo rpm-ostree …
=> Make runlocal-rp with Container Image

.github/CODEOWNERS
Removes @AldoFusterTurpin from our CODEOWNERS. Thank you so much for all you've done for our team, and good luck in your future endeavors!
=> Thank you Aldo, and good luck

pkg/cluster/denyassignment.go, pkg/cluster/denyassignment_test.go, pkg/cluster/deploybaseresources_additional.go, pkg/cluster/deploybaseresources_additional_test.go
Fixes [ARO-6830](https://issues.redhat.com/browse/ARO-6830)
Add platform workload identities to the list of service principals excluded from the permissions denial so that those identities can manage Azure resources in the cluster's resource group
Test plan is to PUT/PATCH a PlatformWorkloadIdentityProfile on an existing cluster, PUCM/adminUpdate it, and ensure that the deny assignment is updated correctly. Deny assignment isn't present in dev though so it'll have to be tested in canary.
Docs don't need to be updated, this is part of enabling MI/WI
Very simple logic. The main question mark is what kind type of principal an identity should have when added to the `ExcludePrincipals` list
=> Exclude platform identities from permissions denial

Makefile, cmd/aro/portal.go, docs/admin-portal.md
Fixes [ARO-9500](https://issues.redhat.com/browse/ARO-9500)
You can now test portal changes locally the same way it's run in prod - via a container run process on `localhost:8444`
I need confirmation from MacOS users that this works for them - I updated some Portal server configs like we did for Shubhada's PR for RP (e.g. directly use `:8444` instead of `localhost:8444` so it works with podman machine setups).
I have validated on Linux that I can run:
1. `make runlocal-portal`
3. navigate to `https://localhost:8444` to see the portal in action.
Yes, it's in the PR.
This is still an unused container image - it is useful now in local development only and is only bringing conformity between prod and local dev.
=> Containerized portal as it runs in prod, locally

Dockerfile.ci-rp, Makefile
Adds flexibility and correctness to Makefile's `podman` calls. Each commit is a unique fix.
- Strictly calls `podman` instead of `docker` to prevent confusion for local cases
- `NO_CACHE=true` actually works now for ci-rp, and we still correctly tag our builder image layers while only building once
- Standardizes image names and tags + the Makefile variable names used to define these things
- Sets up future changes for "remote" podman sockets (see [run podman](https://github.com/Azure/ARO-RP/blob/a387947960ba60f83ee9473d6c38b6c5f30b4076/hack/e2e/run-rp-and-e2e.sh#L107) and [run selenium](https://github.com/Azure/ARO-RP/blob/a387947960ba60f83ee9473d6c38b6c5f30b4076/hack/e2e/run-rp-and-e2e.sh#L145-L146) in our E2E script to see where this is going - where `make ci-rp` and/or `make …
=> Makefile Podman Refactors

Dockerfile.ci-rp, hack/github-actions/npm_audit.sh, portal/v2/package-lock.json
Fixes no Jira
Updates our `npm audit` steps in the CI RP Dockerfile and npm-audit check to only fail when high/critical severity vulnerabilities are found. 
No
Non-production change
=> Only fail NPM audit on high/critical vulnerabilities 

pkg/cluster/arooperator_test.go, pkg/cluster/install.go, pkg/operator/const.go, pkg/operator/deploy/deploy.go, pkg/operator/deploy/deploy_test.go
Fixes https://issues.redhat.com/browse/ARO-6416
Use the provided identity information to generate a secret for the operator
This will be hard to test until we have a way to provision a cluster that uses workload identities. Until then, unit tests are the best we can do
n/a
As above, this will be very challenging to test until there's a way to provision a workload identity cluster. The new code is gated behind a check to see if a cluster has identity information provided, so at the very least, it shouldn't impact standard clusters
=> ARO-6416 generate a secret for the operator from workload identity

Makefile
Fixed Makefile to use local image for runlocal-rp target
Updated the `runlocal-rp` target to correctly reference the locally built `aro` image instead of attempting to pull from Docker Hub. This resolves the issue to incorrectly attempting to pull the aro image
This PR updates the `runlocal-rp` target to correctly use the local `aro` image. 
This change ensures that the locally built image is referenced, improving the reliability of the local development setup.
- Verified functionality by running the `runlocal-rp` target and confirming it uses the local image.
- No additional unit or integration tests were added as the change is related to the build process.
N/A
N/A
=> Fixed  to correctly reference the local  image tag

cmd/aro/operator.go, pkg/operator/controllers/etchosts/cluster_controller.go, pkg/operator/controllers/etchosts/etchosts.go, pkg/operator/controllers/etchosts/etchosts_test.go, pkg/operator/controllers/etchosts/machineconfig_controller.go, pkg/operator/flags.go
Fixes ARO-9570
This PR adds a MachineConfigs for the ARO operator to lay down:
99-master-aro-etc-hosts-gateway-domains
99-worker-aro-etc-hosts-gateway-domains
During the UDR installation incident we have gone back and forth on how resolve the root issue. The root cause is that the gateway domains are not populated for OpenShift images to be pulled and installed. These domains are IPs so we can pass them into `/etc/hosts` to resolve them before other DNS resolution options are available.
I've some minimal smoke testing on the operator with this PR.
=> ARO-9570: Add a controller to the ARO operator to lay down etchosts

go.mod, test/e2e/ocp_alerts.go, vendor/github.com/jpillora/backoff/LICENSE, vendor/github.com/jpillora/backoff/README.md, vendor/github.com/jpillora/backoff/backoff.go, vendor/github.com/mwitkow/go-conntrack/.gitignore, vendor/github.com/mwitkow/go-conntrack/.travis.yml, vendor/github.com/mwitkow/go-conntrack/LICENSE, vendor/github.com/mwitkow/go-conntrack/README.md, vendor/github.com/mwitkow/go-conntrack/dialer_reporter.go, vendor/github.com/mwitkow/go-conntrack/dialer_wrapper.go, vendor/github.com/mwitkow/go-conntrack/listener_reporter.go, vendor/github.com/mwitkow/go-conntrack/listener_wrapper.go, vendor/github.com/prometheus/common/config/config.go, vendor/github.com/prometheus/common/config/http_config.go, vendor/golang.org/x/net/http/httpproxy/proxy.go, vendor/golang.org/x/oauth2/clientcredentials/clientcredentials.go, vendor/modules.txt
Fixes https://issues.redhat.com/browse/ARO-9826
This PR adds a test that checks if any alerts are firing.
Run `E2E_LABEL=smoke make test-e2e` locally.
N/A
Not production feature.
=> Add alerts smoke test

Makefile
Allows more flexibility to local testing
=> Add the old make runlocal-rp as an alternative to containerization

.github/CODEOWNERS
=> Adding Ayato to CODEOWNERS

Makefile
Fixes local make errors
Typo in image tag.
Fix an error for orphaned running work containers by buildah that prevents prune from working. This can occasionally happen when you kill a build with ctrl-c (which can lead to some _really_ wonky build states, like `RUN` commands missing the cache randomly/etc - `make ci-clean` needs to be capable of fixing these states):
```
$ make ci-clean
podman image prune --all --filter="label=aro-*=true"
WARNING! This command removes all images without at least one container associated with them.
Are you sure you want to continue? [y/N] y
Error: image used by fe1476ec4e2c451b5cdf0788df13f9006a64b4c7efa8cde43b72aec1f673c261: image is in use by a container: consider listing external containers and force-removing image
make: *** [Makefile:222: ci-clean] Error …
```
=> Fix make ci-clean and runlocal-rp

pkg/frontend/admin_openshiftcluster_etcdcertificaterenew_test.go, pkg/frontend/changefeed_test.go
Fixes partially https://issues.redhat.com/browse/ARO-9967
- Clarified why the test was passing (it was reaching a 10s timeout and getting the expected error message)
- Updated the timeout from 10s -> 0s to pass faster (roughly ~10s -> 0.3s for the affected test)
I'm unsure if this was the original _intent_ for the test, but it is what it is currently doing. If we want to supplement this test with others, we should do so in a follow-up PR.
- bumped tick rates and cancel timeouts - tests seem to still pass fine without flakiness.
make unit-test-go
N/A
no modification to prod code.
=> Fix slow tests in /pkg/frontend

pkg/cluster/deploybaseresources_test.go, pkg/env/env.go, pkg/env/prod.go, pkg/util/mocks/env/env.go, pkg/util/oidcbuilder/jwks.go, pkg/util/oidcbuilder/jwks_test.go, pkg/util/oidcbuilder/oidcbuilder.go, pkg/util/oidcbuilder/oidcbuilder_test.go
Fixes https://issues.redhat.com/browse/ARO-9968
Generate smaller OIDC keys for unit tests, which removes all OIDC related tests from the "slowest" in our suite.
- significantly increases unit test performance by moving from 4096 -> 256 bit keys (10s -> 0.01s)
- preserves 4096 bit keys for all non-testing scenarios
make unit-test-go
N/A
env.prod has been hard-coded with the expected 4096 bit size.
=> Fix slow tests in /pkg/cluster

Dockerfile.ci-rp, Dockerfile.ci-rp.dockerignore
Improves local build times by eliminating unnecessary build steps (`go generate` and `golangci-lint`)
1. I think, as much as I hate the pattern - `go generate` should be out of our build process. Surprising to me, we are following golang best practice on go generate which is unintuitive coming from other software development stacks. If you want an interesting read from the go maintainers themselves, have a read of https://go.googlesource.com/proposal/+/refs/heads/master/design/go-generate.md, where they state:
> Generation through go generate is not part of the build, just a tool for package authors. This avoids complicating the dependency analysis done by Go build.
2. linting should be out of the build process for a few reasons:
- It saves real-time ~35s of build time per iteration in my …
=> Remove Generate and Lint from containerized build process

pkg/cluster/apply.go, pkg/cluster/cluster.go, pkg/cluster/install.go, pkg/cluster/tls.go, pkg/operator/deploy/deploy.go, pkg/operator/deploy/deploy_test.go, pkg/operator/helpers.go, pkg/util/clienthelper/clienthelper.go, pkg/util/clienthelper/clienthelper_test.go
Splitout of MIMO M1 work
Retrofits clienthelper support into some functions that MIMO tasks require
CI, E2E
N/A
E2E should cover it, since it applies during install as well
=> [MIMO] Move cluster certificate functionality to ClientHelper

cmd/aro/operator.go, pkg/cluster/arooperator.go, pkg/cluster/install.go, pkg/operator/controllers/base/aro_controller.go, pkg/operator/controllers/dnsmasq/cluster_controller.go, pkg/operator/controllers/dnsmasq/cluster_controller_test.go, pkg/operator/controllers/dnsmasq/machineconfig_controller.go, pkg/operator/controllers/dnsmasq/machineconfig_controller_test.go, pkg/operator/controllers/dnsmasq/machineconfigpool_controller.go, pkg/operator/controllers/dnsmasq/machineconfigpool_controller_test.go, pkg/operator/deploy/deploy.go, pkg/operator/flags.go, pkg/util/mocks/operator/deploy/deploy.go, pkg/util/version/clusterversion.go, test/e2e/operator.go, test/util/clienthelper/hookclient.go
Fixes https://issues.redhat.com/browse/ARO-6250
Only performs MachineConfig reconciliation when OpenShift is being upgraded. 
Unit tests + E2E should cover it.
Yes, SOPs for manually forcing reconciliation
E2E + testing should cover known cases, but might require further testing.
=> Only perform machineconfig reconciliation during OpenShift upgrades

pkg/operator/controllers/etchosts/cluster_controller.go, pkg/operator/controllers/etchosts/cluster_controller_test.go, pkg/operator/controllers/etchosts/machineconfig_controller.go, pkg/operator/controllers/etchosts/machineconfig_controller_test.go, pkg/operator/flags.go, test/e2e/operator.go
Fixes ARO-10003
Adding a managed flag to the etchosts controller so that we can remove these machine configs in the future if needed.
- Run operator unit tests
- Run operator e2e tests
- Manually test using the operator testing procedure outlined in the [operator docs](https://github.com/Azure/ARO-RP/blob/master/docs/operators.md#how-to-run-a-custom-operator-image)
N/A
N/A
=> ARO-10003: Add managed flag to etchosts controller

docs/prepare-a-shared-rp-development-environment.md, hack/devtools/deploy-shared-env.sh, pkg/deploy/assets/shared-rp-secret-storage.json
Generalizes the deployment of the secret storage account used for shared rp development, allowing ARM template deployment to dev and e2e subscriptions.  Updates the documentation on how to deploy secret storage.
Deployed the ARM template verifying it works.
=> generalize secret storage deployment and update shared rp documentation

pkg/operator/controllers/etchosts/cluster_controller.go, pkg/operator/controllers/etchosts/cluster_controller_test.go, pkg/operator/controllers/etchosts/machineconfig_controller.go, pkg/operator/controllers/etchosts/machineconfig_controller_test.go, pkg/operator/flags.go, test/e2e/operator.go
Fixes ARO-9990
This updates the new etchosts controller to wait until the cluster is updating to reconcile the machine configs. This is needed to roll out the controller to the fleet without causing a fleet wide rebooting action.
- New tests added to the controllers
- Functional operator testing
N/A
- New tests added to the controllers
- Functional operator testing
=> ARO-9990: Update etchosts controller to use ForceReconcilation flag

go.mod, go.sum, vendor/github.com/docker/docker/api/swagger.yaml, vendor/github.com/docker/docker/api/types/backend/backend.go, vendor/github.com/docker/docker/api/types/types.go, vendor/github.com/docker/docker/client/client.go, vendor/github.com/docker/docker/client/container_create.go, vendor/github.com/docker/docker/client/container_exec.go, vendor/github.com/docker/docker/client/container_restart.go, vendor/github.com/docker/docker/client/container_stop.go, vendor/github.com/docker/docker/client/container_wait.go, vendor/github.com/docker/docker/client/errors.go, vendor/github.com/docker/docker/client/image_list.go, vendor/github.com/docker/docker/client/network_create.go, vendor/github.com/docker/docker/client/ping.go, vendor/github.com/docker/docker/client/request.go, vendor/github.com/docker/docker/client/service_create.go, vendor/github.com/docker/docker/client/service_update.go, vendor/github.com/docker/docker/client/volume_remove.go, vendor/github.com/docker/docker/pkg/streamformatter/streamformatter.go, vendor/modules.txt
Fixes ARO-9396
The current version of docker has a vulnerability.  It needs to be upgraded to its latest patch version.
E2E
N/A
With E2E passes, it should be ok.
=> [SFI] Fix CVE-2024-41110

.pipelines/ci.yml
This PR solves the issue of unnecessary pipeline triggers on the loki/pipeline-swarm branch by restricting the pipeline to trigger only on the master branch
Fixes: [ARO-9541](https://issues.redhat.com/browse/ARO-9541)
This PR removes the `loki/pipeline-swarm` branch from the pipeline configuration, ensuring that the pipeline only runs on the master branch. Additionally, it refactors the pipeline code for clarity and optimization. This helps streamline the CI process and eliminates unnecessary branch checks.
- Verified the pipeline triggers only on master branch as expected.
- Tested the changes to ensure the removal of loki/pipeline-swarm and that all steps function correctly.
N/A
N/A
=> Remove loki/pipeline-swarm branch from pipeline

pkg/cluster/install.go, pkg/cluster/install_test.go, pkg/hive/install.go, pkg/hive/manager.go, pkg/hive/resources.go, pkg/hive/resources_test.go, pkg/util/mocks/hive/hive.go
Fixes (https://issues.redhat.com/browse/ARO-4518)
Call generatePlatformWorkloadIdentitySecrets() for generating the Platform Identity Secret for a MIWI cluster.
Pass all the Secrets as a hive cluster secret and pass it the name of hive secret to  cluster deployment's `Spec.Provisioning.ManifestsSecretRef`
These secrets will be managed in ARO-Installer-Wrapper
Additional Handling of CredentialsSecretRef is required as it is only used for the Non-MIWI clusters, but since it is used to pass the cluster and subscription doc to wrapper it is still neded.
No
- For non-miwi clusters, tested the the cluster creation flow.
- Custom Manifests creation is tested successfully in combination with the installer-wrapper PR  https://github.com/openshift/installer-aro-wrapper/pull/166
=> ARO-4518 pass custom manifests(MIWI) to hive cluster deployment as secret

env.example
Follow up commit to #3681 when AZURE_PREFIX env var was suggested and fix due to #3593 changes
It complicates testing https://github.com/Azure/ARO-RP/pull/3815 when the USER is not set.
1. Allow using AZURE_PREFIX (when it is set) over USER.
2. Allow using an existing LOCATION over a set value of `westeurope`.
=> Fix env.example Default Values

docs/prepare-ci-environment.md, hack/devtools/deploy-ci-env.sh, pkg/deploy/assets/ci-development.json, pkg/deploy/generator/const.go, pkg/deploy/generator/generators.go, pkg/deploy/generator/resources_ci.go, pkg/deploy/generator/templates_ci.go
https://issues.redhat.com/browse/ARO-10133
Scaffolding for CI env buildouts as per our go generator/ARM deploy scripts. Mostly a stub for now as it only lays down a resource group and an ACR. Meant to be added to when we deploy more infra in the CI/E2E sub.
<!--
Local testing in RH Test sub. 
Included in PR
Not a production feature.
=> Scaffolding for CI environment setup in Azure

pkg/cluster/cluster.go, pkg/cluster/ipaddresses.go, pkg/cluster/ipaddresses_test.go
Fixes a part of https://issues.redhat.com/browse/ARO-4665 and https://issues.redhat.com/browse/ARO-7316
This is blocked until https://github.com/Azure/ARO-RP/pull/3638 is released.
This PR makes `ensureGateway` action use track2 SDK.
unittest for ensureGateway.
e2e
tech debt cleanup N/A
cluster installation test
=> update SDK to track2 in ensureGatewayCreate

pkg/cluster/cluster.go, pkg/cluster/delete.go, pkg/cluster/delete_test.go
Fixes https://issues.redhat.com/browse/ARO-4665
This PR updates the deprecated SDK to the new SDK track 2.
ci, e2e
tech debt cleanup, N/A
by checking if the cluster deletion succeeded.
=> SDK2: remove deprecated securityGroup client

pkg/api/util/subnet/subnet.go, pkg/monitor/azure/nsg/nsg.go, pkg/util/azureclient/azuresdk/armnetwork/subnets.go, pkg/util/azureclient/azuresdk/armnetwork/subnets_addons.go, pkg/util/azureclient/azuresdk/armnetwork/virtualnetworks.go, pkg/util/mocks/azureclient/azuresdk/armnetwork/armnetwork.go, test/e2e/adminapi_delete_managedresource.go, test/e2e/adminapi_resources.go, test/e2e/cluster.go, test/e2e/dns.go, test/e2e/operator.go, test/e2e/setup.go, test/e2e/update.go
Fixes https://issues.redhat.com/browse/ARO-4665
This PR removes deprecated network sdk from e2e.
e2e
N/A
Mostly the changes are nothing to do with prod.
Only monitor nsg has a small change because of the subnets client change.
We can validate the monitor nsg function by checking these metrics.
```
MetricPreconfiguredNSGEnabled  = "monitor.preconfigurednsg.enabled"
MetricFailedNSGMonitorCreation = "monitor.preconfigurednsg.failedmonitorcreation"
MetricInvalidDenyRule          = "monitor.preconfigurednsg.invaliddenyrule"
MetricSubnetAccessForbidden    = "monitor.preconfigurednsg.subnetaccessforbidden"
```
=> SDK2: Remove deprecated network sdk from e2e.

.pipelines/ci.yml, .pipelines/e2e.yml
Back when we had automatically triggering ADO pipelines (which we don't have because "require comment by contributor" is locked on at the org level) it was convenient to have the CI run and then the e2e trigger off a successful CI run to reduce pointless E2E runs. Now that we have to do the `/azp run` command (which triggers CI + E2E), we can end up with cases where the E2E will be manually triggered but also secondarily triggered from the successful CI run for the same commit (an example from this week):
This removes this e2e duplication, which fills up the E2E queue pointlessly and never ends up assigned to the GitHub check anyway.
I've also disabled overriding the YAML in the e2e.yml file in the UI, so it will use these values.
Is CI/E2E based
=> Remove pipeline chaining from our E2E pipeline

.pipelines/e2e.yml, Makefile, test/e2e/adminapi_redeployvm.go, test/e2e/dns.go, test/e2e/setup.go
This runs regression tests on CI runs (i.e. tags and master) but does not run them during PRs, which cuts 20-30 minutes from the runtime.
E2E changes, hopefully just works according to the docs
Comments are added in the relevant code
E2E tests, doesn't touch production
=> Don't run long-running regression tests on PRs

python/az/aro/azext_aro/_params.py, python/az/aro/azext_aro/_validators.py, python/az/aro/azext_aro/custom.py, python/az/aro/azext_aro/tests/latest/unit/test_validators.py
[ARO-9607](https://issues.redhat.com/browse/ARO-9607)
Add support for Cx to provide the value of the OpenShift version they want to upgrade to using UpgradeableTo field during update such that the backend can validate platform workload identities for the current and upgradeableTo minor versions and federate the upgradeableTo version identities.
Not yet
Preview extension-only change. We will perform comprehensive testing before releasing this extension to users.
=> CLI Phase 1 - add UpgradeableTo field to update functionality

cmd/aro/mirror.go
Fixes no Jira
- Updates our OCP artifact mirroring to only mirror OCP releases from 4.12 onwards
No
Mirroring pipeline above still works
=> Bump baseline OCP version used for mirroring artifacts to 4.12

pkg/hive/install.go, pkg/hive/resources.go, pkg/hive/resources_test.go
Fixes [ARO-4374](https://issues.redhat.com/browse/ARO-4374)
No
- Functionality will be tested with overall MIWI efforts
=> MIWI - Provide boundServiceAccountSigningKey secret to Hive Install

python/az/aro/azext_aro/_validators.py, python/az/aro/azext_aro/tests/latest/unit/test_validators.py
[ARO-6451](https://issues.redhat.com/browse/ARO-9607)
This is a small PR to disallow refresh_cluster_credentials with platform_workload_identites
Unit tests for validating the --platform-workload-identities with --refresh-cluster-credentials argument have been added.
Not yet
Preview extension-only change. We will perform comprehensive testing before releasing this extension to users.
=> disallow refresh_cluster_credentials with platowrm_workload_identities

hack/hive/hive-dev-install.sh
hack/util.sh: line 14: would: unbound variable occurs in it's current state.
Fixes [ARO-11090](https://issues.redhat.com/browse/ARO-11090)
I have removed the erroneous `-n` causing the log message to be read as a variable.
`-n` is being passed as a the first argument to [log](https://github.com/Azure/ARO-RP/blob/e20e96f96473091a63585104e43ce5d79373038e/hack/util.sh#L11-L15), which then causes the `msg` string to be used for argument two, [stack_level](https://github.com/Azure/ARO-RP/blob/e20e96f96473091a63585104e43ce5d79373038e/hack/util.sh#L13). Since argument two expects a variable, it then fails with an unbound variable error.
Example of the error in it's current state.
```bash
./hack/hive/hive-dev-install.sh 
main: enter hive installation
main: hive is already installed in namespace …
```
=> Fix bug in hive-dev-install.sh

.pipelines/ci.yml, .pipelines/templates/template-acr-push.yml, Dockerfile.vpn, Dockerfile.vpn.dockerignore, Makefile, docker-compose.yml, env.example
Fixes : [ARO-9501](https://issues.redhat.com/browse/ARO-9501)
This PR migrates the `VPN`, `RP,` and `Portal services` to Docker Compose, simplifying service management by containerizing them. The `docker-compose.yml` now orchestrates all three services. This migration makes the environment setup and service orchestration more efficient and maintainable, improving local development and CI/CD workflows.
Key Updates:
Other Important Highlights:
- Updated Azure DevOps pipeline to ensure correct variable definitions (REGISTRY, VERSION, LOCAL_ARO_RP_IMAGE, etc.).
- Refactored the template to handle Docker authentication and image tagging/pushing with the correct use of VERSION.
- Updated the Docker Compose file to consistently use pipeline variables for image names, tags, and build arguments.
- …
=> Migrate VPN and rp service to Docker Compose

python/az/aro/azext_aro/tests/latest/custom_preparers.py, python/az/aro/azext_aro/tests/latest/integration/test_aro_scenario.py
Fixes https://issues.redhat.com/browse/ARO-8293
This PR implements a scenario-based integration test for all subcommands.
This will increase the test coverage in ARO-RP repo, and will reduce the test execution time in upstream because it doesn't create a cluster for each subcommand.
I'm going to open a PR in upstream after this PR is merged.
Run `azdev test`.
https://github.com/Azure/ARO-RP/blob/master/docs/az-aro-python-development.md#tests
na
not production feature.
=> Update CLI integration test

hack/devtools/local_dev_env.sh
Fixes no Jira
- Add secretLocation for all identities (required to put down CCO secrets in-cluster)
- Update MachineAPI to use correct service account (machine-api-controllers)
- Prefix all service account identifiers with 'system:serviceaccount:'
No
Non-production change. This PR will perform the equivalent changes to production configuration: https://msazure.visualstudio.com/AzureRedHatOpenShift/_git/RP-Config/pullrequest/11037151
=> Update localdev platformworkloadidentityrolesets

pkg/cluster/cluster.go
Fixes N/A
This PR fixes InvalidAuthenticationTokenTenant in Prod.
The old client used `_env.SubscriptionID()` (see L262 and L264 on the left pane in https://github.com/Azure/ARO-RP/pull/3616/files#diff-f4933755bd63c9e160a2068e8ccb4048e8df1b43f7f4544dcbc7ae2650a07478), but the new client uses `r.SubscriptionID`, which caused the subscription mismatch and caused the InvalidAuthenticationTokenTenant error.
This PR fixes the subscription for `armRPPrivateLinkServices` and `armFPPrivateEndpoints`.
e2e, e2e in prod
N/A
Cluster creation in prod
=> Fix subscription ID of armRPPrivateLinkServices client

pkg/cluster/condition.go, pkg/cluster/condition_test.go
Provides more data for ARO-4247
It is hard to troubleshoot worker node creation failures for new cluster installation. We wait for worker nodes, but sometimes they never show up because there was an Azure failure creating the VM. CAPI logs for machine creation happen too early and don't make it to Kusto.
Deploy test clusters and make sure we get the logs desired. Centraluseuap would be a good place to start if the error creating availability sets reproduces.
Happy-path logs look like the following:
```
2024-10-07T17:48:32.6932154Z time="2024-10-07T17:48:32Z" level=info msg="running step [Condition pkg/cluster.(*manager).minimumWorkerNodesReady, timeout 30m0s]" func="steps.Run()" file="pkg/util/steps/runner.go:56"
2024-10-07T17:48:32.7492655Z time="2024-10-07T17:48:32Z" level=info …
```
=> Check machine status and log details if it is not running

pkg/cluster/gatherlogs.go, pkg/operator/deploy/deploy.go
Fixes [ARO-9892](https://issues.redhat.com/browse/ARO-9892)
While troubleshooting aro pod startup failures in https://github.com/Azure/ARO-RP/pull/3755, not enough logging was available to diagnose the problem. An earlier version of this PR was used in 
Revert https://github.com/Azure/ARO-RP/commit/29f922900d79bf73b711e68ff53a0ca12cdb348e in order to cause aro pod startup failure. Gather logs from [failed e2e run](https://msazure.visualstudio.com/AzureRedHatOpenShift/_build/results?buildId=105322883&view=logs&j=10f66467-59e5-53bc-0c8a-42cc89770de4&t=3db7f981-4ce5-5d1c-cd5a-be4e2b8e7f2a), trimmed for clarity:
```
2024-10-09T17:31:44.4956882Z time="2024-10-09T17:31:44Z" level=info msg="running step [Condition pkg/cluster.(*manager).aroDeploymentReady, timeout 20m0s]" func="steps.Run()" …
```
=>  Log operator deployment status and gather pod logs

Makefile
No Jira; addresses a small issue I encountered in my own work.
This ensures that https://github.com/uber-go/mock/issues/185 is always fixed automatically for MacOS users.
I'm not sure why, but I found in the course of my work that I had to run the `codesign` command again even though I figured it was a one time fix. It must be related to the fact that `make install-tools` is rerun each time you `make generate`. So I figured I'd codify the fix.
Only relevant for MacOS users. Run `make generate` and make sure you don't run into https://github.com/uber-go/mock/issues/185.
N/A
N/A
=> Quickfix - codify solution to another `make generate` issue on MacOS

pkg/cluster/delete.go, pkg/cluster/deploybaseresources.go, pkg/cluster/deploybaseresources_test.go, pkg/env/env.go, pkg/util/oidcbuilder/oidcbuilder.go
[ARO-10948](https://issues.redhat.com/browse/ARO-10948)
Currently, an OIDC issuer URL looks like: `https://eastus.oic.aro.azure-test.net/oic-e97c0f2c-38b6-4741-afb5-cbfc20902d80`
Currently, the convention is `<Oic>-<document ID>`
Instead, it should follow the below convention:
`https://<region>.oic.aro.azure.com/<tenant-id>/<guid>` 
Passed all unit tests
not yet
=> Correct convention for OIDC issuer urls

pkg/cluster/deploybaseresources_test.go
Fixes N/A
I merged #3903, which removes a variable, and the variable is used in the recently merged #3847. 
Because the first PR was tested before the second PR was merged, I couldn't notice the change.
Currently we can't build unit test because of it.
https://github.com/Azure/ARO-RP/actions/runs/11400840349/job/31722536610?pr=3876
```
Running [/home/runner/golangci-lint-1.59.1-linux-amd64/golangci-lint run  -v --timeout 15m] in [/home/runner/work/ARO-RP/ARO-RP] ...
Error: : # github.com/Azure/ARO-RP/pkg/cluster [github.com/Azure/ARO-RP/pkg/cluster.test]
Error: pkg/cluster/deploybaseresources_test.go:1682:98: undefined: env.OIDCBlobDirectoryPrefix (typecheck)
```
This PR fixes the part to align with the change in #3903.
ci
N/A
This is a fix in unit tests.
=> Fix lint/test build error

hack/devtools/local_dev_env.sh
Fixes no JIRA
Currently our hack script creates a list of platform identities and assigns roles. This PR extends that functionality to also create the cluster identity so that the developer doesn't need to create this identity manually.
Ran the script locally.
=> Create the cluster identity in hack/devtools/local_dev_env.sh

test/e2e/setup.go
Fixes ARO-9501
During my pairing with Shubhada we discovered if the Selenium hostname varible is unset e2e will panic in its setup.
Run e2e
N/A
N/A
=> ARO-9501: Fix E2E panic when ARO_SELENIUM_HOSTNAME is empty

hack/devtools/local_dev_env.sh, hack/devtools/msi.sh
Fixes no Jira
- Uses the explicit `CLUSTER_RESOURCEGROUP` env var for MIWI resource creation (platform workload identities) in `./hack/local_dev_env.sh`. See `env.example` for where this is set by default (to `${USER}-v4-${LOCATION}`). 
- Local dev steps for MIWI work and make sense
- Local dev steps for MIWI
Non-production change for a feature not yet in production anyways.
=> Avoid conflicts between RP RESOURCEGROUP and the cluster's resource group in MIWI localdev cluster creation

pkg/cluster/delete.go
Fixes no JIRA
Our federated credential built-in role doesn't yet have permissions to clean up federated credentials, so currently wi/mi installs are failing to clean them up. For the time being, we need to tolerate failures to clean up federated credentials rather than fail the whole delete.
Tested this locally on deletion of a wi/mi cluster. Deletion succeeded.
=> Tolerate failures to delete federated credentials during deletion

pkg/util/azureclient/roundtripper.go, pkg/util/azureclient/roundtripper_test.go
While building a cluster installation dashboard, I tried to correlate cluster installs with the corresponding ARM request/response logs. I could not, and it turns out it's because we end up logging the wrong correlation ID.
When we get a request to create a cluster, openshiftcluster_putorpatch.go loads ARM's correlation_id into a context variable using `GetCorrelationDataFromCtx()`
https://github.com/Azure/ARO-RP/blob/3d13bc2c317075025d9bfad956663d66f7cb44cd/pkg/frontend/openshiftcluster_putorpatch.go#L56 
Later on, when `ValidateNewCluster()` checks SKU, Quota and provider registration
https://github.com/Azure/ARO-RP/blob/3d13bc2c317075025d9bfad956663d66f7cb44cd/pkg/frontend/openshiftcluster_putorpatch.go#L369-L375
it makes outbound calls to ARM. Roundtripper clobbers the caller's …
=> Set correlation ID on outbound Azure requests

pkg/cluster/delete.go
Fixes no Jira
Replaces the manual identification of Azure SDK Response Errors for 404/Not Found when deleting federated identity credentials, with the helper function already defined for this purpose. 
No
Not yet in production
=> Follow-up for #3913

portal/v2/package-lock.json
Fixes https://github.com/advisories/GHSA-c7qv-q95q-8v27
Bumps http-proxy-middleware to 2.07
No
Should not impact production, this dependency is only used for local portal dev.
=> Bump http-proxy-middleware to 2.0.7

pkg/deploy/assets/rp-development.json, pkg/deploy/assets/rp-production-parameters.json, pkg/deploy/assets/rp-production.json, pkg/deploy/config.go, pkg/deploy/config_test.go, pkg/deploy/deploy_rp.go, pkg/deploy/generator/resources_rp.go, pkg/deploy/generator/templates_rp.go
While updating OpenShift version in CosmosDB, the pipeline does not authorise to access CosmosDB. This PR will create role assignments when RP will be deployed so that when a OpenShift version is added/removed it has access to CosmosDB. 
We will need to edit the rp-config as well.
Fixes - ARO-9920
Will be tested in INT env
=> Adding role assignment for the devops managed identity

pkg/cluster/deploybaseresources.go, pkg/cluster/deploybaseresources_additional.go, pkg/cluster/storageaccounts.go, pkg/util/storage/manager_test.go
Fixes https://issues.redhat.com/browse/ARO-9712 in combination with installer-wrapper PR:- https://github.com/openshift/installer-aro-wrapper/pull/186
For MIWI:
- The storage accounts(Cluster and ImageRegistry) should have the shared access keys disabled
For MIWI + Cluster Storage Account:
- Set SAS policy such that all the SAS tokens on the Storage Account expires in 1hr.
[x] CI
[x] e2e
[x] Test the flow of cluster install such that the Shared Access Keys are disabled.
[x] Test the flow of cluster install such that the Cluster Service Principal Cluster are created correctly.
No
- For non-MIWI cluster there's no functionality change
- For MIWI cluster the flow has been tested by reversing the usesWorkloadIdentity function. The whole flow can be tested once the feature is tested.
=> disable storage account shared key access for miwi and use sas policy for cluster storage account

pkg/operator/deploy/deploy.go, pkg/operator/deploy/deploy_test.go, pkg/operator/deploy/staticresources/master/deployment.yaml.tmpl
Fixes https://issues.redhat.com/browse/ARO-11546
ARO-Operator fails because of AZURE_FEDERATED_TOKEN_FILE(`/var/run/secrets/openshift/serviceaccount`) being a directory and not a file.
Updated AZURE_FEDERATED_TOKEN_FILE env value to have `/token` at the end of above path.
[x] Passes unit tests
[x] MIWI cluster get created with ARO-Operator not facing Authorization issues.
No
Tested the functionality by creating a MIWI cluster. CSP Clusters are not impacted.
=> ARO-11546 update AZURE_FEDERATED_TOKEN_FILE value to have /token at end

pkg/api/admin/openshiftcluster.go, pkg/api/admin/operatorflags.go, pkg/api/admin/operatorflags_test.go, pkg/frontend/openshiftcluster_putorpatch.go, pkg/frontend/openshiftcluster_putorpatch_test.go
Fixes https://issues.redhat.com/browse/ARO-1885
Allows us to 'reset' feature flags to their defaults by providing ones that we wish to layer on top of said defaults.
Broken out of #3571 because I needed it for some tests. Based off work by @SrinivasAtmakuri in another PR.
Unit tests
SOPs for operator flag working might be needed? 
Unit tests, plus it won't do anything in production unless we make it do so
=> [ARO-1885] Implement OperatorFlagsMergeStrategy

pkg/cluster/failurediagnostics/virtualmachines.go, pkg/cluster/failurediagnostics/virtualmachines_test.go, pkg/cluster/gatherlogs.go, pkg/cluster/install.go, pkg/cluster/install_test.go
Fixes ARO-11578
Reduces the logs on install failure to the last 50kB to prevent spamming the logs, and removes duplicates. Doesn't log serial console logs on Updates/AdminUpdates, only Installs.
Unit tests are added
N/A
Unit tests should cover it
=> [ARO-11578] Don't log serial console logs on adminUpdate/Update failures, and cap the amount we log

pkg/api/platformworkloadidentityrolesetdocument_example.go, pkg/cluster/workloadidentityresources_test.go, pkg/operator/const.go
Fixes MIWI Install failures
Replaces the name of ServiceOperator by aro-operator, missed in https://github.com/Azure/ARO-RP/pull/3916
Test creation of MIWI cluster
None
It will work. :-)
=> Update manifests creation to skip aro-operator

hack/devtools/local_dev_env.sh, hack/devtools/msi.sh
No Jira
Fixes a couple issues we noticed during wi/mi hackdays:
- Shell scripts exit the terminal on a non-zero exit code
- When running local_dev_env.sh, the env var PLATFORM_WORKLOAD_IDENTITY_ROLE_SETS gets incorrect double quotes rather than single quotes, making it impossible to source
Ran them locally.
=> Local dev script fix ups

pkg/cluster/install.go, pkg/cluster/storageclass.go, pkg/cluster/storageclass_test.go
https://issues.redhat.com/browse/ARO-9716
Since shared access key is disabled for Cluster & Image Registry Storage Account in case of Workload Identity Cluster, we cannot support default File CSI Storage class. Since there's a chance the file csi driver can use those storage accounts.
ADR:- https://docs.google.com/document/d/150MJvfTSgvY8LWp_iRh9-En1jIxvMPf3NlKTzfn36Bw/edit
[x] Unit Tests
[x] Test by MIWI Cluster Creation
[x] CI
[x] e2e
No.
Tested by creating MIWI cluster locally
=> ARO-9716 during miwi cluster install remove azure file csi storage class

pkg/cluster/install.go
Supports self-service rotation of kubeconfigs should the user admin kubeconfig expire.  
`Update` path now rotates kubeconfigs.  
1. create cluster
2. fetch kubeconfig, check expiration
3. call Update() code path
4. fetch kubeconfig, see if expiration is newer
=> Support rotation of kubeconfigs on Update for cx self-service

pkg/api/admin/openshiftcluster.go, pkg/api/admin/openshiftcluster_convert.go, pkg/frontend/openshiftcluster_putorpatch_test.go
Fixes no Jira
Ensures that the status of the cluster document's `networkProfile.preconfiguredNSG` property is included on Admin API representations of the document. 
No
Testing done above
=> Fix AdminAPI representation of PreconfiguredNSG status

pkg/deploy/deploy.go, pkg/deploy/deploy_rp.go
No Jira - fixes an issue I found while doing a test deployment to canary
Deployment attempts were failing because the devops MSI isn't in the sub that the user assigned identities client was scoped to. This PR adds an additional client to the deployer that's properly scoped to get the devops MSI.
Deploy to canary.
N/A
Will be testing in canary soon.
=> Deploy fix - GET devops MSI using properly scoped Azure client

pkg/api/v20240812preview/openshiftcluster_validatestatic.go, pkg/api/v20240812preview/openshiftcluster_validatestatic_test.go
Fixes ARO-11689
This adds a step to static validation that checks to see if operator identities use the same resource ID as any other operator identities and causes the cluster installation to fail if so. Each operator should have its own identity.
Unit test added
No, this is already documented as a requirement
Unit tests for other static validation cases have already been added and accepted, this just expands on what's already there
=> disallow duplicate operator identity resource IDs

hack/devtools/local_dev_env.sh
n/a
A couple az commands in the `create_miwi_env_file` function in hack/devtools/local_dev_env.sh script didn't specify to use json output, so changing the default output type (eg: to table) breaks things
Manually run
No, this is a bugfix of a dev script
It will not go to production, it's a dev script
=> specify json output for a couple az commands that were missing it

pkg/api/v20240812preview/openshiftcluster_validatestatic.go, pkg/api/v20240812preview/openshiftcluster_validatestatic_test.go
Fixes a test failing on #3571 
Depending on map key ordering, this test can fail because it will log the capitalised version or vice versa. Now it will return the lowercased version always in the error, which is the same as other parts of the code.
Is a unit test
N/A
N/A
=> Fix test flake in preview API for MIWI

docs/deploy-development-rp.md, docs/prepare-your-dev-environment.md
Follow up to split between `runlocal-rp` and `run-rp` - these docs outline how to use the new feature of containerized builds and RP execution
- adds documentation on build/run dependencies of containerized build
- adds instructions on how to use 'make run-rp'
Docs
N/A - docs
Yes, this PR
N/A - docs
=> Add run-rp docs

pkg/deploy/assets/rp-development.json, pkg/deploy/assets/rp-production.json, pkg/deploy/generator/resources_rp.go
Fixes [ARO-5514](https://issues.redhat.com/browse/ARO-5514)
This PR will disable local authentication on CosmosDB to force use of managed identities for the same implemented under  [ARO-7195](https://issues.redhat.com/browse/ARO-7195).
NA
NA
NA
=> Disable cosmosdb local auth

docker-compose.yml
No Jira
Adds a missing env var needed for MIWI cluster installation to the RP startup command in `docker-compose.yml`.
Tested locally; RP successfully accepts a MIWI cluster create request.
N/A
N/A
=> Add missing env var to containerized RP startup command

hack/db/db.go, pkg/database/database.go
Follow-up to #3561
If we're disabling local auth, we can no longer use master key authorizers.  There's still generated code from go-cosmosdb to include master key authorizers, but since it's not being used anymore it should be fine.  
Ran `go run ./hack/db <resource-id>` to confirm it still worked.
=> remove master key authorizer in favor of local auth

pkg/frontend/openshiftcluster_putorpatch.go, pkg/frontend/openshiftcluster_putorpatch_test.go, pkg/frontend/validate.go
https://issues.redhat.com/browse/ARO-12022
We didn't notice this until we tried to create more than one MIWI cluster inside the same Cosmos DB container, but the service principal client ID was part of our Cosmos DB unique key policy. This PR updates our code to use the cluster MSI resource ID (lowercased) for MIWI clusters instead.
Tested locally by creating two cluster docs in my dev Cosmos DB database and manually checking the `clientIdKey` attributes. Also added a unit test case in this PR.
The Cosmos DB key attribute is keeping the name `clientIdKey`, which could be a little confusing considering it's not a client ID in the case of MIWI clusters, but I put a detailed comment in the code to explain this quirk.
Will eventually test in canary.
=> MIWI Cosmos DB key uniqueness fix

pkg/api/v20240812preview/openshiftcluster_convert.go, pkg/cluster/install.go, pkg/cluster/workloadidentityresources.go, pkg/cluster/workloadidentityresources_test.go, pkg/frontend/openshiftcluster_putorpatch_test.go, pkg/operator/deploy/deploy.go, python/az/aro/azext_aro/custom.py
Fixes [ARO-4371](https://issues.redhat.com/browse/ARO-4371)
Adds required behavior to the RP for performing Updates (e.g. `az aro update`) on workload identity clusters:
- This was already implemented in #3619 
- This was already implemented in #3653
- This was already implemented in #3575
There were also some ad-hoc fixes performed in order to get this functionality working:
- This was done in order to not delete fields present on the resource that do not exist in the RP's vendored struct definition (we currently vendor in the 4.12 specification which is missing fields present in 4.14+). 
Note that fully handling federated credentials (validating existing, federating new required credentials) will be handled in a separate, follow-up effort. See …
=> Support Update requirements for Workload Identity clusters

pkg/cluster/delete.go, pkg/cluster/serviceprincipal.go
[ARO-11687](https://issues.redhat.com/browse/ARO-11687)
Passed all unit tests
N/A
=> confirm UsesWorkloadIdentity shared utility function is used everywhere in ARO-RP

pkg/api/admin/openshiftcluster_convert.go, pkg/api/v20240812preview/openshiftcluster_convert.go, pkg/frontend/openshiftcluster_putorpatch_test.go
No Jira
Fixes two issues with the API converters:
1. Ensures all cluster MSI / `Identity` fields are included in conversions
2. Ensures that all platform workload identities are included when converting from internal -> admin
I tested both the admin and preview APIs with my local dev RP. I'll also be testing in canary.
N/A
Will be tested in canary.
=> MIWI API converter fixes

pkg/operator/deploy/staticresources/credentialsrequest.yaml
Partially fixes [ARO-12070](https://issues.redhat.com/browse/ARO-12070)
Resets ARO Operator CredentialsRequest to the base role definition we have now for MiWi. Prepares it for any future permissions we need to add.
MiWi clusters are already using this definition
n/a
MiWi clusters are already using this definition
=> Realign CredentialsRequest to match current ARO operator role definition

pkg/backend/openshiftcluster.go
nil was mistakenly being passed to emitMetrics, causing resultType to always fail collection due to the nil backendError provided.
Fixes [ARO-10816](https://issues.redhat.com/browse/ARO-10816)
The backend error was not being passed to `emitMetrics`, `nil` was being provided instead.
This caused the resultType to always fail to collect, given that the error was always `nil`.
Example of this:
```bash
WARN[0000] failed to collect metric: resulttype          resource_group=resourcegroup resource_id=/subscriptions/00000000-0000-0000-0000-000000000000/resourcegroups/resourcegroup/providers/microsoft.redhatopenshift/openshiftclusters/resourcename resource_name=resourcename subscription_id=00000000-0000-0000-0000-000000000000
INFO[0000] backend.openshiftcluster.AdminUpdating: resulttype = empty …
```
=> Pass backendErr to emitMetrics

pkg/util/heartbeat/heartbeat.go
Fixes no Jira
- Emits the RP version as a dimension on the heartbeat metric. This can be used in downstream operational improvements, e.g. dashboards to answer "Do we have enough running instances of the desired version?", "What version of the RP are we running in a given region?" etc questions. 
The change is small and straightforward (add a static string dimension to the metric emission), and I do not see any easy way to provide meaningful unit tests or E2E tests on this change. Open to suggestions though. 
No
We'll have to deploy it and see if it works with our metrics ingestion in production regions.
=> Emit version as a dimension on heartbeat metrics

pkg/cluster/install.go, pkg/cluster/validate.go, pkg/util/azureclient/azuresdk/armmsi/user_assigned_identities.go, pkg/util/mocks/azureclient/azuresdk/armmsi/user_assigned_identities.go, pkg/util/mocks/dynamic/dynamic.go, pkg/validate/dynamic/diskencryptionset_test.go, pkg/validate/dynamic/dynamic.go, pkg/validate/dynamic/dynamic_test.go, pkg/validate/dynamic/platformworkloadidentityprofile.go, pkg/validate/dynamic/platformworkloadidentityprofile_test.go, pkg/validate/openshiftcluster_validatedynamic.go
Fixes https://issues.redhat.com/browse/ARO-12034
After https://github.com/Azure/ARO-RP/pull/3920 got merged, the MIWI cluster dynamic validation fails as the access token is mandatory to use checkAccessV2.
But since Platform Workload Identities are used via Federated Credentials or OIDC way, the access token for them can only be fetched after KubeAPI Server is up. So, for the fix, when validating Platform Workload Identity, we won't be using the access token and also won't be using the Group Expansion.
Related Thread:- https://redhat-external.slack.com/archives/C03F6AA3HDH/p1730225417576639
[x] Unit Test Cases
[x] Local Cluster Creation
[x] CI
[x] E2E
Update the Customer Facing documentation for MIWI, such that the customer should only perform the role assignment directly on the platform …
=> ARO-12034 Fix CheckAccessV2 usage for MIWI dynamic validation

pkg/cluster/deploybaseresources_additional.go, pkg/cluster/deploybaseresources_test.go, pkg/cluster/loadbalancerprofile.go, pkg/cluster/loadbalancerprofile_test.go, pkg/util/arm/types.go
Fixes https://issues.redhat.com/browse/ARO-4665
This PR replaces the old SDK in reconcileLoadBalancerProfile.
This includes the change in deployBaseResources.
The changes are related to cluster creation, so e2e and CI can verify the changes. 
N/A
By creating a cluster.
=> SDK2: Replace old SDK in reconcile load balancer profile

pkg/operator/deploy/deploy.go, pkg/operator/deploy/deploy_test.go
Fixes no Jira
Skips setting the upgradeableTo annotation (for MIWI clusters) when no value is specified in the cluster document.
This avoids a nil pointer dereference. 
No
MIWI is not yet in production
=> Do not try to set UpgradeableTo annotation in-cluster if it is empty

pkg/api/admin/openshiftcluster_convert.go, pkg/api/v20240812preview/openshiftcluster_convert.go
Fixes no Jira
Ensures our ExternalNoReadOnly converters for the v20240812preview and admin APIs set the managedServiceIdentity's PrincipalID and TenantIDs to `''`. This allows us to correctly perform PATCH operations that do not modify this field (e.g. an empty JSON object payload). 
No
v20240812preview API is not yet available in production, MIWI fields/functionality are not enabled in production
=> Ensure MSI readonly fields are set to '' in ExternalNoReadOnly converters

pkg/util/azureclient/azuresdk/armcontainerservice/managedcluster_addons.go, pkg/util/liveconfig/hive.go, pkg/util/liveconfig/hive_test.go
No Jira
This PR reintroduces the `serverFqdn` parameter used to get AKS admin credentials that we removed in #3906. I noticed it needed to be added back in when I found that my local dev RP was trying to connect to AKS through a private endpoint.
Ran my local dev RP and confirmed that it can connect to AKS again with this fix.
N/A
Canary E2E during next release.
=> Fix AKS connectivity 

pkg/cluster/clustermsi.go, pkg/cluster/install.go
https://issues.redhat.com/browse/ARO-12501
During cluster updates, the tenant ID gets overwritten by the API conversions done during PUT/PATCH requests and needs to be repopulated before we start trying to do anything else related to the MSI. This PR adds a step to repopulate the tenant ID using the subscription doc, fixing an error that we found was occurring during `az aro update` operations.
1. Ran an "empty" `az aro update` against local dev RP for a MIWI cluster and observed that the RP fails to populate the MSI client/principal IDs because the missing tenant ID prevents use of the MSI dataplane
2. Made code changes on this branch
3. Ran another `az aro update` and observed that the update process was fixed
4. Ran one more `az aro update` to ensure the fixed update process works …
=> Repopulate MSI tenant ID during update

pkg/cluster/cluster.go
Fixes https://issues.redhat.com/browse/ARO-4665
This PR removes unused old publicIPAddresses client.
Now all publicIPAddresses clients used in cluster creation are SDK2.
CI
just cleanup, N/A
cluster creation
=> SDK2: remove unused publicIPAddresses client

pkg/cluster/deploybaseresources_additional.go, pkg/cluster/deploybaseresources_additional_test.go
https://issues.redhat.com/browse/ARO-13080
From the Jira:
>The deny assignment code currently adds the platform identities to the excluded principals list by looping over them, with each iteration grabbing a pointer to the loop variable containing the identity struct and adding the pointer to the excluded principals list. The same pointer is being added each time, and therefore the excluded principals list ends up containing N pointers to the platform identity read in in the last loop iteration. This is a common Golang bug and a relatively easy fix.
- Augmented unit tests
- Will eventually be tested in canary
N/A
MIWI feature testing in higher environments
=> MIWI bug fix - deny assignment

pkg/cluster/deploybaseresources_additional.go, pkg/cluster/deploybaseresources_additional_test.go
https://issues.redhat.com/browse/ARO-13246
This PR adds the FPSP to the MIWI deny assignment's `ExcludePrincipals`. See the Jira for more context on why we're doing this.
Augmented unit tests; will soon test in canary
N/A
MIWI feature testing
=> Add FPSP to MIWI deny assignment ExcludePrincipals

.pipelines/ci.yml
This PR addresses the issue where the pipeline does not fail correctly when the E2E tests fail. The exit code from the docker compose up e2e command was not being captured and handled properly, resulting in the pipeline incorrectly reporting success even when the tests failed.
=> Fix E2E pipeline failure handling

python/az/aro/azext_aro/_params.py, python/az/aro/azext_aro/_validators.py, python/az/aro/azext_aro/tests/latest/unit/test_validators.py
Fixes N/A
When I try to create a cluster with `--client-id` and `--client-secret`, it failed with the error `'Namespace' object has no attribute 'upgradeable_to'`.
`--upgradeable-to` doesn't exist for `create` subcommand, but `--client-id` and `--client-secret` options have a validation to validate `namespace.upgradeable_to`.
So the validator tries to access `namespace.upgradeable_to` and it failed.
This PR makes the validator aware of if it is `create` or `update`, and don't validate `upgradeable_to` when it is `create`. 
This is the error I got (with `--debug`)
```
❯ az aro create \
--resource-group $MY_RESOURCEGROUP \
--name $MY_CLUSTER \
--vnet aro-vnet \
--master-subnet master-subnet \
--worker-subnet worker-subnet \
--pull-secret @/Users/atokubi/Downloads/pull-secret.txt \
--version …
```
=> Fix 'Namespace' object has no attribute 'upgradeable_to'

pkg/hive/resources.go, test/e2e/hive.go
Fixes no Jira
With the merge of #3978, the Hive tests now function correctly in CI (tested manually, see https://msazure.visualstudio.com/AzureRedHatOpenShift/_build/results?buildId=109487069&view=logs&j=db690490-d817-5143-da35-29bc37ac10d9&t=7ab7f38e-816f-5a76-939c-0ca727e8db32 for an example).
This PR re-enables these tests. Note that they are still skipped when not in the development context, e.g. during release E2E.
In this PR, we also update the "adoptedClusterDeployment" definition, which happens to also be put down in the Hive cluster when an ARO cluster is Updated or AdminUpdated, to set  various additional properties:
- Hive labels (`cluster-platform` and `cluster-region`)
- `Spec.Platform.Azure.BaseDomainResourceGroupName`
- `Spec.ControlPlaneConfig.APIURLOverride`
These …
=> Enable Hive E2E tests in CI

pkg/hive/install.go, pkg/hive/resources.go, test/e2e/hive.go
Fixes [ARO-11607](https://issues.redhat.com/browse/ARO-11607)
Adds the `hive.openshift.io/infra-disabled` annotation to our Hive ClusterDeployments (for both new installs as well as adopted clusters), set to `true`. This is required in order to disable the hibernation controller, which does not currently work for ARO MIWI clusters. 
> [!NOTE]
> This PR currently disables the hibernation controller for all cluster installations (CSP and MIWI) - we do not use this functionality in ARO's implementation of Hive today. 
See corresponding change in Hive to add this annotation for more details: https://github.com/openshift/hive/pull/2501 
No
E2E tests outlined above
=> Add disable-infra annotation to hive clusterdeployments

pkg/cluster/removebootstrap.go
Fixes https://issues.redhat.com/browse/ARO-12543
Removing calls to mgmt/network in favor to azuresdk/armnetwork
This is being called during cluster install so covered by E2E.
No need for documentation update specific to this sub task as technical migration.
Technical migration, standard monitoring will be use to monitor it works as expected.
=> Replace usage of mgmt/network use by azuresdk/armnetwork

pkg/operator/controllers/pullsecret/pullsecret_controller.go, pkg/operator/controllers/pullsecret/pullsecret_controller_test.go
Fixes https://issues.redhat.com/browse/ARO-3258
It is needed to propagate errors of ARO PullSecret controller to ARO operator in order to see those errors at the Operator level and to see all the controller errors in one place.
[x] Unit Test Cases
[x] Local Cluster Creation
[] CI
[] E2E
Yes, https://github.com/Azure/ARO-RP/blob/master/pkg/operator/controllers/pullsecret/pullsecret_controller_test.go
Running all unit tests locally and verifying tests output
N/A
=> ARO-3258: propagate errors of ARO PullSecret controller to ARO operator

hack/e2e/run-rp-and-e2e.sh
No Jira
There's recently been a large buildup of orphaned E2E resource groups in our test tenant. I looked at recent E2E runs and found that the `AfterSuite` is passing without deleting the resource groups and traced it to this environment variable that was probably set somewhere else prior to our recent move to docker compose.
Run E2E and validate that the resource group gets cleaned up by the `AfterSuite`
N/A
N/A
=> Ensure E2E clusters are deleted

pkg/cluster/install.go
https://issues.redhat.com/browse/ARO-13782
We found that E2E has been failing recently because the Hive unreachable controller seems to have started taking longer than the timeout of 5 minutes to reconcile the `Unreachable` condition on the `ClusterDeployment`, which was one of the things we were checking before considering a Hive install successful.
The outcome of our conversation with Eric from the Hive team was that we don't necessarily need to check these status conditions; if the OpenShift installer is done, which the previous step validates, then that's good enough. So rather than increasing our timeout or continuing to try to figure out why the timeout needed to be increased, we can simply stop some unnecessary checks.
PR E2E
N/A
Prod E2E
=> Quit checking ClusterDeployment status conditions during cluster installation

pkg/validate/openshiftcluster_validatedynamic.go
Fixes Azure Client Action failure due to missing FP Creds during MIWI Dynamic Valdiations.
This was caused due to changes done in https://github.com/Azure/ARO-RP/pull/3889
Pass a fp Credential while initializing dynamic validator for the managed identities.
This allows an authorizer header to be passed for calls to ARM.
- Tested Local Cluster Creation
- No test case to test the authorization failures
No
- MIWI not available in prod currently, need to be tested in Canary.
=> pass fp cred to the dynamic validator for miwi flow

pkg/util/namespace/namespace.go, pkg/util/namespace/namespace_test.go
Fixes [ARO-13390](https://issues.redhat.com/browse/ARO-13390)
Adds the `openshift-ovn-kubernetes` namespace to the list of OpenShift namespaces permitted for SREs to access using admin API endpoints. 
No
We will have to see if it works in production or not, we cannot replicate the full SRE admin environment locally without extreme effort.
=> Add openshift-ovn-kubernetes NS to permitted NS list in admin actions

.github/workflows/ci-guardrailpolicies.yml
Fixes our OPA CI
[OPA v1.0.0](https://github.com/open-policy-agent/opa/releases/tag/v1.0.0) was just released 25 minutes ago, which has breaking changes.  Pin the OPA version to v0.70.0 until we resolve them.
https://github.com/Azure/ARO-RP/actions/runs/12439052381/job/34732133679?pr=4030
CI
N/A
Tests
=> Pin OPA to v0.70.0

pkg/cluster/workloadidentityresources_test.go, pkg/util/platformworkloadidentity/federatedcredentials.go, pkg/util/platformworkloadidentity/federatedcredentials_test.go, pkg/validate/dynamic/platformworkloadidentityprofile_test.go
[ARO-13251](https://issues.redhat.com/browse/ARO-13251)
Fixes
The customer should have a clear idea of what federated credentials are associated with a given cluster.
Currently, we use subscription ID + service account name + hash.
We want to move the naming to cluster name + service account name (without the namespace)  + hash instead, so it’s clear what cluster a federated credential is associated with.
Updated unit tests
Tested by creating a MIWI cluster
Not yet
=> improve federated cred naming

pkg/api/util/subnet/subnet.go, pkg/util/purge/purge.go, pkg/util/purge/resourcegroups.go
https://issues.redhat.com/browse/ARO-12538
Besides the change to arm.network, some functions from arm.network like 'CreateOrUpdateAndWait' and 'Get' requires passing the exact name of multiple arguments rather than using the ID.
To adhere with the new implementation.
Tested locally and manually triggering the pipeline:
https://msazure.visualstudio.com/5d69ab04-7ded-49dc-84d5-bbbcac4add8d/_apis/build/builds/110655017/logs/13
No. Tech debt.
=> aro-12538 - Migrating subnet client in purge.go to use arm.network

.pipelines/ci.yml
No Jira
We found that E2E broke because temporary DBs from previous runs haven't been cleaned up. This PR attempts to ensure that the deletion command has what it needs to work.
Run E2E and then manually check that the DB has been cleaned up
N/A
N/A
=> Ensure necessary env vars are set for temp E2E DB deletion

cmd/aro/mirror.go, go.mod, hack/hive/hive-generate-config.sh, vendor/modules.txt
Fixes [ARO-5066](https://issues.redhat.com/browse/ARO-5066)
Resolve vulnerabilities reported via POAMS.
Deploy to shared aks cluster in westeurope.
No.
I've successfully deployed the hive operator image update to our shared aks cluster in westeurope.
After this, I then successfully provisioned a dev cluster via this hive deployment.
```bash
steven@rh-thinkpad-p1:~/go/src/github.com/Azure/ARO-RP$ ./hack/hive/hive-generate-config.sh 
main: Using hive commit: af54e2fbd9
install_kustomize: starting
hive_repo_clone: starting
hive_repo_clone: Cloning https://github.com/openshift/hive.git into /tmp/tmp.BffogcFuLC for config generation
Cloning into '/tmp/tmp.BffogcFuLC'...
remote: Enumerating objects: 160527, done.
remote: Counting objects: 100% (131/131), done.
remote: Compressing objects: 100% …
```
=> Hive Update af54e2fbd9

pkg/frontend/adminactions/resources_list_test.go, pkg/util/arm/marshal.go, pkg/util/arm/marshal_test.go, test/util/json/json.go
Fixes [ARO-13920](https://issues.redhat.com/browse/ARO-13920)
Updates our custom ARM resource marshaler to skip its custom implementation for track2 SDK resources and to use the built-in `MarshalJSON()` functions for those resources.
This is required as the track2 SDK structs do not have JSON tags, and instead expect the use of their `MarshalJSON()` functions in order to correctly marshal into valid ARM JSON. 
There was a previous implementation to skip the custom marshaling for specific CosmosDB resources; this PR will now skip for all structs in the track2 package (`sdk/resourcemanager`)
No
This should only impact pre-production flows (e.g. deployment template generation) as well as the List Cluster Azure Resources admin endpoint, which is currently (as of latest master) exhibiting the …
=> Use built-in marshaler for all track2 SDK structs

pkg/api/operation.go, pkg/api/v20240812preview/register.go
Fixes https://issues.redhat.com/browse/ARO-13257
Adds missing PWIRS list to operations for the MIWI preview API.
CI and E2E
=> Add PlatformWorkloadIdentityRoleSetsList to operations list for v2024-08-12-preview

pkg/cluster/sshkeys.go, pkg/cluster/storageSuffix.go
Increased the length of the storage suffix generated from 5 to 10 characters for improved uniqueness.
https://issues.redhat.com/browse/ARO-9582
We sometimes see CIF with the error "StorageAccountAlreadyTaken".
According to the document https://learn.microsoft.com/en-us/azure/storage/common/storage-account-overview storage account is unique within Azure, and our random storage account suffix is now 31^5 kinds.
Considering the number of clusters, it's too small.
This PR increases the length of suffix to 10 and lower the probability of collision.
e2e
N/A
cluster creation
=> [ARO-9582] Increase storage suffix length

pkg/frontend/openshiftcluster_preflightvalidation.go, pkg/frontend/openshiftcluster_preflightvalidation_test.go, pkg/frontend/openshiftcluster_putorpatch.go, pkg/frontend/openshiftcluster_putorpatch_test.go, pkg/frontend/platformworkloadidentityrolesets_list.go, pkg/frontend/platformworkloadidentityrolesets_validate.go, pkg/frontend/platformworkloadidentityrolesets_validate_test.go, pkg/util/mocks/platformworkloadidentity/platformworkloadidentity.go, pkg/util/platformworkloadidentity/platformworkloadidentityrolesbyversion.go
Fixes [ARO-12514](https://issues.redhat.com/browse/ARO-12514)
- Moves the expected platform workload identity check to the frontend so that all the invalid platform workload identities are never persisted to cluster doc during create and update flow.
- Also, added the validation for the deployment preflight check.
[x] Unit tests added/updated for the above implementation
[x] Create/Update MIWI cluster in local
[x] CI
[x] e2e
Not yet.
Feature is not in production yet.
=> Fix unexpected workload identity update in workload identity clusters

pkg/backend/openshiftcluster.go, pkg/backend/openshiftcluster_test.go
Fixes https://issues.redhat.com/browse/ARO-12518
NOTE: I have to recreate this PR from a direct branch of this repo as my previous PR from my fork was not picked up by azure CI (see 
https://github.com/Azure/ARO-RP/pull/3981)
**What**
Map other known backend errors returned by azure to their correct result type when logging them. 
**Why**
Currently, these known errors are mapped to "InternalServerError" regardless of their nature (e.g. 5xx, 4xx) and logged as an InternalServerError. This breaks our CIF SLO reporting as it depends on parsing these logs.
**Example UserErrors that are mapped to InternalServerError**
```
network.SubnetsClient#CreateOrUpdate: Failure sending request: StatusCode=403 – Original Error: Code="LinkedAuthorizationFailed" Message= (backend)
ClientSecretCredential …
```
=> [ARO-12518] Map other error's http status codes to correct result type.

docs/deploy-development-rp.md
NA
When creating local RP, it was not obvious to create the OCP release.
Also, for DEV we do not need to specify the sha for the image, and this eases the add of a release in the DB.
So I propose this PR.
NA
NA
NA
=> improve OCP version definition in local RP

python/az/aro/azext_aro/custom.py
Fixes broken `azdev` tests against the MIWI preview API, as a part of [ARO-8297](https://issues.redhat.com/browse/ARO-8297)
Adds the `--enable-managed-identity`, `--platform-workload-identities`, and `--mi-user-assigned` parameters to the `az aro validate` command, in order to fix validation issues on the client_id/client_secret parameters due to these fields being missing. 
Note that this does not implement any CLI-side dynamic validation for these properties. 
No
We would need to make this corresponding CLI change to the production Azure CLI, but as we have not upstreamed any part of the MIWI implementation yet, nor is any ARO API version supporting MIWI available in production, this will have no impact currently.
=> Add WI create parameters to validate

pkg/util/version/const.go
Fixes no Jira
Updates the default install version in localdev to 4.15.35, to match the eventual production change. 
No
Non-production change
=> Update default install version in localdev to 4.15.35

pkg/operator/flags.go, test/e2e/operator.go
Fixes [ARO-13325](https://issues.redhat.com/browse/ARO-13325)
Defaults to having the monitoring controller in the ARO operator to off. This will allow ARO cluster administrators to enable persistence for the core monitoring stack. 
Installed cluster, ran operator locally with flag set.
Externally yes
Tested on development cluster
=> Default `MonitoringEnabled` flag to false

pkg/cluster/gatherlogs.go, pkg/cluster/gatherlogs_test.go, pkg/cluster/install_test.go
Fixes [ARO-13611](https://issues.redhat.com/browse/ARO-13611)
This PR splits the logging output of k8s resource lists emitted during operation failures to output one object per-line, and to also log a "summary" of all objects (somewhat resembling `oc get ${RESOURCE}`'s default output format). 
This is necessary as our log viewer has a presentation limit of 32767 characters per-field. This makes some output, such as our cluster operator output, currently unusable due to the sheer size of the list. 
This PR also switches the JSON output from MarshalIndent to Marshal - in order to further reduce the character count of the resulting field. We can use tools such as `jq` or KQL's [`parse_json`](https://learn.microsoft.com/en-us/kusto/query/parse-json-function) to consume this output and …
=> Split output of failurelogs' list results

pkg/cluster/gatherlogs.go, pkg/cluster/gatherlogs_test.go, pkg/cluster/install_test.go
Fixes [ARO-13781](https://issues.redhat.com/browse/ARO-13781)
- Logs Hive CD on install failures
No
If we see Hive CDs in RP logs when an install fails, we'll know
=> Log Hive CD on install failures

python/az/aro/azext_aro/_params.py
Fixes [ARO-12200](https://issues.redhat.com/browse/ARO-12200)
This updates the usage for `az aro create` to show the expected values for the `--assign-platform-workload-identity`/`--assign-platform-wi` and `--mi-user-assigned`/`--assign-cluster-identity` arguments. This should make it easier for users to provide the expected input
Ran `az aro create -h` after configuring `az` to use my local files as the aro extension
No, this is updating documentation to match expectations
=> ARO-12200 include expected values for MIWI arguments in az aro create usage

go.mod, go.sum, vendor/modules.txt
https://issues.redhat.com/browse/ARO-14549
go-restful 2.15.0 is exposed to CVE-2022-1996, this replaces the 
This is a stop-gap until we can vendor in hive's own fix for this: https://github.com/openshift/hive/pull/2549
=> Update go-restful to 2.16.0

pkg/api/admin/openshiftcluster.go, pkg/cluster/adminupdate_test.go, pkg/cluster/install.go
https://issues.redhat.com/browse/ARO-12033
This PR fixes several small issues with admin updates on MIWI clusters. Each one of my original three commits to this branch fixes one issue.
- Tested all four different types of admin updates against a dev cluster and made sure that the update succeeded and no fields in the cluster doc were clobbered/erased
- After each of the admin updates runs, did an admin GET and verified that all MIWI-specific fields were present in cluster doc and available via the admin API (except for the identity URL and the bound service account signing key, which I don't think we need to be there)
- Updated unit tests where applicable
Note that the Jira says we should add unit tests to ensure that none of the MIWI fields are clobbered/erased. It can't really be …
=> Fix MIWI admin update

.gitleaks.toml
Fixes false positive secret scanning on red hat tooling in relation to scripts that are generated from ARM templates.  
Make scanning tools happy.  
There's a source page underneath "Pattern Distribution Server" that contains the information to test this.  After these changes we shouldn't get any false positives on local dirs.  
no
Non-prod functionality.
=> Add gitleaks.toml to avoid false positives on generated ARM template scripts

pkg/backend/openshiftcluster.go, pkg/backend/openshiftcluster_test.go
Fixes https://issues.redhat.com/browse/ARO-11772
Enables https://issues.redhat.com/browse/ARO-7841
For dashboarding purposes, we're missing a few things:
We wish to include cluster deletion success/failure rates in a dashboard. This is not possible because currently we don't log the completion of successful cluster deletions. That's because the logs (and other metrics) get emitted by endLease(), and the lease doesn't get released for deletions because the cluster doc gets deleted instead.
We wish to improve our cluster creation dashboards by distinguishing MIWI clusters installs from Service Principal installs. To do that we need a new field in AsyncQoS that records the cluster identity type requested.
Manual testing will be required, as E2E does not exercise this as part of cluster …
=> Log MIWI/SP install type to AsyncQoS; also log successful cluster deletions

go.mod, go.sum, vendor/github.com/openshift/machine-config-operator/pkg/apis/machineconfiguration.openshift.io/v1/types.go, vendor/modules.txt
https://issues.redhat.com/browse/ARO-14550
github.com/Masterminds/goutils@v1.1.0 is exposed to CVE-2021-4238
On current master:
```
go mod graph | grep github.com/Masterminds/goutils | while read -r line; do dependency=$(awk '{print $1}' <<<${line}); go mod why -m "${dependency%@*}"; done
github.com/Azure/ARO-RP/pkg/monitor/cluster
github.com/openshift/machine-config-operator/pkg/apis/machineconfiguration.openshift.io/v1
```
After manually updating the dep on machine-config-operator,
```
go mod graph | grep github.com/Masterminds/goutils | while read -r line; do dependency=$(awk '{print $1}' <<<${line}); go mod why -m "${dependency%@*}"; done
> No Output
```
=> Update go module deps to fix CVE-2021-4238

pkg/cluster/adminupdate_test.go, pkg/cluster/install.go
https://issues.redhat.com/browse/ARO-14878
This PR sort of follows up on https://github.com/Azure/ARO-RP/pull/4037. We separated the platform identity IDs step into two steps, and since we were working on admin update in parallel in a different PR, the changes to update didn't get carried over to admin update.
1. Created local dev cluster
2. Ran admin update
3. Verified that admin update completed successfully and platform identity IDs were still present in cluster doc
4. Removed changes, ran admin update again, verified that platform identity IDs will not be present in cluster doc after admin update without this change
N/A
N/A
=> Ensure admin updates persist platform workload identity IDs

pkg/operator/flags.go
Pauses rollout of https://issues.redhat.com/browse/ARO-13325
There's some concern that allowing persistence in prometheus will break some critical metrics for ARO SRE. This PR pauses the rollout of enabling customers to use persistence until further discussion
=> Change monitoringenabled back to true by default

.github/workflows/codeql-analysis.yml
Fixes #4051
Apparently the last person to modify the `cron` on a scheduled job gets [notified about failures](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#schedule).  So instead of bothering someone else who no longer is here, we'll bother myself :old-man-yells-at-ben: 🤷 
Watch the thing notify me when it fails
nope
N/a
=> Bother bennerv instead of mjudeikis when failing codeql analysis cron

pkg/cluster/clustermsi.go, pkg/cluster/clustermsi_test.go, pkg/cluster/delete.go, pkg/cluster/delete_test.go
https://issues.redhat.com/browse/ARO-14968
This PR tweaks the secret name that MSI certs are stored in KV under so that we don't end up with orphaned KV secrets in the event that we ever support changing a live cluster's MSI.
Ran local dev RP and validated that it used the new secret name
N/A
MIWI feature testing
=> Use cluster doc ID as cluster MSI KV secret name

go.mod, go.sum, vendor/modules.txt
https://issues.redhat.com/browse/ARO-14553
Upgrade github.com/elazarl/goproxy from v0.0.0-20190911111923-ecfe977594f1 to 0.0.0-20230731152917-f99041a5c027 to fix [CVE-2023-37788](https://nvd.nist.gov/vuln/detail/cve-2023-37788)
=> Attempt to fix CVE-2023-37788

pkg/cluster/clustermsi.go, pkg/cluster/clustermsi_test.go
No Jira
This PR ensures that we parse any KV errors correctly, preventing cluster creation/deletion from being cut short by non-existent MSI certificates.
Reproduced Caden's issue during cluster creation in local dev and then validated that my change fixes it
N/A
MIWI feature testing
=> MIWI bug fix: parse KV error correctly

pkg/cluster/clustermsi.go, pkg/cluster/clustermsi_test.go, pkg/cluster/delete_test.go
We want a consistent naming convention for the MSI secret name so the certificate refresher can know what secrets to refresh.  As a result, all uamsis are prefixed with the constant in msi-dataplane library.  
Unit tests.
=> Update msi secret name in key vault

pkg/util/clienthelper/clienthelper.go, pkg/util/clienthelper/clienthelper_test.go, pkg/util/dynamichelper/dynamichelper.go, pkg/util/dynamichelper/dynamichelper_test.go
Fixes https://issues.redhat.com/browse/ARO-15038
Reduces logging spam from over-remediation of ServiceAccounts in 4.16.
Unit tests added
N/A
Unit tests, plus testing of 4.16 when available
=> [ARO-15038] Allow through openshift.io/ annotations on service accounts

pkg/cluster/clustermsi.go, pkg/cluster/deploybaseresources_additional.go, pkg/cluster/ipaddresses.go, pkg/cluster/loadbalancerprofile.go, pkg/deploy/devconfig.go, pkg/env/prod.go, pkg/util/cluster/cluster.go, pkg/util/storage/manager.go, test/e2e/ocp_machine.go, test/util/azure/msi/armmsi.go
Consistent usage of a library rather than using 3 different ones. 
The team agreed that they want to use the library we've written prior to the k8s generic bumps and what not.  If we start using functionality that's present in k8s.io/utils/ptr or azcore, then we will pivot.  
https://redhat-internal.slack.com/archives/C02ULBRS68M/p1738697814649279?thread_ts=1731940533.915429&cid=C02ULBRS68M
e2e & CI
=> Update all to.Ptr equivalents to our internal one

pkg/cluster/install.go, pkg/cluster/install_test.go, pkg/cluster/samples.go
Fixes [ARO-14389](https://issues.redhat.com/browse/ARO-14389)
Extends the implementation of #4045 to additionally pass the disabling samples config as an install manifest to Hive/the installer. This ensures that the cluster is born with the Samples operator disabled, rather than waiting until the RP reaches its post-install step to do so.
The post-install step is still retained to absolutely ensure the operator is disabled after install when it needs to be. 
```
$ kubectl get secrets -n ${CLUSTER_NS} cluster-manifests-secret -o jsonpath='{.data.cluster-config-samples\.yaml}' | base64 -d
apiVersion: samples.operator.openshift.io/v1
kind: Config
metadata:
creationTimestamp: null
name: cluster
spec:
managementState: Removed
status: {}
```
No
Above testing/validation
=> Add disable samples manifest to install

pkg/deploy/assets/rp-production-global.json, pkg/deploy/generator/resources_rp.go, pkg/deploy/generator/templates_rp.go, pkg/deploy/predeploy.go, pkg/deploy/predeploy_test.go, pkg/util/rbac/rbac.go
Part of building a pipeline to achieve [ARO-4399](https://issues.redhat.com/browse/ARO-4399)
Adds the [Storage Account Contributor](https://learn.microsoft.com/en-us/azure/role-based-access-control/built-in-roles/storage#storage-account-contributor) role over the rpversion storage account to our devops managed identity. This allows us to build pipelines that upload data to this storage account.
This privilege will be used in an upcoming pipeline to build and deploy the `az aro` Azure CLI preview extension into this storage account in order to serve it for external consumption. 
No
This change should not impact the production service, as it simply adds a new role assignment to the devops identity used during deployments.
=> Add devops identity as Storage Account Contributor to rpversion SA

pkg/frontend/adminactions/azureactions.go, pkg/frontend/adminactions/resources_list.go, pkg/frontend/adminactions/resources_list_test.go
Fixes [ARO-13921](https://issues.redhat.com/browse/ARO-13921)
Currently the List Cluster Azure Resources admin endpoint lists all resources within the managed resource group.
BYO NSGs, that some customers might have configured, belong to different resource groups, and are therefore omitted from this endpoint's output.
This change checks whether a subnet has an NSG that belongs to a different RG, and appends it to the Cluster Resources list.
The test mocks two subnets, one containing a managed NSG, the other containing a BYO NSG, then runs [WriteToStream()](https://github.com/Azure/ARO-RP/blob/d813341a11fda7da4567f116c88d7dab9900e3a3/pkg/frontend/adminactions/resources_list.go#L209).
That, in turn, calls [appendAzureNetworkResources()](https://github.com/Azure/ARO-RP/blob/d813341a11fda7da45 …
=> ARO-13921 Add cluster subnets' network security groups to List Cluster Azure Resources output if cluster uses preconfiguredNSG

pkg/frontend/adminactions/azureactions.go, pkg/util/azureclient/mgmt/compute/diskencryptionsets.go, pkg/util/cluster/cluster.go, pkg/validate/dynamic/dynamic.go, test/e2e/setup.go
Fixes https://issues.redhat.com/browse/ARO-15116
When we retry the creation of a cluster in CI mode, it fails because we create a new KeyVaults that cannot be used by existing DiskEncryptionSet.
Solution is to reuse Keyvault storing the current key of DES if it exists.
In order to test, we create a cluster, stop the process once DES is created (no need to create the full cluster), and then relaunch the creation, and previous created KeyVault storing the DES current key should be reused.
N/A: no change in the way we create cluster.
I've tested the creation of cluster with hack in CI mode, and rerun the creation which reused the KeyVault instead of recreating a new one.
=> [ARO-15116] DES missing Keyvault Access Policy on E2E retry

pkg/monitor/worker.go
Fixes [#itn-2025-00034](https://redhat.enterprise.slack.com/archives/C08CWJ84GN9)
WebRCA: https://web-rca.devshift.net/incident/ITN-2025-00034
This PR removes the repetitive expensive instantiation of env struct that also calls to AIMS. Instead using the env already set on the monitor object.
- Test the fix in Canary if the logs are still present for the env instantiation and AIMS calls.
No, updated the WebRCA doc.
- No restarts of monitor service expected in Canary and Prod(Busier regions)
=> Fixes itn-2025-00034 | removes iterative instantiation of env struct from monitor service

pkg/monitor/cluster/cluster.go, pkg/monitor/cluster/clusterwideproxystatus.go, pkg/monitor/cluster/clusterwideproxystatus_test.go, pkg/monitor/worker.go, test/e2e/monitor.go
Fixes
https://issues.redhat.com/browse/ARO-13380 
Develop metrics to create a monitoring alert for the SRE team when the CWP configuration is incorrect or any expected no_proxy url/ip is missing.
Check all the necessary no_proxies that needs to be verified at the time of enabling cluster wide proxy.
Necessary documents are currently being developed as part of the epic.
Metrics will be available in Geneva for cwp status.
=> ARO-13380 - metrics: cwp status

pkg/monitor/cluster/clusterwideproxystatus.go
Fixes https://issues.redhat.com/browse/ARO-13380
`golangci-lint` is failing due to a change made in https://github.com/Azure/ARO-RP/pull/4002.  
The linter is failing because a non-constant message to logrus.Infof without a formatter.
This PR passes the message in as a formatted message.
Error from locally running `make lint-go`:
```bash
make lint-go
...
INFO [runner] linters took 1m18.659622584s with stages: goanalysis_metalinter: 1m18.648949119s 
::error file=pkg/monitor/cluster/clusterwideproxystatus.go,line=211,col=18::printf: non-constant format string in call to (*github.com/sirupsen/logrus.Entry).Infof (govet)
INFO File cache stats: 1 entries of total size 7.8KiB 
INFO Memory: 2015 samples, avg is 721.6MB, max is 3688.6MB 
INFO Execution took 3m43.74316685s                
make: …
```
=> Correct log message format to pass golangci-lint

cmd/aro/mirror.go, go.mod, hack/hive/hive-generate-config.sh, vendor/modules.txt
Fixes [ARO-15148](https://issues.redhat.com/browse/ARO-15148)
Need to resolve vulnerabilities:
* POAMS Prio 1: Go (Go) Security Update for golang.org/x/crypto GHSA-v778-237x-gjrc
* POAMS Prio 2: Go (Go) Security Update for golang.org/x/net GHSA-w32m-9786-jp63
Tested the updated aks deployment by updating the westeurope aks hive deployment successfully.
This is the same process that occurs during the production hive deployment update.
I've made minor updates to our internal wiki documentation.
Otherwise no.
Local testing with shared aks cluster:
```bash
steven@rh-thinkpad-p1:~/go/src/github.com/Azure/ARO-RP$ hack/hive/hive-generate-config.sh 
main: Using hive commit: 5d3f4d77dc
install_kustomize: starting
hive_repo_clone: starting
hive_repo_clone: Cloning …
```
=> Update Hive API and Image to 5d3f4d77dc

docs/deploy-development-rp.md, docs/prepare-your-dev-environment.md
This PR addresses minor gaps in the environment setup docs, to make them more accessible for onboarding team members.
1. Some of the env variables are only required when deploying a MIWI cluster
2. Golang 1.22 is highly recommended, due to issues being encountered with 1.22+
3. CosmosDB database should only be created once per user.
4. `make init-contrib` adds a pre-commit hook for branch naming convention
5. Branch naming rule can be overridden in cases of PRs not tied to a work item (like this PR)
=> Dev environment doc updates

Makefile, docs/unit-testing-for-monitoring-metrics.md
Execute "make runlocal-monitor" to start a local instance of ARO monitor in development environment.
Fixes https://issues.redhat.com/browse/ARO-15502
This change introduces a new target in Makefile to start a local instance of ARO monitor which can be used to debug/develop monitors. Executing it via a target makes it quite convenient to use instead of executing the go run command.
Yes, changes will land in GitHub docs. 
Not a production change.
=> Create a target to start aro monitor

pkg/util/clienthelper/clienthelper.go, pkg/util/clienthelper/clienthelper_test.go
Fixes ARO-15124
Makes admin-updates not over-reconcile the Hive deployment (e.g. erasing the version tags)
I added unit tests, hopefully E2E checks it doesn't break anything? 
N/A
Not sure how we test Hive-touching changes.
=> Improve over-reconciliation of Hive Deployments

pkg/util/clienthelper/clienthelper.go, pkg/util/clienthelper/clienthelper_test.go
Fixes a regression from #4096 
Reintroduces code from dynamichelper's merge() that was not included into clienthelper's as well
Test cases
N/A
Tests
=> Reapply changes from #3704 into clienthelper as well

pkg/api/admin/openshiftcluster.go
This pull request reverts the changes made in PR #3941,  which had made the PreconfiguredNSG feature mutable. The purpose of this reversal is to restore its immutability, ensuring that administrative actions cannot accidentally toggle this essential feature on or off within ARO clusters.
Fixes: [ARO-12508](https://issues.redhat.com/browse/ARO-12508)
The objective of this PR is to reinstate the immutability of the PreconfiguredNSG setting. Reverting to the prior state ensures that inadvertent administrative adjustments that could compromise cluster security settings are prevented.
=> Revert changes to restore immutability of PreconfiguredNSG 

.pipelines/vars.yml, pkg/containerinstall/install.go, pkg/util/cluster/cluster.go, pkg/util/version/const.go
Fixes https://issues.redhat.com/browse/ARO-15564 
Moves our default for E2E + local installs to 4.16. Also updates some code that is relevant for this, notably:
1. Allowing podman to not pull images down, which was used when testing the locally built Installer image
2. Not running with FIPS when you are in local development. 4.16 requires the Installer environment to have FIPS enabled, not just the client, which is a bit much for local dev machines.
Manually tested, plus E2E.
N/A
Doesn't affect production.
=> Update local development to deploy OpenShift 4.16 by default

pkg/monitor/cluster/clusterwideproxystatus.go, pkg/monitor/cluster/clusterwideproxystatus_test.go
Fixes
Making api and api-int values as optional if clusterDomain is given. 
Also added few entries to identify the missing noProxy values.
This is an enhancement for existing CWP monitor for better Cx experience.
=> CWP - Optional checks with clusterDomain

docs/deploy-development-rp.md, pkg/containerinstall/install.go, pkg/containerinstall/manager.go, pkg/operator/controllers/checkers/clusterdnschecker/controller_test.go, pkg/operator/controllers/checkers/ingresscertificatechecker/controller_test.go, pkg/operator/controllers/checkers/internetchecker/controller_test.go, pkg/operator/controllers/checkers/serviceprincipalchecker/controller_test.go, pkg/util/pullsecret/extract.go, pkg/util/pullsecret/extract_test.go
Allow testing for [ARO-15149](https://issues.redhat.com/browse/ARO-15149)
In case the aro-installer image defined for the release is not in domain ACRDomain (mainly for test purpose), then if we run the installer in container, we need to be able to provide docker auth for this domain in PULL_SECRET
create a cluster running the installer in container and using a release that defines aro-installer image in quat.io. PULL_SECRET will need to define the auth for quay.io.
Procedure to use images via hive has been updated
N/A: Only for development mode
=> Allow installer in container to use other auth token than arosvc

pkg/cluster/deploybaseresources_additional.go
Fixes [ARO-14151](https://issues.redhat.com/browse/ARO-14151)
Permits creating and deleting policy remediations via the deny assignment. This allows customers to remediate their tagging policies
I deployed this to the canary environment and tested that tagging policies can be successfully remediated
No, this brings our policy in line with existing documentation
Tested in canary
=> allow Microsoft.PolicyInsights/remediations in deny assignment

python/az/aro/azext_aro/_validators.py, python/az/aro/azext_aro/custom.py
Fixes [ARO-15596](https://issues.redhat.com/browse/ARO-15596)
Currently, our CLI, on cluster creation as well as update, attempts to ensure the cluster identity (CSP only currently) has the required permissions over all cluster resources. It does this by retrieving each subnet present on the cluster's masterProfile, workerProfiles, and workerProfilesStatus, and ensuring permissions over each subnet itself, and any route tables, NAT Gateways, and NSGs (preconfiguredNSG only) attached to each subnet. 
It is possible for these subnets to be invalid, in the following scenarios:
- A cluster is created with a specific worker subnet provided, but then all worker nodes on the cluster are replaced with new nodes pointing to a new subnet, and the original worker subnet is deleted
- A cluster has an …
=> CLI - Do not fail ensuring resource permissions if workerprofiles or workerprofilesstatus contain profiles with invalid subnets

pkg/deploy/devconfig.go
Right now, when trying to run a RP locally on Dev environment `make deploy` throws a below error. This is due to missing `OtelAuditQueueSize` in dev-config.yaml file which is generated by running `make dev-config.yaml`. 
```
❯ make deploy                                        
go run -ldflags "-X github.com/Azure/ARO-RP/pkg/util/version.GitCommit=latest" ./cmd/aro deploy dev-config.yaml eastus
INFO[2025-03-11T22:23:07+05:30]cmd/aro/main.go:47 main.main() starting, git commit latest                  
INFO[2025-03-11T22:23:07+05:30]pkg/env/core.go:132 env.NewCoreForCI() running in local development mode            
INFO[2025-03-11T22:23:07+05:30]cmd/aro/deploy.go:69 main.deploy() deploying version latest to location eastus  
FATA[2025-03-11T22:23:07+05:30]cmd/aro/main.go:87 main.main() …
```
=> Add OtelAuditQueueSize in dev configuration

pkg/api/admin/openshiftcluster.go, pkg/api/admin/openshiftcluster_convert.go, pkg/api/admin/openshiftcluster_validatestatic.go, pkg/frontend/admin_openshiftcluster_list_test.go, pkg/frontend/openshiftcluster_putorpatch_test.go
This commit fixes a regression in the conversion logic for OpenShiftCluster objects where the **PreconfiguredNSG** field in the **NetworkProfile** was not correctly preserved or defaulted when converting from the internal `(api.OpenShiftCluster)` to the external `(admin.OpenShiftCluster)`
representation.
- Previously, if the **PreconfiguredNSG** field was missing from the internal object, the external representation did not default to the expected value (**Disabled**), leading to discrepancies in behavior. 
- if the field was explicitly set to **Enabled** internally, that value wasn’t properly carried over.
**Fixes** :  [ARO-12509](https://issues.redhat.com/browse/ARO-12509)
1. In **pkg/api/admin/openshiftcluster_convert.go** 
- Update the mapping for the NetworkProfile field so that: …
=> fix(admin): preserve PreconfiguredNSG in OpenShiftCluster conversion

.pipelines/e2e.yml, hack/devtools/platform_workload_identity_role_sets.json
Fixes https://issues.redhat.com/browse/ARO-13401
- Fixes miwi e2e pipeline issue e.g.: https://github.com/Azure/ARO-RP/runs/38530144373
- In a previous PR, the default install version was changed to `4.16.30`
- The E2E pipeline however was hardcoding 4.15.35 as the version it wants to use
- the cluster 
- PR E2e pipeline should be green
=> [ARO-15680] Use default openshift version in miwi e2e pipeline

pkg/util/clientauthorizer/arm.go, pkg/util/clientauthorizer/arm_test.go
Fixes [ARO-15927](https://issues.redhat.com/browse/ARO-15927)
Updates our clientauthorizer code to utilize the known correct ARM endpoint in usgovcloud, instead of inferring it from IMDS
Not sure. 
Confirmation discussed internally.
=> Add explicit Resource Manager Endpoint for USGovernmentCloud

pkg/api/error.go, pkg/validate/dynamic/dynamic.go, pkg/validate/dynamic/dynamic_test.go
As part of ARO-15514 to descope permissions, move the validation logic for validating subnet permissions down the subnet level.  This removes the need for the cluster identities to have visibility to all subnets associated with the ARO VNET, as some ARO users will inter-mix ARO subnets with their other application subnets.
Additionally, adjust VNET/subnet tests to account for the split between the new logic.
Fixes https://issues.redhat.com/browse/ARO-15514
This PR moves the validation logic for the cluster identities for the subnet actions from the VNET level down to the subnet level.  This is to address a tighter least privilege implementation for the cluster identities that run the ARO service within the cluster.  Prior to this change, subnet permissions were required at the VNET level, …
=> [ARO-15514] feat: move subnet validation logic to subnet level

pkg/operator/controllers/guardrails/policies/gktemplates-src/library/common.rego, pkg/operator/controllers/guardrails/policies/gktemplates/aro-deny-delete-pull-secret.yaml, pkg/operator/controllers/guardrails/policies/gktemplates/aro-deny-machine-config.yaml, pkg/operator/controllers/guardrails/policies/gktemplates/aro-deny-master-toleration-taints.yaml, pkg/operator/controllers/guardrails/policies/gktemplates/aro-deny-privileged-namespace.yaml
Fixes ARO-15551
removed some unnecessary namespaces from privileged_ns in common.rego, as some of them are empty after fresh install or found Customer's operations in that ns from previous sample rollout in dryrun mode:
empty namespaces found on sre-shared-cluster:
No resources found in openshift-console-user-settings namespace.
No resources found in openshift-operators namespace.
$ ./scripts/test.sh 
expand constraints gkconstraints/aro-cluster-role-deny.yaml
expand constraints gkconstraints/aro-machine-config-deny.yaml
expand constraints gkconstraints/aro-machines-deny.yaml
expand constraints gkconstraints/aro-master-toleration-pod-deny.yaml
expand constraints gkconstraints/aro-privileged-namespace-deny.yaml
expand constraints gkconstraints/aro-pull-secret-deny.yaml
expand constraints …
=> remove some namespaces from privileged_ns for guardrails

pkg/deploy/assets/gateway-production.json, pkg/deploy/assets/rp-production.json, pkg/deploy/generator/resources_gateway.go, pkg/deploy/generator/resources_rp.go
Required for https://issues.redhat.com/browse/ARO-15312
Fixes https://issues.redhat.com/browse/ARO-15312
Use the Non HOBO 1P image gallery for first party services.
Deploy to INT, ensure VMSS instances can pull the image URI and create the VMs.
Design documentation (to be located).
I have successfully deployed the ARM templates in INT.  
For the public image gallery, there is no difference in FF. There was no mention of FF having a separate 1P image gallery URI.
I had a successful VMSS creation in [this pipeline run in Canary](https://msazure.visualstudio.com/AzureRedHatOpenShift/_build/results?buildId=118928428&view=logs&s=edf8ecb0-00a4-5494-e73a-6d50a5bb0760&j=0fb17de2-5f19-5aee-4a4b-dbe8a1dc9cb9). The pipeline overall failed due to it not being able to find/pull the ARO image related …
=> Update Image Gallery to Non HOBO 1P for VMSS instances

.github/list-prune-tags.sh, .github/workflows/prune-tags.yml
Fixes ARO-14879
This PR introduces a GitHub Action to delete all non-production git tags from the repo that are older than 60 days.
Run `.github/list-prune-tags.sh -h` to get help text for how to use it.
One can test (a portion of) this PR by running `.github/list-prune-tags.sh` locally to view what tags it prints. **`list-prune-tags.sh` does not carry out any destructive actions.**
Unsure.
This does not affect production.
=> [ARO-14879] chore: introduce GHA to prune non-production tags

pkg/util/cluster/cluster.go
Update Default VM Sizes to Dsv5 for Cluster Creatio
Fixes: [ARO-14965](https://issues.redhat.com/browse/ARO-14965)
This PR updates the Go-based tooling to use Dsv5 as the default VM type in tests. The changes ensure that:
- go run` ./hack/cluster` create now defaults to Dsv5 instead of Dsv3.
- PR and Release E2E tests reflect the new default.
Additionally, this PR updates the default VM sizes for master and worker nodes in cluster creation:
1. Master VM Size: `Standard_D8s_v3` → `Standard_D8s_v5`
2. Worker VM Size: `Standard_D4s_v3` → `Standard_D4s_v5`
By switching to Dsv5, new clusters will use the latest available VM series, reducing capacity issues and improving reliability.
1.  Verified go run` ./hack/cluster` create successfully provisions a cluster with Dsv5 defaults.
N/A
=> Update Default VM Sizes to Dsv5 for Cluster Creation

pkg/deploy/assets/gateway-production-parameters.json, pkg/deploy/assets/gateway-production.json, pkg/deploy/assets/rp-production-parameters.json, pkg/deploy/assets/rp-production.json, pkg/deploy/generator/templates_gateway.go, pkg/deploy/generator/templates_rp.go
https://issues.redhat.com/browse/ARO-15954
Fixes
JapanWest was recently updated on the cloud provider side to support availability zones (AZ). Our current infrastructure deployed in this region is deployed as `nonZonal` and updating some of these components (mainly the gateway service ILB) is not possible once it has been deployed. This PR should set JapanWest to nonzonal explicitly which should allow for the deployment to complete. 
We will need to follow up this PR with an action plan on how to support zones that become AZ enabled after the initial deploy has been completed. 
Currently, the RP deploy into JapanWest for release 267 is incomplete. This change will allow the RP deploy into that region to complete. 
No
The GWY and RP deploy will succeed.
=> Adding JapanWest to nonzonal list

pkg/monitor/cluster/clusterwideproxystatus.go
https://issues.redhat.com/browse/ARO-15873 
Fixes
SRE observed that geneva is not able to parse some special characters thus not able to view the metrics and it is affecting the monitor. So we changed special chars that we used in our messages
Also during the scrutiny we observed that Cx are not adding the the full gatewayDomains in the noProxy list, only a part of it is added to noProxy, so inorder to avoid false alerts and better Cx experience, did some adjustments.
Note: Creating it as draft because expecting peer review for the changes.
=> Cluster-Wide Proxy monitor changes for enhancement and better Cx experience

.golangci.yml, pkg/api/admin/openshiftcluster_validatestatic_test.go, pkg/api/correlation.go, pkg/api/util/uuid/uuid.go, pkg/api/v20191231preview/openshiftcluster_validatestatic.go, pkg/api/v20191231preview/openshiftcluster_validatestatic_test.go, pkg/api/v20200430/openshiftcluster_validatestatic.go, pkg/api/v20200430/openshiftcluster_validatestatic_test.go, pkg/api/v20210901preview/openshiftcluster_validatestatic.go, pkg/api/v20210901preview/openshiftcluster_validatestatic_test.go, pkg/api/v20220401/openshiftcluster_validatestatic.go, pkg/api/v20220401/openshiftcluster_validatestatic_test.go, pkg/api/v20220904/openshiftcluster_validatestatic.go, pkg/api/v20220904/openshiftcluster_validatestatic_test.go, pkg/api/v20230401/openshiftcluster_validatestatic.go, pkg/api/v20230401/openshiftcluster_validatestatic_test.go, pkg/api/v20230701preview/openshiftcluster_validatestatic.go, pkg/api/v20230701preview/openshiftcluster_validatestatic_test.go, pkg/api/v20230904/openshiftcluster_validatestatic.go, pkg/api/v20230904/openshiftcluster_validatestatic_test.go, pkg/api/v20231122/openshiftcluster_validatestatic.go, pkg/api/v20231122/openshiftcluster_validatestatic_test.go, pkg/api/v20240812preview/openshiftcluster_validatestatic.go, pkg/api/v20240812preview/openshiftcluster_validatestatic_test.go, pkg/util/uuid/fake/fake_uuid.go, pkg/util/uuid/uuid.go
Fixes ARO-3865
This removes the dependency on pkg/util/uuid in pkg/api, so we can make pkg/api a subpackage.
Unit tests
N/A
N/A, just code moving
=> [ARO-3865] Remove dependence on pkg/util/uuid in pkg/api

.github/workflows/prune-tags.yml
ARO-14879
Fixes the "Prune tags" GitHub Workflow. Command substitution does not work in a
`run` step.
n/a
No.
This change does not affect the RP running in production.
=> fix: GHA prune-tags

cmd/aro/mirror.go
Fixes no Jira
Updates the baseline (minimum) version of OpenShift we mirror artifacts for to 4.14 (from 4.12). 4.12 and 4.13 are now EOL. 
No
Mirror pipeline passes
=> Set baseline OCP version used for mirroring artifacts to 4.14

pkg/cluster/correct_cert_issuer.go, pkg/cluster/correct_cert_issuer_test.go
Fixes (no JIRA)
The issuer and certificate name were swapped in the `CreateCertificate` method, causing the certificate to be created with the wrong parameters.
- CI and e2e
- Unit test adjustments
=> hotfix: correct certificate issuer

pkg/operator/controllers/dnsmasq/scripts/dnsmasq.conf.gotmpl, pkg/operator/controllers/etchosts/etchosts.go, pkg/operator/controllers/etchosts/etchosts_test.go
Fixes ARO-2799 and ARO-15424
Companion PR to https://github.com/openshift/installer-aro-wrapper/pull/263
Implementation of TDR: https://docs.google.com/document/d/1nA1udF8RbJdpFgW3sezlEQGPMgqEQAZ7zvbCu18Zr5Q/
I also slipped in a small tweak to the etchosts template since my editor kept wanting to delete the trailing space from installer-aro-wrapper's storage_files_testdata.go
=> dnsmasq.conf: remove strict-order and add dns-forward-max

pkg/operator/controllers/dnsmasq/scripts/aro-dnsmasq-pre.sh.gotmpl, pkg/operator/controllers/dnsmasq/scripts/dnsmasq.service.gotmpl
Fixes ARO-15180
Companion installer PR https://github.com/openshift/installer-aro-wrapper/pull/255
Derived from the method in https://github.com/openshift/machine-config-operator/blob/master/templates/common/gcp/files/usr-local-bin-update-dns-server.yaml
We've been overwriting `/etc/resolv.conf`. NetworkManager owns this file and if NetworkManager needs to refresh it we will lose our changes. Instead, create a NetworkManager drop-in `/etc/NetworkManager/conf.d/dns-servers.conf` with the node's IP.
No, but the change needs to be socialized amongst ARO SRE since it affects how nameservers are managed.
Testing has been done with an extant UDR+bad dns cluster to ensure there are no external DNS dependencies. Nodes boot and scale correctly.
=> Refactor aro-dnsmasq-pre.sh to not overwrite /etc/resolv.conf

pkg/util/cluster/cluster.go
Fixes https://issues.redhat.com/browse/ARO-15117 
Previously we included this code because the disk-csi built-in role was missing a permission, and adding actions to built-in roles takes a while.
Now, the built-in has the permission, so we can safely remove this code:
```
az role definition list --name "Azure Red Hat OpenShift Disk Storage Operator"
[
{
"assignableScopes": [
"/"
],
"createdBy": null,
"createdOn": "2024-01-30T16:11:37.947432+00:00",
"description": "Install Container Storage Interface (CSI) drivers that enable your cluster to use Azure Disks. Set OpenShift cluster-wide storage defaults to ensure a default storageclass exists for clusters.",
"id": "/subscriptions/60bf318d-6914-4105-a3b5-d0d2c10388c8/providers/Microsoft.Authorization/roleDefinitions/5b7237c5-45e1-49d6-bc18-a1f …
```
=> [ARO-15117] MIWI e2e - remove disk-csi missing permissions workaround

cmd/aro/deploy.go, pkg/deploy/assets/rp-production-global.json, pkg/deploy/deploy.go, pkg/deploy/generator/resources.go, pkg/deploy/generator/resources_miwi_dev.go, pkg/deploy/generator/resources_rp.go, pkg/deploy/saveversion.go, pkg/util/azureclient/azuresdk/azblob/blobs.go, pkg/util/mocks/azureclient/azuresdk/azblob/blobs.go, pkg/util/rbac/rbac.go
https://issues.redhat.com/browse/ARO-14659
As part of security wave, all SAs need to disable local/shared key auth.
=> Disable and remove use of local/shared key auth for SAs

pkg/frontend/admin_openshiftcluster_serialconsole.go, pkg/frontend/admin_openshiftcluster_serialconsole_test.go
Fixes https://issues.redhat.com/browse/ARO-13386
The original description of the ticket asks for E2E coverage for any VM console log ingestion code paths that aren't covered in E2E.
Upon some investigation, this is not required. However, I did notice that admin_openshiftcluster_serialconsole_test.go is not covered by UT. 
The PR adds UT coverage for admin_openshiftcluster_serialconsole_test.go
NA
Negative
NA
=> [ARO-13386] Add UT coverage for admin_openshiftcluster_serialconsole.go

Makefile
This PR adds the Makefile target for logging into sre-shared-miwi-cluster
No
=> add Makefile target for logging into shared MIWI cluster

pkg/api/error.go, pkg/cluster/platformworkloadidentities.go, pkg/cluster/platformworkloadidentities_test.go, pkg/util/azureerrors/error.go
[ARO-15923](https://issues.redhat.com/browse/ARO-15923) and [ARO-15931](https://issues.redhat.com/browse/ARO-15931)
This PR is created to return an actionable error when an invalid platform workload identity is provided during MIWI cluster installation, instead of an Internal Server Error.  
Intentionally failing the cluster creation by providing an invalid identity in the create command to get an InvalidPlatformWorkloadIdentity error. 
No
=> return actionable error when invalid identity is passed

cmd/aro/mirror.go, go.mod, hack/hive/hive-generate-config.sh
Hive Operator updated to 87bff5947f in order to resolve P1s pending in POAMs report.
Hive APIs updated to match Hive operator image.
Fixes https://issues.redhat.com/browse/ARO-16359
This is needed to resolve pending P1s in POAMs reports.
Resolves GHSA-mh63-6h87-95cp
Fixed in upstream hive:
* https://github.com/openshift/hive/blob/master/go.mod#L420
* https://github.com/openshift/hive/blob/master/go.mod#L107
I've deployed the `hive-operator` image update to the shared aks cluster in westeurope.
An improvement to the docs should be made. A majority of the documentation detailed in our ARO Wiki is more appropriately placed within this repository. I will open a follow up PR with the documentation updates.
See the terminal output below:
Local Hive config generation:
```bash
(3.11.0) …
```
=> Update Hive APIs to 87bff5947f, Hive Operator to Image 87bff5947f

pkg/cluster/install.go
Fixes ARO-16202
If there's a delay between when the first party service principal is granted the necessary roles and the RP tries to perform these actions, an authorization error is returned. Instead of failing (and returning a relatively unhelpful error message to the customer), these changes cause the steps to be retried instead.
We can't really reproduce this issue so we'll need to watch to see if these errors continue popping up or not. If so, it's likely they'll be on a different step of the install process which will then need to be updated to retry also
No; this is a bugfix
The functions used are identical except for retrying if given an authorization failure
=> ARO-16202 retry bootstrap steps if an authentication error is returned

pkg/api/v20240812preview/openshiftcluster_convert.go, pkg/api/v20240812preview/openshiftcluster_validatestatic.go, pkg/api/v20240812preview/openshiftcluster_validatestatic_test.go, pkg/cluster/install.go, pkg/cluster/workloadidentityresources.go, pkg/cluster/workloadidentityresources_test.go, pkg/frontend/openshiftcluster_putorpatch_test.go
Fixes [ARO-8880](https://issues.redhat.com/browse/ARO-8880)
Enables the ability to replace existing platform workload identities on a MIWI cluster, by performing the following changes:
- Remove our existing validation that prevented updating the ResourceID field on existing platform workload identities
- Clear the ClientID and ObjectID fields on any platform workload identities whose ResourceID has changed
- This is not strictly required, but it prevents the output of the update request from displaying the "old" values for these fields. The RP returns a response immediately on a PUT/PATCH request, before the backend has the chance to update these fields to the new correct values.
- Adds a new step to the backend Update process to reconcile roleassignments for platform workload identities …
=> Enable the ability to replace platform workload identities on a MIWI cluster

pkg/cluster/adminupdate_test.go, pkg/cluster/install.go
No Jira
This PR removes the `HiveClusterDeploymentReady` check from cluster updates, I opened this PR because I noticed that at least in the past week or so, E2E has been timing out on this step.
See for reference a similar PR to fix broken E2E on a different occasion by removing the same step from the install code path: https://github.com/Azure/ARO-RP/pull/4027
E2E
N/A
Prod E2E
=> Fix E2E - remove HiveClusterDeploymentReady from cluster updates

pkg/util/clusterdata/worker_profile.go, pkg/util/clusterdata/worker_profile_test.go
Fixes no Jira (follow-up to [ARO-15918](https://issues.redhat.com/browse/ARO-15918)/#4155)
In workerprofile enrichment: forcibly converts any tag values present on the raw Azure Machine Provider Spec to strings before unmarshaling in to the AzureMachineProviderSpec struct, similar to the previous fix done for the zone field. 
Once released and confirmed successful, we will need to update our internal guidance on dealing with CLI errors caused by invalid workerprofilestatus enrichment (again). 
Tests covered above
=> Workerprofile Enrichment: Forcibly convert all tags in raw machine providerSpec to string before parsing

.github/workflows/prune-tags.yml
I was incorrectly storing the `gather_tags` step output. Each bit of
stored output needs to be assigned to a key for recall later.
ref: https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions#setting-an-output-parameter
Related to ARO-14879
This time (third time's the charm?) the GHA should output non-production git
tags that are older than 60 days, and prune them from the repo.
Feel free to run `.github/list-prune-tags.sh` by hand to see what the script
returns for pruning.
No.
This GitHub Workflow and Actions do not affect production.
=> fix(prune-tags): correctly store command step output

pkg/frontend/adminactions/azureactions.go, pkg/frontend/adminactions/delete_managedresource.go, pkg/frontend/adminactions/delete_managedresource_test.go, pkg/util/loadbalancer/loadbalancer.go, pkg/util/loadbalancer/loadbalancer_test.go
Fixes https://issues.redhat.com/browse/ARO-12533
tech debt, moving to armnetwork client
https://issues.redhat.com/browse/ARO-12531
UT were amended to use new client and are passing, e2e will run in PR
No
N/A
=> ARO-12533: Migrate mgmt/network in deleteFrontendIPConfiguration

cmd/aro/operator.go, pkg/operator/deploy/staticresources/master/deployment.yaml.tmpl, pkg/operator/deploy/staticresources/master/service.yaml, pkg/operator/deploy/staticresources/master/servicemonitor.yaml, pkg/operator/deploy/staticresources/namespace.yaml, pkg/operator/deploy/staticresources/prometheus-role.yaml, pkg/operator/deploy/staticresources/prometheus-rolebinding.yaml
Fixes ARO-15543
Enables monitoring of the ARO Operator master pod into the cluster Prometheus
Manual testing
SOPs, eventually
Testing :)
=> [ARO-15543] Enable monitoring the aro operator master pod

pkg/monitor/cluster/cluster.go, pkg/monitor/cluster/clusterauthenticationtype.go, pkg/monitor/cluster/clusterauthenticationtype_test.go, test/e2e/monitor.go
[ARO-15682](https://issues.redhat.com/browse/ARO-15682)
This PR creates a monitor for cluster authentication type, either CSP or MI, So that metrics are emitted which report the authentication type in use by every cluster and we have an accurate, live count of clusters using both authentication types.
Unit tests have been added
=> Impliment Monitoring for Cluster Authentication Type

pkg/cluster/delete.go, pkg/cluster/delete_test.go
Implements https://issues.redhat.com/browse/ARO-12544
Partial implementation of the migration from mgmt/network to azuresdk/armnetwork (focused on pkg/cluster/delete.go)
Technical migration, e2e covering it
No
Technical migration.
=> Migrate to azuresdk/armnetwork in pkg/cluster/delete.go

.github/workflows/prune-tags.yml
Fourth time is the charm?
I can't believe it took me this long to remember that [actions/checkout](https://github.com/actions/checkout) is a shallow checkout by default. That means that only the git objects directly associated with the given git reference are checked out. All other branches, tags, and objects are not.
Setting `fetch-depth` to `0` ([ref](https://github.com/actions/checkout?tab=readme-ov-file#Fetch-all-history-for-all-tags-and-branches)) instructs actions/checkout to carry out a full clone of the repository, including tags which is what we're interested in for this GitHub Actions Workflow.
Fixes: ARO-14879
Prune old, non-production tags from this GitHub repository whenever a tag is pushed.
n/a
None.
This change does not affect how ARO-RP runs in production.
=> fix(prune-tags): actions/checkout set fetch-depth

.github/workflows/ci-go.yml, .github/workflows/ci-python.yml, .pipelines/ci.yml, .pipelines/clean-subscription.yml, .pipelines/e2e.yml, .pipelines/onebranch/pipeline.buildrp.official.yml, .pipelines/onebranch/pipeline.buildrp.pullrequest.yml, .pipelines/rp-full-dev-setup.yml, Dockerfile.aro-e2e, Dockerfile.aro-multistage, Dockerfile.autorest, Dockerfile.ci-rp, Dockerfile.ci-tunnel, Dockerfile.gatekeeper, Dockerfile.portal_lint, Dockerfile.proxy, Makefile, cmd/aro/mirror.go, hack/fips/validate-fips.sh, hack/ssh-k8s.sh, pkg/containerinstall/install_test.go, pkg/frontend/fixetcd.go
Fixes https://issues.redhat.com/browse/ARO-16975
- Move us off of RHEL 8 + go-toolset for building, and onto RHEL 9 + golang-builder images, which are published internally by OpenShift, and support newer Go versions
- Move dockerfile references over to the new image.
- Pull the images from arointsvc.
- Use dockerfile ARGs that are required when building with these new images.
- Confirmed that CI passes.
- Tested this change alongside ev2 changes to ensure that production builds will still work with these changes.
No
This PR was tested alongside https://msazure.visualstudio.com/AzureRedHatOpenShift/_git/ARO-Pipelines/pullRequest/12256781 to confirm that it will work in ev2 builds as well as CI builds.
=> *: use partner Go toolset, UBI9

cmd/aro/deploy.go, cmd/compareconfig.go, go.mod, pkg/deploy/config.go
A new initiative is moving ARO RP-Config to an Ev2 RA-style, which allows us to be much more succinct and makes new region build-out easier. This commit adds the capacity to load the new configuration file, if one is provided, and to error out if any difference is found. This behavior is configurable to allow a pipeline to be forced to run while a diff exists if there's an emergency.
A new command-line tool was added, as well, that diffs a directory of classic configurations with a directory of new-style ones, to ensure that there are no changes.
=> cmd: allow loading and comparing RA-style config

pkg/cluster/cluster.go, pkg/env/env.go, pkg/env/prod.go, pkg/util/mocks/env/env.go
https://issues.redhat.com/browse/ARO-16945
This small PR grabs correlation data from the cluster doc and passes it to `MsiDataplaneClientOptions` such that the correlation data is used for MSI dataplane client logs, making it easier to correlate those client logs to specific cluster installations.
Let me know if you see a cleaner way to pass the correlation data to the right place.
Tested in canary and confirmed that MSI dataplane logs now include correlation data.
If we have a TSG for MIWI cluster installation failures, we should update it to let readers know to search by correlation ID if they want to find MSI dataplane logs for a given CIF.
Tested in canary; also CI
=> Include correlation data in MSI dataplane client logs

.github/workflows/prune-tags.yml
Fixes ARO-14879
We have at least one tag in the repo that shares a name with a branch, so this commit makes the push more explicit for tags only. Git was refusing to delete any refs because the provided refspec matched more than one object.
n/a
No.
This change does not affect the RP running in production.
=> fix(prune-tags): explicitly delete to refs/tags

pkg/cluster/clustermsi.go, pkg/cluster/clustermsi_test.go, pkg/cluster/delete.go, pkg/cluster/delete_test.go
Fixes https://issues.redhat.com/browse/ARO-17110
- MSI certs are required to refresh federated identity credentials on MIWI clusters and have a valid lifespan of 90 days.
- We are working on a credential refresher which will run in in an AKS cluster and refresh these automatically before expiration, but as a stop-gap we also want to refresh them in case they expire or are eligible for a refresh and an update / adminUpdate is ran, so that subsequent update steps that require valid MSI certs don't fail.
- Create, update, delete, with expired and eligible MSI certs to confirm they were refreshed
=> Refresh MSI certs on update, adminUpdate if eligible for rotation

pkg/monitor/cluster/podconditions.go, pkg/monitor/cluster/podconditions_test.go
Fixes [ARO-7793](https://issues.redhat.com/browse/ARO-7793)
Add the reason for last termination state of pods stuck in waiting state as a dimension in pod.containerstatuses metric. The value of this field could further be used to segregate pod failures such as `OOMKilled`.
- Unit tests
- CI/CD 
- Canary
=> Enhance pod.containerstatuses metric to include lastTerminationState of failed pods

pkg/util/version/const.go
Fixes https://issues.redhat.com/browse/ARO-17293
- This PR bumps the fluentbit base image versions
- This is needed to be compliant to Microsoft policies and avoid any POAMS
Test results are attached in JIRA ticket
NA
We will Test with a cluster creation in Canary eastus2euap and also checking if the Canary VMSS is forwarding logs proplerly. Receiving expected logs in Dgrep
=> Bumping up fluentbit image

test/e2e/setup.go
Clusters from prior E2E runs sometimes remain stuck in the Deleting state, especially when reusing the same cluster name. This causes subsequent runs to fail during setup with a 400 RequestNotAllowed error when trying to create the same cluster.
- Added  pre-check + retry loop in setup.go so we don’t race on a leftover Deleting cluster
- fail early if deletion never completes within 5m
Fixes  [ARO-4483](https://issues.redhat.com/browse/ARO-4483)
Clusters from prior e2e runs can be stuck in `Deleting` state. This causes new test runs to fail if the cluster name hasn't been fully cleaned up. This PR adds logic to detect that case, retry up to 5 minutes, and fail fast if it doesn’t clear.
N/A
=>  Wait for cluster deletion before retrying Create in e2e setup

python/az/aro/azext_aro/custom.py
Fixes [ARO-17762](https://issues.redhat.com/browse/ARO-17762)
In #4155, we updated our handling of worker profile enrichment to skip propagating values for the subnet or other fields if we consider a machineset "invalid" (has no ready machines). 
The Azure CLI ARO module unfortunately does not filter these out, and cluster updates will fail as a result, including if a cluster has a machineset that's simply scaled to 0 members. 
This PR filters such "empty" subnets from _just_ the workerprofilesstatus field. We still want to fail cluster create operations if the initial passed-in master/worker subnets, which are propagated on the workerprofiles field, are invalid or missing. 
- Ensured that `az aro update --refresh-credentials` fails against a cluster with an empty machineset on ARO-RP …
=> CLI: Do not include 'missing' subnets in workerprofilestatuses in network resource handling

docs/deploy-development-rp.md
Fixes: Fixes [ARO-16119](https://issues.redhat.com/browse/ARO-16119)
This PR adds documentation for two existing admin endpoints (`/top/pods` and `/top/nodes`) that allow developers to fetch pod and node metrics from a locally running RP. These are helpful for debugging and performance analysis of OpenShift clusters during development.
- Verified that both endpoints return data when called against a locally running RP using `curl`.
- Used known cluster values and confirmed responses were formatted correctly with `jq`.
- This PR directly updates `docs/deploy-development-rp.md`.
- The endpoints already exist and are being used internally.
- This PR only updates documentation and does not affect runtime behavior.
=> Add top pods and nodes admin endpoints to local RP doc

pkg/util/log/audit/otel_audit.go
Right now, the Otel Audit logs error `Portal - Error sending audit message: identity is required: validation error` whenever an identity or description is not set. We need to set these values to default "unkown" value when these values are not set or available from the incoming request.
Here is the [reference](https://github.com/microsoft/go-otel-audit/blob/cdfeea399bd85d6af31e8178c59a78e838e0aabc/audit/msgs/msgs.go#L468) to code that's handling validation from go-otel-audit
Set the values to default "unkown" value when these values are not set or available from the incoming request.
- existing E2E and unit tests
No
=> Set the identity and description to "Unkonw" when empty

cmd/aro/mirror.go, pkg/mirror/mirror.go
Fixes ARO-17788
Mirror logging is too verbose and Ev2 truncates it.
- Suppress the per-image log message by changing it's log level to `debug`.
- Print a summary at the end of how many images were mirrored per version.
Local testing (done).
Test [mirroring in INT](https://msazure.visualstudio.com/AzureRedHatOpenShift/_build/results?buildId=126148575&view=logs&j=9869a09b-f8ba-573a-fac8-26a599004c05). [Success](https://ev2portal.azure.net/#/Rollout/AROMirrorImage/27e2b6ae-a80b-4c1e-9350-e1d76f32a0a9?RolloutInfra=Test)
Tested both locally and to mirror INT.
=> mirror: Improve logging

Makefile
Makefile: add a target to run the auto-fixer
The --fix argument to the linter will automatically update the AST where
possible to make the codebase conformant.
Signed-off-by: Steve Kuznetsov <stekuznetsov@microsoft.com>
---
=> Makefile: add a target to run the auto-fixer

cmd/aro/mirror.go
No Jira
- Mirror the newly available OCP ART Golang-builder image for Go 1.24 so that we can update ARO-RP to 1.24 when we're ready.
- Run the mirroring pipeline in INT using this PR
=> Mirror Go 1.24 builder images

pkg/portal/middleware/panic.go, pkg/portal/middleware/panic_test.go
Fixes ARO-17565
Go 1.11 introduced a sentinel panic value `ErrAbortHandler` that `ReverseProxy` throws when a connection is aborted. This panic is intended to suppress backtrace logging. This PR skips logging a backtrace when the error is `ErrAbortHandler`.
See https://pkg.go.dev/net/http#ErrAbortHandler
Unit test added
No
Unit test, e2e.
=> middleware: suppress panic logging when it's an http.ErrAbortHandler sentinel value

python/az/aro/azext_aro/_validators.py, python/az/aro/azext_aro/tests/latest/unit/test_validators.py
[ARO-4400](https://issues.redhat.com/browse/ARO-4400)
This is a small PR that updates `_validators.py`'s `validate_enable_managed_identity` function to no longer check the `–version` argument
During preview development, ARO still supported some OCP versions that were not compatible with MIWI. By the time the stable release of MIWI will roll out, ARO will only support MIWI-compatible OCP versions (4.14.38 or newer, 4.15.35 or newer, any 4.16 or newer y version).
I tested for platform workload identity replacement using `az aro update --assign-platform-workload-identity` and was able to replace a few identities.  
no
=> update validate_enable_managed_identity function to no longer check the --version argument

.github/CODEOWNERS
Removes @bitoku who has moved to OCP
Adds @pepedocs
=> Update CODEOWNERS for Jun 25

pkg/operator/flags.go
Fixes [ARO-13325](https://issues.redhat.com/browse/ARO-13325)
Defaults to having the monitoring controller in the ARO operator to off. This will allow ARO cluster administrators to enable persistence for the core monitoring stack. 
Installed cluster, ran operator locally with flag set.
Externally yes
Tested on development cluster
=> Default monitoring enabled flag to false

.gitignore, pkg/cluster/tls.go, pkg/util/azureclient/azuresdk/azcertificates/helpers.go, pkg/util/azureclient/azuresdk/azcertificates/helpers_test.go
Fixes ARO-11589
In some cases, we are facing Failure that have status `FailedCanRetry`. In those cases, it is better to consider it as `inProgress` to continue trying until eventual timeout, instead of just exiting with an error.
I did my best to try to face those `FailedCanRetry`, but was not able...
NA
In best cases, we will have situation where we have `FailedCanRetry` that will be retied and complete after some time, and in worst cases, we will reach the 15 timeout and have install failure arriving later, but we will have re-tried...
=> [ARO-11589] consider failed operation that can retry as not an error, but as if inProgress

hack/devtools/deploy-shared-env.sh, pkg/deploy/assets/rp-development.json, pkg/deploy/generator/templates_rp.go
During investigation of [ARO-14166](https://issues.redhat.com/browse/ARO-14166) we saw that rp-development template was broken with a missing defined parameter which was used in the template.
This PR will fix the broken PR adding the param in the template and also pass the param from deploy-shared-env functions
Run the deploy_rp_dev with new param
No, this does not change way deploy_rp_dev function is called
Not used in production.
=> fix rp-development template with missing param

pkg/operator/controllers/subnets/subnet_controller_test.go, pkg/operator/controllers/subnets/subnet_nsg.go, pkg/operator/controllers/subnets/subnet_serviceendpoint.go, pkg/operator/controllers/subnets/subnets_controller.go
Card https://issues.redhat.com/browse/ARO-12537 
Migrates the outdated client Manager for the subnet to use armnetwork.
Unit tests and e2e
No. Tech debt
=> Migrate from subnet.Manager to use armnetwork.SubnetsClient

pkg/portal/ssh/proxy_test.go, pkg/portal/ssh/ssh.go, pkg/portal/ssh/ssh_test.go
Fixes ARO-18925
We have better SSH algorithms available to us. Specifying all of them on the ssh command line allows us to target testing for a specific set of algorithms. This PR updates the portal's ssh command line that it presents for the user to copy-and-paste into their terminal with all the algorithms specified.
Manual testing was done from the SAW using git-bash's ssh, to a dev portal. Note that the current prod portals don't support mlkem768x25519-sha256 yet, this will come with the update to go 1.24.
Proxy tests were also updated to use these same algorithms, and new tests were created to verify that unsupported algorithms fail as expected.
=> portal: ssh: specificy various algorithms on the command-line

python/az/aro/azext_aro/_client_factory.py
Fixes ARO-20029
Fixes a multi-argument-to-kwargs situation with newer autorest generated clients.
See: https://github.com/Azure/azure-cli-extensions/blob/bdb16f761c89242c80959dae1b60639167e7f42a/src/aosm/azext_aosm/_client_factory.py#L15 
Unit tests
N/A
N/A
=> [ARO-20029] Fix az aro dev client on newer autorest/az CLI

pkg/api/v20191231preview/openshiftcluster_validatestatic_test.go, pkg/api/v20200430/openshiftcluster_validatestatic_test.go, pkg/api/v20210901preview/openshiftcluster_validatestatic_test.go, pkg/api/v20220401/openshiftcluster_validatestatic_test.go, pkg/api/v20220904/openshiftcluster_validatestatic_test.go, pkg/api/v20230401/openshiftcluster_validatestatic.go, pkg/api/v20230401/openshiftcluster_validatestatic_test.go, pkg/api/v20230701preview/openshiftcluster_validatestatic.go, pkg/api/v20230701preview/openshiftcluster_validatestatic_test.go, pkg/api/v20230904/openshiftcluster_validatestatic.go, pkg/api/v20230904/openshiftcluster_validatestatic_test.go, pkg/api/v20231122/openshiftcluster_validatestatic.go, pkg/api/v20231122/openshiftcluster_validatestatic_test.go, pkg/api/v20240812preview/openshiftcluster_validatestatic.go, pkg/api/v20240812preview/openshiftcluster_validatestatic_test.go, pkg/api/v20250725/openshiftcluster_validatestatic.go, pkg/api/v20250725/openshiftcluster_validatestatic_test.go
Fixes ARO-17423
Some API versions check the visibility of IngressProfiles[0]. When IngressProfiles is empty this fails with a boundsError. Now we skip this validation when IngressProfiles is empty, because it will fail validation later with "There should be exactly one ingress profile."
Added unit tests to replicate the issue.
No, bug fix
Unit tests + e2e
=> Fix bounds error validating network profile when IngressProfiles is empty

pkg/operator/controllers/muo/staticresources/muo_monitoring_interactor_role.yaml, pkg/operator/controllers/muo/staticresources/muo_monitoring_interactor_rolebinding.yaml, pkg/operator/controllers/muo/template_test.go
https://issues.redhat.com/browse/ARO-20112
Adds RBAC that was added to MUO here:
https://github.com/openshift/managed-upgrade-operator/commit/8c1047d2c7eadbfd5a64a2e31b9a9bd4098a43ba
Since this was added directly to the `olm-artifacts-template.yaml`, this was missed by ARO when updating the RBAC used by MUO. 
OSD operators, like MUO, are deployed by OLM. Resources in the `deploy/` directory get rolled up into the OLM bundle. However, the OLM bundle can only deploy a limited number of CRD types, and with those that it can deploy, it is limited to only deploying things within the namespace of the operator the OLM bundle is deploying. So for anything that does need to be applied as part of the operator, but that is either outside of the allowed CRDs or the namespace constraints of OLM, in …
=>  Add missing RBAC for MUO to create a serviceaccount token for openshift-monitoring

test/e2e/setup.go
Fixes blocker for [ARO-20197]
Fixes prod E2E by not requiring the admin API in the before checks
It is tests :)
N/A
N/A
=> [ARO-20197] Move e2e hive check to use liveconfig instead

.github/CODEOWNERS
N/A
Remove me from CODEOWNERS. I haven't been actively reviewing things here in a bit, and in an emergency situation I can use JIT admin access to merge things.
No testing required. GitHub configuration change.
N/A
GitHub will let us know if the CODEOWNERS file is invalid.
=> Remove cblecker from codeowners

pkg/hive/resources.go, pkg/hive/resources_test.go, pkg/util/pullsecret/pullsecret.go
Fixes https://issues.redhat.com/browse/ARO-20277
Removes the user pullsecret from the pullsecret for the Hive Installer pod, since it isn't used at all and can cause decoding errors.
E2E, since that installs via Hive now, to ensure it doesn't break the existing functionality
N/A
E2E
=> [ARO-20277] Don't use the user pullsecret to pull the Installer container

pkg/cluster/deploybaseresources.go, pkg/cluster/deploybaseresources_additional.go, pkg/cluster/deploybaseresources_test.go
Fixes https://issues.redhat.com/browse/ARO-20202
Tech debt
Covered in UT and E2E
tech debt
This is part of cluster creation and is covered in E2E tests
=> ARO-20202 - get rid of deprecated mgmt network cilent in deploybaseresources.go and deploybaseresources_additional.go

pkg/api/admin/openshiftcluster.go, pkg/api/openshiftcluster.go, pkg/api/validate/vm.go, pkg/api/validate/vm_test.go
https://issues.redhat.com/browse/ARO-20556
Adds support for Lsv4 instance types for worker nodes in 4.19+
Installing 4.19 and 4.18 with specifying the various versions
Yes, customer facing docs
Trying installs of 4.18 and 4.19 clusters
=> Add Lsv4 instance types

pkg/cluster/delete.go, pkg/cluster/delete_test.go
https://issues.redhat.com/browse/ARO-20784
See error message from RP:
```
failed to format managed identity credentials for storage: assumption violated, "NotAfter" was nil
```
(May also be some other property of the cred object, like "NotBefore")
I was able to reproduce the error using a test cluster in southeastasia with the following steps:
1. Create MIWI cluster with Bicep by following instructions at https://learn.microsoft.com/en-us/azure/openshift/howto-create-openshift-cluster?pivots=aro-az-bicep
2. Delete the cluster's MSI certificate from the aro-$LOCATION-msi Key Vault in the AME tenant
3. Delete the cluster managed identity
4. Attempt to delete the ARO resource; it will get blocked on this error
I gathered from the Slack thread where the issue came up that cluster MSI had been …
=> Bug fix - MIWI cluster deletion blocker

.github/workflows/ci-go.yml
No JIRA
https://github.com/Azure/ARO-RP/pull/4304 bumped the golangci-lint version to v2.2.1 - we need to do the same in github actions so that PR CI completes successfully.
- Green CI :)
=> Bump golangci-lint to v2.2.1 in github actions

pkg/api/openshiftcluster.go, pkg/cluster/deploybaseresources_additional.go, pkg/cluster/deploybaseresources_additional_test.go, pkg/cluster/deploybaseresources_test.go, pkg/cluster/validate.go, pkg/cluster/validate_test.go, pkg/util/pointerutils/pointerutils.go
Fixes ARO-20979
Fixes creation of UDR clusters by moving the zones param into the general properties. This is generally where we should keep it anyway.
Unit tests
N/A, doesn't have a matched exposed public API
It's simpler than what was there before :)
=> Fix creation of UDR clusters

pkg/api/admin/openshiftcluster.go
Fixes ARO-17997
The JSON struct tag for `Identity` in the admin API is not currently in sync with the public API. This brings them into alignment.
- Unit tests pass
- e2e passes
No
=> Align identity struct tags in admin API with public APIs

pkg/monitor/cluster/cluster.go, pkg/monitor/cluster/clusterwideproxystatus.go
Fixes panic in monitor dereferencing a nil pointer.  
Don't panic, check for nil beforehand.
=> monitor: check that the subnet response doesn't include a nil properties

test/e2e/fix_etcd.go
Fixes https://issues.redhat.com/browse/ARO-11486
It adds a new E2E Regression test that:
1. Temporary disables reconciliation
2. Checks if there are guardrails preventing machines to be deleted, and disables them if necessary
3. Deletes first master machine
4. Enables operators
5. Recreates Machine
6. Waits for new Etcd pod
7. Runs the fix
8. Waits until operators recover from degraded
9. Enables back guardrails if necessary
As with the [PR that fixed the action](https://github.com/Azure/ARO-RP/pull/4358), this is heavily based on https://github.com/Azure/ARO-RP/pull/4034
I ran this E2E test on a local cluster, I used the following commands:
```
make e2e-test
./e2e.test -test.v --ginkgo.vv --ginkgo.timeout 180m --ginkgo.flake-attempts=2 --ginkgo.junit-report=e2e-report.xml …
```
=> E2E for FixEtcd Geneva action

pkg/monitor/azure/nsg/nsg.go, pkg/monitor/cluster/cluster.go, pkg/monitor/cluster/cluster_test.go, pkg/monitor/cluster/errors.go, pkg/monitor/dimension/const.go, pkg/monitor/hive/errors.go, pkg/monitor/hive/hive.go, pkg/monitor/hive/hive_test.go, pkg/monitor/monitoring/errors.go, pkg/monitor/monitoring/interface.go, pkg/monitor/worker.go, pkg/monitor/worker_test.go, pkg/util/stringutils/stringutils.go, pkg/util/stringutils/stringutils_test.go
Fixes ARO-21181
Adds panic-catching code in various parts of the monitor. Panics at the top monitor-level now emit the failed worker metric, panics in individual collectors will instead be included like any other error and allow the other collectors to run.
Unit tests to cover the new code.
N/A
Tests :)
=> [ARO-21181] Fix panics taking down the Monitor

pkg/cluster/adminupdate_test.go, pkg/cluster/install.go
Fixes No Jira
- During a certificate renewal we should also be checking MIWI clusters for MSI certs in KV that may be eligible for renewal as they only last 90 days. We currently already do this on full update or adminUpdate - let's add it for certificate renewal task as well.
- Unit testing should be sufficient.
No
=> Run ensureClusterMsiCertificate during MaintenanceTaskRenewCerts
