- pkg/frontend/frontend.go
The swagger schema for cluster put and patch says that we should return body
> Makes put and patch handlers return body again

- pkg/util/dns/dns.go
If DNS was deleted because backend went dark, this will be not found and `rs` = nil
> nil dns error

- pkg/frontend/frontend.go
- pkg/frontend/frontend_test.go
> Adds a test to ensure URL paths are lower case

- python/az/aro/azext_aro/_validators.py
Current CLI is not working when passing `--client-id` and `--client-secret`
`az aro create -g "$RESOURCEGROUP" -n "$CLUSTER" --vnet dev-vnet --master-subnet "$CLUSTER-master" --worker-subnet "$CLUSTER-worker" --client-id "<ID>" --client-secret "<Secret>"`
```bash
cli.azure.cli.core.util : Must specify --client-id with --client-secret.
```
> CLI - Wrong validation when client-id and client-secret used

- deploy/rp-development.json
- deploy/rp-production.json
- pkg/deploy/rp.go
- pkg/env/env.go
- pkg/env/prod.go
- pkg/env/test.go
- pkg/util/azureclient/mgmt/network/virtualnetworks_addons.go
- pkg/util/privateendpoint/privateendpoint.go
- pkg/util/privateendpoint/privateendpoint_test.go
note: we already know the rp-pe-subnet piece has to be reworked in the short term to overcome the Azure 1000 PE/vnet limit
> Fix broken vnet detection logic

- Makefile
On macOS username != group usually. This change makes the make target platform agnostic
> Fixes make client for macOS users

- pkg/util/immutable/immutable.go
- pkg/util/immutable/immutable_test.go
Prevents `panic: reflect: call of reflect.Value.Type on zero Value` when a map has same length, but keys do not match.
> Fixes immutable validation for map

- Makefile
I believe two $ are needed as per GNU Make documentation:
`... the variable you want to reference is a make variable (use a single dollar sign) or a shell variable (use two dollar signs)`
https://www.gnu.org/software/make/manual/html_node/Variables-in-Recipes.html
on my system without this fix, it is expanded as `sudo chown -R : pkg/client python/client`
> Fix chown in make client recipe

- .pipelines/ci.yml
Looks like GH / MS changed the way python is installed on the hosted agent.
This could be related? https://github.com/actions/virtual-environments/issues/302
+1 on having our own agents to have better control on what's installed and wherein the machine ;)
Fixing #139
> Fix CI - Add symlink for python path to keep makefile structure

- docs/deploy-development-rp.md
libassuan is another dependency not installed by default on Fedora
> Docs update - libassuan

- deploy/rp-development.json
- deploy/rp-production.json
- pkg/deploy/rp.go
- pkg/env/env.go
- pkg/env/prod.go
- pkg/env/test.go
- pkg/util/privateendpoint/privateendpoint.go
- pkg/util/privateendpoint/privateendpoint_test.go
added a separate static vnet for PEs
added peerings between RP and PE vnets
changed PE creation - PEs should now be created in the PE vnet.
I'm not sure if modifying the env (pkg/env) definition is the right way to go, or if I should hard code the pe vnet name for now.
> Separate vnet for PEs

- pkg/install/1-installresources.go
Reorders two dependencies in the resource installer ARM template to be consistent with another reordering, as described in the following comment: https://github.com/Azure/ARO-RP/pull/151/commits/2488c3d5010b4812791c45c279d3ec209c71de3b#r377766135
> Order ARM dependencies consistently

- pkg/api/v20191231preview/openshiftcluster_validatestatic.go
- pkg/util/immutable/immutable.go
- pkg/util/immutable/immutable_test.go
With the new approach to #145, circular imports are not longer an inssue (for now at least), but I think it will be nice to get rid of unnecessary dependencies in `pkg/util/immutable`.
> Removes unnecessary dependencies from immutable

- pkg/api/register.go
- pkg/api/v20191231preview/openshiftcluster_validatestatic.go
- pkg/api/v20191231preview/openshiftcluster_validatestatic_test.go
- pkg/api/v20191231preview/register.go
- pkg/api/validate/openshiftcluster_validatedynamic.go
- pkg/frontend/frontend.go
- pkg/frontend/openshiftcluster_putorpatch.go
- pkg/frontend/openshiftcluster_putorpatch_test.go
- pkg/frontend/openshiftclustercredentials_post_test.go
Moves dynamic validator to a shared location so we don't have to duplicate it in each API version.
> Validator refactoring to allow better reusability between API versions

- .pipelines/ci.yml
This should missing the go generate step when it comes to generated Go code and deploy/*.json files.
> Added validation for generated files

- deploy/rp-development.json
- deploy/rp-production.json
- docs/prepare-a-shared-rp-development-environment.md
- pkg/deploy/rp.go
The preferred image for this VM would be one that doesn't have any operating system, however I'm not sure if there has to be an active DHCP lease to keep the PE Vnet running correctly.
The credentials installed on the VM are the minimum required, I deleted the private key matching the generated public key. There is no way to ssh into that Virtual Machine.
Context:
A running VM is required in a vnet to make it active and to make PEs accessible.
> Adding dummy VM to make PEs work in a separate vnet.

- pkg/api/admin/openshiftcluster_validatestatic_test.go
A tiny thing: I was initially going to use `time.Now()`, but changed my mind. There is no need in the `AddDate` call since we provide a specific date in the test.
> A tiny update in openshiftcluster_validatestatic_test.go

- deploy/rp-production-parameters.json
- deploy/rp-production.json
- pkg/deploy/rp.go
* Function now requires a vmssName but prefixes `rp-vmss-` to vmssName if it is a production cluster
> Add parameter to vmss to deploy with vmss name

- pkg/install/consolebranding.go
- pkg/install/disableupdates.go
- pkg/install/install.go
- pkg/install/ipadresses.go
- pkg/install/tls.go
- pkg/install/waitforconfigmap.go
Refactoring to make Kubernetes clients part of `Installer` struct, rather than create them in multiple places throughout the install. This will allow easier mocking when writing unit tests in the future.
> Move k8s clis to Installer to allow unit tests

- pkg/install/1-installresources.go
allows restarts of the cluster creation process. Previously ARM templates had a conflict on the autogenerated LB rules.
> WIP: explicitly empty Load Balancer rules and Probes in the "aro" LB

- hack/rhcos-sas/rhcos-sas.go
- pkg/backend/openshiftcluster/create.go
- pkg/backend/openshiftcluster/delete.go
- pkg/install/0-installstorage.go
- pkg/install/1-installresources.go
- pkg/install/install.go
- pkg/install/ipadresses.go
- pkg/install/removebootstrap.go
- pkg/util/log/log.go
- pkg/util/stringutils/stringutils.go
- pkg/util/stringutils/stringutils_test.go
Adds a new utility function for getting the last token in a string `s` after it is split by a separator `sep`.
This function abstracts a very commonly used pattern in this repo. Switching to this function would enhance readability by reducing the width of some lines by up to 35%.
The function is named `LastTokenByte` to differentiate it from another possible function which might accept a string or `func(rune) bool` argument, following the convention used in the `strings` package.
> Add LastTokenByte func

- cmd/aro/rp.go
- pkg/api/openshiftcluster_test.go
- pkg/frontend/frontend.go
- pkg/frontend/ready_get.go
- pkg/frontend/security_test.go
Add /live endpoint to Frontend. 
It will aggregate data from backend manager to advertise if backends are still live/active or we can shut down fully. 
This enabled easier determination if we can kill RP or still need to wait a bit.
> add healthz endpoint and shutdown order

- pkg/api/openshiftclusterdocument_example.go
- pkg/api/v20191231preview/openshiftcluster_example.go
- pkg/api/v20191231preview/openshiftcluster_validatestatic_test.go
* Makes tests to not rely on examples. Currently changes in examples can cause tests to fail. Hopefully without dependency on examples there will be less false positives.
* Also changes examples structure: `pkg/api` now has an examole of `OpenShiftClusterDocument` with the `OpenShiftCluster` field populated. Specific API versions can now convert this (internal) model into their representation.
> Updates API examples and tests

- pkg/install/1-installresources.go
- pkg/install/1-installresources_test.go
- Moves code for getting zones into own unit-tested function.
- Moves template creation and deployment logic up in scope (out of block) and simplifies return (currently it returns `err` if it's not nil, otherwise returning `nil`... can just return `err`).
- Most of the changes are indent-related, hence the suggestion to hide whitespace changes below.
> Test zone config

- pkg/api/admin/openshiftcluster.go
- pkg/api/admin/openshiftcluster_validatestatic_test.go
- pkg/api/openshiftcluster.go
- pkg/api/openshiftclusterdocument_example.go
- pkg/api/zz_generated_installphase_enumer.go
- pkg/install/install.go
- Consolidates `InstallPhaseDeployStorage` and `InstallPhaseDeployResources` into `InstallPhaseBootstrap` ("Bootstrap" in the name is a verb)
- Reason: https://github.com/Azure/ARO-RP/issues/106
- `startInstallPhase` renamed to `startInstallation`
- Reason: It is not called at the start of each phase
- `endOfInstallPhase` renamed to `finishInstallation`
- Reason: It is not called at the end of each phase
> regroup steps into 2 phases; more accurate names

- Makefile
- docs/deploy-development-rp.md
- hack/get-admin-kubeconfig.sh
- pkg/api/openshiftcluster.go
- pkg/install/0-installstorage.go
- pkg/install/kubeconfig.go
- pkg/install/kubeconfig_test.go
- pkg/util/pem/pem.go
- pkg/util/restconfig/restconfig.go
This is a re-make of https://github.com/Azure/ARO-RP/pull/250
It stores a new context for aro-service in a separate file as requested. 
It doesn't create additional role binding. 
I wasn't able yet to confirm that we can distinguish between the two identities in the audit logs. I've checked `/var/log/openshift-apiserver/audit.log` on all masters, but haven't found any action done by any of them (maybe we need to update audit policy to include these actions?)
Since we don't want to leverage kubeconfig context to manage context, we will need to either 
1. decide that `aro-service` kubeconfig is the admin kubeconfig we (as SRE team) are always using and ignore the default admin kubeconfig entirely.
2.  or manage multiple files ourselves and make sure KUBECONFIG points to the right place.
> Add new cluster admin kubeconfig for aro service

- pkg/genevalogging/genevalogging.go
Setting the values in the mdsd pod for QoS.  If left empty a best-effort policy is applied.  If defined then it can be either burstable or guaranteed.  This sets the values to burstable.  We need this setting applied to pass the upstream origin test suite.
Specific test:
```
"[Feature:Platform] Managed cluster should ensure control plane pods do not run in best-effort QoS [Suite:openshift/conformance/parallel]"
```
@jim-minter @JackQuincy Any ideas on the proper settings for this pod?  I uncommented the settings that were existing.  I attempted a higher CPU value (`500m`) as a test but received the following error: 
```
<unknown>   Warning   FailedScheduling   pod/mdsd-ll7rf   0/6 nodes are available: 1 Insufficient cpu, 5 node(s) didn't match node selector.
```
fixes #324
> Setting limits and requests for mdsd

- pkg/backend/openshiftcluster/delete.go
Fix billing ordering
@jim-minter @julienstroheker If deploy fails in first 2 phase, cluster is stuck in deleting phase as `Delete` can't complete due to :
```
INFO[2020-03-26T09:59:33Z]pkg/backend/openshiftcluster/delete.go:109 openshiftcluster.(*Manager).Delete() updating billing record with deletion time    component=backend correlation_id= resource_group=v4-eastus resource_id=/subscriptions/225e02bc-43d0-43d1-a01a-17e584a4ef69/resourceGroups/v4-eastus/providers/Microsoft.RedHatOpenShift/openShiftClusters/mjudeikis resource_name=mjudeikis subscription_id=225e02bc-43d0-43d1-a01a-17e584a4ef69                                                                                                         
ERRO[2020-03-26T09:59:34Z]pkg/backend/openshiftcluster.go:140 …
```
> Billing failure fix

- .pipelines/deploy-azure-env.yml
- .pipelines/int-release.yml
- .pipelines/prod-release.yml
- .pipelines/templates/template-job-deploy-azure-env.yml
* making location and environment parameters for deploy-azure-env.yml.  Environment seems to have to be passed as a parameter rather than a variable.
* standardising to camelCase rather than using_underscore for parameter names - spotting the difference between hyphens and underscores is confusing.
* renamed aro_v4_ci_devops_spn -> azureDevOpsJSONSPN to match other pipelines
> fixes and standardising some pipelines

- .pipelines/templates/template-job-deploy-azure-env.yml
error was `Job Deploy eastus2 has an invalid name. Valid names may only contain alphanumeric characters and '_' and may not start with a number.`
> fix job deploy name error

- pkg/database/billing.go
- pkg/util/mocks/database/database.go
We need to provide the time value to update `LastBillingTime`. Unlike `CreationTime` and `DeletionTime`, this value will not be generated using current time. The billing service will specify the time which needs to be set for `LastBillingTime`.
> Adding time to update lastbillingtimestamp

- pkg/database/openshiftclusters.go
- pkg/util/mocks/database/database.go
Dumping the whole DB at once into RAM is maybe a bad idea
/cc @jim-minter
> Remove ListAll DB methods

- pkg/api/validate/openshiftcluster_validatedynamic.go
- pkg/backend/openshiftcluster/create.go
- pkg/backend/openshiftcluster/openshiftcluster.go
- pkg/backend/openshiftcluster/update.go
- pkg/frontend/frontend.go
- pkg/frontend/openshiftcluster_putorpatch.go
- pkg/frontend/openshiftcluster_putorpatch_test.go
- pkg/install/0-installstorage.go
- pkg/install/1-installresources.go
- python/az/aro/azext_aro/custom.py
* move dynamic validation to the backend in order to let it retry CSP AAD authentication for longer
* retry CSP AAD authentication in installer as well.  This is is needed because this step will be brought forwards in #363
> Cluster SP authentication fixes and deny assignment

- pkg/install/0-installstorage.go
The goal is to avoid the following:
The client 'xxx' with object id 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx' has permission to perform action 'Microsoft.Network/virtualNetworks/write' on scope '/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/xxx/providers/Microsoft.Network/virtualNetworks/xxx'; however, it does not have permission to perform action 'Microsoft.Network/networkSecurityGroups/join/action' on the '0' linked scope(s) '' or the linked scope(s) are invalid and is blocked by deny assignments on the '2' linked scope(s) '/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/aro-xxx/providers/Microsoft.Network/networkSecurityGroups/aro-controlplane-nsg,/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/aro-xxx/providers/Microsoft.Network/n …
> Try relaxing deny assignment

- pkg/install/0-installstorage.go
otherwise cluster deploys fail with code DenyAssignmentExists, message "Custom deny assignment with the same name xxx already exists."
> make deny assignment name globally unique

- pkg/monitor/cluster/cluster.go
- pkg/monitor/cluster/healthz.go
- pkg/monitor/cluster/nodes.go
- pkg/monitor/cluster/nodes_test.go
- pkg/monitor/worker.go
Emit metrics for each possible node condition.
Emit metrics for each condition only if the number of nodes expressing this condition is more than 0 - this is by requirement.
Treating "unknown" status as an unhealthy status.
> Emit metrics for node conditions

- pkg/monitor/cluster/cluster.go
- pkg/monitor/cluster/nodes_test.go
- pkg/monitor/cluster/version.go
- pkg/monitor/cluster/version_test.go
This pulls in Olga's changes to the context and emits desired and actual version from the cluster.
> Emit cluster version metrics

- .pipelines/templates/template-deploy-shared-env.yml
- .pipelines/templates/template-push-images-to-acr.yml
- .pipelines/templates/template-run-rp-and-e2e.yml
- .pipelines/templates/template-setup-azure-tools.yml
- .pipelines/templates/template-setup-golang-env.yml
I added set -e to multiline scripts in the pipelines. I didn't add it when the only command is the last one in the script - but now I'm thinking about adding it everywhere  for consistency in case we extend any of the templates.
I set cleanup tasks to always run (even if a pipeline fails in the middle).
Are there any places where we don't want 
set -e (fail on the first command with non-zero exitcode)
set -u (fail on unset env variable)
set -o pipefail (fail on the first command in a line | of | pipes)
?
CC @julienstroheker
Related to issue #246
> Pipelines set -e

- pkg/genevalogging/genevalogging.go
If phase with scc operation is restart, this fails with "already exist error".
As currently we dont support configuration update and this code is used only in the "install" this should not try to update-if-exists.
> fix scc operation restart

- pkg/util/azureclient/apiversions.go
- pkg/util/azureclient/apiversions_test.go
Use LastIndexByte() so we remove the last entry in the path
The error was:
No registered resource provider found for location 'global' and API version '2019-07-01' for type 'privateDnsZones/virtualNetworkLinks'.
> Fix admin resources list

- pkg/frontend/admin_openshiftcluster_resources_list.go
- pkg/frontend/admin_openshiftcluster_resources_list_test.go
don't use the MarshalJSON provided by the Azure go library because it drops fields
> marshal all resource fields returned by geneva action

- Makefile
Python CI tests are failing because [`SkuNameEnum`](https://github.com/Azure/azure-sdk-for-python/blame/8f4553893913217673156e7c78a9c42a539ff684/sdk/loganalytics/azure-mgmt-loganalytics/azure/mgmt/loganalytics/models/__init__.py#L96) in the [Azure SDK for Python](https://github.com/Azure/azure-sdk-for-python), which is imported in [`log_analytics_workspace.py`](https://github.com/Azure/azure-cli/blob/8adf97355a605d147afc26f6c1b6f6afb6651c2f/src/azure-cli/azure/cli/command_modules/monitor/operations/log_analytics_workspace.py#L5) in the [Azure CLI](https://github.com/Azure/azure-cli), no longer exists as of [`azure-mgmt-loganalytics` 0.3.0](https://github.com/Azure/azure-sdk-for-python/commit/dcee774851b7306563c85f255a4b71e30723d294#diff-39b89ae5851a1af2106297e15b96dd82L96).
To temporarily …
> Temporarily pin azure-mgmt-loganalytics to 0.2.0

- docs/deploy-development-rp.md
- pkg/api/admin/register.go
- pkg/api/register.go
- pkg/api/v20191231preview/openshiftcluster_validatestatic.go
- pkg/api/v20191231preview/openshiftcluster_validatestatic_test.go
- pkg/api/v20191231preview/register.go
- pkg/api/v20200430/openshiftcluster_validatestatic.go
- pkg/api/v20200430/openshiftcluster_validatestatic_test.go
- pkg/api/v20200430/register.go
- pkg/frontend/openshiftcluster_putorpatch.go
- pkg/frontend/openshiftcluster_putorpatch_test.go
- python/az/aro/HISTORY.rst
- python/az/aro/azext_aro/azext_metadata.json
- python/az/aro/azext_aro/custom.py
- python/az/aro/setup.py
for discussion - should we do this?
performance and scale testing suggests that incidence of problems is significantly reduced by using minimum Standard_D4s_v3.
> don't allow clusters to be created with Standard_D2s_v3 in prod -- too small?

- pkg/backend/backend.go
- pkg/backend/openshiftcluster.go
- pkg/backend/openshiftcluster/openshiftcluster.go
do this (a) because it is independent of any cluster; (b) to avoid making ListKeys calls more than necessary; (c) so that if it fails initialisation, RP startup fails
> move billing initialisation to backend

- docs/deploy-development-rp.md
because command group 'group deployment' is deprecated and will be removed in a future release. Use 'deployment group' instead.
> This command is implicitly deprecated

- pkg/database/openshiftclusters.go
- pkg/frontend/admin_openshiftcluster_list.go
- pkg/frontend/admin_openshiftcluster_list_test.go
- pkg/frontend/frontend.go
- pkg/util/mocks/database/database.go
See [Admin API list by region](https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/6098213).
Based on the public list clusters by subscription API call, but with a few differences because YAGNI?:
- no enrichment of the data for now
- no pagination for now (if we need that, unclear if we should be paginating here or on the admin actions backend)
Will attempt to write the backend C# code next so I can test e2e.
> Admin action for listing all clusters

- pkg/monitor/cluster/version.go
- pkg/monitor/cluster/version_test.go
at the moment "cluster desired versions" is incorrectly showing old values because monitoring does not honour spec.desiredUpdate.version
> honour spec.desiredUpdate.version in monitoring

- cmd/aro/rp.go
- pkg/frontend/admin_openshiftcluster_kubernetesobjects.go
- pkg/frontend/admin_openshiftcluster_kubernetesobjects_test.go
- pkg/frontend/admin_openshiftcluster_mustgather.go
- pkg/frontend/admin_openshiftcluster_upgrade.go
- pkg/frontend/admin_openshiftcluster_upgrade_test.go
- pkg/frontend/frontend.go
- pkg/frontend/kubeactions/mustgather.go
Adds logging to Must Gather Geneva Action and changes kubeaction instantiation to use a factory as suggested in [the original PR](https://github.com/Azure/ARO-RP/pull/470).
> Add logging to Must Gather

- pkg/install/deploystorage.go
- pkg/install/error.go
- pkg/install/install.go
Fixes https://github.com/Azure/ARO-RP/issues/398
Reimplements changes originally made in https://github.com/Azure/ARO-RP/pull/380, which will be rebased off of this, to make two more manageable PRs.
- Checks to see if graph already exists to avoid error caused by calling `Encrypt` twice if installation was interrupted during first phase.
- Only sets `doc.OpenShiftCluster.Properties.Install.Now` if it has not been set
- InstallPhaseBootstrap runs twice in development RP mode to help ensure that it remains restartable
[Diff with whitespace ignored](https://github.com/Azure/ARO-RP/pull/448/files?diff=unified&w=1)
> Make InstallPhaseBootstrap restartable

- Gopkg.lock
- pkg/api/error.go
- pkg/frontend/admin_openshiftcluster_kubernetesobjects.go
- pkg/frontend/admin_openshiftcluster_list.go
- pkg/frontend/admin_openshiftcluster_resources_list.go
- pkg/frontend/frontend.go
- pkg/frontend/validate.go
- vendor/github.com/gorilla/mux/go.mod
This is so we don't have to get huge results from "oc get" and grep for the values we want.
The following works nicely:
```
curl -k "https://localhost:8443/admin/<resourceID>/kubernetesObjects?kind=configmap&namespace=openshift-apiserver&filter=items\[:2\]" | jq "."
```
Note: requires #528
> Add jmespath "filter" option to admin kubernetes.List

- pkg/frontend/kubeactions/kubeactions.go
- pkg/frontend/kubeactions/kubeactions_test.go
Note: the apiresource object very seldom actually has .Group and .Version set.
From what I logged, it seemed like only a handful had them set.
The most consistently provided Group and Version is in the "apiresources"
object and in the form of GroupVersion that needs to be parsed out.
an example of an apiresources object is:
```
APIResourceList{
GroupVersion:machine.openshift.io/v1beta1,
APIResources:[]APIResource{
APIResource{Name:machines,Namespaced:true,Kind:Machine,Verbs:[delete deletecollection get list patch create update watch],ShortNames:[],SingularName:machine,Categories:[],Group:,Version:,StorageVersionHash:GLEf6/W/4xY=,},
APIResource{Name:machines/status,Namespaced:true,Kind:Machine,Verbs:[get patch update],ShortNames:[],SingularName:,Categories:[],Group:,Version:,StorageVersionH …
```
> Fix kubeactions.findGVR

- pkg/frontend/subscriptions_put.go
- pkg/frontend/subscriptions_put_test.go
Removes email from subscription doc on new request before submitting data to the db. 
If the PII already exists in DB it is not removed.
> Do not persist email information to database

- .pipelines/prod-release.yml
- pkg/backend/openshiftcluster/create.go
fixes #199
Now that we optionally allow an RH pull secret to be applied, we should keep the quay.io secret to fix #199.  That works around the fact that the cvo/samples operator/imagestreams do not honour ImageContentSources.
> don't trim quay.io secret from pull secret

- python/az/aro/azext_aro/_validators.py
- python/az/aro/azext_aro/custom.py
In attempt to address #549, I have normalized the `Public` and `Private` parameters for ingress and apiserver visibility to be forced to be capitalized.  This allows for `public`, `private`, `Public`, or `Private` to pass validation.
Fixes #549
> Allow visibility parameters to be lower or upper case in az cli

- pkg/api/validate/openshiftcluster_validatedynamic.go
- pkg/backend/openshiftcluster/delete.go
- pkg/install/deploystorage.go
also allow deleting a cluster where we never managed to connect to the subnet in the first place
> retry connecting to subnet in face of AuthorizationFailed errors

- pkg/monitor/cluster/cluster.go
reduced the loglevel of errors comming from monitoring functions, added a metric to track the errors.
ref #572
> monitoring func errors don't emit an Error level log anymore.

- pkg/frontend/admin_openshiftcluster_list.go
- pkg/frontend/admin_openshiftcluster_list_test.go
change the output
```
value:
- foo
- bar
```
to
```
- foo
- bar
```
It's a nit, but it makes the jmespath expression less un-obvious
> remove values wrapping object from list clusters json

- pkg/api/billingdocument.go
- pkg/util/billing/billing.go
- pkg/util/billing/billing_test.go
This PR adds InfraID property to billing document so that it can be used by billing service.
> Add InfraID to Billing Document

- pkg/frontend/frontend.go
- pkg/frontend/ready_get.go
- pkg/frontend/security_test.go
- pkg/monitor/monitor.go
- pkg/util/heartbeat/heartbeat.go
We saw a transient on upgrade where /healthz had indicated OK, so upgrade
proceeded, but the health *metric* had not yet indicated OK.  This caused a
false alarm on Geneva.
> ensure that our emitted health metrics match our /healthz behaviour

- pkg/monitor/worker.go
if a cluster goes from creating->create failed quickly, it can cause a
harmless monitoring goroutine NPE due to a missing nil check
> fix harmless monitoring traceback

- pkg/frontend/ready_get.go
As reported in issue #603, we are delaying up to two minutes to start the frontend which causes a failure.
As a work around, we only want to verify readiness when we are not in our development environment.  This should appease our CI.
Fixes #603
> Do not do the frontend checkReady on dev environment

- pkg/util/version/version.go
https://access.redhat.com/errata/RHBA-2020:1529
```
curl -s -H "Accept: application/json" https://api.openshift.com/api/upgrades_info/v1/graph?channel=stable-4.3 | jq '.nodes[] | select(.version == "4.3.18")'                                                      
{                                                                                                                                                                                                                                             
"version": "4.3.18",                                                                                                                                                                                                                        
"payload": …
```
> Update to 4.3.18

- pkg/install/deployresources.go
- pkg/install/loadbalancer.go
Move LB  probes to https.
Need to merge first: https://github.com/Azure/ARO-RP/pull/648
Replaces: https://github.com/Azure/ARO-RP/pull/625
Fixes: https://github.com/Azure/ARO-RP/issues/620
> Move probes from TCP to HTTPS 

- .pipelines/e2e-with-billing.yml
location parameter is a mandatory input when kick off a release run, pipeline scheduled run doesn't accept pipeline parameter which failed daily e2e. 
With this PR to set region in pipeline variable instead of pipeline parameter to fix daily e2e failure.
> remove location parameter

- python/az/aro/azext_aro/_rbac.py
- python/az/aro/azext_aro/custom.py
- python/az/aro/azext_aro/tests/latest/test_aro_scenario.py
**Why this PR is needed**
Reintroduce `uuid.uuid4()` as the GUID generator for role assignment.
The original reason for having the semistable GUID was the test replay stabilization.
It turned out that the replay can be stabilized much easier with the use of a mock interface and prepared mocked GUID generator.
Also, semistable GUID poses an issue when creating multiple assignments on the same vnet in multiple regions as reported in #670 
/cc @m1kola would you please do a review on this?
> Switch uuid5 back to uuid4 in az aro extenstion

- python/az/aro/azext_aro/custom.py
- python/az/aro/azext_aro/tests/latest/test_aro_helpers.py
https://github.com/Azure/ARO-RP/issues/671
> Add function generate_random_id to always start with lowercase letter

- pkg/install/upgrade.go
I might be doing something wrong but when searching through RP logs to try to figure out when an upgrade was initiated, I couldn't find a corresponding direct log line entry and had to guess which admin update it corresponded to. Perhaps this will make it more clear?
> Log when cluster upgrade begins

- pkg/monitor/monitor.go
- pkg/monitor/worker.go
it's set to false until the monitor successfully lists assigned buckets.
Fixes #548
> added isHealthy flag, changed monitor heartbeat

- pkg/env/dev.go
It now implements the `Dev` interface again which fixes interface assertions such as this:
https://github.com/Azure/ARO-RP/blob/cdbe75feeb35ce1a524832b661dc673206cb500e/cmd/aro/rp.go#L45-L60
> Fixes dev environment

- python/az/aro/azext_aro/custom.py
To enable pairing between cluster resource groups
and active directory application, this pr
switches application name from random to the
resource group name.
This enables the pairing.
/cc @mjudeikis 
> Switch from random app names to RG naming

- pkg/deploy/upgrade.go
minute is causing some of our alert noisiness.  Let's try a sleep and see
if that helps.
> maybe starting the new RP and stopping all the old ones in the same

- operator/generate.go
This PR fixes the output of the aro-operator clientset generated code.
I've noticed that `github.com/operator` has been added to my working directory. Looking closer I realised that the clientset have not been generated lately:
```
$ ls -la operator/github.com/
total 0
drwxr-xr-x. 3    19 Jun  2 15:24 .
drwxrwxr-x. 5   101 Jun  3 09:41 ..
drwxr-xr-x. 3    20 Jun  2 15:24 Azure
$ ls -la  pkg/util/aro-operator-client/clientset/
total 0
drwxrwxr-x. 3   23 May 29 14:31 .
drwxrwxr-x. 3   23 May 29 14:31 ..
drwxrwxr-x. 5   79 May 29 14:31 versioned
```
> Fix output location for clientset generated files

- test/e2e/e2e_test.go
- test/e2e/list.go
- test/e2e/operations.go
- test/e2e/scalenodes.go
- test/e2e/setup.go
- test/e2e/update.go
I see no reason why we need to export clients and logger in `setup.go`. Let's make it non-exported and export it again when/if we actually need it.
> Makes e2e clients to be non-exported

- pkg/monitor/worker.go
SubscriptionWarned powers off VMs, we shouldn't monitor clusters in such subscriptions.
> Removing monitoring of unpaid subscriptions.

- .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
With some inspiration from https://github.com/openshift/openshift-azure/pull/531 as well as the Kubernetes PR templates.
Goal of this change is to add a PR template that will ensure team members include sufficient context in their PRs for reviewers.
I'm not strongly attached to any particular bullet in this template (docs one is particularly aspirational) but these are the things I'd like folks to think about and submit for each PR.
> Add GitHub PR template

- pkg/util/clusterdata/worker_profiles_task.go
- pkg/util/clusterdata/worker_profiles_task_test.go
Fixes the following panic:
```
May 29 13:09:11 rp-52a6c99b-000000 docker[23476]: panic: runtime error: invalid memory address or nil pointer dereference
May 29 13:09:11 rp-52a6c99b-000000 docker[23476]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x2398718]
May 29 13:09:11 rp-52a6c99b-000000 docker[23476]: goroutine 174 [running]:
May 29 13:09:11 rp-52a6c99b-000000 docker[23476]: github.com/Azure/ARO-RP/pkg/util/clusterdata.(*workerProfilesEnricherTask).FetchData(0xc000bb2c40, 0xc000d90d20, 0xc000d90d80)
May 29 13:09:11 rp-52a6c99b-000000 docker[23476]:         /home/vsts/work/1/s/gopath/src/github.com/Azure/ARO-RP/pkg/util/clusterdata/worker_profiles_task.go:72 +0x478
May 29 13:09:11 rp-52a6c99b-000000 docker[23476]: …
```
> Fixes nil pointer dereference

- pkg/util/log/log.go
- pkg/util/log/log_test.go
currently we have some logs being logged with `.../resourceGroup/...` while others with `.../resourcegroup/...` (https://github.com/Azure/ARO-RP/blob/master/pkg/util/log/log.go#L101)
This makes Jarvis think of the same resource_id values as different ones, making it even more confusing for us.
> Convert resource_id string to lower case to match other places

- docs/deploy-development-rp.md
Since the RP logs are completely not readable, we need a convenient way to present them in a friendly way
> Add one-liner to parse RP logs to our docs

- .golangci.yml
- Makefile
- docs/testing.md
Configures golangci-lint with our existing linters + staticcheck (see https://github.com/Azure/ARO-RP/issues/765 ). This PR does not include running as a part of CI.
> Add golangci-lint configuration file and instructions to run it

- pkg/install/fixcloudconfig.go
- pkg/install/fixcloudconfig_test.go
- pkg/install/install.go
This PR appends AAD SP details to cloud-config.
This is needed to fix PVC panic, until cherry-pick lands. 
TODO:
> cloud config panic

- hack/e2e/run-rp-and-e2e.sh
- python/az/aro/azext_aro/_rbac.py
- python/az/aro/azext_aro/custom.py
If there are subnets that are associated to a routetable, ARO requires the `Microsoft.Network/routeTables/join/action`.  This allows us to properly clean up and disassociate subnets from routetables when a delete call is issued.
Fixes #425
> Attempt to update routetable permissions

- python/az/aro/azext_aro/_rbac.py
This caused the deployment in INT to fail.
The problem is we are using the wrong variable, it should be the loop
variable "rt" and not subnet.route_table.id
In the block above we carefully check subnet.route_table is not None but then use
it unguarded below. This patch changes to using the loop variable.
Not tested at all. It will be tested in the e2e and then in INT
> Fix assign_contributor_to_routetable

- .pipelines/build-and-push-images.yml
- .pipelines/ci.yml
- .pipelines/clean-e2e.yml
- .pipelines/deploy-dev-env.yml
- .pipelines/e2e-loop.yml
- .pipelines/templates/template-job-deploy-azure-env.yml
WIP - untill DS2 VMs are deployed in ARO-CI and ARO-E2E pools (I'm running the pipelines to do that now).
I'm not sure if I should use the ARO-Build agent pool in .pipelines/build-and-push-images.yml (and also add nodes there - it's empty right now) or just use the ARO-CI pool for that and adjust the scale set size based on the job queue.
cc @jim-minter, @julienstroheker
> changed the default vmImage: ubuntu-latest to agent pools.

- docs/deploy-development-rp.md
- docs/prepare-a-shared-rp-development-environment.md
- hack/devtools/deploy-shared-env.sh
- hack/e2e/run-rp-and-e2e.sh
Documentation and scripts that were using the commands that are implicitly deprecated.  Issue #326 
`NONE`
Resolves issue #326
> Az command changes in documentation and in E2E scripts 

- pkg/api/admin/openshiftcluster.go
- pkg/api/admin/openshiftcluster_convert.go
- pkg/api/admin/openshiftcluster_validatestatic_test.go
Reverts Azure/ARO-RP#808 (also see #853)
> Revert "Add RegistryProfile to admin API"

- pkg/install/deployresources.go
- pkg/install/deploystorage.go
- pkg/install/fixnsg.go
- pkg/install/fixnsg_test.go
- pkg/install/install.go
- pkg/install/loadbalancer.go
- pkg/install/nsg.go
- pkg/util/azureclient/mgmt/network/securitygroups.go
- pkg/util/azureclient/mgmt/network/securitygroups_addons.go
- pkg/util/mocks/azureclient/mgmt/network/network.go
Fixes ICM 194780831
Don't add *:6443 NSG rule to clusters with private API server, it's not necessary.
Remove *:6443 NSG from private production clusters on upgrade.
Ran a test deploy of a private API server cluster locally.
Validated that a Kubernetes admin GA curl call worked against the cluster.
Manually added :6443 rule to NSG
Ran an admin upgrade and validated that :6443 rule was removed.
Deleted cluster.
No.
> Don't configure :6443 NSG on private clusters

- pkg/install/upgrade.go
- pkg/install/upgrade_test.go
Fixes Inc 194950388
Currently, if the cluster is subscribed to the channel we do not upgrade. The cluster might be in the old version, as upgrade might be set to manual. This leave cluster behind. 
I think we still should upgrade those clusters to next release when we do our upgrades. 
This removes channel condition from the upgrade path. 
We will still check the version before upgrade. 
N/A
N/A
> Upgrade all clusters

- .pipelines/e2e-with-billing-all-regions.yml
- .pipelines/prod-release.yml
https://dev.azure.com/msazure/AzureRedHatOpenShift/_workitems/edit/7065227
This PR adds koreacentral to nightly tested regions in our E2E tests. It's a newly rolled out region.
None. This adds more tests.
None, just another region to test.
> adding koreacentral to nightly tests

- test/e2e/adminapi.go
- test/e2e/adminapi_cluster_get.go
- test/e2e/adminapi_cluster_update.go
- test/e2e/adminapi_kubernetesobjects.go
- test/e2e/adminapi_mustgather.go
- test/e2e/adminapi_redeployvm.go
- test/e2e/adminapi_resources.go
Partially fixes [Work item #6098209](https://dev.azure.com/msazure/AzureRedHatOpenShift/_workitems/edit/6098209/)
Adds more admin API tests.
PR only includes tests.
No, PR only includes tests.
> Adds E2E tests for admin API: get cluster, update cluster

- pkg/api/error.go
- pkg/api/validate/openshiftcluster_validatedynamic.go
- pkg/backend/openshiftcluster.go
- pkg/backend/openshiftcluster/openshiftcluster.go
- pkg/frontend/admin_openshiftcluster_redeployvm.go
- pkg/frontend/admin_openshiftcluster_redeployvm_test.go
- pkg/frontend/admin_openshiftcluster_resources_list.go
- pkg/frontend/admin_openshiftcluster_resources_list_test.go
- pkg/frontend/validate.go
https://msazure.visualstudio.com/AzureRedHatOpenShift/_backlogs/backlog/Azure%20Red%20Hat%20OpenShift/Features/?showParents=true&workitem=7609206
Subscription Document is more reliable source of `TenantID` value. There is a case where a subscription containing cluster has been moved to another tenant and RP fails to delete this cluster because it is using old tenant id value from the OpenShiftCluster document. 
Tested manually:
1) create cluster on master branch
2) modify cluster document property `ServicePrincipalProfile.TenantID` in DB to have an non-existing tenant id. 
3) while on master branch attempt to delete the cluster. 
4) Observe error similar to the prod issue: `Status Code = '400'. Response body: {"error":"invalid_request","error_description":"AADSTS90002: Tenant '<REDACTED>' …
> Fetch TenantID from subscription doc when initializing FPAuthorizers

- pkg/util/version/version.go
- pkg/util/version/version_test.go
Fixes https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/7519657
This PR changes the internal representation of the cluster version from bytes to uint32s.
It's possible z in x.y.z goes >255, it's improbable it will go above 4294967295 .
Added one more unit test for values >255 of x.y.z
No, it's just internal representation. Code logic remains the same and the version is instanciated either by passing numeric literals to NewVersion or a version string to ParseVersion, so usage doesn't change either.
> Changing internal version representation from byte to int32.

- pkg/api/admin/openshiftcluster.go
- pkg/api/admin/openshiftcluster_convert.go
- pkg/frontend/openshiftcluster_putorpatch_test.go
Related to: 
* https://github.com/Azure/ARO-RP/issues/853
* https://github.com/Azure/ARO-RP/pull/808
* https://github.com/Azure/ARO-RP/issues/685
Fixes #808 
Re-add the registry profile to the API. It ignores conversion from external to internal as it creates issues.
The test covering the empty request scenario is added.
> Add RegistryProfile to admin API

- cmd/aro/rp.go
- pkg/frontend/admin_openshiftcluster_kubernetesobjects_test.go
- pkg/frontend/admin_openshiftcluster_list_test.go
- pkg/frontend/admin_openshiftcluster_redeployvm_test.go
- pkg/frontend/admin_openshiftcluster_resources_list.go
- pkg/frontend/admin_openshiftcluster_resources_list_test.go
- pkg/frontend/asyncoperationresult_get_test.go
- pkg/frontend/asyncoperationsstatus_get_test.go
- pkg/frontend/frontend.go
- pkg/frontend/openshiftcluster_delete_test.go
- pkg/frontend/openshiftcluster_get_test.go
- pkg/frontend/openshiftcluster_list_test.go
- pkg/frontend/openshiftcluster_putorpatch_test.go
- pkg/frontend/openshiftclustercredentials_post_test.go
- pkg/frontend/security_test.go
- pkg/frontend/subscriptions_put_test.go
Adds VNET output to resources
Story number: TBC
To see if user changed vnet settings
TBC
TBC
> Add vnet to geneva output

- pkg/frontend/openshiftcluster_putorpatch_test.go
Fixes CI by adding a missing, newly added parameter to a function call.
A recent merge lacked a necessary change to the function signature of `NewFrontend` in one unit test, `pkg/frontend/openshiftcluster_putorpatch_test.go`. As a result, Go CI is now failing.
Watch CI pass.
No. Fixing a unit test.
> Add missing new parameter so that CI passes

- .pipelines/templates/template-az-cli-set-context.yml
- .pipelines/templates/template-clean-e2e-db.yml
- .pipelines/templates/template-clean-e2e-deps.yml
- .pipelines/templates/template-deploy-e2e-db.yml
- .pipelines/templates/template-deploy-e2e-deps.yml
- .pipelines/templates/template-prod-e2e-steps.yml
- .pipelines/templates/template-run-rp-and-e2e.yml
- hack/e2e/run-rp-and-e2e.sh
To simplify debuging the e2e pipeline
add the -x option.
Care is taken around the secrets, to print
only required info.
FIXES: #619 
/cc @mjudeikis 
> Add debug info to e2e

- pkg/api/validate/openshiftcluster_validatedynamic.go
- pkg/api/validate/openshiftcluster_validatedynamic_test.go
cleanup from #891.  That PR adds the Microsoft.Network/virtualNetworks/write, which we don't strictly need, but it's probably worth ensuring we get + syncing the dynamic validator.
@mjudeikis ptal
> synchronise dynamic validator with actions granted to "ARO v4 Development Subnet Contributor"

- hack/clean/clean.go
- pkg/util/purge/resourcegroups.go
On production fails (it happens), we have 2 RG. One is with Deny assignment and fails to purge. We will clean those once we delete the cluster object.
> Purge - dont fail, and continue

- .gitignore
- Dockerfile.aro
- Makefile
- docs/testing.md
- hack/e2e/run-rp-and-e2e.sh
Fixes [Work Item#6602294](https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/6602294)
Preparation to CI refactoring so we can use a pre-built e2e test binary of specific version against the RP of the same version.
```
export RP_IMAGE_ACR=test-acr
make image-aro
```
Also need to run e2e in the PR itself to make sure that e2e did not break due to make target changes.
Documentation updated as part of this PR (make target changes), but still a good idea to notify the team about changes.
> Adds e2e image publishing into CI pipelines

- pkg/api/validate/format_regexps.go
- pkg/api/validate/format_regexps_test.go
Fixes VSTS7809447
Domain must start with the letter. 
TBC
TBC
Related to: https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/7809447
https://github.com/kubernetes/apimachinery/blob/master/pkg/util/validation/validation.go#L229
> Verify if domain starts with the letter

- pkg/backend/openshiftcluster/adminupdate.go
- pkg/backend/openshiftcluster/create.go
- pkg/backend/openshiftcluster/openshiftcluster.go
- pkg/install/deploystorage.go
- pkg/install/deploystorage_test.go
- pkg/install/install.go
Fixes https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/7480894/
Continues the work started in https://github.com/Azure/ARO-RP/pull/837 by putting the additional permissions added by @troy0820 and required for disk snapshots behind a new feature flag, `Microsoft.RedHatOpenShift/EnableSnapshots`.
This feature flag will add necessary exceptions (in the form of `NotActions`) to the `DenyAssignment` for the storage ARM template during cluster creation and upgrade.
Unit test added for `denyAssignments`.
This will be documented alongside the other feature flag documentation.
> Snapshot permissions with feature flag

- test/e2e/operator.go
This is trying to fix: https://msazure.visualstudio.com/AzureRedHatOpenShift/_build/results?buildId=33494233&view=logs&j=64095ab9-d84a-583b-4a30-0975ff6d5921&t=edb0e708-88e9-5861-d88f-71d0311e1597&l=637
If we run master e2e against prod (that does not have the operator) e2e will fail. This skips the operator e2e if the
cluster CRD does not exist.
it is a test..
no
> Skip operator e2e tests if the cluster CRD does not exist

- pkg/frontend/admin_openshiftcluster_serialconsole.go
- pkg/frontend/frontend.go
With its [counterpart in the Geneva Actions repo](https://msazure.visualstudio.com/One/_git/Compute-ARO-GenevaActions/pullrequest/3225400), fixes [Azure DevOps 7623834](https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/7623834)
Adds admin endpoint and handler for a new Geneva Action based on @jim-minter's [prior work](https://github.com/jim-minter/ARO-RP/tree/702edbf74665fe67e5751aa6be3d177a1f1aebfa/hack/serialtool). The Geneva Action will return the output of the serial console for a given VM to assist in debugging.
Also removes the deprecated `restartvm` admin endpoint, which had become just an alias for the newer `redeployvm` endpoint and is no longer needed.
Tested by running RP and GA code locally.
The new Geneva Action should be documented. I am also documenting …
> Add serial console kubeaction and endpoint

- pkg/install/upgrade.go
- pkg/install/upgrade_test.go
- pkg/util/status/clusterversionoperator_status.go
- pkg/util/version/stream.go
- pkg/util/version/stream_test.go
- pkg/util/version/version.go
- vendor/github.com/sirupsen/logrus/go.mod
Fixes ability to upgrade to Y streams
Lets assume we have Stream as befflow configured in our code:
4.3.28
4.4.10
4.5.1
1. The assumption that our code always has upgrade edged configured as jump points to major versions.
2. If the cluster is lower than 4.3.28, we will upgrade to `4.3.28` first. Will need the second adminPut to trigger upgrade to `4.4.10`
3. If the cluster is higher than `4.3.28` - we don't upgrade as manual check is needed to confirm upgrade path is valid.
4. If cluster is on `4.4.10` next jump will be `4.5.1`
5. If cluster can execute any of the previous upgrades BUT CVO is unhealthy - don't upgrade. 
Unit testing, mock testing.
TBD after merge.
> Enable 4.3 to 4.4 upgrade

- .pipelines/templates/template-push-images-to-acr.yml
- Makefile
Fixes the ability to publish `aro:master` images into `acrint`
@asalkeld  this one is for you urgent.
Currently logic in make file do now work because azure CI checksout commit id (not branch reference). See checkout step in ci[1]
```
git checkout --progress --force 500a5cc37f6c40030b6ef91cd574b0e106152681
Note: checking out '500a5cc37f6c40030b6ef91cd574b0e106152681'.
You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
a state without impacting any branches by performing another checkout.
```
So because of this we never publish an image with `latest` tag. 
I am removing BRANCH reference and using CI native way to set BRACH name. If can think a better way to do so, please push ontop or open your …
> Fix arosvc registry push

- hack/clean/clean.go
Fixes issues with purge
Pattern matches MSFT subs rg. we need to match specific names
> Purge nits

- docs/az-aro-python-development.md
N/A
Clarifies documentation for contributing to upstream az cli.
Our use of upstream and downstream in this document is backwards, so I have swapped it to be less confusing.
I also added a helpful diff command for assisting in review with these PRs (ala https://github.com/Azure/azure-cli/pull/14362#issuecomment-662142932).
N/A
This is the documentation update :)
> Clarify docs for Python review

- pkg/util/status/clusterversionoperator_status.go
- pkg/util/version/stream.go
when you are on 4.4.10 and run an adminupgrade it will error first with
"not upgrading: previous upgrade in-progress" - see ClusterVersionOperatorIsHealthy()
then it will error with
"not upgrading: stream not found"
todo, add unit tests..
no
> AdminUpgrade fixes

- pkg/install/install.go
Fixes #941
There's a panic during cluster create, probably due to missing value.
Prod deploy pipeline - seems to work on dev
No
> adding missing value

- pkg/operator/apis/aro.openshift.io/v1alpha1/cluster_types.go
- pkg/operator/controllers/condition.go
- pkg/operator/deploy/deploy.go
https://msazure.visualstudio.com/AzureRedHatOpenShift/_boards/board/t/Azure%20Red%20Hat%20OpenShift/Features/?workitem=7862793
Wait for the controllers to reconcile before completing create.
Note not all controllers create a condition, but this is a good start.
Tested during e2e create
no
> Wait for operator to be functioning

- pkg/api/openshiftcluster.go
- pkg/monitor/cluster/arooperatorconditions.go
- pkg/monitor/cluster/cache.go
- pkg/monitor/cluster/cluster.go
- pkg/monitor/cluster/clusteroperatorconditions.go
- pkg/monitor/cluster/clusteroperatorversions.go
- pkg/monitor/cluster/clusterversionconditions.go
- pkg/monitor/cluster/clusterversions.go
- pkg/monitor/cluster/machineconfigpoolconditions.go
- pkg/monitor/cluster/nodeconditions.go
- pkg/monitor/cluster/nodeconditions_test.go
- pkg/monitor/cluster/podconditions.go
- pkg/monitor/cluster/summary.go
- pkg/monitor/cluster/summary_test.go
- pkg/monitor/worker.go
Fixes Kevin's request to generate more detail report for V4 :)
1 Introduces one time cache for repeatable API calls in monitoring
2. Introduces `clusters.summary` metric for reporting 
N/a
Only dashboard and report creation/reading once merged.
> Add summary metric for reporting

- pkg/frontend/adminactions/serialtool.go
application/octet-stream gives us an xml + base64 encoded response; I think we should probably be ok just to use text/plain.
> let's try returning text/plain in serial console geneva action

- Makefile
This fixes the `make pyenv` step in the [Deploy Development RP document](https://github.com/Azure/ARO-RP/blob/master/docs/deploy-development-rp.md) if `python3-wheel` package is not installed.
When I tried to follow the steps outlined in the document I got the error
```
...
cd python/az/aro && python ./setup.py bdist_wheel || true
Wheel is not available, disabling bdist_wheel hook
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
or: setup.py --help [cmd1 cmd2 ...]
or: setup.py --help-commands
or: setup.py cmd --help
```
1. Make sure that python3-wheel package is not installed
2. Proceed with the steps in [Installing the extension section](https://github.com/Azure/ARO-RP/blob/master/docs/deploy-development-rp.md#installing-the-extension)
3. It will fail with the error …
> Makefile: add "wheel" to pip install

- test/e2e/cluster.go
Fixes https://github.com/Azure/ARO-RP/issues/970
The name of the test is incorrect. It uses Azure Disk, not Azure File. 
N/A
I will keep looking why it fails. I am pretty sure this is because it is the first test, it runs a few seconds right after the cluster is created.
> Fix storage type name in e2e test name

- pkg/operator/controllers/workaround/ifreload.go
This is a follow-up for https://github.com/Azure/ARO-RP/pull/974
A typo crept-in which made the operator produce error messages after the namespace was deleted.
I noticed the generated operator error messages while working on an unrelated issue. The fix eliminates them.
> ifreload workaround: fix typo in error checking logic

- test/e2e/adminapi_resources.go
> HACK: exclude route tables from the e2e resources comparison for now

- cmd/aro/deploy.go
- pkg/deploy/config.go
- pkg/deploy/config_test.go
- pkg/deploy/deploy.go
Fixes #954
TL;DR: Move the checkRequiredField to the `deployer.New` which is a more logical place for this code.
The checkRequiredField is left in the `config.go` source, but is left unexposed.
This enables easier reading as the code is linked to work on the config struct.
Call to the `checkRequiredField` is done in the `deployer.New` as the first step,
and fails when the config does not meet the required field criteria.
This PR also sets all fields as required, as this is the current reality.
Tests already in place for existing code.
None needed.
> Move checkRequiredFields to deployer.New and mark all fields required

- pkg/database/openshiftclusters.go
- pkg/frontend/admin_openshiftcluster_kubernetesobjects.go
- pkg/frontend/admin_openshiftcluster_list.go
- pkg/frontend/admin_openshiftcluster_list_test.go
- pkg/frontend/admin_openshiftcluster_resources_list.go
- pkg/frontend/frontend.go
- pkg/frontend/frontend_test.go
- pkg/frontend/openshiftcluster_list.go
- pkg/util/mocks/database/database.go
- test/e2e/adminapi_cluster_list.go
This PR makes the cluster list API pageable. [Here is the corresponding change to the geneva action codebase.](https://msazure.visualstudio.com/One/_git/Compute-ARO-GenevaActions/pullrequest/3158068)
This PR overrides https://github.com/Azure/ARO-RP/pull/705 (I couldn't push to that PR)
fixes #703
@jim-minter I added a commit to your PR that fixes listing with a filter, the problem is
1. we have changed from [cluster, cluster] to {value: [cluster, cluster], nextPageLink: "url"}
2. the jsmespath is run on the server so we have to page and run the filter multiple times
My solution to the above is to attempt to "scope" the jmespath query to ".value" so that the nextPageLink is never butchered. My specific implementation in adminJmespathFilter() does not feel very elegant, so open to better …
> Add pagination to admin cluster list API

- pkg/cluster/fixpullsecret.go
- pkg/cluster/fixpullsecret_test.go
- pkg/cluster/install.go
FIxes operator deployments
We can't fix the secret because the operator is not yet running. 
We can't rollout operator because we can't pull the image. 
We can't pull image because customers deleted the pull secret.
Test in prod
no
> Rollback fixpullsecret to enable operator deployment 

- pkg/util/dynamichelper/dynamichelper.go
- pkg/util/dynamichelper/dynamichelper_test.go
Fixes prod error
This prevents the below error I got when updating a cluster where the operator was not running, but the cluster object had been created.
```
+   "status":   map[interface{}]interface{}{},
}
step [Action github.com/Azure/ARO-RP/pkg/cluster.(*manager).ensureAROOperator-fm] encountered error: json: unsupported type: map[interface {}]interface {}
```
unit tests
no
> Fix dynamichelper.merge when status exists but is empty

- pkg/util/version/const.go
Fixes https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/8350168 (pt. 2)
This is the patched version of the 4.3.x series for the CVE in title.
N/A
Nope!
> Pull in latest 4.3.x patch (fixes: CVE-2020-14386)

- pkg/operator/controllers/checker/internetchecker.go
- pkg/operator/controllers/checker/internetchecker_test.go
- test/e2e/operator.go
Fixes #979 by retrying each request multiple times.
Note: this is a re-created #980 PR. Due to multiple changes in files I found re-basing on the recent master branch was more laborious.  
Each URL from the check list is tested concurrently. A failed request is retried using exponential randomized back-offs. The number of retries/test run time is capped to 1 minute or 5 attempts, whichever happens first.
I tested it with a unit test and a focused e2e test by running the operator locally and by deploying an updated image to my dev cluster.
Unit tests:
```
make test-go
```
End to end tests:
```
make test-e2e
```
> Fix for #979 operator internet checker is catching transient errors Mk II

- pkg/cluster/install.go
Extend the operatorConsoleReady timeout.
I've seen a few flakes where we timed out on this.  Investigating one, I saw that the API servers were rotating and this was preventing authentication and the console from going ready.
I don't *think* that ARO was causing the API server rotation, and indeed we had already passed steps.Condition / i.apiServersReady.  I think there's little alternative but to be more flexible here.
> extend operatorConsoleReady timeout

- pkg/util/billing/billing.go
Container name for billing e2es is invalid because of a trailing -. It was discovered because of a new region billing rollout to germanywestcentral which results in container name being the follow format: bill-germanywestcentral-v4-e2e-rg-V35265891-germanywestcentral-
Here's the link for RP logs that shows error: https://jarvis-west.dc.ad.msft.net/5933C2DA
> Fix E2Es to not have invalid name

- pkg/util/billing/billing.go
Container name for billing e2es is invalid because of a trailing -. It was discovered because of a new region billing rollout to germanywestcentral which results in container name being the follow format: bill-germanywestcentral-v4-e2e-rg-V35265891-germanywestcentral-
Here's the link for RP logs that shows error: https://jarvis-west.dc.ad.msft.net/5933C2DA
> Fix E2E Container Name Changes

- pkg/deploy/deploy.go
- pkg/deploy/predeploy.go
I spotted today that we have accidentally created an empty global RG in every prod subscription.  We shouldn't have done.
This code fixes the issue, we should remove the RGs manually in prod.
> don't create a global RG in every prod subscription

- .pipelines/e2e-with-billing-all-regions.yml
- .pipelines/prod-release.yml
Fixes [8379768](https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/8379768)
Adds two regions to pipelines. Just getting it ready ahead of time - don't merge yet.
Verify that locations are in the right spots
No
> Add germanywestcentral & norwayeast to pipelines

- pkg/frontend/adminactions/serialtool.go
Adding a check for nil pointer in GA action. There is no ticket, but it happens if people try to get serial console from worker node.
Serial console on worker nodes is not available. When we try to run serial console on a worker PR gets nil pointer dereference panic. This will also save time for on-call SRE as it will provide a better explanation rather than a 500 on GA.
none
no
> Add check for nil pointer in get serial log GA

- pkg/cluster/gatherlogs.go
- pkg/cluster/install_test.go
Fixes https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/8523734
If a cluster fails deployment due to the Ingress Operator staying degraded, then we do not log the cause of the degradation as the ClusterOperator logging does not contain information required to debug it once a cluster is deleted, just that it was in the degraded state.
Unit tests are provided.
N/A
> Log the status of the ingress controllers on failure to get the statuses that are not presently captured

- pkg/cluster/install_test.go
- pkg/frontend/frontend_test.go
- pkg/util/recover/recover_test.go
- pkg/util/steps/runner_test.go
- test/util/log/log.go
- test/util/log/log_test.go
refactor test/util/log to allow matching of arbitrary log fields - I'd like to be able to do this for the new portal work
> refactor test/util/log to allow matching of arbitrary log fields

- pkg/api/validate/openshiftcluster_validatedynamic.go
- pkg/util/aad/aad.go
- pkg/util/mocks/refreshable/refreshable.go
- pkg/util/refreshable/refreshable.go
- pkg/util/steps/refreshing.go
- pkg/util/steps/runner_test.go
Fixes [8440740](https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/8440740)
Previous PR (https://github.com/Azure/ARO-RP/pull/1031) was not updating with new commits in my branch, so this is a new PR.
Should check for `AADSTS700016` and `TokenRefreshError` whenever refreshing authorizer.
Run existing E2Es
No
> Auth refresh error check

- python/az/aro/azext_aro/__init__.py
- python/az/aro/azext_aro/azext_metadata.json
- python/az/aro/setup.py
Fixes https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/7851789/
The idea is to bump aro extension version to 2.0.0 and prohibit extensions version  <= 1.0.0.
Effectively this allows us (after merging the change upstream) to force people use the bundled-in version of `az aro` in case someone still uses an outdated extension.
Change version to 0.1.0 in the source code, run `make az` and make sure that it says "Extension aro (0.1.0) has been suppressed. ..."
Now revert the version back to 2.0.0 and make sure that the extension works by running, e.g. `az aro --help`.
Perhaps [az aro Python development](https://github.com/Azure/ARO-RP/blob/master/docs/az-aro-python-development.md) document should be updated. However, I'm not sure that it should be done before merging the …
> Suppress aro extension

- pkg/cluster/deploystorage.go
- pkg/cluster/deploystorage_test.go
Fixes https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/7710488/
The change should allow customers to inspect a cluster's effective route table. The feature is hidden behind a feature flag
`Microsoft.RedHatOpenShift/InspectEffectiveRouteTable`
It's tricky to test the change because it is effective only for production clusters. We can't deploy it to dev clusters.
There is a unit test, however it doesn't check much.
Perhaps the feature flag should be documented somewhere.
> Deny assignments effective route table exclusion

- pkg/cluster/install_test.go
- pkg/frontend/admin_openshiftcluster_kubernetesobjects_test.go
- pkg/frontend/admin_openshiftcluster_list_test.go
- pkg/frontend/admin_openshiftcluster_redeployvm_test.go
- pkg/frontend/admin_openshiftcluster_resources_list_test.go
- pkg/frontend/asyncoperationresult_get_test.go
- pkg/frontend/asyncoperationsstatus_get_test.go
- pkg/frontend/openshiftcluster_delete_test.go
- pkg/frontend/openshiftcluster_get_test.go
- pkg/frontend/openshiftcluster_list_test.go
- pkg/frontend/openshiftcluster_putorpatch_test.go
- pkg/frontend/openshiftclustercredentials_post_test.go
- pkg/frontend/subscriptions_put_test.go
- pkg/util/billing/billing_test.go
- test/database/check.go
- test/database/fixtures.go
@hawkowl ptal, should all be no-op.  `...` syntax can save us dual functions + a few typos/heterogeneous functions fixed out
> Minor changes to #1006

- pkg/deploy/deploy.go
- pkg/deploy/upgrade.go
Fixes [7590001](https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/7590001)
Saves the RP version to storage after successful deployment on a per-location basis. This will enable us in the future to make the E2Es target the correct version for each location.
To test this, deploy RP to INT and verify that the proper blob was created. Then, when doing rollout to canary regions, check again that separate blobs were created per location.
No
> Save RP version for location

- pkg/deploy/deploy.go
- pkg/deploy/upgrade.go
Fixes an issue with RP Version storage
Moves storing the RP Version after upgrade to the global subscription. Prevents from storing bits and pieces in every client sub.
Credit: @mjudeikis 
Running an upgrade should store the version in the central subscription instead of local sub.
No docs changed, not described in any documentation.
> changing accounts client to one using global subscription id for RP Version Storage

- pkg/deploy/upgrade.go
Timeout fails sometimes in busy regions as 20 min is not enough for RP to gradually finish
> bump timeout for deploy

- .pipelines/e2e-with-billing-all-regions.yml
- .pipelines/prod-release.yml
Part of Azure DevOps 7065216 and 7065243 (rollout of australiasoutheast and switzerlandwest regions)
Adds the 2 new regions to Prod Deploy ALL Regions, and E2E tests
N/A
No documentation update required.
> adding switzerlandwest australiasoutheast to pipelines

- docs/deploy-development-rp.md
Documentation update as requested by @jim-minter. 
Update the "Deploy development RP" doc to remove the step to run the `pyenv` make target. 
This step is no longer needed as the `az` target will run it.
> Update docs to remove pyenv instruction

- pkg/backend/openshiftcluster/delete.go
- pkg/cluster/cluster.go
- pkg/cluster/delete.go
Part of  https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/7574586
This moves the delete functionality into cluster/ so that it can be split into runsteps later.
Haven't added any, that'll come with the runsteps refactoring.
N/A
> Move delete functionality from backend/openshiftclusters to cluster/

- pkg/monitor/cluster/summary.go
- pkg/monitor/cluster/summary_test.go
Required for [work item №7792860](https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/7792860/).
Adds a new dimension to the `cluster.summary` metric so we can have a view of clusters in Failed/Creating and Failed/Deleting states (combination of `ProvisioningState` + `FailedProvisioningState`).
Updated unit tests.
No, but need to add a dashbaord.
> Adds a new dimension to the cluster.summary metric

- pkg/cluster/deploystorage.go
- pkg/cluster/deploystorage_test.go
Adds Microsoft.Resources/tags/* to deny assignment allowing the customer to tag resources.
Build on top of: https://github.com/Azure/ARO-RP/pull/1041 . It needs to get merge first 
Info: https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/tag-resources
> Add ability to tag resourceGroups

- .pipelines/e2e-with-billing.yml
- .pipelines/e2e.yml
- .pipelines/mirror-images.yml
Fixes `##[error]The job running on agent ARO-RHEL-ci-00000W ran longer than the maximum time of 60 minutes. For more information, see https://go.microsoft.com/fwlink/?linkid=2077134` 
Image mirror job and some testing jobs gets canceled due to long execution
Test by :fire: 
No
> increase timeouts on jobs

- .gitignore
- cmd/aro/operator.go
- pkg/env/core.go
- pkg/util/deployment/deployment.go
Logs the RP deployment mode during startup.
The log output ensures developers are aware of the deployment mode that
their RP is running in.
Executes the `go run ./cmd/aro rp` command locally, with different `RP_MODE`
values:
```sh
RP_MODE="development" go run ./cmd/aro rp                                         
INFO[2020-10-20T15:19:59-07:00]cmd/aro/main.go:45 main.main() starting, git commit unknown
INFO[2020-10-20T15:19:59-07:00]pkg/env/core.go:52 env.NewCore() running in development mode
RP_MODE="int" go run ./cmd/aro rp                                           
INFO[2020-10-20T15:20:45-07:00]cmd/aro/main.go:45 main.main() starting, git commit unknown
INFO[2020-10-20T15:20:45-07:00]pkg/env/core.go:52 env.NewCore() running in int mode
RP_MODE="" go run ./cmd/aro rp …
```
> Logs RP deployment mode during startup

- pkg/frontend/middleware/log.go
currently lines like `r.URL.Path = filepath.Dir(r.URL.Path)` alter our frontend sent response URLs.  Fix this.
> don't let any in-place modifications of r affect our "sent response" logging

- pkg/frontend/admin_openshiftcluster_upgrade.go
- pkg/frontend/adminactions/adminactions.go
- pkg/frontend/adminactions/upgrade.go
- pkg/frontend/adminactions/upgrade_test.go
- pkg/util/mocks/adminactions/adminactions.go
- pkg/util/version/const.go
- pkg/util/version/stream.go
- pkg/util/version/stream_test.go
Fixes [8573199](https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/8573199)
Checks if a new query string for the admin upgrade endpoint is set to true which allows the cluster to be upgraded to the next Y version. Will need to have corresponding Geneva Action changed.
Also fixed the error checking logic in an existing unit test and corrected or clarified some comments.
Updated unit tests to include this new case
Yes, cluster upgrade SOP will need to be updated
> Check if Y version cluster upgrade is allowed

- pkg/monitor/cluster/cache.go
- pkg/monitor/cluster/cluster.go
- pkg/monitor/cluster/clusterversions.go
- pkg/monitor/cluster/clusterversions_test.go
- pkg/monitor/cluster/deploymentstatuses.go
- pkg/operator/deploy/deploy.go
Adds RP version
Cluster last successful put/patch version
Current operator version
The plan is to do something similar we have for ClusterVersion dashboards:
RP Version |  Cluster last admin action Version | Operator Version |
Where in theory all 3 should be the same when all maintenance is done
unit and in prod
Dashboards story in VSTS
> rp,operator version metrics

- pkg/monitor/cluster/arooperatorheartbeat.go
- pkg/monitor/cluster/arooperatorheartbeat_test.go
- pkg/monitor/cluster/cluster.go
Fixes https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/6470481/
It adds a new metric called arooperator.heartbeat for every cluster, which checks the availability of deployment replicas in the "openshift-azure-operator" namespace. It adds on the generic deployment metric by also emiting a value when everything is working correctly.
There are unit tests which verify if the correct values of the metric are emitted for different replicasAvailable/replicas values in the deployments.
N/A
Might require documentation if an alert is added based on the new metric.
> adding a new metric called arooperator.heartbeat

- pkg/util/cluster/cluster.go
* limit ARM deploy time, this limits flailing when the role assignment deployment fails with HashConflictOnDifferentRoleAssignmentIds and keeps retrying
* fix up NSGs in CI: work around auto-generated NSGs in MSFT tenant until we go to private clusters in CI
* ensure that cluster deletion errors block CI
> Fix CI NSG trouble

- pkg/monitor/cluster/nodeconditions.go
- pkg/monitor/cluster/nodeconditions_test.go
- pkg/monitor/cluster/podconditions.go
- pkg/monitor/cluster/podconditions_test.go
Related to work items [№8390641](https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/8390641/) and [№7418602](https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/7418602/).
It adds node name into pod.condition metric so we can create incidents such as "API server replica is down" enriched with node information and save some time required to dig this out from Kube objects or logs. It will enable us to do incidnet aggregation in the future, if we decide to do so.
Updates unit tests.
No
> Adds node name into pod metrics

- python/az/aro/azext_aro/_rbac.py
- python/az/aro/azext_aro/custom.py
Fixes [8367811](https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/8367811).
Customers keep messing with their AAD app/SPN permissions, resulting in the long runbook at https://msazure.visualstudio.com/AzureRedHatOpenShift/_wiki/wikis/ARO.wiki/82747/Customer-Common-Mistakes?anchor=removed-permissions.
This attempts to automate fixing a bunch of the permission problems we typically encounter upon deletion.
TBD; does not appear to be a lot of unit tests and I haven't tested this manually with the locally built extension (hence "WIP" label).
No, this is just cleanup work that will avoid an update to customer-facing docs.
When this is released upstream, we may want to note the version this landed in for the runbook above.
> Fix permissions on cluster deletion in az cli

- pkg/frontend/adminactions/upgrade.go
- pkg/frontend/adminactions/upgrade_test.go
Currently, if upgrade check fails it returns internal server error to Geneva. And SRE needs to go into RP logs to find out why.
This will help to debug faster skipping this step
Usual flow now:
1. Start upgrade
2. Internal Server Error
3. Check RP logs
4. Check CVO in most cases it is unhealthy because of "reasons".
This will help to skip 2-3 steps 
N/A
N/A
> Propagate cvo error to geneva

- pkg/api/openshiftcluster.go
- pkg/frontend/openshiftcluster_putorpatch.go
- pkg/frontend/openshiftcluster_putorpatch_test.go
Part of the 4.5 release #972 
Saves the version of the RP that creates a cluster (or at least the doc) into the document, so we can see what clusters were created with what version of the RP.
Contains unit tests.
N/A
> Save the version of the RP that creates a cluster

- .pipelines/int-release.yml
Enables custom builds to be deployed into INT.
Helps with more advanced testing when before merge we want to try to deploy
> Enable INT pipeline to deploy custom runs

- .pipelines/e2e-with-billing-all-regions.yml
Split billing e2e delays out because we've been growing
Redistributed regions to match prod-release for ease of management
Added canary regions
> align .pipelines/e2e-with-billing-all-regions.yml with .pipelines/prod-release.yml

- .pipelines/int-release.yml
- .pipelines/templates/template-job-deploy-azure-env.yml
Fix to make the yaml files more readable.
We're changing a " " which is semantically different from "" because "" is treated as unset string.
." " might cause confusion, so we're changing that to an actual string ("master" as it represents the branch it will use)
> VSTS fix for null string

- pkg/util/dynamichelper/discovery/cache_fallback_discovery_client.go
- pkg/util/dynamichelper/dynamichelper.go
Fixes "Internal Server Error" when live and cache discovery fails. 
In cases where we have a dead `APIService` object, we get internal server error. This hack ignores the error
`oc new-project test`
```
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
name: v1beta1.test.faros.sh
spec:
caBundle: fakebundle
group: test.faros.sh
groupPriorityMinimum: 100
service:
name: test
namespace: test
port: 443
version: v1beta1
versionPriority: 100
```
`of create -f api.yaml`
```
curl -k -X GET      -H 'Content-Type: application/json'      "https://localhost:8443/admin/subscriptions/${AZURE_SUBSCRIPTION_ID}/resourcegroups/${RESOURCEGROUP}/providers/Microsoft.RedHatOpenShift/openShiftClusters/${CLUSTER}/kubernetesobjects?api-version=admin&kind=test.example.com"
curl -k -X GET      -H …
```
> Discovery cache hack 

- docs/deploy-development-rp.md
- hack/ssh-agent.sh
Update the development RP cluster deploy docs to specify missing `CLUSTER` environment variable and other potential dependencies.
`/hack` resources so no testing plan.  Can validate changes by running:
```bash
sudo openvpn secrets/vpn-$LOCATION.ovpn &
CLUSTER=mycluster hack/ssh-agent.sh master1
```
Output below:
```bash
$ CLUSTER=bvesel hack/ssh-agent.sh master1
INFO[2020-11-06T15:33:54-05:00]pkg/env/core.go:52 env.NewCore() running in development mode                  
INFO[2020-11-06T15:33:58-05:00]pkg/env/core.go:52 env.NewCore() running in development mode                  
Warning: Permanently added '10.98.66.9' (ECDSA) to the list of known hosts.
Red Hat Enterprise Linux CoreOS 44.82.202009261130-0
Part of OpenShift 4.4, RHCOS is a Kubernetes native operating system
managed by the …
```
> Update Development RP Cluster Deploy Docs

- .pipelines/mirror-images.yml
- cmd/aro/mirror.go
In clusters with no pull secret we can't advise to use `oc debug node/` as it is not reachable. 
This potentially is the first step to remove need in a pull-secret need for debugging tooling. 
N/a
potentially adding `oc debug node/{node_name} --image acr.name/image` somewhere
> Sync tooling image into ACR

- pkg/util/azureclient/mgmt/authorization/roleassignments.go
- pkg/util/azureclient/mgmt/authorization/roleassignments_addons.go
- pkg/util/azureclient/mgmt/features/deployments_addons.go
- pkg/util/azureclient/mgmt/network/routetable.go
- pkg/util/azureclient/mgmt/network/routetable_addons.go
- pkg/util/azureclient/mgmt/network/subnets_addons.go
- pkg/util/cluster/cluster.go
- pkg/util/mocks/azureclient/mgmt/authorization/authorization.go
- pkg/util/mocks/azureclient/mgmt/features/features.go
- pkg/util/mocks/azureclient/mgmt/network/network.go
Need VSTS story/number associated with this. (I don't have access to VSTS yet)
This PR introduces functionality to clean up left-over resources on creation of a dev cluster.  It cleans up the following left-behind resources.
- master/worker subnets
- route tables
- role assignment RBAC for cluster SP
See below for testing in-action
1. Create two clusters
1. Delete one cluster using old method
1. Delete one cluster using new PR
1. See that new cluster deletion removes the subnets, route tables, and role assignments for the cluster service principal.  
Check these variables before delete
```bash
CLUSTER=bvesel
APP_ID=76f37f3a-785a-40a9-85c0-b8f9900e33d3
SP_OBJ_ID=5a0f5697-a8bc-49b1-8e2d-15259e9b0d45
```
---
Check subnets
```bash
$ az network vnet subnet show -g v4-eastus --vnet-name …
```
> Clean-Up Resources on Dev Cluster Delete

- pkg/cluster/deploystorage.go
- pkg/cluster/deploystorage_test.go
Tagging - attempt 2 
Due to this:
```
ValidationError: Deployment failed. Correlation ID: d78a5fd7-0305-4b90-a1ba-65e4d01e6dc2. {"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","target":null,"details":[{"code":"BadRequest","message":"{\r\n  \"error\": {\r\n    \"code\": \"InvalidActionOrNotAction\",\r\n    \"message\": \"'Microsoft.Resources/resourceGroups/write' does not match any of the actions supported by the providers.\"\r\n  }\r\n}"}],"innererror":null,"additionalInfo":null}
```
> Change deny assignment rg permissions 

- test/e2e/adminapi_resources.go
- test/e2e/setup.go
Fixes #985 by adding the route tables to expected resources
It fixes the e2e tests to properly include routeTables in expected resources for the comparison.
Run e2e test.
None. Fixing a test. Inline information is enough to understand the change.
> fixed e2e test re: routeTables

- pkg/util/log/log_test.go
N/A
The hardcoded GoPath in this unit test introduces a hard dependency on our
local file path. Since we have migrated to go modules in 4.5, we are no longer
required to couple ourselves to GoPath.
Run the `go test ./.. -count=1` on my local repo both inside and outside of
GoPath:
```sh
$ pwd 
/home/isim/go/src/github.com/Azure/ARO-RP
$ go test ./... -count=1 | grep -i fail
$ pwd
/home/isim/ARO-RP
$ go test ./... -count=1 | grep -i fail
````
N/A
> Remove Hardcoded GoPath in Unit Test

- .sha256sum
- pkg/client/services/redhatopenshift/mgmt/2020-10-31-preview/redhatopenshift/client.go
- pkg/client/services/redhatopenshift/mgmt/2020-10-31-preview/redhatopenshift/models.go
- pkg/client/services/redhatopenshift/mgmt/2020-10-31-preview/redhatopenshift/openshiftclusters.go
- pkg/client/services/redhatopenshift/mgmt/2020-10-31-preview/redhatopenshift/operations.go
- pkg/swagger/paths.go
- pkg/swagger/swagger.go
- python/client/azure/mgmt/redhatopenshift/v2020_10_31_preview/_azure_red_hat_open_shift_client.py
- python/client/azure/mgmt/redhatopenshift/v2020_10_31_preview/operations/_open_shift_clusters_operations.py
- python/client/azure/mgmt/redhatopenshift/v2020_10_31_preview/operations/_operations.py
- swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/stable/2020-10-31-preview/redhatopenshift.json
ARO-RP update to match https://github.com/Azure/azure-rest-api-specs/pull/9681.
@sakthi-vetrivel this is the master copy that generates the swagger file - without updating this, your changes would have been overwritten.  Also, unfortunately it's not possible to maintain the title change of `Azure Red Hat OpenShift Client` -> `Azure Red Hat OpenShift 4 Client` because it affects the class names in the generated codebase.
> Swagger documentation updates

- pkg/cluster/deploystorage.go
- pkg/cluster/deploystorage_test.go
This does not work.
https://docs.microsoft.com/en-gb/azure/azure-resource-manager/management/tag-resources in the only way which we cant support at this point :/
> Revert tagging attempt 

- pkg/env/prod.go
- pkg/util/cluster/cluster.go
If a role assignment already exists, on cluster creation using `CLUSTER=cluster go run ./hack/cluster create` it will throw error and throw the following exceptions:
```
INFO[2020-11-19T15:11:29-05:00]pkg/util/cluster/cluster.go:184 cluster.(*Cluster).Create() creating role assignments                    
INFO[2020-11-19T15:11:31-05:00]pkg/util/cluster/cluster.go:207 cluster.(*Cluster).Create() authorization.RoleAssignmentsClient#Create: Failure responding to request: StatusCode=409 -- Original Error: autorest/azure: Service returned an error. Status=409 Code="RoleAssignmentExists" Message="The role assignment already exists." 
INFO[2020-11-19T15:11:32-05:00]pkg/util/cluster/cluster.go:207 cluster.(*Cluster).Create() authorization.RoleAssignmentsClient#Create: Failure responding to …
```
> Don't create role assignments if they already exist

- README.md
- cmd/aro/operator.go
- pkg/operator/controllers/alertwebhook/alertwebhook_controller.go
- pkg/operator/controllers/checker/checker_controller.go
- pkg/operator/controllers/const.go
- pkg/operator/controllers/genevalogging/genevalogging_controller.go
- pkg/operator/controllers/monitoring/monitoring_controller.go
- pkg/operator/controllers/monitoring/monitoring_controller_test.go
- pkg/operator/controllers/pullsecret/pullsecret_controller.go
- pkg/operator/controllers/workaround/workaround_controller.go
- test/e2e/operator.go
Fixes https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/7854151/
Currently, if not specifically configured by a customer, cluster monitoring Prometheus data is stored on the node. This PR adds a controller in ARO operator which will ensure that Prometheus is using PVC.
Storage/Retention proportion is taken from OSD https://github.com/openshift/managed-cluster-config/blob/be795d9e0e10205998dd9b600fcee4c03193f87e/deploy/cluster-monitoring-config/cluster-monitoring-config.yaml#L8-L22
Unit tests added. 
I have also tested on development cluster by running operator locally and performing different operations on the configMap
included in this PR
> Add monitoring controller to configure prometheus to persist data

- pkg/util/azureerrors/error.go
- pkg/util/azureerrors/error_test.go
Saw this today on a RP deployment e2e
https://msazure.visualstudio.com/AzureRedHatOpenShift/_build/results?buildId=36907046&view=logs&j=a30d20ff-f92a-5002-40fa-f468a85b0b36&t=7112a0c0-3080-579a-c35b-bcde84b4adbd
> catch unlikely authorization failure on create

- pkg/cluster/deployresources.go
- pkg/cluster/deployresources_resources.go
Partially fixes [8763812](https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/8763812)
- Use correct domains for current cloud during cluster creation
- Refactor cluster resource deployment functions to use receiver so they have access to manager data
Run existing unit and E2E tests.
No
> cloud awareness in cluster creation

- pkg/api/validate/openshiftcluster_validatedynamic.go
- pkg/api/validate/openshiftcluster_validatedynamic_test.go
- pkg/backend/openshiftcluster/adminupdate.go
- pkg/backend/openshiftcluster/update.go
- pkg/util/subnet/subnet.go
Implements most of the work described here: https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/7124129/
Invoke dynamic validator code on Update and/or AdminUpdate flows to pick up possible misconfigurations in cluster infrastructure. 
When creating a new worker pool by applying a new machineset as described here https://docs.openshift.com/aro/4/machine_management/creating-infrastructure-machinesets.html
it is possible to provide either a new subnet in the same vnet or the use the same subnet as used for the original worker pool. If the new subnet happen to overlap with pod CIDR then the machines in the new machineset will never got provisioned successfully but there is no easy way to identify what the actual problem is. While this is not a valid configuration, it is not …
> Invoke dynamic validator on Update

- .pipelines/templates/template-clean-subscription.yml
Fixes failure in Purge MSFT CI Subscription pipeline.  
With the introduction of `NewCoreForCI()` refactor, the `InstanceMetadata` type requires the `LOCATION` and `RESOURCE` environment variables to be set.  For the Purge MSFT CI Subscription pipeline, we do not set these typically as they are parsed based on the subscription we want to clean up.  By setting dummy `LOCATION` and `RESOURCEGROUP` environment variables, this should fix the pipeline.  
Run the pipeline once merged.
No
> Add dummy LOCATION env var to prevent pipeline failures

- pkg/cluster/condition.go
- pkg/cluster/condition_test.go
- pkg/cluster/install.go
[8790368](https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/8790368)
On cluster install, validate that the minimum amount of worker nodes (2) are ready before progressing with additional cluster operators which rely on the min amount of worker nodes to be up to report Ready. 
e2e testing, and writing a test in condition_test.go.  Additionally installed the cluster and it checked for the condition as shown below.  
```
starting phase InstallPhaseRemoveBootstrap
running step [Action github.com/Azure/ARO-RP/pkg/cluster.(*manager).initializeKubernetesClients-fm]
running step [Action github.com/Azure/ARO-RP/pkg/cluster.(*manager).removeBootstrap-fm]
removing bootstrap vm
removing bootstrap disk
removing bootstrap nic
running step [Action …
```
> Add condition to check minimum number of ready worker nodes

- docs/deploy-development-rp.md
- docs/prepare-a-shared-rp-development-environment.md
Fixes docs: we now use Go 1.14, but these docs still mention Go 1.13
> Doc fix: we now use Go 1.14

- pkg/frontend/openshiftcluster_putorpatch.go
- pkg/util/clusterdata/cluster_service_principal_task.go
- pkg/util/clusterdata/cluster_service_principal_task_test.go
- pkg/util/clusterdata/clusterdata.go
Fixes stale data in customer get when cluster SP is rotated.
In the case of rotation flow, we need to make sure cluster service principal is shown, one which is being used in the cluster as a primary source. Database data might be stale.
> Add Cluster Service Principal enrich

- python/az/aro/azext_aro/_rbac.py
- python/az/aro/azext_aro/custom.py
[8730829](https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/8730829/)
Fixes the RBAC for the Cluster and RP service principals if they are removed.
On `az aro update`, the RBAC for the cluster and RP service principals are checked to ensure they have contributor access to the corresponding vnets and routing tables in order to perform operations on the cluster.  
See below for testing plan.
```bash
CLUSTER=bvesel
RESOURCEGROUP=bvesel
CLUSTER_CLIENT_ID=$(az aro show -g bvesel -n $CLUSTER | jq -r .servicePrincipalProfile.clientId)
CLUSTER_SERVICE_PRINCIPAL=$(az ad sp list --all --filter "appId eq '${CLUSTER_CLIENT_ID}'" | jq -r '.[].objectId')
RP_CLIENT_ID=1516efbc-0d48-4ade-a68e-a2872137fd79
RP_SERVICE_PRINCIPAL=$(az ad sp list --all --filter "appId eq '${RP_CLIENT_ID}'" …
```
> Add rbac validation to aro update

- python/az/aro/azext_aro/__init__.py
- python/az/aro/azext_aro/_help.py
Reconcile some changes that should've been in upstream az aro extension but were only in downstream (Azure/azure-cli)
Same as above
N/A
No
> Reconcile `az aro` with Azure/azure-cli

- pkg/api/admin/openshiftcluster.go
- pkg/api/admin/openshiftcluster_convert.go
- pkg/api/admin/openshiftcluster_validatestatic_test.go
- pkg/api/openshiftcluster.go
- pkg/api/openshiftclusterdocument_example.go
- pkg/api/validate/openshiftcluster_validatedynamic.go
- pkg/api/validate/quota.go
- pkg/cluster/billing.go
- pkg/cluster/billing_test.go
- pkg/cluster/cluster.go
- pkg/cluster/deploystorage.go
- pkg/cluster/generateconfig.go
- pkg/cluster/validate.go
- pkg/frontend/openshiftcluster_putorpatch.go
- pkg/frontend/openshiftcluster_putorpatch_test.go
- pkg/util/aad/aad.go
- pkg/util/billing/billing.go
- pkg/util/billing/billing_test.go
- pkg/util/mocks/billing/billing.go
- test/e2e/adminapi_cluster_get.go
- test/e2e/adminapi_cluster_list.go
Fixes [8857852](https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/8857852/)
We can't delete the cluster if the subscription has been transferred.  This will look at the tenantID from the subscriptionDoc and not the openshfitclusterdocument to do the deletion.
Modified unit tests from before to use the required TenantID from the subscriptionDoc.  
No docs updates are necessary.
> Remove TenantID from OpenShiftClustersDocument

- python/az/aro/azext_aro/custom.py
Fixes a case where a cluster deletion will fail if the associated cluster resources are already deleted, or the worker_profiles enricher fails, resulting in the oc cluster's worker_profiles being `nil`.  
Cannot delete a cluster under the above circumstances.  
Python unit tests. 
No
> az aro delete worker_profile check

- pkg/monitor/cluster/clusterversions.go
- pkg/monitor/cluster/clusterversions_test.go
metric availableRP signals whether the current cluster document required updating to the
newer RP version by calling put/patch.
When no action is needed, the metric is empty.
Added unit test. Tested locally.
> Add metric helping determine cluster action after RP rollout

- pkg/monitor/cluster/nodeconditions.go
- pkg/monitor/cluster/nodeconditions_test.go
Part of [8697880](https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/8697880)
Cleans up old dimensions in node metrics which we no longer need.
Tests updated.
No
> Cleans up old dimensions in node metrics

- pkg/monitor/cluster/cluster.go
- pkg/monitor/cluster/summary.go
- pkg/monitor/cluster/summary_test.go
For work item [№8785023](https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/8785023/).
There is currently no way to build a dashboard showing dynamic of failed clusters (failed creation or failed deletions). We do have required data in the `cluster.summary` metric, but we don't emit it for clusters where we fail to get clsuter version or a list of nodes due to this piece of code:
https://github.com/Azure/ARO-RP/blob/606bcb52e27dfd47e38772d021c5b9a2a6a7bb0f/pkg/monitor/cluster/summary.go#L23-L31
It leaves us only with a small portion of failed clusters which doesn't give us an accurate representation.
This PR changes our metrics:
* Introdueces a new metrics which contains provisioning state and failed provisioning state.
Alternatively we can keep metric as is and use …
> Cluster provisioning state metrics

- pkg/api/openshiftcluster.go
- pkg/cluster/createdat.go
- pkg/cluster/createdat_test.go
- pkg/cluster/install.go
- pkg/frontend/frontend.go
- pkg/frontend/openshiftcluster_putorpatch.go
- pkg/frontend/openshiftcluster_putorpatch_test.go
- pkg/monitor/cluster/summary.go
- pkg/monitor/cluster/summary_test.go
[Work item 9057017](https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/9057017/)
We want to have better visibility into cluster age. This PR:
* Adds `createdAt` field to the internal document which is being populated by front-end when we receive a cluster creation request
* Adds temporary piece of code required to populate `createdAt` for older clusters. We do it based on the creation timestamp from the default namespaec
* Adds the cluster creation timestamp to the `cluster.summary` metric
Includes tests
No
> Adds cluster creation timestamp to the internal document

- pkg/cluster/deploystorage.go
- pkg/cluster/deploystorage_resources.go
- pkg/cluster/resources.go
Fixes https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/9174341
This is no-op preparation for credential rotation so we could re-use these functions when required.
no-op
no
> Split resources to separate files

- pkg/api/validate/openshiftcluster_validatedynamic.go
- pkg/cluster/deploystorage.go
- pkg/env/dev.go
- pkg/util/aad/aad.go
Partially fixes [8644408](https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/8644408)
Based on https://github.com/Azure/ARO-RP/pull/1257
Additional fixes to move towards ARO in AzureUSGovernment cloud. Currently contains temporary hacks to enable cluster creation.
Run existing unit and E2E tests
No
> Make ClientCredentialsConfig cloud-aware

- .pipelines/e2e.yml
- hack/cluster/cluster.go
- pkg/util/cluster/cluster.go
- test/e2e/adminapi_cluster_list.go
- test/e2e/adminapi_redeployvm.go
- test/e2e/adminapi_resources.go
- test/e2e/list.go
- test/e2e/scalenodes.go
- test/e2e/setup.go
- test/e2e/update.go
proposed alternative to https://github.com/Azure/ARO-RP/pull/1258
> stop e2e and hack/cluster from being dependent on the RESOURCEGROUP env var

- cmd/aro/rp.go
- pkg/frontend/admin_openshiftcluster_kubernetesobjects_test.go
- pkg/frontend/admin_openshiftcluster_list.go
- pkg/frontend/admin_openshiftcluster_list_test.go
- pkg/frontend/admin_openshiftcluster_redeployvm_test.go
- pkg/frontend/admin_openshiftcluster_resources_list_test.go
- pkg/frontend/asyncoperationresult_get_test.go
- pkg/frontend/asyncoperationsstatus_get_test.go
- pkg/frontend/frontend.go
- pkg/frontend/openshiftcluster_delete_test.go
- pkg/frontend/openshiftcluster_get.go
- pkg/frontend/openshiftcluster_get_test.go
- pkg/frontend/openshiftcluster_list.go
- pkg/frontend/openshiftcluster_list_test.go
- pkg/frontend/openshiftcluster_putorpatch.go
- pkg/frontend/openshiftcluster_putorpatch_test.go
- pkg/frontend/openshiftclustercredentials_post_test.go
- pkg/frontend/security_test.go
- pkg/frontend/subscriptions_put_test.go
I spotted that the frontend enrichers use baseLog rather than the enriched log with cluster details broken out as additional fields.
This PR refactors such that the enrichers are created just in time in the frontend flows using a factory, so that the appropriate logger can be passed in.
We reuse the factory pattern used by kubeActionsFactory and as a side benefit get rid of `f.(*frontend).ocEnricher = ti.enricher`, which was a bit of an ugly hack.
Existing unit tests + e2e pass
No.
> pass enriched log to enrichers

- pkg/frontend/adminactions/upgrade.go
- pkg/frontend/adminactions/upgrade_test.go
something I noticed doing upgrades
This will make custom DNS preflight checks return the error (like when the CVO is unhealthy) instead of a non-descript 500.
tests updated
no
> Turn custom DNS upgrade errors into 500s with text

- pkg/operator/deploy/deploy.go
- test/e2e/operator.go
Currently `condition=False` is causing deployment to be "not ready" from RP standpoint. 
Conditions should not be used as liveness/readiness rp PATCH might be fixing them. 
When we add more conditions will will make it even worse.
> Conditions should not block

- pkg/util/clusterdata/clusterdata.go
- pkg/util/clusterdata/ingress_profiles_task.go
- pkg/util/clusterdata/ingress_profiles_task_test.go
Fixes https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/8670466
This PR aims at enriching information returned by azo aro show for IngressProfiles. This is needed to refresh information from database in case Default IngressProfile visibility is changed after creation or when a new IngressProfile is created afterwards.
- Unit tests available in the PR
- Manual test of az aro show after cluster creation in DEV
-> normal cluster creation, az aro show (non-regression)
-> normal cluster creation, replacement of default ingress controller by putting its scope as Internal, az aro show, check IngressProfile is updated (correctly enriched, IP, Visibility)
-> normal cluster creation, creation of an additional ingress controller, with internal scope (aside the default …
> Ingress Profile enricher

- .pipelines/mirror-images.yml
- .pipelines/templates/template-mirror-images.yml
- cmd/aro/mirror.go
Notes:
1) keeping the codebase to mirror these images to our ACR as I think we're likely to need to do that in government cloud
2) need to follow up and remove acr-geneva-pull-auth from our VSTS pipeline configs/libraries
> remove SRC_AUTH_GENEVA: anonymous read is now enabled

- pkg/api/admin/openshiftcluster.go
- pkg/api/admin/openshiftcluster_convert.go
- pkg/api/admin/openshiftcluster_validatestatic_test.go
We expose it as a metric, but not in the admin API. It was missed from the original work item / PR.
Work item [№9293969](https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/9293969).
Unit test is included
> Add createdAt into the admin API

- pkg/api/validate/openshiftcluster_validatedynamic.go
- pkg/api/validate/quota.go
Fixes _none_
Validates cluster AAD application doesn't have Application.ReadWrite.OwnedBy.  I've been suspicious for a while that this was broken, and today got to the bottom of it.  I believe the fix is correct because now it exactly matches [the code that enables or disables the cred minter](https://github.com/openshift/cloud-credential-operator/blob/d30a4e15fb7720e7446ef377ab43f3ab653f3cd9/pkg/operator/secretannotator/azure/reconciler.go#L215-L252).
A unit test is needed.  This is waiting on foundational work that @mjudeikis has in flight.  TODO for now.
No.
> validate that cluster SP does not have Application.ReadWrite.OwnedBy

- pkg/operator/controllers/alertwebhook/alertwebhook_controller.go
- pkg/operator/controllers/alertwebhook/alertwebhook_controller_test.go
Fixes https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/9303382
This PR aims at fixing the current Alertwebhook hack from Aro operator which removes AlertManagerReceiverNotConfigured alerts, which are noisy otherwise.
**! Remark: Outstanding question**. Clusters created before the change of behaviour described in the issue will need to have their configuration adjusted to in case of cluster upgrade
- Are there unit tests? Yes, modified current unit to reflect reality of recent default alertmanager.
- Are there integration/e2e tests? No, not to my knowledge, but open to suggestions
- Manual testing
+ Create a new aro cluster in dev.  Log into the web console and check AlertManagerReceiverNotConfigured is firing in Monitoring/Alerting
+ Start operator in local with this …
> Fix hack for alertwebhook to stop AlertmanagerReceivers alerts

- cmd/aro/portal.go
- pkg/deploy/deploy.go
- pkg/deploy/upgrade.go
- pkg/env/prod.go
- pkg/portal/middleware/aad.go
- pkg/portal/middleware/aad_test.go
- pkg/portal/portal.go
Partially fixes [8644408](https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/8644408)
Further changes to allow RP to work in multiple clouds.
Todo: Figure out `ContainerRegistryDNSSuffix`
E2E, unit tests, creating cluster in gov cloud.
No
> govcloud enablement, continued

- pkg/util/azureclient/apiversions.go
Relates to #1313 (quickfix, needs a proper solution for all resource types)
If List Azure Resources Geneva Action is run in a cluster which has VM snapshots in its resource group, the old code will fail due to API Version mismatch. This PR adds a snapshot specific API Version.
I ran a List on snapshots with 2020-05-01 and it didn't fail.
also ((Get-AzureRmResourceProvider -ProviderNamespace Microsoft.Compute).ResourceTypes | Where-Object ResourceTypeName -eq snapshots).ApiVersions shows that the API version is available.
N/A - fixes issue with existing code.
> adding API Version for snapshots

- test/e2e/get.go
This PR aims at adding a new e2e test, get, to validate we can get info from cluster and retrieve some enriched fields
This PR adds get.go e2e test, which checks we can retrieve the cluster just created in the test suite and then retrieve some enriched fields.
- Are there unit tests? N/A
- Are there integration/e2e tests? well, it adds a new one
N/A
> add get e2e test

- pkg/monitor/cluster/clusteroperatorconditions.go
https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/9326693
Currently, kube-storage-version-migrator is constantly reported with status Upgradeable/Unknown. This disrupts the readability of dashboards.
- Are there unit tests? No - but it is in theory possible to test the filtering of ignored. This PR is meant to gather opinions on that possibility of ignoring this status for now
- Are there integration/e2e tests? No
- If it is not possible to write automated tests, explain why and document how
to manually test and verify the feature. I am not sure how to perform a manual test on that one.
N/A
> Ignore Upgradeable/Unknown condition in pushed metrics

- pkg/api/openshiftcluster.go
- pkg/cluster/deploystorage.go
- pkg/cluster/deploystorage_resources.go
- pkg/cluster/deploystorage_test.go
- pkg/cluster/install.go
- pkg/cluster/serviceprincipal.go
Addresses errors seen in admin cluster upgrade
Store the cluster SP object ID in the database, and if we don't have it, don't fail the deny assignment ARM deploy in admin upgrade.  This should ensure we get to other updates that we need (e.g. operator and certs).
E2E
No
> store SPObjectID in database

- pkg/monitor/cluster/cluster.go
- pkg/monitor/cluster/jobconditions.go
- pkg/monitor/cluster/jobconditions_test.go
https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/9338328/
PR aims at added a new metric emitted by the monitor in order to notify about kube/openshift system jobs failures. Currently, promotheus alert emission only notify about job failure, but nothing about its name/namespace. This PR adds those to be able to monitor possibly recurring failures and/or patterns.
- Are there unit tests? Yes
- Are there integration/e2e tests? No
Possibly, I need to check.
> job condition gauge emission

- pkg/bootstraplogging/bootstraplogging.go
- pkg/cluster/delete.go
- pkg/cluster/tls.go
- pkg/deploy/generator/resources.go
- pkg/deploy/generator/templates.go
- pkg/env/dev.go
- pkg/env/env.go
- pkg/env/int.go
- pkg/env/prod.go
- pkg/operator/deploy/deploy.go
- pkg/util/mocks/env/env.go
we're half and half on clusterskeyvault and clusterkeyvault.  Let's use the latter.  I was mistaken to start the codebase with the former.
> noop rename clusterskeyvault -> clusterkeyvault

- .pipelines/templates/template-prod-e2e-steps.yml
- pkg/util/cluster/cluster.go
vnet peering code broke INT E2E and will break PROD E2E too if it's not fixed.
I'm not wild about the hard coding of the CI VNET address but am prepared to accept it to get this fixed.
Note that we have to do the subscription gymnastics because INT and DEV/PROD CI is handled in separate subscriptions.  It is supposedly possible to peer vnets across subscriptions.
> fix vnet peering code in INT

- pkg/cluster/deploystorage_resources.go
Seeing the following in E2E:
Code="DeploymentFailed" Message="Deployment failed." Details=[{"message":"{\"code\":\"DeploymentFailed\",\"message\":\"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.\",\"target\":null,\"details\":[{\"code\":\"Conflict\",\"message\":\"{\\r\\n  \\\"error\\\": {\\r\\n    \\\"code\\\": \\\"RoleDefinitionWithSameNameExists\\\",\\r\\n    \\\"message\\\": \\\"A role definition cannot be updated with a name that already exists.\\\"\\r\\n  }\\r\\n}\"}],\"innererror\":null,\"additionalInfo\":null}"}]
> make role definition name unique

- pkg/frontend/frontend.go
- pkg/frontend/ready_get.go
- pkg/frontend/security_test.go
- pkg/monitor/monitor.go
We were lucky to see a crashloop given that I removed this code (#1071).  Revert it for safety.
Wait for 2 mins before advertising readiness to help detect crashlooping services.
By eye.  Revert.
No.
> Partially revert #1071: wait for 2 mins before advertising readiness

- pkg/cluster/deploystorage.go
- pkg/cluster/install.go
- pkg/env/dev.go
- pkg/env/env.go
- pkg/env/prod.go
- pkg/util/mocks/env/env.go
n/a
According to https://stackoverflow.microsoft.com/a/245391/62320, re-PUTting our RG should re-create RP RBAC after a customer subscription migrates between tenants.
In production.
No.
> re-create RP RBAC if needed after tenant migration

- pkg/operator/controllers/routefix/routefix_controller.go
Makes `RouteFix` controller watch relevant namespace. Currently it only reconciles the namespace when it needs to reconcile `arov1alpha1.Cluster` or `appsv1.DaemonSet`. But if someone makes changes to the namespace - it will ignore the new state of the namespcae object.
Modify namespace (node selector, for example):
```
oc patch ns openshift-azure-routefix --type json -p '[{ "op": "replace", "path": "/metadata/annotations/openshift.io~1node-selector", "value": "boo" }]
```
Verifty that the namespace got reconciled by running `oc get ns openshift-azure-routefix -o yaml` and making sure that that the node selector is empty:
```
apiVersion: v1
kind: Namespace
metadata:
annotations:
openshift.io/node-selector: ""
````
> Makes RouteFix reconcile namespace

- pkg/frontend/middleware/log.go
- pkg/frontend/middleware/log_test.go
- pkg/frontend/security_test.go
Part of [9274304](https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/9274304/).
Set the IFxAudit target resource name field to the resource URI, instead of
the cluster name. During the auditing process, the audit team uses the target
resource fields to identify the affected resources.
Also, fixed incorrect ordering of the return values.
Updated unit tests.
N/A.
> Update IFxAudit Target Resource Fields

- pkg/cluster/deploystorage.go
- pkg/cluster/deploystorage_test.go
Improves catching of RequestDisallowedByPolicy during creation of ResourceGroup
Currently, RequestDisallowedByPolicy is not caught correctly I think during ensureResourceGroup. RequestDisallowedByPolicy service error is not converted in a CloudError when facing this issue during aro cluster creation (and so will result in Internal Server Error).
This PR corrects that and adds also unit tests for error handling in deploystorage step
- Are there unit tests? yes
- Are there integration/e2e tests? no
- If it is not possible to write automated tests, explain why and document how
to manually test and verify the feature.
Also tested one cluster creation and deletion (for non-reg). Did not find a way to reproduce the error case in dev.
No
> add new case for RequestDisallowedByPolicy catching with unit tests

- hack/gendiscoverycache/main.go
- pkg/cluster/removeprivatednszone.go
- pkg/cluster/removeprivatednszone_test.go
- pkg/operator/controllers/workaround/workaround_controller.go
- pkg/util/version/clusterversion.go
don't remove dns private zones if not all nodes are under MCPs
don't remove dns private zones on 4.3 clusters
remove private dns zone config setting on upgrade
also update dns config on clusters which are already upgraded
> DNS update fixes

- pkg/cluster/denyassignment.go
- pkg/cluster/denyassignment_test.go
- pkg/cluster/deploystorage_resources.go
- pkg/cluster/deploystorage_test.go
1. remove feature flag preventing Microsoft.Network/networkInterfaces/effectiveRouteTable/action
2. re-add missing rbac permission (Microsoft.Compute/snapshots/*)
3. re-deploy role definition on admin upgrade so that we correct clusters that miss the permission
> RBAC fixes

- pkg/monitor/cluster/daemonsetstatuses.go
- pkg/monitor/cluster/daemonsetstatuses_test.go
- pkg/monitor/cluster/deploymentstatuses.go
- pkg/monitor/cluster/deploymentstatuses_test.go
- pkg/monitor/cluster/jobconditions.go
- pkg/monitor/cluster/jobconditions_test.go
- pkg/monitor/cluster/machineconfigpoolconditions.go
- pkg/monitor/cluster/machineconfigpoolconditions_test.go
- pkg/monitor/cluster/podconditions.go
- pkg/monitor/cluster/prometheusalerts.go
- pkg/monitor/cluster/replicasetstatuses.go
- pkg/monitor/cluster/replicasetstatuses_test.go
- pkg/monitor/cluster/statefulsetstatuses.go
- pkg/monitor/cluster/statefulsetstatuses_test.go
Fixes our ability to see object counts. This will prevent "exploding object count" cluster issues. 
Relates to ability detect enormous amounts of objects on the clusters ddos'ing etcd
unit
no
> add count metrics for components

- docs/upstream-differences.md
Updated the link to compare upstream installer `release-4.6` branch and a branch in ARO fork.
> Updates the link in docs

- pkg/cluster/clusterserviceprincipal.go
- pkg/cluster/clusterserviceprincipal_test.go
- pkg/cluster/delete.go
- pkg/cluster/denyassignment.go
- pkg/cluster/denyassignment_test.go
* use createOrUpdateClusterServicePrincipalRBAC to migrate any clusters
back from the custom role definition to Contributor.  Currently this
will only take place on customer PUT but later the plan is that this
will go in admin PUT too.
* re-add cluster deletion handling code to clean up custom role
definitions if they still exist at cluster deletion time.
* ensure createOrUpdateDenyAssignment always PUTs the deny assignment so
that we keep it up-to-date.
@mjudeikis @gvanderpotte ptal
> More fixups from the custom role definition fallout

- .pipelines/ci.yml
Currently linting and go-test is in the same job, this making it unnecessarily indirect to figure
out which failed.
This PR makes linting a separate job, which makes understanding where CI failed easier and faster to read.
None
None
> Move linting to separate job

- cmd/aro/mirror.go
Allow one to run `go run ./cmd/aro mirror latest` instead of specifying a release image.  
Run manually
Yes - will update as part of #1406
> Add 'latest' option to mirroring script

- pkg/deploy/predeploy.go
- pkg/util/azureclient/mgmt/compute/virtualmachinescalesetvms.go
this should help prevent us timing out in deployment when scaling down VMSSes if there is a backend job running at the same time
hopefully help with recent eastasia RP deploy failure
> bump PollingDuration on VirtualMachineScaleSetVMsClient

- Dockerfile.routefix
- Makefile
- pkg/operator/controllers/routefix/routefix.go
- pkg/util/ready/ready.go
- pkg/util/version/const.go
- test/e2e/operator.go
* Logs when a node cannot recover from https://bugzilla.redhat.com/show_bug.cgi?id=1941753
* Deploys and maintains iptables rules to block ICMP traffic so we don't hit anymore
Part of https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/9588105 
First commit updates routefix DS to add a container that logs when we hit a state that will not automatically be remediated
Second commit replaces original container with 'drop-icmp' that deploys and maintains iptables rules.
Note that there is some refinement of the logging container in the second commit.
'detect' container: deployed manually to shared cluster which exhibits this issue on one node right now.  Confirmed the logs:
1. logs the problem node is "broken=true"
2. logs are shipped to Geneva
3. logs can be queried in …
> Update routefix to block ICMP and log when nodes are in a bad state

- test/e2e/adminapi_redeployvm.go
ActivityLogs.List has stopped returning the correct activity log record.  The record is visible via the portal, which uses api-version 2017-03-01-preview, but that's not available in the Go SDK.
> disable VM redeploy action test

- go.mod
- go.sum
- vendor/github.com/openshift/installer/pkg/asset/openshiftinstall/openshiftinstall.go
- vendor/modules.txt
Addresses https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/9376061/
Following Carry patch of ARO's openshift installer fork, this PR aims at vendoring the corresponding installer version which contains the override of invoker in openshift-installer-manifests ConfigMap.
- Are there unit tests? No
- Are there integration/e2e tests? No
- If it is not possible to write automated tests, explain why and document how
to manually test and verify the feature 
Cluster was created with vendored installer, openshift-installer-manifests ConfigMap invoker value checked, "cluster_install" metric queried from  openshift-monitoring/prometheus-k8s-0
Not sure, I guess not
> vendor new version of our fork of openshift installer (for invoker)

- go.mod
- go.sum
- vendor/github.com/openshift/installer/pkg/aro/dnsmasq/dnsmasq.go
- vendor/modules.txt
Vendor in the installer changes to fix a bug with selinux labels on `/etc/resolv.conf` file.  
Without this, customers who modify their VNET's DNS won't see the changes reflected on existing nodes.  No VNET changes will propagate to the nodes.  
Deploy updated operator on a cluster, ensure it has the updated systemd service. 
No
> Vendor Installer dnsmasq bugfix

- docs/prepare-your-development-environment-using-osx.md
* grep has its own `brew install grep` package, and grep to front of `path` so gnu grep is ahead of freebsd grep.
* install python3 virtualenv for mac, worth adding because package name is different on mac `virtualenv` vs `python-virtualenv`.
> Add GNUgrep and pip3 install virtualenv

- pkg/cluster/deploystorage.go
- pkg/cluster/deploystorage_test.go
it turns out it is currently necessary because if the ManagedBy flag is
set in e2e, the clean script won't clean up the RG :-(
> revert "remove group.ManagedBy change in development, don't believe it's necessary"

- pkg/operator/controllers/genevalogging/genevalogging.go
Fixes production logging `Messagepack read failed: array size overflow`
This is based on https://stackoverflow.microsoft.com/questions/249827/251179#251179 and https://genevamondocs.azurewebsites.net/collect/instrument/linux/fluent.html#size-considerations
Tested manually. Can see improvement, 
No.
> Add MsgPack value

- pkg/operator/controllers/alertwebhook/alertwebhook_controller.go
- pkg/operator/controllers/checker/checker_controller.go
- pkg/operator/controllers/dnsmasq/cluster_controller.go
- pkg/operator/controllers/dnsmasq/machineconfig_controller.go
- pkg/operator/controllers/dnsmasq/machineconfigpool_controller.go
- pkg/operator/controllers/genevalogging/genevalogging_controller.go
- pkg/operator/controllers/monitoring/monitoring_controller.go
- pkg/operator/controllers/node/node_controller.go
- pkg/operator/controllers/pullsecret/pullsecret_controller.go
- pkg/operator/controllers/rbac/rbac_controller.go
- pkg/operator/controllers/routefix/routefix_controller.go
- pkg/operator/controllers/workaround/workaround_controller.go
Makes the ARO operator use more appropriate context and clarifies the comment around the ctx in the `Reconcile` methods.
> Replaces Background ctx with TODO one

- cmd/aro/operator.go
- pkg/operator/apis/aro.openshift.io/v1alpha1/cluster_types.go
- pkg/operator/controllers/checker/checker_controller.go
- pkg/operator/controllers/checker/const.go
- pkg/operator/controllers/checker/machinechecker.go
- pkg/operator/controllers/checker/serviceprincipalchecker.go
- pkg/operator/controllers/checker/serviceprincipalchecker_test.go
Work in progress for some early feedback
Fixes [8858759](https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/8858759/)
Expose the cluster service principal validity as a condition in the ARO cluster CRD through use of the operator. 
Unit tests, e2e, manual
Check the Service Principal is Valid
```bash
oc get cluster cluster -o json | jq -r '.status.conditions[] | select(.type == "ServicePrincipalValid") | .'
{
"lastTransitionTime": "2021-01-04T23:57:03Z",
"message": "service principal is valid",
"reason": "CheckDone",
"status": "True",
"type": "ServicePrincipalValid"
}
```
Get Service Principal Information
```bash
CLUSTER=bvesel
RESOURCEGROUP=bvesel
CLUSTER_CLIENT_ID=$(az aro show -g bvesel -n $CLUSTER | jq -r .servicePrincipalProfile.clientId) …
```
> Operator: Expose Cluster SP as Condition

- Makefile
The number of characters that is output from the `--short` option in `git rev-parse` is defaulted to the effective value of `core.abbrev` config variable, which can be different across systems.  
Specifying a specific amount should ensure that if any config changes are made through either by the user or through different system/git default values will result in a consistent experience and image reference across runs.  
__NOTE:__ This matches the amount currently set in the openshiftcluster doc in cosmos as well as the operator image tag used deployed to production clusters.    
e2e
No
> Specify Length of Commit Hash for Tags 

- hack/ssh-agent.sh
Makes $CLUSTER required only if $RESOURCEID is missing
Manually test hack scripts followng [this doc](https://github.com/Azure/ARO-RP/blob/50b70103f1d012a4bbbc640147230de33fe427fc/docs/deploy-development-rp.md#debugging).
> Changes required variables in ssh-agent.sh

- .github/PULL_REQUEST_TEMPLATE.md
- docs/deploy-development-rp.md
- hack/ssh-agent.sh
Minor update in local dev documentation and usage update in `hack/ssh-agent.sh`. Provide more detail on how `hack/agent.ssh` works.
The parameter for the `hack/ssh-agent.sh` is not the name of the node, but the name of the NIC on the node as shown [here `ssh-agent.sh`](https://github.com/bryanro92/ARO-RP/blob/d4ad225184bf9b9f596073c3dad1d267676e7590/hack/ssh-agent.sh#L41). 
For reasons unknown to me at this time: 
* master nodes are created with pattern `Resourcegroup-Purpose-Number` and master NICs are created and bound to nodes with the pattern `Resourcegroup-PurposeNumber`
* worker nodes are created with pattern `Resourcegroup-Purpose-RandID` and worker NICs follow the pattern `Resourcegroup-Purpose-RandID`
Given that information, to connect to masters you provide the arg master[0-2], …
> Ssh docs/examples , PR template update

- cmd/aro/main.go
- cmd/aro/portal.go
- pkg/frontend/security_test.go
- pkg/portal/kubeconfig/kubeconfig.go
- pkg/portal/kubeconfig/kubeconfig_test.go
- pkg/portal/kubeconfig/proxy_test.go
- pkg/portal/middleware/aad.go
- pkg/portal/middleware/aad_test.go
- pkg/portal/middleware/log.go
- pkg/portal/middleware/log_test.go
- pkg/portal/portal.go
- pkg/portal/security_test.go
- pkg/util/log/log.go
Partially fixes [9509844](https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/9509844/).
This PR updates the admin portal's `Log` middleware to generate audit logs for
all inbound requests. The ensures that the ARO-RP admin portal is compliant
with the MSFT Software Development Lifecycle (SDL)/OSA security audit
requirements.
The implementation in this PR closely aligns with that in #1243.
* Added additional unit tests
* Used `curl` to send requests to unauthenticated endpoints at https://localhost:8444. 
* Sample test output attached to [story](https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/9509844/)
* Unable to test JIT-authenticated endpoints in local environment
In the `pkg/portal/security_test.go` unit test, I had to omit the audit log
checks …
> Add IFxAudit Logging To Admin Portal

- pkg/operator/controllers/workaround/cleanprompvc.go
- pkg/operator/controllers/workaround/cleanprompvc_test.go
- pkg/operator/controllers/workaround/workaround_controller.go
Fixes https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/9450186/
Introduce workaround to remove stale prometheus-db PVCs
left after switch to emptydrive as store by disabling featureGate
PersistentPrometheus.
Added unit tests with mocks.
Provided detailed comment in the workaround header.
> Add prometheus PVC clean workaround

- pkg/operator/controllers/monitoring/monitoring_controller.go
- pkg/operator/controllers/monitoring/monitoring_controller_test.go
Fixes [8964694](https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/8964696/)
Removes the persistent volume configuration for prometheus by not allowing the setting to be triggered by the feature flag in the operator.  This will disable persistent prometheus across the fleet of clusters.
Modified unit tests that reflect the disabling of the prometheus persistence.  
`None`
> Remove persistence prometheus

- go.mod
- go.sum
- vendor/github.com/openshift/installer/pkg/aro/dnsmasq/dnsmasq.go
- vendor/modules.txt
Fixes https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/9745819/
Requires ARO operator image deployment.
If dnsmasq is suddenly killed the ExecStart part of service unit might rerun causing /etc/resolv.conf.dnsmasq to point to localhost.
This file is used by dnsmasq running on localhost - this leads to a loop in DNS resolution causing image pull backoff and other issues.
set ARO_IMAGE env var to a location you can push images to
make publish-image-aro
start the RP and create a cluster
The cluster should have the updated service unit file deployed.
oc debug node/[one of the nodes in the cluster] --image=fedora:31 (or any other image)
chroot /host
cat /etc/resolv.conf.dnsmasq
killall -9 dnsmasq
cat /etc/resolv.conf.dnsmasq
Both times the resolv.conf.dnsmasq should point …
> DNSMasq override fix

- pkg/monitor/cluster/cluster.go
- pkg/monitor/cluster/machineconfigpool.go
- pkg/monitor/cluster/machineconfigpool_test.go
- pkg/monitor/cluster/machineconfigpoolunmanagedcounts.go
emit count of nodes which are not managed by MCP
```
=0 is expected normal (all nodes are managed) 
>0 mcp isn't managing all nodes 
<0 nodes are missing from mcp
```
Fixes User Story 9534737 in ADO
Monitor for unmanaged nodes. Defined as a difference between a count of known nodes (`oc get nodes`) and the total of machineconfigpool.machinecount (`oc get mcp`) 
1. Create a new machineset with bad labels:
https://docs.openshift.com/container-platform/4.6/machine_management/creating_machinesets/creating-machineset-azure.html
```
spec:
metadata:
labels:
node-role.kubernetes.io/tester: ""
node-role.kubernetes.io/worker: "no"
```
2. Note the number of nodes is different from the machineconfigpool.machinecount in `oc get nodes,machines,machineset,mcp -A`
3. Check the number emitted to Geneva is …
> Monitor for MCP unmanaged nodes

- pkg/cluster/arooperator.go
Partially helps Fix: https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/9404970/
Add error verbosity when ensuring ARO Operator. Verbosity is needed when tracing the reason for timeouts. Currently many parts of ensure can fail with timeout.
This PR helps adding point to the logs from which we can start the search.
Does not apply
Self documentary
> Add log verbosity for ensureAROOperator

- pkg/cluster/tls.go
Partially Fixes #[9404950](https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/9404950/)
Unwraps the error and return cloudError to provide customer more info.
Add log to show trace of timeouts when it happens.
Does not apply
Self explanatory, info provided in commit.
> Add verbosity to tls createCertificate

- pkg/cluster/install.go
Fixes cases where we remove DNS zone without notice 
WIll be re-enabling once communication is sorted out. 
No
No
> Stop removing DNS

- pkg/operator/controllers/routefix/routefix.go
Fixes production ssh. Most of this are just small cosmetics making it to real easier. Change is how we mount host path. 
This should fix SSH in production
Manually tested on shared cluster with custom image deployed and geneva action
No
> Fix SSH in prod

- pkg/operator/controllers/routefix/routefix.go
The detect container in routefix ds is failing after changes made to address ssh issues.
Fixes https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/9877734
Switch to full path for br0 to successfully run ovs-ofctl in detect container.
Manually tested.  I suspect RP E2E was catching this, we saw some failures.  Will have to investigate further and will add to this PR if required.
No, related KCS already updated: https://access.redhat.com/solutions/5252831
> Use unix socket for br0 so detect container works in routefix DS

- pkg/operator/controllers/workaround/systemreserved.go
- pkg/operator/controllers/workaround/systemreserved_test.go
Fixes hidden values we took over
Fixes values which are not added anymore by kubelet defaulting code
test in prod
no
> Eviction hard custom value fix: no more hiding the default values 

- .pipelines/e2e-with-billing.yml
FIX: set RP mode to empty string, this job calls the prod e2e steps so we should use the prod rp fp id
Fixes https://msazure.visualstudio.com/AzureRedHatOpenShift/_build/results?buildId=42572582&view=logs&j=df9ad2af-5995-5033-aecf-e677e5d59e8d&t=a5ded6da-dce5-5d24-ad96-b2ceb408f1a4 resulting from logic @ https://github.com/Azure/ARO-RP/blob/master/.pipelines/templates/template-prod-e2e-steps.yml#L31
RP Mode should ideally be set as a variable in the ADO pipeline, but alas we are toggling it at the pipeline/template level. This PR sets rpMode to empty string, which in the child template being called sets the `AZURE_FP_CLIENT_ID` to the prod instead of INT.
The goal is to get the manual prod pipelines running against the prod RP FP ID; I am open to other suggestions on how to achieve that. …
> FIX: set RP mode to empty string

- pkg/api/v20200430/openshiftcluster_validatestatic.go
- pkg/api/v20200430/openshiftcluster_validatestatic_test.go
- pkg/api/v20210131preview/openshiftcluster_validatestatic.go
- pkg/api/v20210131preview/openshiftcluster_validatestatic_test.go
Fixes issues with 2 ingress controllers and update uperations
Currently we validate ingress controllers on update.
As these fields are immutable - we should not do this tin the first place.
They are validate in Delta validators already. 
This is no difference than machineSet validators. 
Test with :fire: 
no
> Ingress profile validator fixups

- pkg/operator/controllers/routefix/routefix_controller.go
Adds consistency in the operator code
```
Owns defines types of Objects being **generated** by the ControllerManagedBy,
and configures the ControllerManagedBy to respond to create, 
delete and update events by *reconciling the owner object
```
Adding this will reconcile the routefix controller in the event the `privileged-routefix` SCC is deleted, etc.
Current Unit tests and E2E 
None
> Add SecurityContextConstraints to OWNS in Routefix controller

- pkg/operator/controllers/alertwebhook/alertwebhook_controller.go
- pkg/operator/controllers/monitoring/monitoring_controller.go
- pkg/operator/controllers/pullsecret/pullsecret_controller.go
- pkg/operator/controllers/workaround/systemreserved.go
When `Reconcile` returns an error, the job will be requeued taking rate limiting into account which should reducing chatter with the API server.
Existing unit tess + manual testing. For manual testing, you need to [run the operator locally](https://github.com/Azure/ARO-RP/tree/c98f6b589e1ef62895b80c91db8502207f7ffc4c/pkg/operator#how-to-run-the-operator-locally-out-of-cluster) trigger reconciliation of the resources by making changes to watced resources like this:
```
oc edit cluster/cluster
oc edit -n openshift-monitoring secret alertmanager-main -o yaml
oc -n openshift-config delete secret pull-secret
oc -n openshift-monitoring edit cm cluster-monitoring-config -o yaml
```
No, it is refactoring of the existing functionality
> Removes unnecessary retries from the reconcilers

- pkg/operator/controllers/monitoring/monitoring_controller.go
- pkg/operator/controllers/monitoring/monitoring_controller_test.go
- pkg/operator/controllers/workaround/cleanprompvc.go
- pkg/operator/controllers/workaround/cleanprompvc_test.go
- test/e2e/operator.go
Addresses: [Bug 9991650](https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/9991650/)
If one sets the below yaml on the configmap named "cluster-monitoring-config" in the "openshift-monitoring" namespace, the cluster operator will go unhealthy because we currently are only resetting any storage requested size.  The cluster monitoring operator is dumb and will just blindly apply the volumeClaimTemplate in the configmap to the prometheus statefulset even if it's not a valid volumeClaimTemplate (volumeClaimTemplate requires a size to be valid). 
Instead, let's just zero out the volumeClaimTemplate so that the monitoring cluster operator should never go unhealthy.  
```yaml
config.yaml: |
prometheusK8s:
volumeClaimTemplate:
spec:
storageClassName: managed-premium
```
This …
> Bugfix: Revert any `volumeClaimTemplate` values set in openshift-monitoring ConfigMap

- pkg/util/cluster/cluster.go
Fixes E2E failing in USGov INT because it is hardcoded for public cloud INT.
Initially hard coded for public cloud int.  Use env to identify the
cloud and if USGov use hard coded ff int resource.  This is not ideal,
but is parallel of what is done in public.  Will create card to track a
real fix.
Verify public cloud INT E2E still works.  PR will trigger that.
New ADO for tracking this as it doesn't scale for future clouds.
> Add support for USGov e2einfra

- pkg/util/ready/ready.go
- pkg/util/ready/ready_test.go
Fixes #1271 
Adds tests to the package `pkg/util/ready`.  
Issue #1271 points out issues that this package experienced weird behavior.  With no unit tests, it was hard to pinpoint what was driving the weird behavior.  Adding tests will increase our coverage and create more confidence when using the functions supplied by this package.  
This PR will add tests to the package `pkg/util/ready`.  The package exports functions directly so no mocking is accomplished with interfaces. The mechanism used to tests these functions were using the built-in library that supports all the types referenced in the functions (i.e. corev1.Nodes, corev1.Pods, etc).  Also using `fake` clientsets provided by the k8s/openshift libraries allow the creation/failure of objects that are necessary to create errors for …
> tests: add tests for util/ready package

- cmd/aro/mirror.go
Fixes [9962203](https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/9962203/)
FF INT needs to use public Geneva images. This will allow that.
Try mirroring images on FF INT
No
> Allow Geneva source ACR override

- cmd/aro/mirror.go
Fixes https://dev.azure.com/msazure/AzureRedHatOpenShift/_workitems/edit/10060677
In some environments, there are ACRs that do not allow anonymous pull access.  This addresses that concern.
Run OB pipeline and Ev2 Release
N/A
> Update to mirror to check for env var for geneva

- pkg/deploy/deploy_rp.go
Deploy ARO to USGov.
Cloud names in go-autorest don't match names used by az cli.  Deploy is
using az cli.  So it needs translated for public and usgov.
Existing tests, E2E, etc.
No
> Translate cloud names for deploy

- pkg/operator/controllers/monitoring/monitoring_controller.go
- pkg/operator/controllers/monitoring/monitoring_controller_test.go
Wrote this while we were talking about it in the review meeting.  Empty out the PVC for Alertmanagermain as it's configurable from an openshift-monitoring perspective.
> Don't allow Setting AlertManager PVC

- pkg/mirror/graph.go
Fixes broken mirroring due to openshift-release.svc endpoint being decommissioned.
Point to newer endpoint which is what old openshift-release.svc redirected to (confirmed with OCP engineering).
Verified manually endpoint returns data expected.  INT and PROD mirror runs will show if this is successful.  Impact is low of not mirroring, it's an additive sync and doesn't destroy anything prior to executing.
No
> Updated graph endpoint for mirror (svc was decommissioned)

- README.md
minor README doc update for dnsmasq controller. explain that it points to azure load balancers.
> minor README doc update for dnsmasq

- python/az/aro/azext_aro/_params.py
Fixes [699](https://github.com/Azure/ARO-RP/issues/699) 
Upstream PR is https://github.com/Azure/azure-cli/pull/18457
Adds CIDR ranges for both pod and service network in the help command of the azure cli. 
az aro create --help with output showing the help command and unit test that exists already.
output: 
```bash
--pod-cidr                     : CIDR of pod network. Should be a minimum of /18 or larger.
--pull-secret                  : Pull secret of cluster.
--service-cidr                 : CIDR of service network. Should be a minimum of /18 or larger.
```
No additional documentation is necessary.
> python: add pod/service cidr minimum in help

- pkg/util/keyvault/keyvault.go
- pkg/util/keyvault/keyvault_test.go
In non-public cloud we cannot use "reserved.aroapp.io" CN.
Use long CN to fabricate a shorter CN.
Unit test and E2E.
No.
> Support short CN in any cloud

- test/e2e/adminapi_redeployvm.go
Fixes timeout in E2E waiting for activity logs.
Increase timeout waiting for vm redeploy.  Logs show some take over 5 minutes (6 min 7 seconds in one case).  And tests are failing consistently timing out even when the activity log viewed later indicates it finished in under 5 minutes.
Verify E2E passes.
No
> Increase timeout for getting activity logs to 10 minutes

- python/az/aro/azext_aro/custom.py
Fixes https://github.com/Azure/azure-cli/issues/18501
If you call `az aro delete -g myRg -n cluster` on a cluster that doesn't exist it won't output a nice message.  instead it will output something like:
```bash
The command failed with an unexpected error. Here is the traceback:
local variable 'oc' referenced before assignment
Traceback (most recent call last):
File "/usr/lib64/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
cmd_result = self.invocation.execute(args)
File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
raise ex
File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
results.append(self._run_job(expanded_arg, cmd_copy))
File …
```
> Fix non-existing resource on aro_delete

- Dockerfile.fluentbit
- Makefile
- pkg/util/version/const.go
Ev2 cannot build the fluentbit image with base image rhel7
Switch our fluentbit image from rhel7 base to ubi7/ubi-minimal base.
Bump fluentbit version to 1.7.8-1
Manually verified on development cluster.
Yes, we need documentation on how we manage fluentbit images.  Current process is a manual release.  That means once this is approved the new image needs to be pushed, ideally before merged, else cluster logging stacks will be broken.  I have added "hold" label.  If merged early it would break only INT, so blast radius is small.
> Bump fluentbit version, change to ubi7/ubi-minimal base image

- test/e2e/adminapi_redeployvm.go
Fixes timeouts waiting for activity logs on redeployvm E2E test.
It was recently increased from 5 to 10 minutes but it isn't enough.  Per
documentation (linked in code now) it can take up to 15 minutes to ship
activity logs in some situations.
Exiting E2E.
No
> Increase redeployvm wait to 15 minutes

- pkg/cluster/deploystorage.go
- pkg/cluster/fixinfraid.go
- pkg/cluster/fixinfraid_test.go
- pkg/cluster/install.go
- pkg/cluster/ipaddresses.go
Fixes put or patch for new clusters
Retrofit for old clusters
First we fixup broken put or patch by adding missing infra ID override (commit 1)
We add missing infraID into database so we can remove override across the code. 
No
No
> Fixup for infraID and legacy retrofit

- hack/db/db.go
Fixes #1557 
The `hack/db.go` script now uses the RP client secret from the environment variable instead of the user's `az` command login credentials for accessing the key vault. We need that so that successfully running the script does not depend on the ADD groups the user is in.
Manually tested by running `hack/get-admin-kubeconfig.sh [...]`. First I verified that it doesn't work without the fix by trying to run the command with a user without the necessary permissions, then I reran the script with the fix and the same user.  
I also verified that `hack/ssh-agent.sh`, which relies on the same code, still works.
I could not find documentation on this, but it also works more intuitively now so probably no documentation required.
> Use RP client credentials to access KeyVault in DB script

- pkg/util/instancemetadata/prodfromenv.go
Fixes, in theory, MSI endpoint not being set for E2E run via Ev2.
Get errors in E2E that MSI_ENDPOINT is not setup.  This is one change from the prod instancemetadata we took out.  We expect this IMDS call to work given manual tests.
Unit test and try E2E in INT with MSI.
No.
> Add MSI back into prodfromenv

- pkg/api/admin/openshiftcluster.go
- pkg/api/admin/openshiftcluster_convert.go
- test/e2e/adminapi_cluster_get.go
Fixes #1537
Adds the InfraID of the Cluster to the Admin API.
Added a test case to the e2e tests.
> add InfraID to admin API

- Makefile
macOS has different patch for python executable. This change 
Run `make pyenv` on linux and macOS
> Makes pyenv target more platform agnostic

- pkg/util/cluster/cluster.go
- test/e2e/get.go
Fixes path from Ev2 run E2E to infra.
With adoption of Ev2, e2e.test runs in an ACI and doesn't have access to the private e2e clusters.  We have no requirement to make the clusters private.
This has been successfully tested in a fork of ARO-RP in FF INT for several weeks.
No.
> Make CI/E2E clusters public

- pkg/portal/security_test.go
Fixes [Issue-1563](https://github.com/Azure/ARO-RP/issues/1563)
There was an intermittent issue with TestSecurity unit tests. It was reproducible by continuously running this test.
This PR checks for the payload to be part of the map as well vs just having a single entry which was not fully populated previously in some rare cases due to a race condition.
Ran the following test and the previously discovered issue is no longer reproducible.
```bash
while true
do
go clean -testcache
go test -timeout 30s -run ^TestSecurity$ ./pkg/portal
echo $?
done
```
n/a
> Adj poller to check for payload

- cmd/aro/operator.go
- pkg/operator/controllers/routefix/routefix_controller.go
- pkg/util/version/clusterversion.go
Fixes regression from https://github.com/openshift/cluster-network-operator/pull/1059/files 
This will remove existing route fix from Azure as it now part of upstream. 
Tested manually. 
No
> Fixup routefix for 4.7.15+

- .sha256sum
- go.mod
- go.sum
- pkg/api/admin/openshiftcluster.go
- pkg/api/admin/openshiftcluster_convert.go
- pkg/api/openshiftcluster.go
- pkg/api/v20210131preview/openshiftcluster.go
- pkg/api/v20210131preview/openshiftcluster_convert.go
- pkg/client/services/redhatopenshift/mgmt/2021-01-31-preview/redhatopenshift/models.go
- pkg/cluster/deployresources_resources.go
- pkg/cluster/generateconfig.go
- pkg/util/clusterdata/worker_profiles_task.go
- python/client/azure/mgmt/redhatopenshift/v2021_01_31_preview/models/_models.py
- python/client/azure/mgmt/redhatopenshift/v2021_01_31_preview/models/_models_py3.py
- swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/preview/2021-01-31-preview/redhatopenshift.json
- vendor/github.com/openshift/installer/pkg/aro/dnsmasq/dnsmasq.go
- vendor/github.com/openshift/installer/pkg/asset/machines/azure/machines.go
- vendor/github.com/openshift/installer/pkg/types/azure/machinepool.go
- vendor/modules.txt
Relevant installer (fork) PR: https://github.com/mjudeikis/installer/pull/5
Fixes work item [№9586080](https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/9586080/).
Addds support for:
* Server-Side Encryption 
* Encryption At Host support
Execute the following command to register the feature for your subscription (**Not required in ARO dev sub**):
```
az feature register --namespace Microsoft.Compute --name EncryptionAtHost
```
```
RESOURCEGROUP=$USER-test
CLUSTER=$RESOURCEGROUP-cluster
CLUSTER_DOMAIN=<replace-me> # dwfcu1jm, for example. Generate your own
LOCATION=eastus
KEYVAULT_NAME=$USER-kv
KEYVAULT_KEY_NAME=$USER-disk-encryption-key
DISK_ENCRYPTION_SET_NAME=$USER-disk-encryption-set
CLUSTER_SP_NAME=$CLUSTER
AZURE_FP_CLIENT_ID=<known-value-from-sub>
```
Resource …
> Server-Side Encryption and Encryption At Host support

- pkg/cluster/deploystorage_resources.go
Fixes ability to tag ONLY RG
This permission allows to tag Resource RP resources only as its scoped resource.
So we get ability to tag Resource Groups only. but nothing else for now. 
No
No
> Enable RG tagging

- pkg/env/prod.go
Improves SKU request: ask Azure API for SKU related only to the RP location, not all SKUs.
Tested locally in eastus. I guess we will have to test in prod for rest of the regions.
No, it is just optimisation.
> Improves SKU request

- pkg/cluster/install.go
- pkg/cluster/install_test.go
Enable failure gathering in dev
Our e2e does not show failures currently. I think it should
no
no
> Enable failure gathering in dev

- pkg/deploy/upgrade_rp.go
We seen few flakes where this is just on the limit of how long we can wait. Bumping timeout a bit 
Fix deploy flakes
no
no
> Increase wait timeout

- .pipelines/onebranch/pipeline.bootstrapper.official.yml
- .pipelines/onebranch/pipeline.bootstrapper.pullrequest.yml
- .pipelines/onebranch/scripts/bootstrapper.sh
- .pipelines/onebranch/templates/template-bootstrapper-fluentbit.yml
Fixes: https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/10157189
Builds and publishes the Fluentbit image for Ev2 to consume and push into ACR
Manually tested
N/A
> Add Fluentbit Image to bootstrapper pipeline

- pkg/operator/controllers/workaround/workaround_controller.go
Follow up for https://github.com/Azure/ARO-RP/pull/1579#discussion_r666047504
I think logging here is not necessary becuase controller-runtime does logging for us:
https://github.com/kubernetes-sigs/controller-runtime/blob/5a2de70a6eb671a133e421c92c4445dbd0051074/pkg/internal/controller/controller.go#L298-L304
> Removes unnecessary logging

- python/az/aro/azext_aro/_aad.py
Fixes
This makes AAD Manager cloud aware between Azure Public Cloud and Azure US Government Cloud
> AAD Manager cloudaware changes

- pkg/util/instancemetadata/prodfromenv.go
This reverts commit 5395132447f9d609fa2f7097854f6fc32098535f. I don't understand why we need this dead piece of code. Or is it not dead and actually being used in some non obvious way? Could please someone explain?
Comes from https://github.com/Azure/ARO-RP/pull/1542#issuecomment-868431901:
> I don't understand why we need `newServicePrincipalTokenFromMSI` in `prodFromEnv`. We do not call it anywhere.
> Revert "Add MSI back into prodfromenv (#1542)"

- cmd/aro/dbtoken.go
RP startup errors out with 
```
oidc: issuer did not match the issuer returned by provider, expected "https://login.microsoftonline.us/cab8a31a-1906-4287-a0d8-4eef66b95f6e/" got "https://sts.windows.net/cab8a31a-1906-4287-a0d8-4eef66b95f6e/"
```
this is because we use "https://login.microsoftonline.us" (comes from autorest environment config) but we compare it with the issuer advertised by the v1 well-known openid config endpoint :   
V1 : 
https://login.microsoftonline.us/cab8a31a-1906-4287-a0d8-4eef66b95f6e/.well-known/openid-configuration
returns issuer as `https://sts.windows.net/cab8a31a-1906-4287-a0d8-4eef66b95f6e/`
V2: 
https://login.microsoftonline.us/cab8a31a-1906-4287-a0d8-4eef66b95f6e/v2.0/.well-known/openid-configuration
returns issuer as …
> fix: use oidc v2.0 issuer in db-token.service

- pkg/operator/controllers/node/node_controller.go
The node controller in the ARO operator is logging many of the following errors on reconcile:
```
ERRO[2021-07-15T11:41:10-04:00]vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:267 controller.(*Controller).reconcileHandler() Reconciler error clusters.aro.openshift.io "cadenaro-7jbhs-master-2" not found  Node= controller= controller-runtime= manager= name=cadenaro-7jbhs-master-2 namespace= reconciler group= reconciler kind=Node
ERRO[2021-07-15T11:41:10-04:00]vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:267 controller.(*Controller).reconcileHandler() Reconciler error clusters.aro.openshift.io "cadenaro-7jbhs-worker-eastus1-qrh7b" not found  Node= controller= controller-runtime= manager= name=cadenaro-7jbhs-worker-eastus1-qrh7b …
```
> Fix reconciler errors from Node controller

- pkg/cluster/condition.go
- pkg/cluster/condition_test.go
We observed the failure where timeline is like this:
15:02 Master VM created
15:08 Bootstrap wait started
15:13 Worker put observed in CRP
15:17 Bootstrap complete log live observed [CODE](https://github.com/mjudeikis/installer/blob/b3dae7f4736bcd1dbf5a1e0ddafa826ee1738d81/data/data/bootstrap/files/usr/local/bin/report-progress.sh#L15)
15:39 `bootstrapConfigMapReady` failed with timeout
For some reason bootstrap completed we never read its value.
This will log errors we are getting to help identify if this is coming from informers cache, api unavailability, etc
Hunt the flakes...
No
No
> Debug bootstrapConfigMapReady phase

- cmd/aro/operator.go
- pkg/cluster/arooperator.go
- pkg/operator/controllers/alertwebhook/alertwebhook_controller.go
- pkg/operator/controllers/alertwebhook/alertwebhook_controller_test.go
- pkg/operator/controllers/azurensg/azurensg_controller.go
- pkg/operator/controllers/azurensg/subnetnsg.go
- pkg/operator/controllers/azurensg/subnetnsg_test.go
- pkg/operator/controllers/checker/checker_controller.go
- pkg/operator/controllers/checker/internetchecker.go
- pkg/operator/controllers/checker/serviceprincipalchecker.go
- pkg/operator/controllers/clusteroperatoraro/clusteroperatoraro_controller.go
- pkg/operator/controllers/genevalogging/const.go
- pkg/operator/controllers/genevalogging/genevalogging.go
- pkg/operator/controllers/genevalogging/genevalogging_controller.go
- pkg/operator/controllers/machine/machine.go
- pkg/operator/controllers/machine/machine_controller.go
- pkg/operator/controllers/machine/machine_controller_test.go
- pkg/operator/controllers/monitoring/monitoring_controller.go
- pkg/operator/controllers/node/node_controller.go
- pkg/operator/controllers/pullsecret/pullsecret_controller.go
- pkg/operator/controllers/pullsecret/pullsecret_controller_test.go
- pkg/operator/controllers/rbac/rbac_controller.go
- pkg/operator/controllers/routefix/routefix.go
- pkg/operator/controllers/routefix/routefix_controller.go
- pkg/operator/controllers/workaround/const.go
- pkg/operator/controllers/workaround/ifreload.go
- pkg/operator/controllers/workaround/systemreserved.go
- pkg/operator/controllers/workaround/workaround_controller.go
- pkg/operator/controllers/workaround/workaround_controller_test.go
- pkg/operator/deploy/deploy.go
Fixes [10345343](https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/10345343)
Just a minor noop for legibility. Right now arguments, fields, and one function definition are not in a consistent order in the ARO operator, which makes it a little harder to read. Additionally, names are not completely standardized.
This PR standardizes the order and/or names of some arguments, fields, variables, functions, and types.
It also places some constants into separate files.
Run existing tests.
No, changes are entirely superficial.
> standardize names/order of args/fields in ARO operator

- pkg/api/validate/dynamic/dynamic.go
- pkg/operator/controllers/checker/serviceprincipalchecker.go
https://github.com/Azure/ARO-RP/pull/1595 needs to be merged first.
Adds a simplified constructor for dynamic validator used in the ARO operator.
> Refactor dynamic validator

- pkg/operator/controllers/routefix/routefix_controller.go
- pkg/operator/controllers/routefix/routefix_controller_test.go
Fixes 4.6 cluster upgrade with route fix
It was backported to 4.6 too :/ 
Unit
Maybe
> Route fix 4.6

- pkg/operator/controllers/routefix/routefix_controller.go
- pkg/operator/controllers/routefix/routefix_controller_test.go
Fixes https://github.com/Azure/ARO-RP/pull/1618#discussion_r672469019
Changes fix version for routefix on 4.6 to correct z.
Run existing tests; verify manually that 4.6.37 contains `drop-icmp` (see https://openshift-release.apps.ci.l2s4.p1.openshiftapps.com/releasestream/4-stable/release/4.6.37).
No
> correct fix version for icmp on 4.6

- .sha256sum
- pkg/api/admin/openshiftcluster.go
- pkg/api/admin/openshiftcluster_convert.go
- pkg/api/admin/openshiftcluster_validatestatic_test.go
- pkg/api/openshiftcluster.go
- pkg/api/v20210131preview/openshiftcluster.go
- pkg/api/v20210131preview/openshiftcluster_convert.go
- pkg/api/v20210131preview/openshiftcluster_validatestatic.go
- pkg/api/v20210131preview/openshiftcluster_validatestatic_test.go
- pkg/client/services/redhatopenshift/mgmt/2021-01-31-preview/redhatopenshift/enums.go
- pkg/client/services/redhatopenshift/mgmt/2021-01-31-preview/redhatopenshift/models.go
- pkg/cluster/generateconfig.go
- pkg/util/cluster/cluster.go
- python/client/azure/mgmt/redhatopenshift/v2021_01_31_preview/models/__init__.py
- python/client/azure/mgmt/redhatopenshift/v2021_01_31_preview/models/_azure_red_hat_open_shift_client_enums.py
- python/client/azure/mgmt/redhatopenshift/v2021_01_31_preview/models/_models.py
- python/client/azure/mgmt/redhatopenshift/v2021_01_31_preview/models/_models_py3.py
- swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/preview/2021-01-31-preview/redhatopenshift.json
ADO [9823641](https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/9823641/)
Adds SDNProvider to the API
Sets OVNKubernetes as the default option for E2E
Maintains OpenShiftSDN as the default option for production
Unit tests exists for API behavior (`make test-go`) 
E2E tests will transition to OVNKubernetes
Auto-generated Swagger API client docs are available in PR.
> Default to OVNKubernetes NetworkType for E2E, enable API access for production

- .pipelines/onebranch/pipeline.bootstrapper.pullrequest.yml
- .pipelines/onebranch/templates/template-bootstrapper-fluentbit.yml
Fixes: https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/10157198
This allows a user to decide if they want to build the fluentbit container during the bootstrapping pipeline.  It defaults to false and will skip building.
Versioning will remain in the pipeline template to require peer reviews.
https://dev.azure.com/msazure/AzureRedHatOpenShift/_build/results?buildId=44742337&view=results (With Fluentbit)
https://dev.azure.com/msazure/AzureRedHatOpenShift/_build/results?buildId=44741921&view=results (Without Fluentbit)
No
**NOTE**: const.go is still hardcoded for version 1.7.8-1.  While that exists in our local ACRs, updating that file is outside of the scope of this pipeline work.
> Add toggle to build fluentbit

- Makefile
Fixes: 
`make aro` would tag images as `-dirty` as well as throw the following error:
`/bin/sh: 1: [[: not found`
Fixes:
Building container from `Dockerfile.aro-multistage` would fail with the following error:
```bash
#12 [builder 5/5] RUN make aro && make e2e.test 
#12 0.435 go generate ./... 
#12 0.435 make: go: Command not found 
#12 0.435 make: *** [generate] Error 127 
#12 ERROR: executor failed running [/bin/sh -c make aro && make e2e.test]: runc did not terminate sucessfully 
```
Fixes the above issues
https://dev.azure.com/msazure/AzureRedHatOpenShift/_build/results?buildId=44752229&view=results
N/A - fixes build issue
> Update Makefile to specify shell

- .config/CredScanSuppressions.json
Fixes credscan triggering on unit tests.
Suppress credscan in certificateRefresher_test.go
Existing tests.  Validated passes scanning in internal test.
No
> Add credscan suppression for certificateRefresher_test.go

- pkg/deploy/devconfig.go
Missing fields cause `make deploy` to fail because dev-config.yaml target doesn't have all the RP Config fields used
`make deploy` using this
No
> Add Missing RP Configs to devconfig

- pkg/api/validate/dynamic/dynamic.go
- pkg/operator/controllers/checker/serviceprincipalchecker.go
- pkg/operator/controllers/checker/serviceprincipalchecker_test.go
#1615 got merged too early: I did not address the feedback about unused argument. This PR addresses https://github.com/Azure/ARO-RP/pull/1615#discussion_r671382173
> Simplifies dynamic.NewServicePrincipalValidator

- pkg/env/certificateRefresher_test.go
None
Fixes flaky certRefresher error when running test in a CI.
Issue was hidden in the time.Ticker. When counting number of access to the keyvault, the event occured exactly on the edge of the timeout. Thus it once happened, next time it did not.
Fixed by moving the event closer to the middle of the interval.
N/A
N/A
> fix: certificateRefresher ticker.C timeout

- pkg/util/version/stream_test.go
Fixes issue of pushing invalid pullspec for OCP versions.
The pullspec for a release image has been open-ended to date and I messed up recent PR which caused churn and took time to trace down.  This PR adds a unit test to at least validate the *format* of the pullspec.  It does **not** validate the pullspec references an actual image.
Ran locally with valid and invalid pullspecs.  Also will run in CI for all PRs.
No, wiki had the format correct, I failed to follow it.  This PR will ensure we don't push invalid values and wiki can be reviewed if check fails.
> Unit test to verify PullSpec format

- pkg/cluster/install.go
- pkg/cluster/storageclass.go
- pkg/cluster/storageclass_test.go
Work item [№9586080](https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/9586080/).
Otherr PRs related to this work item:
* https://github.com/Azure/ARO-RP/pull/1569 - Frontend API & backend PR
* https://github.com/Azure/ARO-RP/pull/1599 - Prerequisite for validations
* https://github.com/Azure/ARO-RP/pull/1595
* https://github.com/Azure/ARO-RP/pull/1615 - Refactors [dynamic.NewValidator](https://github.com/Azure/ARO-RP/pull/1595/files#r668060547) (side effect of this work item, not requirement).
This PR add a new installation step which replaces default `StorageClass` provided by OCP with a new one which uses disk encryption set (if one supplied by a customer).
PR adds unit tests + Manual tests.
For instructions on how to create a cluster with SSE and encryption at host …
> Makes default StorageClass to use disk encryption set, if provided

- hack/clean/clean.go
- pkg/cluster/deploystorage.go
This now allows dev clusters to be created with a proper ManagedBy field. Purger determined if production cluster by `ManagedBy == nil && *ManagedBy == ""`, and now we will look for a tag `purge: true`. If that tag exists it is a devCluster and the purger will attempt to purge it.
I've verified it creates new clusters with `purge:true` tag, but will need to confirm purger cleaning up resources after their TTL expires. 
tech debt clean up, n/a.
> fix/ change purger logic

- .pipelines/e2e.yml
E2E runs every time when commit/PR is raised even when it would fail on basic checks.
E2E pipeline will start after successful run of CI checks
Manual
No
> Introduce pipeline chaining

- hack/validate-imports/validate-imports.go
Fixes code scanning alerts in `/hack/validate-imports/`
We don't escape the `.` character in our regex defined in validate-imports.  Places an `\` character to escape the period.  
Tested `validate-imports` and pipelines should run `Makefile` target of `validate-imports`
No
> Escape periods in regex expression

- pkg/operator/controllers/node/const.go
- pkg/operator/controllers/node/node_controller.go
- pkg/operator/controllers/node/node_controller_test.go
https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/10227470/
Adds some coverage to the Node controller to ensure we're adding and reading our annotations properly. Also adds a const.go file for the node package since it's standard practice among other operator controllers.
`make test-go`
`go test -v`
No
> Add unit test for Node controller

- .pipelines/ci.yml
Fixes partially https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/9739113/
Trigger code check and following chain of pipelines when tag is pushed into the ARO-RP repository.
This is required for next steps for https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/9739113/
It is done separately as Azure Pipelines does not reliably handle new pipeline code in the PR.
At this point only CI and E2E will fire up on tag.
Manual
None needed
> Trigger CI with a tag

- pkg/api/featureflags.go
- pkg/cluster/deploystorage.go
- pkg/cluster/overridemtu.go
This implements [10080838 Support for larger MTUs](https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/10080838/) at cluster install time.
See [Matt Woodson's summary in the ADO feature](https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/10080838/#11860858).  (It's customer-specific so not sure I should paste details here.)
So far only manual testing until the subscription feature flag exists.
Microsoft will be delivering documentation about the larger MTU in the October/November timeframe, but presumably it will not mention Azure Red Hat OpenShift.  Waiting to see what Microsoft delivers but likely we'll need to add a mention under [Azure Red Hat OpenShift documentation](https://docs.microsoft.com/en-us/azure/openshift/).
> Add subscription feature MTU3900

- pkg/cluster/install.go
- pkg/cluster/tls.go
- pkg/util/steps/condition.go
- pkg/util/steps/runner_test.go
Fixes https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/10631458
Customer sometimes deletes secrets which we populate from the key-vaults[1]. If those secrets are gone we can't restore them with [2] because of [3].
We should be doing this:
Make Conditional wait best effort where we can. In this case scenario API server is partially alive but our condition fails as Operator is not happy. In those cases actions timeouts, attempts to try other steps and should work. Worst case we will fail down the chain...
We should move certificate configuration higher in the AdminUpdate order to avoid somebody else tripping us.
We should have a backup secret copy in ARO operator namespace just for cases when 1-2 fails. 
https://github.com/Azure/ARO-RP/blob/master/pkg/cluster/tls.go#L72 …
> Certificate issue adjust

- pkg/operator/controllers/banner/banner.go
- pkg/operator/controllers/banner/banner_controller.go
- pkg/operator/controllers/banner/banner_controller_test.go
Fixing newBanner to be generic, fixing test cases to make sure we're not expecing an error, filtering Watch to only the ConsoleNotification with the right name
Fixes  https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/9396114/
Suggestions from PR #1589 
Unit test + same as #1589
N/A
> Minor fixes to Banner Controller + tests

- cmd/aro/mirror.go
Mirror ose-support-tools so we can create a pod with the `oc-cli` in it if a cluster does not have the registry.redhat.io pull secret to pull the image down.  
N/A
SOP needs image updates for approving CSRs.
> Add ose-tools to mirroring if registry.redhat.io pull secret not present

- pkg/util/conditions/condition_test.go
Fixes https://github.com/Azure/ARO-RP/pull/1700#issuecomment-908544661
Uses new import alias in one file to unblock CI.
Run CI
No
> Fix import name to unblock CI

- docs/az-aro-python-development.md
Adhoc discovered problem with running `azdev test aro` on macOS.
Fixes
This doc update explains how to solve an issue with the following error:
```
+[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called.
```
`azdev test aro` executes successfully after applying the fix on macOS.
This PR is only for documentation purposes.
> Update az aro Python development documentation

- pkg/mirror/mirror.go
This reverts commit 0324434dcc48666eee87b701147d328201096fa7.
This was pushed by accident.  This needs to be reverted and reviewed.
Fixes
reverting an errant push.
> Revert "added a 'doNotMirrorTags' map to skip un-mirrorable versions"

- cmd/aro/mirror.go
Certain releases are not able to be mirrored since they are on internal sites.  This adds a denylist to skip mirroring these relases.
Currently CI jobs are failing trying to pull these.  This should fix it.
Fixes
Currently CI fails trying to pull certain rleases.  This skips these.
> added a 'doNotMirrorTags' map to skip un-mirrorable versions

- .config/CredScanSuppressions.json
Fixes:
All existing builds using Onebranch.  Credscan picks up a private/public key as a potential vulnerability.  Confirmed with Benjamin Vesel that this file is provided by a vendor and is only used for testing purposes.  This key combo is not used in any production environments.
Suppresses credscan finding for verify_test_dsa.go
N/A
N/A
> Adding credscan suppression for verify_test_dsa.go

- test/e2e/adminapi_redeployvm.go
Partial fix for [103726609](https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/10372609)
Adds a grace period to the activity log search when in e2e redeploy stage. Accounts for some clock drift on CI agent VMs.
After merge, e2e will improve success rate of vm redeploy
No
> Add grace period to account for clock drift in e2e vm deploy

- test/e2e/operator.go
- test/e2e/scalenodes.go
https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/10900528
Billing E2E expects 4 VMs, and with scaling tests we have 5. This skips operator e2e if not in dev mode. Band aid for now.
E2E passes
No
> Add skip to operator e2e if not in dev mode

- pkg/util/cluster/cluster.go
Cluster creations will now use openshiftsdn by default
Appears to be a flake with `apiServerReady` and CNI issues.  Since we default to SDN, it shouldn't be an issue.  
Create multiple clusters using OpenShiftSDN, ensure that it doesn't break on the above step.  
No
> Default e2e Clusters to Create with OpenShiftSDN Instead of OVNK8s

- pkg/deploy/deploy_gateway.go
- pkg/deploy/deploy_rp.go
None, noop code cleanup
I found two instances where manually setting deployment parameters from `d.config.Configuration` is not needed, because it has already been done above in the call to [`getParameters`](https://github.com/Azure/ARO-RP/blob/558fc5d0240dc61d281f7917fd276f6f523fb016/pkg/deploy/deploy.go#L119). `dbtokenClientId` and `fpServicePrincipalId` are mapped to fields in `Configuration`.
Deploy to INT, make sure everything still works.
No
> remove redundant code (covered by getParameters)

- .pipelines/onebranch/pipeline.bootstrapper.pullrequest.yml
- .pipelines/onebranch/pipeline.image.mirror.pullrequest.yml
- .pipelines/onebranch/templates/template-generate-ev2-manifests.yml
- .pipelines/onebranch/templates/template-image-mirror.yml
Which issue this PR addresses: / ### What this PR does / why we need it:
Checked out RP-Config for mirroring and the bootstrapper.
Added RP_CONFIG_PATH to the go Ev2 manifest generation. RP_CONFIG_PATH is used to point to the RP-Config from the Ev2 Generator to generate the Ev2 manifests
Removed whitespace
Build Logs Attached (for brevity the results can be viewed at this link: https://dev.azure.com/msazure/AzureRedHatOpenShift/_build/results?buildId=46986050&view=results)
[logs_46986050.zip](https://github.com/Azure/ARO-RP/files/7205578/logs_46986050.zip)
Test plan for issue:
Ran the Ev2 Generator and completed a deployment.
Is there any documentation that needs to be updated for this PR?
No, this process is already documented.
@troy0820 - this replaces PR 1754 that I closed due to merge …
> Updated pipelines to use the RP-Config for Ev2 Manifest Generation

- .sha256sum
- pkg/api/admin/openshiftcluster.go
- pkg/api/admin/openshiftcluster_convert.go
- pkg/api/defaults.go
- pkg/api/defaults_test.go
- pkg/api/openshiftcluster.go
- pkg/api/v20210901preview/openshiftcluster.go
- pkg/api/v20210901preview/openshiftcluster_convert.go
- pkg/client/services/redhatopenshift/mgmt/2021-09-01-preview/redhatopenshift/enums.go
- pkg/client/services/redhatopenshift/mgmt/2021-09-01-preview/redhatopenshift/models.go
- pkg/cluster/generateconfig.go
- pkg/frontend/openshiftcluster_putorpatch_test.go
- pkg/util/cluster/cluster.go
- python/client/azure/mgmt/redhatopenshift/v2021_09_01_preview/models/__init__.py
- python/client/azure/mgmt/redhatopenshift/v2021_09_01_preview/models/_azure_red_hat_open_shift_client_enums.py
- python/client/azure/mgmt/redhatopenshift/v2021_09_01_preview/models/_models.py
- python/client/azure/mgmt/redhatopenshift/v2021_09_01_preview/models/_models_py3.py
- swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/preview/2021-09-01-preview/redhatopenshift.json
- test/e2e/fips.go
- test/e2e/setup.go
Fixes https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/10901527/
Exposes a Cluster Profile parameter named `FipsValidatedModules` which is sent to the installer to determine if FIPS mode is turned on for cluster.
Added frontend tests, defaults tests, e2e tests checking database document and machineconfigs for FIPS, and manual verification process:
Setup basic vars and create network:
```
RESOURCEGROUP=$USER-fips
CLUSTER=$RESOURCEGROUP-cluster
CLUSTER_RESOURCEGROUP=$CLUSTER
LOCATION=eastus
AZURE_FP_CLIENT_ID=#well known value
CLUSTER_SP_NAME=$CLUSTER
CLUSTER_DOMAIN=#yourdomainhere
az group create --name $RESOURCEGROUP --location $LOCATION
az network vnet create \
--resource-group $RESOURCEGROUP \
--name aro-vnet \
--address-prefixes 10.0.0.0/22
az network vnet subnet …
```
> ARO Fips Mode Installation

- pkg/util/log/audit/audit.go
- pkg/util/log/log.go
- test/util/log/log.go
Fixes IFX audit lack of logging.
We do logging directly to journald via logrus hooks:
https://github.com/Azure/ARO-RP/blob/master/pkg/util/log/journald.go#L49
And we use hooks for multiple purpose.
Hooks are being executed in order how they are being loded. So when we log out to stdout (what you see in the cmd) is not the same as we ship into journald, because for audit we load audit hook After we loaded journald.
So what happens is :
Log entry constructed with RP fields -> journald emmits the log -> enrich with audit data- > emit audit log.
So we never log it to journald but cmd makes impression that we do.... 
This re-orders bit our hooks loading order making journald last to be loaded, so antything we do before, will be included.
test in prod
No
> Ifx log fix

- Makefile
- cmd/aro/ensurebuildtag.go
- cmd/aro/ensurebuildtag_aro.go
- cmd/aro/ensurebuildtag_test.go
- cmd/aro/main.go
- docs/deploy-development-rp.md
Fixes https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/9778719/
ARO-RP must be built with `-tags aro` which will filter down to the vendor directory and disable certain functionality from the openshift/installer. 
This PR is trying to block ARO-RP from being built/tested/run without the required tag.
The code should automatically fail unit tests and execution tests if executed without `-tags aro`.
Development docs may need updating.
> Ensure build tag "aro" is present

- pkg/cluster/install.go
Fixes case when PUCM is attempted on a cluster when VMs are all stopped.
At the moment, when all VMs are stopped, PUCM  fails as API server is accessed in a recently added step before startVM. This PR fixes the order by putting the startVM before.
Will rely on CI, E2E
N/A
> change order to ensure startVM is done early

- .github/CODEOWNERS
Fixes admin's ability to approve PR's.
We added some additional admins recently and missed updating codeowners.
N/A
ADO wiki is updated.
> Update CODEOWNERS to align with ARO-RP repo admins

- pkg/api/v20210901preview/openshiftcluster_validatestatic.go
- pkg/api/v20210901preview/openshiftcluster_validatestatic_test.go
* Adds extra test cases to cover the bug.
* Fixes worker profile static validation for Encryption At Host: instead of validating worker profile we were validating master profile in `validateWorkerProfile`.
Unit tests cover it.
No, it is a bug fix.
> Fixes worker profile static validation for Encryption At Host

- docs/disk-encryption-set.md
- python/az/aro/HISTORY.rst
- python/az/aro/azext_aro/_client_factory.py
- python/az/aro/azext_aro/_params.py
- python/az/aro/azext_aro/_rbac.py
- python/az/aro/azext_aro/_validators.py
- python/az/aro/azext_aro/commands.py
- python/az/aro/azext_aro/custom.py
disk encryption sets, sdn selection, encryption at host options
Fixes https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/7403671/
This PR switches the Azure CLI extension to the 2021-09-01-preview API, address the additional create parameters. We need it for customers who want to use the disk encryption features and have the feature flag enabled on their subscription to access the preview API. The plan is to give those customers an extension while the API is in preview, and keep it in parallel to the officiall AzureCLI command.
I didn't find any documentation on supporting multiple API versions inside an AzureCLI extension, so I went ahead with updating it to latest. This means that the extension can't be used anymore as a step in AzureCLI command development directly. …
> AzExt - Adding support for the v2021-09-01-preview API

- pkg/portal/middleware/aad.go
- pkg/portal/middleware/aad_test.go
The PR addresses SRE Portal oauth2 Active Directory endpoints not being cloud aware and creating the following error within the PR: 
`auth2: cannot fetch token: 400 Bad Request#012Response: {"error":"invalid_request","error_description":"AADSTS900432: Confidential Client is not supported in Cross Cloud request.`
USGovernmentCloud requires:
ActiveDirectoryEndpoint:      "https://login.microsoftonline.us/"
PublicCloud requires:
ActiveDirectoryEndpoint:      "https://login.microsoftonline.com/"
Work Item: https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/9964892
The SRE Portal oauther.Endpoint value will be set from [environments.go](https://github.com/Azure/ARO-RP/blob/master/vendor/github.com/Azure/go-autorest/autorest/azure/environments.go#L134) based off of which …
> Cloud Aware SRE Portal Oauth Endpoints

- .pipelines/onebranch/pipeline.logging.geneva.bootstrapper.pullrequest.yml
- .pipelines/onebranch/pipeline.logging.geneva.pullrequest.yml
- .pipelines/onebranch/pipeline.logging.kusto.pullrequest.yml
Fixes (https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/11124811)
This PR allows us to read configs from the RP Config for Kusto and Geneva pipelines.
We ran the pipeline and saw that it pulled in the rp config appropriately.
no
> Add RP Config as a dependency for Kusto and Geneva Pipelines

- pkg/monitor/cluster/cluster.go
- pkg/monitor/cluster/nodeconditions.go
- pkg/monitor/cluster/nodeconditions_test.go
Fixes [10557489](https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/10557489)
[SPOT VMs](https://docs.microsoft.com/en-us/azure/virtual-machines/spot-vms) can go offline at any time, so SRE should not be concerned if they become deallocated.
Manual testing
No
> don't monitor spot node conditions

- test/e2e/operator.go
- test/e2e/scalenodes.go
Followup PR to the conversation here https://github.com/Azure/ARO-RP/pull/1655#discussion_r691430553
Right now, E2E cluster isn't reverted back to 3 worker replicas after the operator test. This fixes that, so we're covered in case we introduce a E2E test later that requires the full worker capacity.
Because this adds another scale and wait, it adds a few minutes to E2E test runs.
- `make test-e2e` on a dev environment with availability zones
- `make test-e2e` on a dev environment without availability zones
- CI E2E
No
> E2E - revert cluster worker replicas after test

- python/az/aro/HISTORY.rst
- python/az/aro/azext_aro/_help.py
- python/az/aro/azext_aro/azext_metadata.json
- python/az/aro/azext_aro/commands.py
- python/az/aro/azext_aro/custom.py
- python/az/aro/setup.py
Fixes ADO-11136013
Adds `az aro list-admin-credentials` command which allows customers to get the cluster admin kubeconfig which skips the authorization operator.
This requires the Microsoft.RedHatOpenShift/AdminKubeconfig feature to be registered.
make az
Test by running the command (getting a warning + failure), registering the feature, re-running the command (getting a success), unregistering the feature, re-running the command (getting a warning + failure).
Note that ARM caches the feature state for some time so `az feature list | grep Microsoft.RedHatOpenShift/AdminKubeconfig` might show a different state to what the RP sees.
Help section added to the Azure CLI extension itself.
Next steps after merge: publish AzureCLI extension v1.0.2
> Adding support for list-admin-credentials (getting kubeconfig)

- pkg/frontend/openshiftcluster_putorpatch.go
- pkg/frontend/openshiftcluster_putorpatch_test.go
Enables gateway for all new clusters
Needed for rollout of gateway feature.  
We'll update the `PUCM.ps1` script to add in the gateway feature on patch if it doesn't exist.  If something goes wrong, we can disable it and we won't impact rollout.
We will have a future work item to remove the feature flag.  
Yes - there's doc writers working on publishing public docs for this.
> Remove gateway check for ARM feature flag on cluster create

- python/az/aro/setup.py
Fixes
Need to publish the az-aro extension for BYOK support along with the upstream updates.  
N/A version bump.  Wait for green CI 
Updated the docs with missing version bump.
> Need to Bump `setup.py` version as well

- docs/publish-rhcos-image.md
The Partner Portal step in `docs/publish-rhcos-image.md` left me adrift.
The procedure is non-trivial and [detailed steps](https://msazure.visualstudio.com/AzureRedHatOpenShift/_wiki/wikis/ARO.wiki/186149/How-To-Publish-New-OCP-Image-for-ARO) exist in the ADO wiki, so link to them.
> docs/publish-rhcos-image.md: Link to ADO wiki

- .pipelines/onebranch/pipeline.bootstrapper.official.yml
- .pipelines/onebranch/pipeline.bootstrapper.pullrequest.yml
- .pipelines/onebranch/pipeline.buildrp.official.yml
- .pipelines/onebranch/pipeline.image.mirror.official.yml
- .pipelines/onebranch/pipeline.image.mirror.pullrequest.yml
- .pipelines/onebranch/pipeline.logging.geneva.bootstrapper.pullrequest.yml
- .pipelines/onebranch/pipeline.logging.geneva.pullrequest.yml
- .pipelines/onebranch/pipeline.logging.kusto.pullrequest.yml
[ADO Work Item 12413343](https://dev.azure.com/msazure/AzureRedHatOpenShift/_workitems/edit/12413343)
This PR updates the build image for the OneBranch logging pipelines (Geneva-Bootstrapper, Geneva, Kusto). The current build image does not include Go, so the Ev2 manifest generation step fails.
Change was tested by running each build pipeline using the new build image. Successful pipeline runs linked below:
- [Geneva-Bootstrapper](https://dev.azure.com/msazure/AzureRedHatOpenShift/_build/results?buildId=48137030&view=results)
- [Geneva](https://dev.azure.com/msazure/AzureRedHatOpenShift/_build/results?buildId=48137049&view=results)
- [Kusto](https://dev.azure.com/msazure/AzureRedHatOpenShift/_build/results?buildId=48137077&view=results)
No, execution of build pipeline has not not changed, …
> feat: updated build container image for onebranch logging pipelines

- Makefile
Fixes ADO-12526877
Added Colorama package to pyenv
no new functionality - when ci nodes are rebuilt the colorama package won't be missing
N/A - CI fix
> futureproofing Python CI -adding colorama to pyenv

- pkg/util/pullsecret/pullsecret.go
- pkg/util/pullsecret/pullsecret_test.go
Fixes
```
Observed a panic: &runtime.TypeAssertionError{_interface:(*runtime._type)(0x3ff8f20), concrete:(*runtime._type)(nil), asserted:(*runtime._type)(0x3dd0f00), missingMethod:""} (interface conversion: interface {} is nil, not string)
goroutine 1292 [running]
```
There's a bug during unmarshalling process. When there's no auth value, a type assertion error is being thrown that causes ARO operator to fail and constantly crash loop its pod. 
Unit test updated to include an empty auth value and it reproduced the issue. Once verification for nil was added, the new test passed successfully.
N/A
> Pull Secret Unmarshalling Bugfix

- test/e2e/adminapi_redeployvm.go
Modified Redeploy VM e2e test to validate success against cluster events rather than azure activity log
Fixes https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/10372609https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/10372609 
The azure activity logs could take over 20 mins to show up meaning we would have to wait at least that long for the test to complete. The cluster events are instant and are a much better metric to validate test success in this scenario.
Modified this test, and tested multiple scenarios in running the test to make sure test is robust
New page in ARO wiki
https://msazure.visualstudio.com/AzureRedHatOpenShift/_wiki/wikis/ARO.wiki/194224/Run-E2E-Tests-Locally
> Redeploy VM e2e Test Validation Rewrite

- pkg/cluster/delete.go
- pkg/cluster/ipaddresses.go
- pkg/frontend/openshiftcluster_putorpatch.go
- pkg/frontend/openshiftcluster_putorpatch_test.go
- pkg/operator/deploy/deploy.go
Fixes a race condition in the gateway enablement.  If we delete the PE, there's a chance another cluster could spin up a PE and get the linkID reused.  
* Fixes a gateway race condition
* Disables egress on new cluster create
* Removes the `gatewayDomains` from `cluster.aro.openshift.io` resource on `AdminUpdate` essentially removing the dnsmasq config that makes egress work.  
* Do it
* No
> Fix race condition in the gateway doc deletion

- pkg/gateway/linkid.go
Make logs more verbose by adding which linkID we are attempting to lookup the gateway record for.  
If we don't have a record for an existing linkID, we should populate the log so we can backtrace where the connection is coming from.  
We should be able to backtrace it by listing all clusters within the region and running a jmespath query like:
`[?contains(properties.networkProfile.gatewayPrivateLinkId, 'LINK_ID').id`
N/A
We should add an SOP for how to look this up and how this works. @gvanderpotte any chance you would want to do this?
> Populate Missing Gateway Record Log with LinkID

- pkg/cluster/fixuserkubeconfig.go
- pkg/cluster/kubeconfig.go
- pkg/cluster/kubeconfig_test.go
Fixes ADO-12394839
On PUCM one of the update steps checks if the user admin kubeconfig is pointing to api-int. URI, and repoints it to api. URI if needed. Since I was refactoring that code the kubeconfig will also be regenerated if the expiry date is too close (<90 days) or if some of the fields are malformed.
No E2E test yet.
Added unit test for the UserAdminKubeconfig generation.
Manual test:
1. run local rp from commit before PR
2. create a cluster
3. Pull kubeconfig with azext
4. run local rp from this PR
5. `curl -v -H "Content-Type: application/json" -d"{}" -X PATCH -k https://127.0.0.1:8443/subscriptions/$SUBSCRIPTION_ID/resourceGroups/$RESOURCEGROUP/providers/Microsoft.RedHatOpenShift/openShiftClusters/$CLUSTER?api-version=admin`
6. Pull kubeconfig with azext
The old kubeconfig …
> fixing user admin kubeconfig api-int to api on PUCM

- Makefile
Fixes attempting to run some code when the `aro` build tags don't exist.  
If you follow or run some documentation, our makefiles don't properly have the build tags in them resulting in immediate failure running commands
```
[bvesel@fedora ARO-RP]$ make deploy 
go run -ldflags "-X github.com/Azure/ARO-RP/pkg/util/version.GitCommit=03b4070" ./cmd/aro deploy dev-config.yaml eastus
FATA[2021-11-15T13:23:40-05:00]cmd/aro/main.go:47 main.main() ARO-RP must be built, run, and tested with '-tags aro' to support github.com/openshift/installer, see https://github.com/openshift/installer/pull/4843/files 
exit status 1
make: *** [Makefile:41: deploy] Error 1
```
Ran it after adding it.  
Nope
> Add `aro` build tags when running code out of cmd

- pkg/api/admin/openshiftcluster.go
- pkg/api/admin/openshiftcluster_convert.go
- pkg/api/admin/openshiftcluster_validatestatic.go
- pkg/api/admin/openshiftcluster_validatestatic_test.go
- pkg/api/defaults.go
- pkg/api/openshiftcluster.go
- pkg/backend/openshiftcluster.go
- pkg/backend/openshiftcluster_test.go
- pkg/cluster/adminupdate_test.go
- pkg/cluster/install.go
- pkg/database/openshiftclusters.go
- pkg/frontend/openshiftcluster_putorpatch.go
- pkg/frontend/openshiftcluster_putorpatch_test.go
Part of https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/10430645/?workitem=10609866
This allows the ARO Operator to update without running the rest of the AdminUpdate. The Operator should always be updated, even if some parts of the Azure infrastructure aren't/can't be (e.g. DNS) since the Operator will be a mechanism to fix or notify the customer of some of these issues.
Tests in PR
maybe?
> Introduce a "task" selection option to AdminUpdate for running just the ARO Operator update steps

- Dockerfile.fluentbit
Fixes an issue attempting to build the `Dockerfile.fluentbit` that was introduced in #1731  
Not sure why it's failing, but it is after the update.  I'm not reverting the whole PR as there is some other stuff in there that's good.  Not spending too much time investigating, but looks similar to https://github.com/rpm-software-management/microdnf/issues/27
```bash
STEP 4/6: RUN microdnf install td-agent-bit-$VERSION
Downloading metadata...
(microdnf:1): libdnf-WARNING **: 19:59:19.508: Skipping refresh of ubi-7: cannot move /var/cache/yum/metadata/ubi-7-7Server-x86_64/packages to /var/cache/yum/metadata/ubi-7-7Server-x86_64.tmp/packages
Downloading metadata...
Downloading metadata...
Downloading metadata...
Downloading metadata...
Downloading metadata...
error: Could not depsolve …
```
> Revert updates to fluentbit dockerfile

- .gdn/.gdnsuppress
Fixes: https://dev.azure.com/msazure/AzureRedHatOpenShift/_workitems/edit/12613527
It appears that cluster-predeploy.json was renamed and modified to cluster-development-predeploy.json and thus the suppression file no longer worked.  This updates the signature and file name in the .gdnsuppress file so that SDL scans can proceed without error
https://dev.azure.com/msazure/AzureRedHatOpenShift/_build/results?buildId=49042994&view=results
N/A
> Update gdnsuppress file

- pkg/util/cluster/aad.go
- python/az/aro/azext_aro/_aad.py
This is a hotfix release for FF which takes our last release `7b70040dd` and cherry-picks the commit in #1816 `0a2b0408` on top of it.  There is no change to master.
INT & Prod have azure.com registered as custom domains.  In FF we don't have that luxury so the e2e fails every time.  
Green e2e.  Ensure that the head is `7b70040dd` + cherry-pick
No
> FF Hotfix Release Removing Identifier URIs

- python/az/aro/HISTORY.rst
- python/az/aro/azext_aro/_help.py
- python/az/aro/azext_aro/_params.py
- python/az/aro/azext_aro/custom.py
- python/az/aro/setup.py
Fixes backwards incompatibility - enums are no longer present in Azure CLI re: Feature state.
Adds saving decoded kubeconfig to file.
Enums present in some but not all versions of Feature command in Azure CLI.
Kubeconfig is decoded and saved to the specified file
Ran az aro get-admin-kubeconfig on a cluster. Verified that the downloaded kubeconfig works with oc and kubectl commands.
Tried re-downloading kubeconfig to the same path - got error (as expected).
Tried re-downloading kubeconfig to the same path with --overwrite flag - worked.
Internal help in extension - fixed.
> AZ CLI - get-admin-kubeconfig command fixes

- .gitignore
Goland creates this project-specific settings directory that shouldn't be pushed.
> For anyone that does or might in the future use Goland

- pkg/operator/controllers/workaround/systemreserved.go
SystemReserved workaround could not be removed due to wrong GVK set.
EnsureDelete requires GroupKind e.g.
KubeletConfig.machineconfiguration.openshift.io
instead the argment received GroupVersionKind
KubeletConfig.machineconfiguration.openshift.io/v1
with GroupVersionKind EnsureDelete does not find the
right schema and cannot delete object.
Manually tested
N/A
> Fix GroupKind argument to EnsureDelete

- docs/deploy-full-rp-service-in-dev.md
Fixes the docs -> add tags aro to mirror step as required to compile installer
mirror command won't compile w/o aro tags
> add tags aro to mirror step docs as required to compile installer

- python/az/aro/HISTORY.rst
- python/az/aro/azext_aro/custom.py
- python/az/aro/setup.py
Azure extension doesn't run well in Python3.6, it's distributed with Python3.6
Fixes tech debt.
Sets the encoding of the kubeconfig file to utf-8
Run "make az", try running the extension in az bound to python 3.6.
Doesn't work with "locale"
N/A
> Fixing encoding to a value supported by Python3.6 AND fulfilling pylint requirements.

- pkg/util/cluster/cluster.go
Fixes failures when not creating clusters in `LocalDevelopmentMode`
If we're not in `LocalDevelopmentMode`, we use the stable API to create a cluster.  This means we can't test e2e features that are only in the new preview API (tests will fail) using the stable API.
e2e in local dev mode, e2e in INT
No.
> Create all e2e clusters with newest preview API

- Makefile
- pkg/util/version/const.go
This reverts fluentbit to the previous version. New version seems to use too much memory which causes pressure on masters.
> Revert fluentbit to the previous version

- .pipelines/e2e.yml
Fixes issues with failure to find the service account because the wrong subscription is set by default for the service principal. 
Should fix our e2e
Check if e2e passes on this PR (or at least gets past the error portion)
~This should be parameterized instead of explicitly set, but I don't believe I have the proper permissions in ADO to do so, hence this PR in such state.~ I can see the variables after logging into ADO with my GitHub account.  This should work, waiting on e2e to pass and we can merge.
> Add subscription of keyvault to e2e template

- cmd/aro/mirror.go
Our mirroring pipeline currently starts reading all releases from 4.3.  We no longer support 4.3 images and OCP engineering [is not publishing any new OCP versions <4.6.](https://access.redhat.com/support/policy/updates/openshift).
Although the new images aren't technically mirrored because they already exist, this will save time in the mirroring pipeline because it won't have to read and attempt to push all the release images in releases <4.6.  
Run mirror pipeline, ensure that it doesn't attempt to mirror any versions less than 4.6.  
No.  The existing images already in ACR are not affected by the mirroring pipeline, nor are we purging ACR imjages over time.
> Start Reading Release Graph from 4.6 for Mirroring Images

- pkg/util/clientauthorizer/arm.go
- pkg/util/clientauthorizer/arm_test.go
This should fix our deploy issues in westcentralus.
Currently, our deployment in westcentralus fails intermittently because the ARM endpoint to authentication between the RP and ARM is not correct for public cloud.  We need to update it to use the correct endpoint so we don't hit redirects and issues when deploying.  
The correct endpoints and structure can be found in the ARM Wiki [Authenticate between ARM and RP](https://armwiki.azurewebsites.net/authorization/AuthenticateBetweenARMandRP.html?q=client%20certificate)
Updated the tests to allow for a different endpoint if it's public cloud.  Will have to test in INT/Canary on deploy though.  
Nope, just gotta know about the arm wiki
> Update ARM authentication metadata endpoint for public cloud

- test/e2e/operator.go
- test/e2e/scalenodes.go
Fixes https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/11718823/
If/when the node scaling test is executed immediately before the List Azure Resources test, the List Azure Resources test can fail, because the two lists that are diff'd at the end of the test don't exactly match. This is because additional resources (VMs/NICs/AS) may still be deleting or creating in the background due to the node scaling tests immediately before.
The machine-api-operator and controller (which is in charge of provisioning and tearing down these resources) contains a `machine-controller` component that updates machine custom resources with provisioning status https://github.com/openshift/cluster-api-provider-azure/blob/6c62b91ee269307cdacb7729dc42f60e730b30a0/pkg/cloud/azure/actuators/mach …
> Wait for machine deletion after node scaling tests

- pkg/util/azureclient/mgmt/keyvault/vaults.go
- pkg/util/cluster/cluster.go
The current keyvault client used in e2e tests is not cloud aware and is hardcoded to the public cloud ARM endpoint.  This makes it cloud aware like the rest of the clients.  
Note: this branch being merged is at 9b4fecf + this commit, which means that once it is merged into master we can use the non-merge commit as a head for deploying to gov cloud.  
Run e2e in Public & Gov Cloud INT environments.  
Nope.
> Make keyvault client cloud aware

- Makefile
Existing code for running localrp does not read version.gitCommit, resulting in ARO operator version as `unknown` for dev clusters.
With this PR, we pass the ${COMMIT} to the go run aro command.
Fixes
> make runlocal-rp read the version.gitCommit

- pkg/operator/controllers/node/node_controller_test.go
Fixes https://github.com/Azure/ARO-RP/issues/1686
Currently we only unit test external functions in node_controller.go. This PR is meant to add unit test coverage for the reconciler method itself.
Unit tests pass, and code coverage is acceptable.
No
> Add a test for NodeDrainer reconciler (node controller)

- pkg/operator/controllers/alertwebhook/alertwebhook_controller.go
https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/12879885/
Fixes
Stops AlertmanagerFailedToSendAlerts from firing on clusters due to a 404 on the endpoint
Change was made locally and alert no longer fires on test cluster
No, small bug fix.
> Alertmanager fix

- pkg/api/defaults.go
Followup to the feature flags PR
Enables reconciling NSGs by default, as discussed in aro-forum
dunno
N/A
> Enable reconciling azuresubnets/NSGs by default

- test/e2e/scalenodes.go
Please include a link to the ADO work item as well as any GitHub issues.
https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/10943719
Fixes
Refactor E2E "Scale Nodes" test to Use go-client Instead of ARO Client
create local RP cluster.
export CLUSTER=#CLUSTERNAME; go test ./test/e2e -tags e2e,codec.safe -c -ldflags "-X github.com/Azure/ARO-RP/pkg/util/version.GitCommit=7cc9e51" -o e2e.test
./e2e.test
> refector e2e for removing dependency.

- pkg/api/validate/dynamic/dynamic.go
- pkg/api/validate/dynamic/dynamic_test.go
Currently if  **AddressPrefixes** is used **AddressPrefix** will have a value of nil which will cause a cluster to fail provisioning.
If  **AddressPrefix**  is nil we try to validate  **AddressPrefixes**  instead. 
I altered one of the existing tests to use the  **AddressPrefixes** field, which I think covers the new and old use cases
I am not sure so if there is please point me to it.
> Handle the use of the AddressPrefixes field

- .pipelines/deploy-azure-env.yml
- .pipelines/int-release.yml
- .pipelines/prod-release.yml
- .pipelines/templates/template-job-deploy-azure-env.yml
Fixes: (partly) https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/9647460/
Over complicated configuration pull using build pipelines, not transparent and adds complexity to deployment pipelines. Decreases readability.
Implements multiple git checkouts into the deploy pipeline. 
No additional changes should be required to the repository. The `RP-Config` repository is part of the 
`AzureRedHatOpenShift` project, meaning no extra permissions are required.
Only drawback is that on a first run it will require manual "give permissions". This is done only
once to verify user intent.
From the user perspective. New parameter: `configVersion` is added. It should be a tag belonging to desired released config. Most likely the same as released RP?
Manual
N/A
> [PIPELINES 2] Replace config fetch with direct code checkout

- pkg/operator/apis/aro.openshift.io/v1alpha1/cluster_types.go
- pkg/operator/controllers/genevalogging/genevalogging.go
- pkg/operator/controllers/genevalogging/genevalogging_controller.go
- pkg/operator/controllers/genevalogging/genevalogging_test.go
for upcoming release
Allows the fluentbit/mdsd image deployed to be overridden in the ARO Operator's config.
Contains tests
N/A
> Allow fluentbit/mdsd image setting via feature flags

- .pipelines/deploy-azure-env-tag.yml
- .pipelines/int-release-tag.yml
- .pipelines/prod-release-tag.yml
- .pipelines/templates/template-job-deploy-azure-env-tag.yml
Fixes [9741850](https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/9741850/)
Introduces a copy of deploy pipelines, but utilizes tag to deploy.
Tagged image is pulled and `aro` binary is extracted and placed into the appropriate directory.
The rest of the pipeline is the same.
Contains: #1674
Manual
Doc will be added as a whole.
> [PIPELINES 3] Add second pipeline deploying from tagged image

- .pipelines/build-and-push-images-tagged.yml
- .pipelines/templates/template-push-images-to-acr-tagged.yml
- Makefile
Fixes https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/9739113/
Fixes https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/9739185/
Fixes https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/9741850/
Changes to makefile:
- Introduces two new entrypoints in the `Makefile` that build and push tagged container image.
- Get tag only when it is annotated and attached to current commit, otherwise error.
Changed to pipelines:
- Add second build pipeline, 
- chained after successful E2E
- triggered when tag started the pipelines
- Generates changelog from commits and summary provided in tag annotation
- Add second build image template 
- build tagged image
- needs to be added as a pipelines into the AZP
Signed-off-by: Petr Kotas …
> [PIPELINES 4] Create release based on annotated git tag

- .pipelines/build-and-push-images-tagged.yml
- .pipelines/templates/template-push-images-to-acr-tagged.yml
- Makefile
Fixes
Removes the tagged build to run automatically after the E2E. 
Manual
Part of pipelines doc
> Stop build to run after E2E

- docs/prepare-a-shared-rp-development-environment.md
Add document detailing the steps taken to rotate certificates in our dev environment.
Will remove the guess work of having to rotate certs every year.
No
> added dev certs rotation doc

- .pipelines/int-release-tag.yml
- .pipelines/templates/template-job-deploy-azure-env-tag.yml
Fixes
Removes the wrong git pull path for ADO RP-config
Removes unused parameter
> Fix: Remove the wrong git pull path

- .pipelines/build-and-push-images-tagged.yml
- .pipelines/build-and-push-images.yml
- .pipelines/templates/template-job-deploy-azure-env-tag.yml
- .pipelines/templates/template-job-deploy-azure-env.yml
Fixes
With addition of 4.9 release, the go build
have to run with go1.16
> fix: Add go1.16 requirement to run pipelines

- Makefile
Fixes `fatal: no tag exactly matches '9bb00e28627b1e2e320a822107f1aaa1a310a72a'` errors in pipelines when the git commit doesn't match up with a specific tag.  
Remove noise.  
Run the pipeline
no
> Suppress stderr within Makefile command

- .pipelines/prod-release-tag.yml
Fixes the update of the wrong variables / parameters used in the prod-release-tag pipeline.  
I updated the wrong parameter in https://github.com/Azure/ARO-RP/pull/1951/files, fixing it now.  
Try running against the specific commit.  
No
> Fix wrongly updated parameters and variables in prod release

- .pipelines/prod-release-tag.yml
We incorrectly used a wrong variable group in our updated pipelines.  Our e2e for prod spins up a cluster in our INT sub as well as pulls from the INT Azure Container Registry.
Fixes e2e for prod.  
Run and done
Not specifically for this PR
> Use INT E2E Creds in Prod pipeline as we pull from the INT image registry and spin up our resources in our INT sub

- .config/CredScanSuppressions.json
Fixes CredScan findings in pipeline, where the `Guardian: Post Analysis` task of the `OneBranch-Build and Publish Binary and Container-Official` pipeline shows two CredScan findings.
Link to pipeline run with failed task: https://dev.azure.com/msazure/AzureRedHatOpenShift/_build/results?buildId=51792403&view=logs&j=096205eb-4599-56da-affa-13246cc49eac&t=7e5c3140-9b2b-5395-0e58-9e02fe0de382
Add two suppression items to the CredScanSuppressions.json file for these files so CredScan will bypass these two findings and not fail the pipeline.
Changes will be tested after merge to master, as they cannot be tested from a branch.
n/a, as this is part of the standard procedure for CredScan findings
> Fix CredScan findings in pipeline

- .config/tsaoptions.json
- .pipelines/onebranch/pipeline.buildrp.official.yml
Fixes "OneBranch - Build and Publish Binary and Container - Official" pipeline in ADO
Link to pipeline: https://dev.azure.com/msazure/AzureRedHatOpenShift/_build?definitionId=258122&_a=summary
Enable TSA (Trust Services Automation) with automations error logging with security and compliance tools.
This is accomplished by uncommenting the `parameters > globalSdl > tsa > enabled: true` section of the pipeline yaml, and adding the tsaoptions.json file in the /.config directory.
The changes are trivial, but they can only be verified by running the pipeline on the code in the master branch. Building from a branch does not fully test the changes because of multiple repo resources referenced by the pipeline, so the next build from master will validate the changes.
Note: TSA tasks will now run …
> Enable TSA in "OneBranch-Build and Publish Binary and Container-Official" pipeline

- docs/testing.md
- hack/local-monitor-testing/deploy_MDM_VM.sh
- pkg/operator/README.md
N/A just cleaning up
minor doc fixes
The instructions now work in the docs
N/A
> quick fixes in docs

- Dockerfile.aro-multistage
Fixes: Build failure due to incorrect image tag: https://dev.azure.com/msazure/AzureRedHatOpenShift/_build/results?buildId=51841300&view=logs&j=af1b0df7-00d6-590e-9da4-78867c0bc7a2&t=69aab5ed-905a-5c08-21b0-dc2b1ae43cf9&l=181
Image tag of 1.16 does not exist in the RH registry for UBI7: https://catalog.redhat.com/software/containers/ubi7/go-toolset/5ce879bcd70cc57c44b49684
N/A
N/A
> Updating go-toolset tag to 1.16.12

- pkg/gateway/linkid.go
ADO 13137631
Adds a metric when there does not exist a host in the http/https request coming to the gateway.
It additionally logs the linkID the request is coming from so we can view which clusters are having issues.  
Run it and check updated metric.
Need an associated dashboard which is part of the story.
> Add gateway metric for nohost

- pkg/operator/controllers/checker/checker_controller.go
- pkg/operator/controllers/node/node_controller.go
- pkg/operator/controllers/workaround/workaround_controller.go
- pkg/operator/controllers/workaround/workaround_controller_test.go
* Adds the clarifying comment on requeues into the checker controller
* Removes `Requeue: true` in places where we use `RequeueAfter` as it is has no effect.
Unit tests updated where applicable.
No, just refactoring
> Refactors operator requeues

- pkg/monitor/cluster/cluster.go
- pkg/monitor/cluster/nodeconditions.go
- pkg/monitor/cluster/nodeconditions_test.go
Fixes https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/10557489
Adds a new dimension for indicating if a node is a spot instance. This will help us enhance our monitors when evaluating node.conditions metrics.
unit test
manual check of metric being populated
N/A
> add a field to indicate spotInstances in node.conditions metric

- test/e2e/adminapi_redeployvm.go
more logging for redeploy vm e2e. doesn't fix anything, but at least adds some more info for when this test fails.
adds additional logging to redeploy vm e2e to better understand state when this job fails
n/a
n/a
> add additional logging to redeploy vm e2e

- pkg/api/admin/openshiftcluster_validatestatic.go
- pkg/api/admin/openshiftcluster_validatestatic_test.go
- pkg/frontend/openshiftcluster_putorpatch.go
- pkg/frontend/openshiftcluster_putorpatch_test.go
- pkg/operator/deploy/deploy.go
- test/e2e/cluster.go
Fixes https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/13137954/
This feature will enable the egress lockdown feature by default on new clusters while also allowing current clusters to be admin-upgraded with the new feature.
> Egress Lockdown: Enable and Toggle

- .pipelines/templates/template-push-images-to-acr-tagged.yml
- Makefile
Fixes https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/13493157
ARO uses both tags and commits as its version.
The commits are used for the development scenario, tags are used when building and deploying to production.
Adds the pipeline step to copy the resulted image to the integration registry.
N/A
Part of the pipeline documentation.
> fix: use the tag/commit as the aro version and copy image to the integration

- pkg/frontend/adminactions/resources_list.go
Fixes https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/12866432
When listing Azure Resources there can be cases where resources are returned whose type is not defined in `pkg/util/azureclient/apiversions.go` and would result in an HTTP 500 being returned for the Geneva Action. This prevents SREs from investigating the known resource types that are defined.
This change switches from returning an error to logging a warning instead, so as to allow the process to complete and a list of known/defined resource types to be returned. 
Should be covered by existing tests. Ran e2e tests in a dev environment to confirm.
None required.
> fix: HTTP 500 from "List cluster Azure resource" Geneva Action for unknown resource types

- .pipelines/mirror-aro-to-int.yml
- .pipelines/templates/template-push-images-to-acr-tagged.yml
Fixes
integration requires it own set of credentials,
this can only by provided in a separate pipeline
> fix: move int mirroring to separate pipelines

- cmd/aro/operator.go
- pkg/operator/controllers/muo/muo_controller.go
Just a tiny follow up PR for #1845 to clean up `muo.NewReconciler`
CI should catch issues, if any
> Cleans up unused args in `muo.NewReconciler`

- pkg/operator/controllers/muo/muo_controller_test.go
- pkg/operator/controllers/storageaccounts/storageaccounts_test.go
`gomock.Eq()` is a default matcher in gomock so it doesn't have to be explicitly called in these cases.
Test refactoring/cleanup. Tests should pass
No, this is just refactoring/cleanup
> Removes explicit `gomock.Eq()` matcher calls

- docs/prepare-your-dev-environment.md
A few developers on various OS flavors have seen `make generate` fail after the upgrade to golang 1.16 due to `client-gen` updates. This appears to fix - spread the word!
Fixes https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/13421209/
Updates documentation to prevent inconsistent local dev environments.
> Docs: Set GOPATH

- pkg/api/validate/dynamic/dynamic.go
- pkg/api/validate/dynamic/sku.go
- pkg/api/validate/dynamic/sku_test.go
- pkg/api/validate/openshiftcluster_validatedynamic.go
- pkg/env/prod.go
- pkg/util/computeskus/computeskus.go
- pkg/util/computeskus/computeskus_test.go
Fixes https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/11028028
If an install is attempted using a VM SKU that is not available or restricted in the target install region, the install fails late in the process because the worker nodes never come up. This PR adds an API call and SKU checking to the dynamic validation process, so that unavailable SKUs or SKUs with subscription restrictions fail early in the install process.
Prerequisite for https://github.com/Azure/ARO-RP/pull/1751
Unit testing, and manual testing steps (for workers) below.
1) Using a SKU that is unavailable in the region (`Standard_L8s` in `eastus`, for example), comment out line 44 `FeatureRequireD2sV3Workers` in pkg/env/dev.go, and then hardcode the unavailable SKU in line 417 of …
> Add SKU availability and restriction checks to dynamic validation

- test/e2e/list.go
Fixes ADO-13764524
The E2E tests first List all clusters in a subscription, then ListByResourceGroup to get the test cluster again.
The first List call succeeds (ARM Legs show: External -> ARM Web -> RP westcentralus + RP eastus), then the ListByResourceGroup fails from cache (ARM Legs show: External -> ARM Web, no calls to RP).
Since this test is more sensitive to non-deterministic behaviour outside of ARO control than to issues with RP I decided to remove the test. Previously relevant queries were modified to avoid ListByResourceGroup (for example https://github.com/Azure/ARO-RP/blob/125b928c986304c1e58cd9d0caae05014657b059/hack/ssh-agent.sh#L41 )
Run the test.
N/A
> Removing call to listByResourceGroup due to flakyness in the Azure API

- Makefile
- docs/testing.md
Fixes ADO-13793176
Currently there's no way to pass flags to the e2e tests. This PR adds that feature through the E2E_FLAGS env variable. Default is empty, so it doesn't change the behaviour.
Running `make test-e2e` behaves as usual. Running `E2E_FLAGS="-ginkgo.noColor" make test-e2e` makes the test output monochromatic.
updated docs/testing.md
> adding a way to pass additional flags to E2E tests

- .gitignore
- docs/deploy-full-rp-service-in-dev.md
- env-int.example
Fixes https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/13111265/
(ref #1917 point 1)
The current setup makes no distinction between different environment types. By splitting up configuration into two files, it is less likely that a developer forgets to comment out envvars in `./env` when swapping between "full" and "regular" type environments - instead, they source the file that makes the most sense for what they want to do. This solution also maintains backwards compatibility with the old instruction set if devs still want to go that route.
N/A - changing dev instructions/workflow
Instructions have been modified and committed here.
> Better support for multiple envs

- cmd/aro/operator.go
- pkg/api/defaults.go
- pkg/operator/controllers/autosizednodes/autosizednodes_controller.go
- pkg/operator/controllers/autosizednodes/autosizednodes_controller_test.go
- pkg/operator/controllers/autosizednodes/doc.go
- pkg/operator/controllers/workaround/ifreload.go
- pkg/operator/controllers/workaround/systemreserved.go
- pkg/operator/controllers/workaround/workaround.go
- pkg/operator/controllers/workaround/workaround_controller.go
- pkg/operator/controllers/workaround/workaround_controller_test.go
- pkg/util/mocks/operator/controllers/workaround/workaround.go
- vendor/modules.txt
- vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/client.go
- vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/doc.go
Fixes https://dev.azure.com/msazure/AzureRedHatOpenShift/_workitems/edit/9673960/
Introduce new feature flag to enable AutoSizedNodes. This enables the openshift feature to compute
resource allocation dynamically based on the node size. It does that by creating Kubeletconfig config with the feature turned on.
It also removes the aro-limits KubeletConfig that will be conflicting.
Unit tests added.
inline
> Autosizednodes

- pkg/frontend/adminactions/resources_list.go
- pkg/frontend/adminactions/resources_list_test.go
Filters out snapshots from geneva action **_list all azure resources_**  [Ticket](https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/13151600)
Run it locally and ensure that snapshot resources are not present.
Unsure, happy to update if it is the case
> Filter out unwanted data from azure list geneva action

- Dockerfile.muo
Part of https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/10430649
Mirrors a FIPS-compliant MUO into the ACR.
not sure since the INT mirroring is broken
MUO SOP when it's updated
> Dockerfile to create MUO image

- .pipelines/onebranch/pipeline.buildrp.official.yml
- .pipelines/onebranch/pipeline.buildrp.pullrequest.yml
- .pipelines/onebranch/templates/template-buildrp-buildaro.yml
- .pipelines/onebranch/templates/template-buildrp-builddocker.yml
Fixes
https://dev.azure.com/msazure/AzureRedHatOpenShift/_workitems/edit/13675519
OneBranch pipelines do not support building from a release tag (fails pre-build validation steps).  This is a workaround to support the RH team to still use release tags.
So long a commitid has a release tag associated with it, we will be able to derive the tag and attach it to the container at build time.  Otherwise, we will attach the commitid.
https://dev.azure.com/msazure/AzureRedHatOpenShift/_build/results?buildId=53181311&view=results
https://dev.azure.com/msazure/AzureRedHatOpenShift/_wiki/wikis/ARO.wiki/233405/Performing-Release
> Update OB Build Pipeline to Pass Build Tag as Var

- test/e2e/adminapi_redeployvm.go
Fixes https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/13703198/
Here are the flakes (with logs) I was able to discover that this PR might address:
- I believe this is not a test issue, but rather something we'd need to solve through code changes (retries)
What we _really_ care about is: **if I redeploy (successfully), do my Nodes reboot and come back up as Ready eventually in OpenShift?** The new tests answer this question.
1. Checking the Azure activity log to ensure the redeploy was successful (past)
- The Azure activity log is eventually consistent, so the delay between events was too great to rely on it
1. Checking the kubernetes events to ensure the node rebooted (current)
- Kubernetes events aren't guaranteed to fire so this is inconsistent
1. Checking that the …
> Fixing E2E Flake Redeploy VM

- pkg/api/defaults.go
- pkg/operator/controllers/muo/muo_controller.go
- pkg/operator/controllers/muo/muo_controller_test.go
- pkg/util/version/const.go
- test/e2e/operator.go
Fixes https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/13776942
Enables MUO on new clusters with a default pullspec.
Unit tests + an E2E test
N/A
> Enable Managed Upgrade Operator on new clusters

- pkg/proxy/proxy.go
This is a cleanup PR
Cleanup 1: Now uses a waitgroup instead of a chan for synchronization. This is the idiomatic way. 
Cleanup 2: Removed a useless anonymous function definition. 
The order of execution is preserved. 
This should be covered by existing tests. 
No
> Proxy cleanup

- Makefile
Running RP locally without this tag on Apple Silicon results in the following:
```
cmarches-mac:ARO-RP marches$ make runlocal-rp
go run -tags aro -ldflags "-X github.com/Azure/ARO-RP/pkg/util/version.GitCommit=b3dcf14-dirty" ./cmd/aro rp
vendor/github.com/mtrmac/gpgme/data.go:4:11: fatal error: 'gpgme.h' file not found
#include <gpgme.h>
^~~~~~~~~
1 error generated.
make: *** [runlocal-rp] Error 2
```
This changes the target to use openpgp rather than the system gpgme.
> Add containers_image_openpgp tag to `make runlocal-rp` target

- Makefile
Fixes #2037 
This will allow reupload of secret bundle to the storage account even if the file already exists.
Ran the target with both when the file already existed and when there was no file.  Both uploaded the new secret bundle successfully.
No, just a util update.
> Change secrets-update to allow subsequent updates

- Makefile
When putting in the PR https://github.com/Azure/ARO-RP/pull/2032 last week, I forgot to add `containers_image_openpgp` to other Makefile targets where it's needed.
This adds the tag to `make deploy`, `make run-portal`, and `make unit-test-go` as well.
Tested each command locally.
> Add `containers_image_openpgp` to deploy, run-portal, and unit-test-go

- pkg/operator/deploy/deploy.go
- pkg/operator/deploy/deploy_test.go
Signed-off-by: Karan.Magdani <kmagdani@redhat.com>
Fixes https://github.com/Azure/ARO-RP/issues/2010
Fixes https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/13948245
Bug where we end up selecting wrong ingress when there are multiple ingressProfiles.
> check for ingressIP when ingressProfiles > 1

- docs/testing.md
- hack/e2e/run-rp-and-e2e.sh
Fixes https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/11839492/
Checked that it worked locally 
This is mainly a doc update.
> added changes to make local e2e test work/ update doc

- pkg/util/cluster/cluster.go
Now it truncates to 14 instead of 15. the corresponding arm templates
truncate to 15.
Fixes #2046 
To fix the off by one error during running local-rp.  See the issue for more details.
Tested my local rp with the provisioned resources in Azure and it worked as expected.
No.  Just a minor bug fix.
> Fix off by one error when truncating name

- pkg/cluster/arooperator.go
- pkg/cluster/arooperator_test.go
- pkg/cluster/ipaddresses.go
Just a follow up for #1972:
* Makes `createOrUpdateRouterIPFromCluster` reuse `isIngressProfileAvailable`
* And after merge I noticed that we should probably add an extra test case into `TestAroDeploymentReady`.
Unit tests should cover the changes
No, just refactoring
> Make createOrUpdateRouterIPFromCluster reuse existing code + extra case for TestAroDeploymentReady

- pkg/gateway/linkid_test.go
Fix: fixes build failure in linkid_test.go because of the renaming of metrics.Interface to metrics.Emitter
Fixes
Fix: fixes build failure because of the renaming of metrics.Interface to metrics.Emitter
> fix: now uses renamed interface metricsEmitter

- pkg/operator/controllers/imageconfig/doc.go
Signed-off-by: Karan.Magdani <kmagdani@redhat.com>
Fixes https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/14178822
Adds doc.go for imageconfig controller
N/A
N/A
> added doc.go for imgconfig controller

- pkg/cluster/delete.go
- pkg/cluster/delete_test.go
Co-authored-by: Ben Vesel <bennerv@users.noreply.github.com>
Fixes 13962494
If a Nic is in a failed provisioning state it will fail to be deleted.  This change will check the provisioning state of the nic and reconcile it if needed prior to attempting to delete the Nic.
Added delete_test.go for unit testing the deleteNic function.
Integration/e2e testing is not present for this change.  These tests would be difficult to automate as it requires a Nic in a failed provisioning state.
To manually test this change, one would need to find and delete a cluster with a failed Nic.
No
> Add logic to reconcile failed Nic on Cluster Delete

- pkg/operator/controllers/muo/muo_controller.go
- pkg/operator/controllers/pullsecret/pullsecret_controller.go
- pkg/operator/controllers/pullsecret/pullsecret_controller_test.go
Fixes wrong pull secret reference used for MUO and pull-secret controller
M2 MUO
> Update pull secret references from cloud.redhat.com to cloud.openshift.com

- .golangci.yml
I noticed that in our golangci config we have [go fmt simplify](https://pkg.go.dev/cmd/gofmt#hdr-The_simplify_command) disabled. I see no reason to disable it. So this PR enables go fmt simplify.
CI run
No, only changes linters
> Enables go fmt simplify in golangci config

- docs/custom-payload-testing.md
I didn't save this file after I made changes and missed checking it in in my other PR.  It's a readme so it's a noop but should update anyway.
> Missed reference to cloud.redhat.com in README file

- pkg/cluster/install.go
https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/14058347/
Fixes
The ensureAROOperator call in pkg/cluster/install.go (see https://github.com/Azure/ARO-RP/blob/master/pkg/cluster/install.go#L170 ) sometimes encounters an error because the API Server is not available between when the configmap is found and it runs. We should perform an APIServer Ready check, like in post-bootstrap, before we ensure the ARO Operator.
> ensure apiserverready check

- pkg/operator/controllers/muo/muo_controller_test.go
Fixes a case where we expect an error to occur but `err == nil`
Fix test code logic
Unit tests
nope
> Fail MUO test if we expect an error but don't get one

- pkg/deploy/predeploy.go
Fixes early rotation of secrets when deploying the RP
If the RP rotates secrets too early, there exists a chance where an RP instance restarts and reads in the new secret which the other instances do not have.  This will result in issues between the instances.  
This doesn't solve the issue, but decreases the likelyhood it will happen.
> Update the secret rotate time to 7 days during RP deploy

- pkg/mirror/graph.go
Removes dead code since we're now reading the release graph from 4.6+
We don't run this code anymore.  Clean up 
n/a
> Remove dead mirror code referencing 4.3 version which isn't mirrored

- pkg/util/version/const.go
Going forward, we will not override the Geneva images in FF Prod, but instead sync the images between gov cloud and public cloud.  
Removes unnecessary environment variable as we will now sync them.  
N/A
Yes, docs have been updated
https://msazure.visualstudio.com/AzureRedHatOpenShift/_wiki/wikis/ARO.wiki?wikiVersion=GBmaster&_a=edit&pagePath=/ARO%20MAG/How%20To/Mirroring&pageId=174102
> Remove ACR Image Override for Geneva

- .github/workflows/golint.yml
- .golangci.yml
- .pipelines/ci.yml
- hack/validate-imports/validate-imports.go
- pkg/operator/controllers/muo/muo_controller.go
- pkg/operator/controllers/muo/muo_controller_test.go
- pkg/operator/deploy/deploy.go
- pkg/operator/deploy/deploy_test.go
- pkg/portal/cluster/clusteroperators.go
- pkg/proxy/proxy.go
- pkg/util/cluster/cluster.go
- pkg/util/conditions/condition_test.go
- test/database/openshiftclusters.go
- test/e2e/adminapi_cluster_update.go
- test/util/project/project.go
Adds stylecheck as TODO was suggesting. Fixed code which did not comply.
I ran into problems updating the golangci-lint in vendor. It was required because the (very) outdated version did not recognize the options in the config file. I moved linting to a GitHub action which 
1. runs it in parallel
2. is much easier to keep up to date
3. has a better UX as linting errors will show up in github directly in the files tab.
> added stylecheck and moved golangci-lint to a github action

- docs/prepare-a-shared-rp-development-environment.md
Minor documentation updates to settings up the shared RP env from our working sessions. @karanmagdani
> Small updates to shared rp docs from working sessions

- python/az/aro/azext_aro/_client_factory.py
- python/az/aro/azext_aro/_params.py
- python/az/aro/azext_aro/commands.py
- python/az/aro/azext_aro/custom.py
Fixes https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/12703356/
⚠️ HOLD: wait to merge until ARM is updated. Reviews still appreciated :)
Updates the az cli extenion to use the new 2022_04_01 API and it's new features, namely, allowing customers to set FIPs mode on `az aro create`.
In addition to E2E/`make test-python` that runs in pipelines, the following manual testing cases have been performed on a local RP instance (and the VM Size test requires [modifying the development RP config](https://github.com/Azure/ARO-RP/blob/master/pkg/env/dev.go#L44)):
> NOTE: I was able to create a cluster with 1 worker as `Standard_L8s_v2`, before hitting a quota... the node came up healthy, even though the cluster operators were complaining because there weren't enough Nodes to …
> Update az cli extension to use api v2022_04_01

- pkg/cluster/deploystorage.go
- pkg/cluster/deploystorage_resources.go
- pkg/cluster/install.go
Part of cleanup for M5: https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/14317614
Removes the installconfig dependency in deploystorage, so that it doesn't have to strictly go after it (and also cleans up some of the code).
Created a cluster locally. E2E should also verify.
N/A
> Remove installconfig dependency from deploystorage

- pkg/cluster/deployresources_resources.go
- pkg/cluster/deploystorage.go
- pkg/cluster/deploystorage_resources.go
- pkg/deploy/devconfig.go
- pkg/deploy/generator/resources.go
- pkg/operator/controllers/previewfeature/nsgflowlogs/nsgflowlogs.go
- pkg/util/dns/dns.go
- test/e2e/operator.go
Removes unnecessary `to.StringPtr` function usage.
Some referenced in #2100 
e2e & deploy to INT
No
> Remove unnecessary to.StringPtr usages

- pkg/util/dynamichelper/dynamichelper_test.go
To improve unit test coverage for dynamichelper. This ADO task can be separated to multiple PRs for each function in the dynamichelper as suggested. This PR is for the function `makeURLSegments`
The dynamichelper is used in multiple important parts of our codebase and need better unit test coverage
No, this PR is mainly to meet the requirement in the ADO task [13525478 - Improve unit test coverage for dynamichelper](https://msazure.visualstudio.com/AzureRedHatOpenShift/_boards/board/t/Skippy/Stories/?workitem=13525478)
> Added unit test for the makeURLSegments function of dynamichelper

- pkg/monitor/cluster/clusterversions.go
- pkg/monitor/cluster/clusterversions_test.go
- pkg/util/version/version.go
We need a quick and live way to check the list of OCP minor versions along with the resourceID and subscriptionID to easily identify out of support lifecycle clusters. Due to Geneva limitations, we need to provide the minor version along with the full version to be able to generate corresponding report on Geneva side. 
Also pushes the GA version to allow out of lifecycle detection from Geneva
We need a quick and live way to check the list of OCP minor versions along with the resourceID and subscriptionID to easily identify out of support lifecycle clusters. Due to Geneva limitations, we need to provide the minor version along with the full version to be able to generate corresponding report on Geneva side. 
Also pushes the GA version to allow out of lifecycle detection from Geneva
- Are …
> add minor version

- pkg/frontend/admin_openshiftcluster_startvm.go
- pkg/frontend/admin_openshiftcluster_startvm_test.go
- pkg/frontend/admin_openshiftcluster_stopvm.go
- pkg/frontend/admin_openshiftcluster_stopvm_test.go
- pkg/frontend/admin_openshiftcluster_vmresize.go
- pkg/frontend/admin_openshiftcluster_vmresize_test.go
- pkg/frontend/admin_openshiftcluster_vmsizelist.go
- pkg/frontend/admin_openshiftcluster_vmsizelist_test.go
- pkg/frontend/adminactions/azureactions.go
- pkg/frontend/frontend.go
- pkg/frontend/validate.go
- pkg/util/azureclient/mgmt/compute/virtualmachines_addons.go
- pkg/util/mocks/adminactions/adminactions.go
- pkg/util/mocks/azureclient/mgmt/compute/compute.go
Net new creation of ARO cluster master resize geneva action
This work will allow us to leverage geneva actions to resize the compute assigned to ARO master nodes. 
Functionality can be tested through both direct calls to the RP as well as the pre-approved Geneva environment mock setup
Documentation and SOP will be provided once process (and PR) has been solidified.
> Geneva master resize

- pkg/cluster/clusterserviceprincipal.go
- pkg/cluster/denyassignment.go
- pkg/cluster/deployresources.go
- pkg/cluster/deploystorage.go
- pkg/cluster/gatewayprivateendpoint.go
- pkg/cluster/storageaccounts.go
- pkg/util/arm/deploy.go
- pkg/util/arm/deploy_test.go
Part of M5 installer cleanup: https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/14317614
When the installer code is isolated we will need to use the `armDeployTemplate` code in two locations. This moves it out of `pkg/cluster/` along with the tests, and also removes the need for a wrapper function in `pkg/cluster/`. We could move it into an interface and mock it later, if we wanted.
Unit tests follow the move, plus E2E should catch any problems.
N/A
> Move armDeployTemplate into util

- pkg/operator/controllers/subnets/subnet_controller_test.go
- pkg/operator/controllers/subnets/subnet_nsg.go
Fixes ADO-10554108
Fixes the issue when there is no NSG assigned to a subnet. Previously it would error out. RIght now it attaches the correct NSG.
added unit test to cover the case
n/a - bug
> NSG controller - reconcile nil NSG

- pkg/cluster/delete.go
- pkg/cluster/delete_test.go
Fixes the deletion of nics when they're in a failed provisioning state.  
Azure resource client returns bad data.  Why?  No clue.  
Below shows inconsistencies in the resource API response and the network RP response.  
```bash
$ az resource list -g aro-v4-e2e-v54339893-westus | jq -r '.[] | select(.id | contains("Microsoft.Network/networkInterface")) | [ .id, .provisioningState]'
[
"/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/aro-v4-e2e-v54339893-westus/providers/Microsoft.Network/networkInterfaces/v4-e2e-v54339893-west-qkbxk-master1-nic",
"Succeeded"
]
[
"/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/aro-v4-e2e-v54339893-westus/providers/Microsoft.Network/networkInterfaces/v4-e2e-v54339893-west-qkbxk-master0-nic",
"Succeeded"
]
[ …
```
> Fix deleteNic when the nic is in failed provisioning state

- pkg/cluster/storageaccounts.go
Fixes https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/14408834
Instead of "**subnet ID "" has incorrect length**", catch the error earlier and provide a clearer `lastAdminUpdateError` message.
This particular PUCM failure occurs when a machineset object fails to decode during cluster document enriching.  See the linked work item for further context.
Manually tested:
- Replicated condition seen in the wild: replaced machineset "zone" field with an unquoted numeric value.
- Ran admin update on cluster, observed error message in cluster document.
No.
> Provide clearer error for a particular type of PUCM failure

- Dockerfile.aro-multistage
Switches to using an ubi8 go-toolset for building.
In the 4.10 PR #2070 the build container was switched to using a different builder container image, because the RHEL 8 1.17 was not available when the PR was created. This PR simply switches back, but to ubi8 instead of ubi7.
Built and tested the container locally.
Nope.
> Switch to using the ubi8 go-toolset for building

- pkg/util/dynamichelper/dynamichelper_test.go
To improve unit test coverage for dynamichelper. This ADO task can be separated to multiple PRs for each function in the dynamichelper as suggested.
The dynamichelper is used in multiple important parts of our codebase and need better unit test coverage
No, this PR is to meet the requirement in the ADO task [Improve unit test coverage for dynamichelper](https://msazure.visualstudio.com/AzureRedHatOpenShift/_boards/board/t/Skippy/Stories/?workitem=13525478)
> Improved the unit test coverage for the merge function of dynamichelper

- pkg/operator/controllers/muo/muo_controller.go
- pkg/operator/controllers/muo/muo_controller_test.go
- pkg/util/version/const.go
Fixes https://dev.azure.com/msazure/AzureRedHatOpenShift/_workitems/edit/14536879
Enables MUO M2 by default.
Unit tests
N/A
> Enable MUO M2 by default

- pkg/api/admin/openshiftcluster.go
- pkg/api/admin/openshiftcluster_convert.go
- pkg/api/openshiftcluster.go
- pkg/operator/deploy/deploy.go
- pkg/operator/deploy/deploy_test.go
Fixes https://dev.azure.com/msazure/AzureRedHatOpenShift/_workitems/edit/14536867
Allows us to perform an Operator release separate to RP releases and specify the desired Operator version in the cluster document.
Unit tests for the functionality. 
Some SOPs, potentially, after merge.
> Allow overriding the operator version in the admin API

- hack/validate-imports/validate-imports.go
- pkg/cluster/deploystorage.go
- pkg/cluster/deploystorage_test.go
- pkg/cluster/install.go
Part of cleanup for M5: https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/14317614
This generates the Infra ID directly, in the same manner as the Installer. This removes a (small) dependency on it, and means we keep it consistent between infra versions. We need the InfraID before the Installer is run to create the Gateway, among other things.
Unit tests for the code, which can be run before and after the change to verify behaviour.
N/A
> Generate the InfraID without Installer dependency

- pkg/cluster/deploystorage.go
- pkg/cluster/install.go
Part of M5 installer cleanup https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/14317614
If we move to using Hive for the installer, we will have to save the InstallConfig that is provided to us *after* we call out to Hive to perform the installation. For the current install method, we can get closer to this by making any customisations before the deployment (which would be removed post-Hive) and then saving the graph after (which would remain after Hive).
E2E should test it.
N/A
> Split ensureGraph into customisations and saving

- python/az/aro/azext_aro/_aad.py
- python/az/aro/azext_aro/custom.py
Also changed the AADManager so that it only returns values
instead of the data structure.  This hides the implementation
details so that in the future if MSAL changes the internal
representation, any required changes will be contained within
the class (vs. right now custom.py has to be changed accordingly).
Fixes #2129 
Migrating from AAD Graph to MS Graph for az cli.  The change also removes all the references of AAD Graph.  It also includes a minor refactoring - AADManager now encapsulates the internal data structures from Microsoft Graph by only returning values and ids instead of maps or classes from the API.
Testing by trying to create, update and delete a cluster with the newly changed cli.  They were all successful.  More tests will be performed once the changes are submitted to …
> Migrate from AD to MS Graph

- hack/validate-imports/allowed-import-names.yaml
- pkg/api/v20191231preview/openshiftcluster_validatestatic.go
- pkg/api/v20191231preview/openshiftcluster_validatestatic_test.go
- pkg/api/v20200430/openshiftcluster_validatestatic.go
- pkg/api/v20200430/openshiftcluster_validatestatic_test.go
- pkg/api/v20210901preview/openshiftcluster_validatestatic.go
- pkg/api/v20210901preview/openshiftcluster_validatestatic_test.go
- pkg/api/v20220401/openshiftcluster_validatestatic.go
- pkg/api/v20220401/openshiftcluster_validatestatic_test.go
- pkg/api/validate/openshiftcluster.go
- pkg/api/validate/openshiftcluster_test.go
Fixes https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/14627987
In OCP 4.10 in non-zonal regions, VMs will be created with availability sets.  The names of these availability sets exceed the maximum length under certain circumstances, so we will prevent these circumstances from occuring by limiting the name length for these regions.  
Unit tests + shared dev env for australiasoutheast region cluster creation name length at 19 characters.
Peter is working on KCS article.  
Revert this once we have the fix upstream and set our default install version to this.
> Add name length validation on ARO clusters for non-zonal regions

- .pipelines/e2e-with-billing.yml
- .pipelines/templates/template-job-deploy-azure-env-tag.yml
- .pipelines/templates/template-job-deploy-azure-env.yml
- .pipelines/templates/template-prod-e2e-steps.yml
- .pipelines/templates/template-rp-and-billing-e2e.yml
- hack/e2e/run-rp-and-e2e.sh
Fixes https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/14628018/
This PR updates all e2e tests where CLUSTER name is generated.  The region under test is checked if it is a non-zonal region, if so the generated name is truncated to 19 characters.  If the region under test is a zonal region, it is generated as it was before.
Locally tested the bash commands in test script to validate logic / commands are correct.
e2e tests will need to be monitored, visually validating the cluster names for non-zonal regions are truncated to 19 characters and not truncated for all other regions.
N/A
> Truncate cluster names to 19 char in e2e pipelines

- pkg/util/namespace/namespace.go
- pkg/util/namespace/namespace_test.go
Fixes the drop of monitoring 'openshift-operator-lifecycle-manager'. [ADO Ticket 14657169](https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/14657169/)
We were previously monitoring this namespace which lead to a few clusters with unresolved issues. This PR is for the event we want to continue monitoring it.
unit test
no.
> include openshift-operator-lifecycle-manager in monitoring

- pkg/operator/controllers/machinehealthcheck/machinehealthcheck_controller.go
https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/14657654/)
When the cluster resource changes the MHC controller should kick in to check the flags. If the MHC deployed by the controller changes the MHC controller should kick in as well.
Manually tested
No
> fix bug where mhc wouldn't kick in after CR change

- pkg/cluster/deployresources.go
- pkg/cluster/deployresources_test.go
Unblocks https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/13111297
Currently, ARO installs fail (intentionally) if attempting to install into a 2-zone region. OpenShift supports installation into 2-zone regions in Azure, and Central US EUAP is a 2-zone region, so we need to allow installation to proceed if the RP detects less than 3 zones.
```
$ openshift-install explain installconfig.controlPlane.platform.azure.zones
KIND:     InstallConfig
VERSION:  v1
RESOURCE: <[]string>
Zones is list of availability zones that can be used. eg. ["1", "2", "3"]
```
Unit testing updated
Likely not
> Add RP support for 2-zone-regions

- pkg/cluster/deploystorage_resources.go
- pkg/cluster/storageaccounts.go
Fixes: https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/14361162
Admin put or patch fails with runtime error: index out of range [0] with length 0 when API server is unavailable (due to VMs being powered off)
Power off the VMs and run admin put or patch: update task starts, it will now skip the process, if there is no VMs with a Warn message
> Panic on AdminUpdate with MaintenanceTaskEverything

- pkg/cluster/install.go
- pkg/cluster/kubeconfig.go
Part of cleanups for https://dev.azure.com/msazure/AzureRedHatOpenShift/_workitems/edit/14625890
Moves InstallTime generation from the KubeConfig generation step (????) to startInstallation. I'm not sure why it was there, but it feels like some technical debt that got missed.
E2E should cover this.
Tech debt cleanup, n/a
> Move installtime set to startInstallation

- hack/validate-imports/allowed-import-names.yaml
- pkg/cluster/fixmcsuserdata.go
- pkg/operator/controllers/machine/machine.go
- pkg/util/clusterdata/worker_profiles_task.go
- pkg/util/machine/azureproviderspec.go
- pkg/util/machine/azureproviderspec_test.go
Fixes https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/14682300
Fix on a regression for azureproviderspec not utilizing the new way to decode/marshal the contents.  
Ran PUCM on 4.9 cluster with older version.  
No
> Fix azureproviderspec regression

- cmd/aro/mirror.go
Fixes https://dev.azure.com/msazure/AzureRedHatOpenShift/_workitems/edit/14536813
Mirrors FIPS-compliant images from the MUO and Hive Quay repos to ACR.
Tested using the instructions for mirroring images in INT. Seems to work fine.
N/A
> Mirror App-SRE images (MUO, Hive) to ACR

- cmd/aro/mirror.go
Offshoot of https://github.com/Azure/ARO-RP/pull/2126 since we wanted the mirror content in a separate PR.
- Adds required build images to cmd/aro/mirror.go
- Ensure pipelines are passing with the changes, and that images are being mirrored as expected.
No
> Add required build images to mirror

- pkg/cluster/deploystorage.go
- pkg/cluster/install.go
- pkg/installer/condition.go
- pkg/installer/custominstallconfig.go
- pkg/installer/deployresources.go
- pkg/installer/deployresources_resources.go
- pkg/installer/deployresources_test.go
- pkg/installer/generateconfig.go
- pkg/installer/graph.go
- pkg/installer/install.go
- pkg/installer/manager.go
- pkg/installer/overridemtu.go
Fixes https://dev.azure.com/msazure/AzureRedHatOpenShift/_workitems/edit/14625890
Moves the code that will later be pulled into/replaced by the standalone installer into a separate package for clarity. Contains no real logic changes.
Unit tests & E2E. 
Reorganisation, N/A
> Move the Installer-related code into a different package

- .pipelines/templates/template-job-deploy-azure-env-tag.yml
- .pipelines/templates/template-prod-e2e-steps.yml
- .pipelines/templates/template-push-images-to-acr-tagged.yml
- .pipelines/templates/template-push-images-to-acr.yml
We used to clear the auth files for docker/podman on exit, but with RHEL8 we switched to podman and it stores it's auth file in a separate location that should be cleared.  
Run e2e a few times
nah
> Clear the auth files when the pipeline exits

- test/util/log/audit.go
- test/util/log/log.go
Part of M5 cleanup work
Since the installer pull-out (or its dependencies) uses logging functionality, but does not need audit logging, we can split it into a different file so that it doesn't pull in any more dependencies.
Unit tests should suffice, this is testing code
N/A
> [M5] Split audit logging test functionality into a different file

- pkg/bootstraplogging/bootstraplogging.go
- pkg/cluster/install.go
- pkg/installer/custominstallconfig.go
- pkg/installer/deployresources.go
- pkg/installer/deployresources_resources.go
- pkg/installer/generateconfig.go
- pkg/installer/graph.go
- pkg/installer/install.go
- pkg/installer/manager.go
Part of https://dev.azure.com/msazure/AzureRedHatOpenShift/_workitems/edit/14625838
Removes the need to know about OpenShiftClusterDocument in pkg/installer. Makes pulling it out easier.
E2E
N/A
> [M5] Remove reliance on the OpenShiftClusterDocument in install code

- cmd/aro/operator.go
- pkg/operator/apis/aro.openshift.io/v1alpha1/cluster_types.go
- pkg/operator/controllers/checker/checker_controller.go
- pkg/operator/controllers/checker/clusterdns.go
- pkg/operator/controllers/checker/clusterdns_test.go
- pkg/operator/controllers/checker/ingresscert.go
- pkg/operator/controllers/checker/ingresscert_test.go
Fixes ADO-12201105
Adds checks for if a cluster has a custom Ingress certificate on the default ingress, or custom DNS operator configuration. These can lead to problems with the Authentication operator not working, so knowing about these configurations being non-default will help debugging.
Includes tests.
Not really, it should show up on the dashboard with other Operator checks.
> Add some egress/networking config checks in the Operator

- pkg/cluster/delete.go
- pkg/cluster/deregisterFromHive.go
- pkg/hive/manager.go
https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/14319615/
Depends on https://github.com/Azure/ARO-RP/pull/2145  ! 
Adds the deregistration of a cluster from hive (deletion of the corresponding namespace) at cluster deletion time
Draft, unit tests to follow
tbc
> Deregister cluster from hive

- pkg/installer/deployresources.go
- pkg/installer/deployresources_test.go
- pkg/installer/generateconfig.go
Fixes https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/14784728
- Fixes an issue deploying clusters in Central US EUAP due to a panic
- Confirm that the bug is no longer occurring (the region may still be impacted by the simply secure race condition)
No
> Fix panic bug in centraluseuap

- pkg/api/validate/dynamic/dynamic.go
- pkg/api/validate/dynamic/dynamic_test.go
- python/az/aro/azext_aro/_validators.py
ADO Card:
Fixes https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/13937166/
This PR adds the functionality to check the provisioning state for the Subnet.
If the subnet provisioning state is not in Succeeded state, there will be an exception raised.
Testing can be done by keeping the master/worker subnet state in a `failed` or `updating` state,
anything other than `Succeeded` and run the installation with `ARM Template`, `Bicept`, `az aro`, `Terraform` etc.
Cluster Installation shouldn't proceed if Subnets are not in the desired state.
> Adding validations for subnet provisioning state

- test/e2e/operator.go
- test/e2e/setup.go
[ADO User Story 11051435](https://msazure.visualstudio.com/AzureRedHatOpenShift/_boards/board/t/Chainsaw/Stories/?workitem=11051435)
This PR adds end-to-end tests for the ImageConfig reconciler. The tests themselves are basically a duplication of the unit tests but in a live cluster. Deployment of images from allowed or blocked registries are not currently tested.
Run e2e tests.
> Add e2e tests for ImageConfig operator

- pkg/frontend/asyncoperationresult_get.go
- pkg/frontend/asyncoperationresult_get_test.go
- pkg/frontend/asyncoperationsstatus_get.go
- pkg/frontend/asyncoperationsstatus_get_test.go
Fixes [14054515](https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/14054515)
If a client makes a request to endpoints "operationsstatus" or "operationsresult" the endpoint checks whether operationId from the request belongs to its subscription.
- new unit tests were added to verify the changes.
- All tests passed and coverage was obtained.
NA
> fix operation uniqueness

- pkg/cluster/fixmcsuserdata.go
- pkg/cluster/fixmcsuserdata_test.go
These changes extends tests of getUserDataSecretReference function that have been added in [another PR](https://github.com/Azure/ARO-RP/pull/2224). (Check @m1kola's comments)
> Update getUserDataSecretReference func and tests

- docs/deploy-development-rp.md
- pkg/util/cluster/cluster.go
[USER STORY 14922870](https://dev.azure.com/msazure/AzureRedHatOpenShift/_workitems/edit/14922870)
This PR adds an environment variable flag that can be used to create a private cluster without also blocking all internet egress traffic.
I set the new environment variable before creating a cluster locally and the verified that a private cluster was created. No additional unit or e2e tests are necessary as this flag is only for local development
Local development documentation has been updated to include this new flag as part of this PR
> Add Private Cluster Flag for Local Development

- test/e2e/aro.go
Signed-off-by: Karan <kmagdani@redhat.com>
Fixes https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/14105220/
This PR adds a new E2E test file. The idea of this file is to add tests that can definitely identify an ARO cluster. A failure here should mean that a cluster is not an ARO cluster. This is needed for clusters created by Hive
Not Applicable 
N/A
> e2e to definitively determine a cluster is ARO

- pkg/operator/controllers/muo/staticresources/config.yaml
- pkg/operator/controllers/muo/test_files/connected.yaml
- pkg/operator/controllers/muo/test_files/local.yaml
The configmap in MUO is changed in the following ways:
watchInterval set to 15 if LOCAL, 60 if OCM
Top level upgradeType key needs to be added, set to ARO
(see https://github.com/openshift/managed-upgrade-operator/pull/313/files )
Fixes: https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/14536830
> update muo configMap to reflect upstream updates

- hack/devtools/deploy-shared-env.sh
- pkg/deploy/assets/aks-development.json
AKS generates a random FQDN for the cluster API and, although we can interrogate for it, we should have a common naming convention. 
Provides a known URL pattern to access AKS in the shared dev environments, namely: api.aks.{australiaeast,eastus,westeurope}.osadev.cloud
The ARM template has already been deployed to the shared environments
No.
> Create DNS record for the AKS API during provisioning

- hack/hive-generate-config.sh
Updates Hive scripts to use latest version which includes support for private endpoints (https://github.com/openshift/hive/pull/1817).
> Updates Hive to the latest version

- .github/workflows/codeql-analysis.yml
updates codeql which now fails because it was using v1 which is being deprecated
All pipelines are going to start failing without that update
Fixes
> bumped version of codeql to v2

- pkg/cluster/hive.go
- pkg/hive/manager.go
- pkg/hive/resources.go
Fixes https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/15014584
Updates the way we create/update `ClusterDeployment`s: we need to provide a value for a new field which was introduced in https://github.com/openshift/hive/pull/1817 to make hive private endpoint aware.
This code path is disabled by default. E2E tests should indicate a regression, if there is any.
No, it is an internal implementation detail.
> Makes ClusterDeployment private endpoint aware

- pkg/api/error.go
- pkg/util/aad/aad.go
Fixes https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/15008430
This PR is intended to have errors returned from parseUnverified in aad specifically to return the same cloudError as serviceProviderCredentials. As of now, we see logs where it keeps retrying to get token and the error "Invalid client secret provided." is displayed for 10 minuets only for it to go through and have invalid segments on a token. This change will give a better idea of the issue and split it from an internalServerError to a userError.
> parseUnverified returns cloudError

- .github/workflows/codeql-analysis.yml
- .github/workflows/codeql-config.yml
Fixes issues with our codeql workflow doing too much.  
Skip scanning of the vendor directory because codeql goes crazy and dies on v2.  
Merge & Test?  
no
> Add codeql configuration to prevent scanning vendor directory

- pkg/backend/openshiftcluster.go
- pkg/hive/manager.go
Just a clean up: `IsConnected` is not used anywhere. We were considering using it in #2175, but most likely we will need something more generic.
> Remove `IsConnected` from `ClusterManager` interface

- pkg/cluster/adminupdate_test.go
- pkg/cluster/arooperator.go
- pkg/cluster/install.go
- pkg/operator/deploy/deploy.go
- pkg/util/mocks/operator/deploy/deploy.go
https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/11055603/
This PR creates an extra check condition for aroDepolymentReady to prevent a race condition while running AdminUpdate between ensureAROOperator and aroDeploymentReady functions. There was a scenario where the aro-operator was not running the desired image but the PUCM succeeds this maybe be because we are checking if aroDepolymentReady even before the deployment was actually applied on the cluster.
This PR helps to prevent such a race condition by checking if the deployment has the right version label.
> ensure that the ARO operator is running at the desired image

- .github/workflows/codeql-analysis.yml
updated to v2 and changed the concurrency on the extraction. This slows down the process a little but it avoid the errors. 
This was recommended by someone from codeQL [here](https://github.com/github/codeql/issues/9888) 
update codeql to v2 because it is being deprecated
https://github.com/Azure/ARO-RP/actions/runs/2733706014 
Ran it multiple times to see if it was working.
> codeql version bump and fix extraction

- hack/validate-imports/validate-imports.go
- pkg/cluster/hive.go
Fixes the issue is that import aliases (from both regex rules and yaml) are only being enforced if an import under the validation uses alias.
The last commit with the correct behaviour is 00fabbb5a3fdeafdfc9cabc098f026cb4f900139.
> Fixes validate-imports

- Dockerfile.aro-multistage
- Dockerfile.fluentbit
- Makefile
Fixes my sanity, and in a roundabout way, https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/14965439/
`microdnf` appears bugged in the ubi7 images. While building, the performance difference is 1 second vs 26 minutes for a "nothing to do" operation. In addition, this brings all images to this version (same as `Dockerfile.aro`, `Dockerfile.autorest`, etc):
UBI7:
```txt
$ docker run --rm -it registry.access.redhat.com/ubi7/ubi-minimal /bin/bash -c "time microdnf update"
Unable to find image 'registry.access.redhat.com/ubi7/ubi-minimal:latest' locally
latest: Pulling from ubi7/ubi-minimal
2447cd0fc475: Pull complete
555332c98e1f: Pull complete
Digest: sha256:dae599fce48f1388a7268010241752b17ea8e1ca524a74fd848cd16bfc61f1e4
Status: Downloaded newer image for …
```
> Remove all UBI7

- cmd/aro/mirror.go
- pkg/mirror/graph.go
Fixes the mirroring code when you pass in a specific version to be mirrored.  It previously would fail, now it works :1st_place_medal: 
```bash
[bvesel@fedora ARO-RP]$ go run -tags aro ./cmd/aro mirror 4.10.15
INFO[2022-07-13T15:39:06-04:00]cmd/aro/main.go:54 main.main() starting, git commit unknown                 
INFO[2022-07-13T15:39:06-04:00]pkg/env/core.go:62 env.NewCoreForCI() running in local development mode            
INFO[2022-07-13T15:39:08-04:00]cmd/aro/mirror.go:126 main.mirror() mirroring release 4.10.15                    
INFO[2022-07-13T15:39:08-04:00]pkg/mirror/mirror.go:72 mirror.Mirror() reading imagestream from quay.io/openshift-release-dev/ocp-release@sha256:ddcb70ce04a01ce487c0f4ad769e9e36a10c8c832a34307c1b1eb8e03a5b7ddb 
```
No
> Fix broken mirror specific version arg

- pkg/cluster/cluster.go
- pkg/hive/manager.go
- pkg/util/dynamichelper/dynamichelper.go
Credit to @hawkowl: it is taked from PR #2215 to make the PR smaller.
* Adds `dynamichelper` support for `ClusterDeployment`: dynamic helper doesn't update the status, but it logs objects diff. We don't care about the diff in status.
* Renaming constructors to be less verbose (it is clear what we return from signrature/return value
> Hive: `ClusterManager` changes and `dynamichelper` support for `ClusterDeployment`

- .config/CredScanSuppressions.json
Fixes 'Guardian: Post Analysis' Cred Scan error for passwords found in `pkg/portal/kubeconfig/kubeconfig_test.go` and `pkg/portal/ssh/ssh_test.go`
Adds `pkg/portal/kubeconfig/kubeconfig_test.go` and `pkg/portal/ssh/ssh_test.go` to `.config/CredScanSuppressions.json` suppression list.  This is needed for `sdl_sources` stage to pass for pipeline `OneBranch - Build and Publish Binary and Container - Official`
Observe build runs and stage passes.
NA
> Suppress CredScan false positives for passwords found in tests

- pkg/cluster/cluster.go
- pkg/cluster/hive.go
- pkg/hive/manager.go
- pkg/hive/resources.go
- pkg/hive/util.go
* Drops `CreateOrUpdateParameters` from `pkg/hive`. We now pass sub doc and cluster doc into the cluster manager instead having params struct.
* Minor renamings and extra comments
Refactoring to play more nicely with https://github.com/Azure/ARO-RP/pull/2215
> Hive, M5 prep: `ClusterManager` refactoring

- pkg/cluster/cluster.go
- pkg/cluster/hive.go
- pkg/hive/manager.go
Fixes the issue raised here: https://github.com/Azure/ARO-RP/pull/2215#discussion_r934123823
If we store a cluster doc or sub doc in `clusterManager` struct we risk it getting outdated during the lifetime of the `clusterManager`.
This happens because in the code calling `clusterManager` we do things like this:
```go
m.doc, err = m.db.PatchWithLease(ctx, m.doc.Key, func(doc *api.OpenShiftClusterDocument) error {
// ...
})
```
So `m.doc` receives a new reference, but `clusterManager`  still holds an old one.
> Hive: fixes the issue with outdated cluster doc

- pkg/deploy/assets/aks-development.json
Aligns the development cloud environment with production naming. Required for simplifying the development process to not force `if local dev` branching
Fixes
> Align AKS cluster naming with production

- hack/validate-imports/allowed-import-names.yaml
- pkg/hive/manager.go
- pkg/hive/resources.go
Refactoring. Prep for #2284
* Moves resource generation out of `ClusterManager`'s `CreateOrUpdate`
* Enforces `hivev1azure` import alias for `github.com/openshift/hive/apis/hive/v1/azure` module.
> Hive: moves resource generation out of `ClusterManager`'s `CreateOrUpdate`

- pkg/hive/util.go
Fixes naming convention and make hive kubeconfig constant unexported (only used inside the package at the moment)
> Makes hive kubeconfig constant unexported

- hack/get-admin-aks-kubeconfig.sh
Fixes old name for AKS cluster in the get kubeconfig script.
Fixes
> Fix the aks name in get kubeconfig

- pkg/deploy/config.go
Since we now manage SSH access through JIT directly, as opposed to using JIT to collect a permanent key, we can now remove the aforementioned private key. In order to pass ARM validation an authentication mechanism is required however so we're choosing to generate this on demand on deploy. 
Fixes
Accompanies the SSH Access JIT changes
Once deployed we can check the key value in authorised keys 
No docs already exist.
> generate and insert public key on deploy

- pkg/cluster/install.go
Some of the clusters in our fleet are not going to be alive enough for Hive to connect to their API server and Hive will not report ready condition. This can happen with clusters where VMs were powered off by customers.
If this happens - we do not want to fail admin patch operation.
> Makes admin patch skip not ready ClusterDeployment

- pkg/deploy/assets/rp-development.json
- pkg/deploy/generator/templates_rp.go
It is worth noting that it is used in the rp-production.json template but leaving it in place in the rp-development.json template unused results in a syntax error that states "unable to parse template on line 1". This causes the process to hang when settings up role assignments for the shared rp.
https://dev.azure.com/msazure/AzureRedHatOpenShift/_workitems/edit/14203980/
Allows us to setup the shared RP.
This has been tested by multiple parties via shared RP setup.
Documentation for this and other issues related to setting up the shared RP env and running the RP process locally is coming in another PR.
> Dropping ipRules parameter; it is not used in this template (causes "unable to parse template on line 1" error)

- pkg/deploy/assets/rbac-development.json
This allows for injecting a custom role definition (id) for the first party sub when preparing a shared environment to develop against.
This issue was tracked down by @karanmagdani and it happens when executing the code below during the shared setup process. Note, the usage of "fpRoleDefinitionId"="$(uuidgen)" below was added to allow the role definition to be created.
`LOCATION=eastus
az deployment sub create \
-l $LOCATION \
--template-file deploy/rbac-development.json \
--parameters \
"armServicePrincipalId=$(az ad sp list --filter "appId eq '$AZURE_ARM_CLIENT_ID'" --query '[].objectId' -o tsv)" \
"fpServicePrincipalId=$(az ad sp list --filter "appId eq '$AZURE_FP_CLIENT_ID'" --query '[].objectId' -o tsv)" \
"fpRoleDefinitionId"="$(uuidgen)" \
"devServicePrincipalId=$(az ad sp list …
> Updated rbac-development.json used in setting up a shared rp environment to allow for creating a custom role definition for the first party sub.

- pkg/frontend/admin_openshiftcluster_cordonnode.go
- pkg/frontend/admin_openshiftcluster_cordonnode_test.go
- pkg/frontend/admin_openshiftcluster_drainnode.go
- pkg/frontend/admin_openshiftcluster_drainnode_test.go
- pkg/frontend/adminactions/drain.go
- pkg/frontend/adminactions/kubeactions.go
- pkg/frontend/frontend.go
- pkg/util/mocks/adminactions/adminactions.go
- test/e2e/adminapi_drainnode.go
This PR creates admin endpoints that can be used to cordon, uncordon, and drain ARO cluster nodes. New endpoints will be targeted by new Geneva Actions (Phase 3)
[USER STORY 13912018 - Create Cordon or Uncordon Node Geneva Action](https://dev.azure.com/msazure/AzureRedHatOpenShift/_workitems/edit/13912018)
[USER STORY 13912064 - Create Drain Node Geneva Action](https://dev.azure.com/msazure/AzureRedHatOpenShift/_workitems/edit/13912064/)
This PR adds admin endpoints that can be used to cordon, uncordon, and drain ARO cluster nodes. These endpoints will eventually be targeted by new Geneva Actions that have been requested by ARO support (Phase 3 Geneva Actions).
Unit tests have been added for each new endpoint. I also ran the RP locally, created a cluster, and manually... 
- curled the new …
> Add Cordon and Drain Related Admin Endpoints for New Geneva Actions

- pkg/deploy/assets/rp-development-predeploy.json
- pkg/deploy/generator/resources_rp.go
Which issue this PR addresses:
https://dev.azure.com/msazure/AzureRedHatOpenShift/_workitems/edit/14178476
What this PR does / why we need it:
This gets us passed this error when deploying the shared RP env and gets the template updated to match production.
{"statusCode":"BadRequest","serviceRequestId":null,"statusMessage":"{"error":{"code":"SubnetsHaveNoServiceEndpointsConfigured","message":"Subnets rp-subnet of virtual network /subscriptions/26c7e39e-2dfa-4854-90f0-6bc88f7a0fb8/resourceGroups/v5-eastus/providers/Microsoft.Network/virtualNetworks/rp-vnet do not have ServiceEndpoints for Microsoft.Storage resources configured...
Test plan for issue:
This has been tested multiple times doing shared RP setups from localhost.
Ran 'make generate'.
Is there any documentation that needs to be …
> Added ServiceEndpoint for Microsoft.Storage to the generator for development

- Makefile
- requirements.txt
Fixes https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/15213631
This PR restricts the version of the python package autopep8 to 1.6.0. In order to accomplish that, a new `requirements.txt` file is added so we can track what specific python package versions we want, instead of relying on whatever is "latest" to work correctly. In the future we can bump package versions once we've tested that they work together.
Python package autopep8 1.7.0 was released yesterday. As a result, when pip installs azdev it now restricts flake8 to 2.3.0 instead of 4.0.1. Unit tests invoke flake8 with the `--append-config` parameter which wasn't supported in 2.3.0 so as a result tests fail.
This PR repairs the python unit tests. It works locally, and CI will confirm that it works from the …
> Pin python package versions using requirements.txt.

- pkg/deploy/assets/env-development.json
- pkg/deploy/assets/rp-development-predeploy.json
- pkg/deploy/assets/rp-production-predeploy.json
- pkg/deploy/generator/resources.go
- pkg/deploy/generator/resources_dev.go
- pkg/deploy/generator/resources_rp.go
- pkg/deploy/generator/templates_dev.go
- pkg/deploy/generator/templates_gateway.go
- pkg/deploy/generator/templates_rp.go
[USER STORY 14932248](https://dev.azure.com/msazure/AzureRedHatOpenShift/_workitems/edit/14932248/)
The current dev RP infrastructure has one VPN connected to the dev VNET. This can be used to access the private ip addresses associated with dev clusters, but cannot be used to access private IP addresses associated with the dev RP. Certain actions, like some E2E tests, require access to both simultaneously. Setting the VPN up in a way where the RP and dev clusters can be accessed simultaneously will allow other SREs to test changes more effectively.
I used the new ARM templates to create a shared RP and then used that RP to...
1. create a private cluster
2. pull the kubeconfig for that cluster and issue kubectl commands against it
3. curl the admin api endpoints to perform various cluster …
> Move Dev Environment VPN to Enable Connection to RP and Cluster Private IPs Simultaneously

- pkg/frontend/admin_openshiftcluster_kubernetesobjects.go
- pkg/frontend/admin_openshiftcluster_kubernetesobjects_test.go
- pkg/frontend/adminactions/kubeactions.go
- pkg/frontend/validate.go
- pkg/util/mocks/adminactions/adminactions.go
- test/e2e/adminapi_kubernetesobjects.go
This PR adds a force parameter to the delete kubernetes object admin endpoint that can be used to force delete pods, and only pods. New parameter will be leveraged by an updated Geneva Action (Phase 3)
[USER STORY 14336714 - Modify Kube Delete Admin Endpoint to Accept Force Parameter for Pods](https://dev.azure.com/msazure/AzureRedHatOpenShift/_workitems/edit/14336714)
This PR adds a force parameter to the delete kubernetes object admin endpoint that can be used to force delete pods, and only pods. This new parameter will eventually be used by an updated Geneva Action (Phase 3). Functionality was requested by ARO support.
Unit tests have been added for the new parameter. I also ran the RP locally, created a cluster, and manually curled the "kubernetesObjects" endpoint to confirm...
- the …
> Add Force Delete Parameter to Delete Kubernetes Object Admin Endpoint for New Geneva Action

- pkg/cluster/install.go
Allows customers to self-service certificate updates instead of relying on ARO SRE to patch the cluster.
> az aro update: startvms, validate api servers, and configure api/ingress certs

- Makefile
N/A
Stops printing the admin password to console in plaintext on login. Output goes from:
```txt
$ make shared-cluster-login
oc login https://foo.bar.com:6443/ -u kubeadmin -p thesamepasswordasmyluggage
Login successful.
You have access to 68 projects, the list has been suppressed. You can list all projects with 'oc projects'
Using project "default".
```
to
```txt
$ make shared-cluster-login
Login successful.
You have access to 68 projects, the list has been suppressed. You can list all projects with 'oc projects'
Using project "default".
```
N/A
> Make: stop printing the admin password to console on login

- .pipelines/generate-release-notes-tagged.yml
- docs/releases.md
Release notes are not currently being generated with EV2 pipelines.
Removes the build steps from the pipeline so it only generates release notes as release notes are not currently being generated with EV2 pipelines.  We don't need build steps as this is also done in EV2 pipelines.
Need to test in ADO when able.
Updated `docs/releases.md`
> update pipeline to only generate release notes

- pkg/cluster/storageclass.go
Fixes https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/15298895
If the installation stops for any reason after the default storage account is already created, and then attempts to resume creation, it will fail since the default storage account already was created.  We shouldn't fail on this error.  
It's a very rare scenario, but technically possible and our installation should be idempotent.  
N/A
N/A
> Do not fail cluster installation if the default storage account already exists

- pkg/operator/controllers/genevalogging/const.go
The PR is to exclude logs from the openshift-logging namespace. 
Fixes [Exclude openshift-logging logs from being ingested into Azure log infrastructure](https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/13146970/)
This is to exclude logs from openshift-logging and openshift-gitops logs going into the Azure Geneva logging infrastructure due to the fact that incorrectly configured customer log ingestion can result in customer workload logs being ingested into Geneva
**Update**:  The PR has been updated to also exclude logs from the `openshift-user-workload-monitoring` namespace
> Add expression to exclude logs from openshift-logging namespace

- pkg/operator/deploy/deploy.go
- pkg/operator/deploy/deploy_test.go
- pkg/operator/deploy/staticresources/master/deployment.yaml.tmpl
- pkg/operator/deploy/staticresources/worker/deployment.yaml.tmpl
Fixes https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/15288173
Currently, if `o.oc.properties.OperatorVersion` is not set (i.e. we're not overriding the operator version we deploy into the cluster), then the label on the aro-operator deployments is set to `unknown`, which results in PUCM always failing since we very rarely override the OperatorVersion. 
This needs some unit tests & manual testing
manual testing:
1.  ARO_IMAGE set & no tag set -> version label should be "latest"
2. ARO_IMAGE set & a tag set -> version label should be tag
3. OperatorVersion set & overridden -> version label should be "operatorVersion"
AdminUpdate with the above scenarios.  They should all work as documented above
no
> Refactor how we version the aro operator deploymennt

- .pipelines/e2e.yml
- hack/e2e/run-rp-and-e2e.sh
Fixes https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/15325401
Add a vpn connection for e2e runs. The connection is configured with the `$VPN` environment variable. 
The variable can be configured in the environment as a pipeline variable.
The current `$VPN` should be set to `vpn-aks-eastus.ovpn`. 
It will enable direct access to the AKS subnet to allow RP to communicate with AKS API.
IMPORTANT: The variable needs to be set up in the pipelines!!!
> Add vpn code run before e2e to connect to the aks

- pkg/frontend/openshiftcluster_putorpatch.go
- pkg/frontend/openshiftcluster_putorpatch_test.go
- pkg/frontend/shared_test.go
Fixes a bug in production.
When a PUT is done, copy over the SystemData so that it does not fail static validation. This would cause PUTs to fail on API v2022-04-01 and above.
Has unit tests.
No, bug fix
> Fix OpenShiftCcluster PUTs causing static validation errors due to ARM metadata

- pkg/api/operation.go
- pkg/api/register.go
- pkg/api/v20191231preview/register.go
- pkg/api/v20200430/register.go
- pkg/api/v20210901preview/register.go
- pkg/api/v20220401/register.go
- pkg/api/v20220904/register.go
- pkg/frontend/operations_get.go
Fixes an issue where we return all operations that are supported no matter the API version used to query
Above
Currently, a call directly to our resource provider returns all supported operations.
```
az rest --method GET --uri /providers/Microsoft.RedHatOpenSHift/operations?api-version=2019-12-31-preview | jq -r '.value[] | .name'
Microsoft.RedHatOpenShift/locations/operationresults/read
Microsoft.RedHatOpenShift/locations/operationsstatus/read
Microsoft.RedHatOpenShift/openShiftClusters/read
Microsoft.RedHatOpenShift/openShiftClusters/write
Microsoft.RedHatOpenShift/openShiftClusters/delete
Microsoft.RedHatOpenShift/openShiftClusters/listCredentials/action
Microsoft.RedHatOpenShift/openShiftClusters/listAdminCredentials/action
Microsoft.RedHatOpenShift/operations/read
```
When running …
> Set supported operations on an API version basis

- pkg/deploy/assets/rp-development.json
- pkg/deploy/assets/rp-production.json
- pkg/deploy/generator/resources_rp.go
- pkg/util/rbac/rbac.go
Fixes https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/15374040 
Add the AKS cluster admin role to the int and production MSI to allow RP reading the kubeconfig.
> Add AKS cluster admin role to the RP MSI

- cmd/aro/mirror.go
Updates the Hive image tag to the latest one that includes the logging field changes. Also merged the loops processing Red Hat registry images into one to reduce code duplication.
Tested locally.
No.
> Update Hive image mirror tag

- Makefile
- hack/build-client.sh
None
Specifies to use linux/amd64 when building or running images. This is needed if you are running a non-amd64 architecture (like arm64/v8).
Ran locally on arm64 based system.
No
> Specify platform when building or running images

- cmd/aro/mirror.go
Adds the azure-cli image to mirror. 
A pod running `az` is required for certain breakglass scenarios executed by SRE, and mirroring this image to prod saves us some time manually installing `az` into a different container image in the event that a production cluster isn't able to pull the image from `mcr.microsoft.com` directly (it happened today).
> Add `mcr.microsoft.com/azure-cli` image to mirror

- .pipelines/e2e.yml
Fixes https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/15372448/
Adds environment variable to the E2E pipeline to read the kubeconfig from the `secrets` folder.
E2E does not have MSI deployed, which means this is the only way to read kubeconfig.
This is for the tests to be able to run.
> Add HIVEKUBECONFIGPATH variable to e2e

- Dockerfile.autorest
- Makefile
- hack/build-client.sh
relates to ADO-15132425
Minor changes to autorest image and client generation:
- remove superfluous flags when installing autorest
- remove no longer needed sudo commands
- run sed operation inside a container, to eliminate flag differences between BSD/Darwin and GNU/Linux versions of sed
Tested locally
No, these are just small fixes to scripts
> Fix autorest client generation

- pkg/deploy/assets/rbac-development.json
This PR addresses [Bug 15410842](https://dev.azure.com/msazure/AzureRedHatOpenShift/_workitems/edit/15410842) which prevents a shared RP from creating clusters with only resource group write permission on the subscription. It now also needs resource group read permission.
This PR adds the `Microsoft.Resources/subscriptions/resourceGroups/read` permission to the "ARO v4 Development First Party Subscription (DEV)" role definition in the `rbac-development.json` ARM template. Without this permission, shared/local RP's cannot be used to create ARO clusters.
I manually added the "Microsoft.Resources/subscriptions/resourceGroups/read" permission to the "ARO v4 Development First Party Subscription (DEV)" in the local dev subscription, then verified I was able to create clusters using a shared RP. …
> Update Shared RP Custom Role Permissions

- hack/rhcos-sas/rhcos-sas.go
N/A, ref: https://github.com/Azure/ARO-RP/pull/2339
This updates the authentication mechanism used by the hack script to get access to the (temporary) Storage Account used to store RHCOS images and get SAS links.
N/A - I did verify that the auth works after sourcing proper envvars and running `az login`.
Yes, I've done that [in our wiki](https://msazure.visualstudio.com/AzureRedHatOpenShift/_wiki/wikis/ARO.wiki/186149/How-To-Publish-New-OCP-Image-for-ARO?anchor=copy-the-image-and-get-os-vhd-link)
> Update auth used by rhcos uploads

- pkg/deploy/assets/rp-production-predeploy-parameters.json
- pkg/deploy/assets/rp-production-predeploy.json
- pkg/deploy/generator/templates_rp.go
- pkg/deploy/predeploy.go
Forces the RP NSG to redeploy in order to get new GenevaActions tag. The commit to do so in #2333 was incorrect and did not cause a redeploy.
Confirm the NSG gets redeployed properly.
No
> Forcibly redeploy RP NSG to get new GenevaActions rule

- pkg/monitor/cluster/clusteroperatorconditions.go
Fixes https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/9338383
In the past: 
"As already [reported](https://github.com/openshift/cluster-kube-storage-version-migrator-operator/issues/25) by another team member, kube-storage-version-migrator is currently being constantly reported as "Upgradeable" condition status "Unknown". This makes the Cluster Operator constantly being reported as unhealthy and creates a lot of noise in our dashboards."
Now:
kube-storage-version-migrator is NO longer reported as "Upgradeable" condition status "Unknown". So we can now remove the filter that was previously done in https://github.com/Azure/ARO-RP/pull/1310
Explanation:
I have created a new cluster (using local ARO-RP) and after executing 
`oc get clusteroperator -o yaml`
we can see the …
> remove kube-storage-version-migrator condition filter (do not Ignore Upgradeable/Unknown condition)

- cmd/aro/mirror.go
- hack/hive-generate-config.sh
Updates the Hive image to the one that has the CLI Image override feature.
I tested the image after building it and it successfully replaced the CLI Image domain.
Nope.
> Hive image with CLI Image domain override support

- pkg/frontend/installversions_list_test.go
Fixes a flake in the list install versions unit test
The response from the RP is non-deterministic.  So we must first sort the response before validating it.
Ideally, we could check the presence of values rather than comparing responses, but then we'd have to write a custom function for this specific test and I would rather just sort.  
```bash
$ while true; do go test -run ^TestListInstallVersions$ -count=1 ./pkg/frontend/; done
PASS
...
```
No
> Fix Frontend Unit Test Flake in List Install Versions

- pkg/deploy/assets/rp-development.json
- pkg/deploy/assets/rp-production.json
- pkg/deploy/generator/resources_rp.go
- pkg/util/rbac/rbac.go
Part 1 of fixing an issue where we are unable to gain access to a regions AKS clusters to debug Hive/Logging until the RP has been deployed in that region.
The AKS resource group role assignment is being removed in this PR and a cluster specific role assignment is being added to the AKS ARM template in the related [ARO Pipelines PR](https://msazure.visualstudio.com/AzureRedHatOpenShift/_git/ARO.Pipelines/pullrequest/6736059).
**Note:** This PR needs to be merged before the next release and the related PR merged and deployed to the existing environments.
This is a direct revert of https://github.com/Azure/ARO-RP/pull/2350
No.
> Revert RP AKS role assignment in favour of the AKS ARM template

- pkg/frontend/admin_openshiftcluster_approvecsr.go
- pkg/frontend/admin_openshiftcluster_approvecsr_test.go
- pkg/frontend/adminactions/certificatesigningrequests.go
- pkg/frontend/adminactions/kubeactions.go
- pkg/frontend/frontend.go
- pkg/util/mocks/adminactions/adminactions.go
- test/e2e/adminapi_csr.go
This PR creates an admin endpoint that can be used to approve CSR's in an ARO cluster. New endpoint will be targeted by a new Geneva Action (Phase 3)
[USER STORY 13911981 - Create Cordon or Uncordon Node Geneva Action](https://dev.azure.com/msazure/AzureRedHatOpenShift/_workitems/edit/13911981)
This PR add an admin endpoint that can be used to approve CSR's in an ARO cluster. CSR's can be approved individually by name, or all CSR's can be approved at once. This endpoint will eventually be targeted by a new Geneva Action that has been requested by ARO support (Phase 3 Geneva Actions).
Unit tests have been added for the new endpoint. I also ran the RP locally, created a cluster, and manually curled the new "approveCsr" endpoint to confirm...
- the approval of a single CSR in the cluster
- …
> Add Approve CSR Admin Endpoint for New Geneva Action

- pkg/deploy/assets/databases-development.json
- pkg/deploy/assets/rp-production.json
- pkg/deploy/generator/resources_rp.go
In CosmosDB, adding unique indexes to existing collections with items is not allowed. 
https://docs.microsoft.com/en-gb/azure/cosmos-db/mongodb/mongodb-indexing#limitations-1
This is causing deployments to fail with an error
```
{"code":"Forbidden","message":"Message: {"Errors":["The unique index cannot be modified. To change the unique index, remove the collection and re-create a new one."]}
```
Reverting for now to unblock deployments, need to regroup later to determine how to implement this change in int and prod.
> Remove the UniqueKeyPolicy from the Subscriptions database

- hack/validate-imports/validate-groups.go
Validate groups can conflict with generated files. This fixes it by ignoring generated files. 
Fixes
> validate-groups now ignores generated files

- pkg/api/openshiftcluster.go
- pkg/api/validate/dynamic/quota.go
- pkg/api/validate/vm.go
[15533999](https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/15533999)
Allows day 1 support for selecting GPU instance types as worker nodes
Create a new cluster with one the new GPU worker types.
Not that I am aware
> add gpu instance types

- pkg/operator/controllers/imageconfig/image_controller.go
- pkg/operator/controllers/imageconfig/image_controller_test.go
- test/e2e/operator.go
Fixes https://msazure.visualstudio.com/AzureRedHatOpenShift/_boards/board/t/Chainsaw/Stories/?workitem=15120407
Makes the ImageConfig controller aware of running in INT/non-INT environments.
Unit tests created or updated as needed, e2e tests updated.
None
> make ImageConfig environment aware

- pkg/cluster/graph/manager.go
- pkg/dbtoken/client_test.go
- pkg/deploy/config.go
- pkg/deploy/devconfig.go
- pkg/deploy/generator/generators.go
- pkg/frontend/middleware/body.go
- pkg/frontend/shared_test.go
- pkg/hive/install.go
- pkg/operator/controllers/checker/internetchecker_test.go
- pkg/portal/kubeconfig/kubeconfig_test.go
- pkg/portal/kubeconfig/proxy_test.go
- pkg/portal/middleware/aad.go
- pkg/portal/prometheus/proxy.go
- pkg/portal/prometheus/proxy_test.go
- pkg/portal/ssh/ssh_test.go
- pkg/portal/util/responsewriter/responsewriter.go
- pkg/proxy/dialer.go
- pkg/proxy/proxy.go
- pkg/util/clientauthorizer/arm_test.go
- pkg/util/clientauthorizer/subject_name_and_issuer.go
- pkg/util/instancemetadata/prod_test.go
- pkg/util/portforward/streamconn.go
ioutil has been deprecated, this replaces it with the new apis.
Fixes
ioutil deprecated https://go.dev/doc/go1.16#ioutil
unit-tests
n/a
> removal of ioutil references

- pkg/api/v20220904/clustermanager_convert.go
- pkg/api/v20220904/register.go
Fixes 2 regressions that occured in the final minutes of M8 implementation
1. During a rebase lost the `ClusterManagerConverter` from the `v20220904` api
2. Changed the API model from accepting JSON input to a base64 encoded string (of JSON) which required the removal of an unnecessary json.Unmarshal
manually tested, unit tets in flight here https://github.com/Azure/ARO-RP/pull/2411/files
n/a
> fix regressions from rebase/refactors

- pkg/api/error.go
- pkg/api/validate/dynamic/provider.go
- pkg/cluster/delete.go
Usage: Fixes https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/14409128
Fixes
This PR adds a new CloudErrorCode for the top incorrectly categorized server error case occurring in cluster delete. While producing the newly created ErrorCode, it essentially transforms a DetailedError into a CloudError type. We need this because currently the metrics for cluster delete looks for the CloudError type to understand if the issue is a user or server error, and when not CloudError, it defaults to server error. Here is a related ICM where the loadbalancer can't be deleted with a privateLinkService, but is mitgated as it's a user error, https://portal.microsofticm.com/imp/v3/incidents/details/305928113/home
When deleting a cluster with a private link service, logs correctly …
> CloudError added for clusterDelete

- .pipelines/e2e.yml
N/A
Removes dupe kill_vpn command from E2E runs
Will review E2E run
No, not required
> Removing dupe kill_vpn

- .pipelines/e2e.yml
- docs/prepare-a-shared-rp-development-environment.md
- hack/devtools/deploy-shared-env.sh
- hack/e2e/run-rp-and-e2e.sh
- pkg/cluster/nsg.go
- pkg/deploy/assets/aks-development.json
- pkg/util/azureclient/mgmt/network/virtualnetworkpeerings.go
- pkg/util/azureclient/mgmt/network/virtualnetworkpeerings_addons.go
- pkg/util/cluster/cluster.go
- pkg/util/mocks/azureclient/mgmt/network/network.go
This reverts #2300 and #2417 which enabled SimplySecure Ev2 pipelines
Will run/monitor e2e pipelines after merge
No
> Revert 'CI E2E in SimplySecure'

- python/az/aro/azext_aro/custom.py
Fixes the ability to install multi-version OCP clusters and the `az aro get-versions` output.
Tested multi-version cluster creation using the az CLI.
Nope.
> az CLI changes required for the latest OpenShiftVersion API version and multi-version functionality

- Makefile
Fixes ADO e2e tests not displaying color, it had bad output in ev2 which is why it was removed, but e2e now uses its own parameters see https://msazure.visualstudio.com/AzureRedHatOpenShift/_git/ARO.Pipelines?path=/ev2/Deployment/ServiceGroupRoot/bin/rpe2e.sh
Makes viewing e2e failures in ADO much easier. 
:fire: 
no
> add color back into e2es, easier to see pass/fails in ADO

- .pipelines/templates/template-prod-e2e-steps.yml
- Makefile
- pkg/operator/README.md
Changes nothing: only adds missing `-` (apperently ginkgo works with single - in flags as well) and re-orders flags so that `go test` flags are grouped together and `ginkgo` flags are together.
> Stylistic: makes e2e flags consistent

- hack/licenses/main.go
- pkg/database/billing.go
- pkg/monitor/cluster/machineconfigpool.go
- pkg/operator/controllers/pullsecret/pullsecret_controller.go
- pkg/operator/controllers/subnets/subnets_controller.go
- pkg/util/pullsecret/pullsecret.go
- pkg/util/purge/resourcegroups.go
- pkg/util/status/clusterversionoperator_status.go
Fixes https://coreos.slack.com/archives/C02ULBRS68M/p1664313661925289
Current golangci-lint (I tested 1.49.0) enforces some go1.19 rules on comment formatting. I have used go1.19.1's `gofmt -s` to fix those comments that golangci-lint complains about. Here's an example of the kind of lint errors I see, although this process had to be repeated on other files that golangci-lint complains about once these first three are gofmt'ed.
```
$ make lint-go
hack/lint-go.sh
WARN [runner] The linter 'deadcode' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.  Replaced by unused. 
pkg/util/pullsecret/pullsecret.go:23: File is not `gofmt`-ed with `-s` (gofmt)
//   {"auths": {"secret key": {"auth": "secret value"}, "secret key": {"auth": "secret value"}}} …
```
> Adjust comment formatting to appease newer golangci-lint versions

- .pipelines/e2e.yml
- docs/prepare-a-shared-rp-development-environment.md
- hack/devtools/deploy-shared-env.sh
- hack/e2e/run-rp-and-e2e.sh
- pkg/cluster/nsg.go
- pkg/deploy/assets/aks-development.json
- pkg/util/azureclient/mgmt/network/virtualnetworkpeerings.go
- pkg/util/azureclient/mgmt/network/virtualnetworkpeerings_addons.go
- pkg/util/cluster/cluster.go
- pkg/util/mocks/azureclient/mgmt/network/network.go
Implements Vnet peering solution for SimplySecure V2. This builds on the solution by adding a check for `RP_MODE=development`. There are two flags at play which work as follows:
1. `CI=False`, `RP_MODE=development` => Used for Local Cluster Creations using hack scripts
2. `CI=True`, `RP_MODE=development` =>  Used for E2E tests run against each PR 
3. `CI=True`, `RP_MODE unset / int / production` => Used for E2E on Int / Prod environments
4. `CI=False`, `RP_MODE unset / int / prodution` => Used for creating actual clusters 
This PR enables VPN support on our CI-E2E Pipelines. The pipeline connects to a vpn before creating private clusters and running end to end tests. This will facilitate running pipelines when SimplySecure V2 is enabled on our subscriptions
Going to wait for Public Int …
> CI E2E in SimplySecure

- pkg/api/admin/openshiftcluster.go
- pkg/api/admin/openshiftcluster_validatestatic.go
- pkg/api/openshiftcluster.go
- pkg/cluster/adminupdate_test.go
- pkg/cluster/arooperator.go
- pkg/cluster/install.go
- pkg/operator/deploy/deploy.go
- pkg/util/mocks/operator/deploy/deploy.go
Fixes: https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/15581636/
During regular PUCM few of the clusters are failing and these clusters are unable to fetch the new certificates from RP as these steps never run after the PUCM failure due to customer policies or other issues. With this PR we can just simply run the steps which will fetch new certificates and install them in the cluster without the need to run all the steps in regular PUCM.
No Test Cases for this issue. Just re-using the existing functions which already have test cases written.
CURL Command to perform Admin Update just for certificates renewal:
curl -X PATCH -k "https://localhost:8443/subscriptions/$AZURE_SUBSCRIPTION_ID/resourceGroups/$RESOURCEGROUP/providers/Microsoft.RedHatOpenShift/openShiftClusters/ …
> Certificate renewal PUCM type to rotate in-cluster MDSD/ingress/API certs

- test/e2e/operator.go
Follow up from https://github.com/Azure/ARO-RP/pull/2430#discussion_r984763943: I think we already have unit test coverage for this in [`pkg/api/defaults_test.go`](https://github.com/Azure/ARO-RP/blob/f7895a143c348cd16e83043d14429504c29f1a13/pkg/api/defaults_test.go).
Run E2E
No, just a E2E clean up
> Removes e2e which duplicates unit test coverage

- pkg/portal/middleware/aad.go
- pkg/portal/middleware/aad_test.go
Fixes: https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/15664001
Instead of responding with an HTTP 500 when a cookie decode error is encountered, we should be clearing the cookie and returning an HTTP 403. This PR changes the behaviour, so that when we are loading the SRE portal in a secret rotated region that we were previously logged into we are presented with a login dialog instead of an internal server error.
Local testing and existing, slightly modified, unit tests.
Nope.
> Fix InternalServerError for decoding outdated securecookie

- test/e2e/disk_encryption.go
- test/e2e/setup.go
Part of the [WI 13667437](https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/13667437).
* Removes unused clients
* Switches some tests to the newer API version
Run E2E
No, just test refactoring.
> E2E clients cleanup

- .pipelines/e2e.yml
- .pipelines/vars.yml
- hack/e2e/run-rp-and-e2e.sh
- test/e2e/setup.go
Fixes https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/11004136 and https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/12519725/
For reviewers - here is a recent pipeline run with these changes where e2e failed, and a must-gather was collected and appended as an artifact: https://msazure.visualstudio.com/AzureRedHatOpenShift/_build/results?buildId=59130662&view=logs&j=0eff6622-f27f-5719-c5b3-a82191700046&t=0eff6622-f27f-5719-c5b3-a82191700046
- Adds a step to CI runs that appends a must-gather
- Executes the step only when the E2E job fails
Confirm in CI that behavior is as expected
Yes, we will need to update documentation on debugging e2e: https://msazure.visualstudio.com/AzureRedHatOpenShift/_wiki/wikis/ARO.wiki/166757/Debug-E2E
> Collect must-gathers on failed e2e runs

- test/e2e/adminapi_cluster_getlogs.go
- test/e2e/adminapi_kubernetesobjects.go
Previously the test was claiming to compare logs from RP with known logs, but in fact we were comparing logs from RP with logs received derectly from API server.
Run E2E
No, just E2E fixes.
> Fixes get pod logs E2E

- pkg/operator/deploy/staticresources/master/deployment.yaml.tmpl
- pkg/operator/deploy/staticresources/worker/deployment.yaml.tmpl
Fixes [ADO15807401](https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/15807401)
If the git commit hash does not contain any letters, the aro operator will fail to deploy the deployments since k8s doesn't like labels that are only numbers.  This change will force a string.  
```bash
time="2022-10-11T04:01:36Z" level=info msg="starting, git commit 8799195" func="main.main()" file="cmd/aro/main.go:55"
time="2022-10-11T04:31:14Z" level=info msg="running step [Action github.com/Azure/ARO-RP/pkg/cluster.(*manager).ensureAROOperator-fm]" func="steps.Run()" file="pkg/util/steps/runner.go:47" 
time="2022-10-11T04:31:14Z" level=error msg="cannot ensureAROOperator.CreateOrUpdate: json: cannot unmarshal number into Go struct field ObjectMeta.metadata.labels of type string" …
```
> Force the aro operator deployment to be a string

- pkg/api/validate/dynamic/quota.go
Fixes [ADO15807536)](https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/15807536)
Fixes the incorrect NCASv3_T4 family type for GPU instances during quota validations\
Try to create a cluster with Standard_NC16as_T4_v3 instance types and have it fail quota validation.
```bash
400: ResourceQuotaExceeded: : Resource quota of Standard NCASv3_T4 Family exceeded. Maximum allowed: 0, Current in use: 0, Additional requested: 192.
```
no
> Set the correct VM family on the currently supported GPU instance types

- test/e2e/setup.go
For better local development experience where we do not have a fresh docker instance on every run.
Run E2E
No, just E2E improvements
> Adds selenium teardown to E2E

- test/e2e/setup.go
Follow-up for https://github.com/Azure/ARO-RP/pull/2467
Moves container name into constant
Run E2E
> Adds selenium teardown to E2E: follow-up

- pkg/deploy/assets/rp-development-predeploy.json
- pkg/deploy/assets/rp-production-predeploy.json
- pkg/deploy/generator/resources_rp.go
- pkg/deploy/predeploy.go
Addresses part of: https://dev.azure.com/msazure/AzureRedHatOpenShift/_workitems/edit/15664463
We need to work towards a single source of truth for our deployment pipelines and, with that in mind, the current deploy pipeline is run in the following order:
1. Bootstrap
1. AKS
1. MDSD
1. Hive
1. RP
The bootstrap pipeline is already adding all of the Keyvault issuers, now that the missing ones have been added ([1](https://dev.azure.com/msazure/AzureRedHatOpenShift/_git/ARO.Pipelines/pullrequest/6812249), [2](https://dev.azure.com/msazure/AzureRedHatOpenShift/_git/ARO.Pipelines/pullrequest/6789244)), so there is no need to duplicate the steps in the RP deploy process and they are being removed in this PR.
The next issue this PR addresses is the issue the RP deploy pipeline is overwriting the …
> AKS AgentPool MSI permissions and remove duplicated Keyvault issuer steps

- pkg/monitor/cluster/cluster.go
- pkg/monitor/worker.go
- test/e2e/monitor.go
There seems to be a useless parameter in the newmonitor function
Fixes
> removed useless parameter in clustermonitor

- pkg/cluster/disableupdates.go
Fixes: https://dev.azure.com/msazure/AzureRedHatOpenShift/_workitems/edit/15728770
Due to the ACR Domain constraints in production, we  set the domain to the ACR Domain during the cluster installation. Once the installation has succeeded we need to put the quay.io domain back, because that is the expected customer experience.
Tested by creating numerous clusters.
No.
> Set OCP pullspec back to quay.io after the Hive installation completes

- pkg/deploy/assets/rp-development-predeploy.json
- pkg/deploy/assets/rp-production-predeploy.json
- pkg/deploy/generator/resources_rp.go
Reverts the Key-vault access policy added in #2440 because it is not being dynamically evaluated in production due to [the way that the access policies are allocated](https://github.com/Azure/ARO-RP/blob/8c0842f6fadc18317f6cc61ddf62efc1ee19d1b2/pkg/deploy/assets/rp-production-predeploy.json#L329). We will be reviting this when we don't have a pending RP release on the cards, because we can't allow the RP to remove the permissions everytime it is deployed.
Tested the inclusion, which failed, so by logical deduction removing it should result in success.
No.
> Revert the svc KV access for the AKS agentpool MSI

- pkg/deploy/predeploy.go
Now that we have deployed the NSG update, we no longer need to force create it. Revert to previous behavior.
> Revert "Temporarily force the rp nsg to redeploy"

- pkg/api/error.go
- pkg/api/validate/dynamic/dynamic.go
- pkg/api/validate/dynamic/dynamic_test.go
We should update our azure-cli command module to include adding the network contributor on the NAT gateway (if one exists). Right now we're only adding the vnet and route tables.
This PR is related to server side changes for Nat Gateway validation.
Client Side Implementation: [https://github.com/Azure/ARO-RP/pull/2394](https://github.com/Azure/ARO-RP/pull/2394)
Below two test cases added:
_TestValidateNatGatewaysPermissions_
_TestGetNatGatewayID_
> validate permissions on NAT gateways

- pkg/mirror/mirror.go
Minor improvement I saw while trying to fix the mirroring in EV2.
Since our mirroring will be replicating images that already exist nearly all of the time, it appears like this optimisation will speed up the usual case where the image already exists.
Don't have a good one, but we could merge it and run it :)
N/A
> Enable copy.Image's optimisation for cases where the destination image already exists

- pkg/deploy/assets/gateway-production-parameters.json
- pkg/deploy/assets/gateway-production.json
- pkg/deploy/assets/rp-production-parameters.json
- pkg/deploy/assets/rp-production.json
- pkg/deploy/generator/templates_gateway.go
- pkg/deploy/generator/templates_rp.go
[WI](https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/16114992/)
Fixes westus being treated as zonal when it is not currently supporting zones.
> include westus as nonzonal

- Makefile
Fixes
Builds proxy image with disabled cgo.
PRoxy needs to include all its dependencies instead of linking them.
With links and ubi-minimal it can lead to missing libraries issue.
> Build fat go file for the proxy

- test/e2e/operator.go
Part of [WI 13667437](https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/13667437/).
Previously in `AfterEach` we were restoring original URLs for the internet checker, but we were not waiting for original conditions to be set before proceeding to the next test.
This led to a flaky `It` containers where we were asserting conditions.
Run E2E locally with repeats:
```bash
ginkgo run --tags e2e,codec.safe --timeout 180m -v --until-it-fails --focus "ARO Operator - Internet checking"  ./test/e2e/...
```
Note `--until-it-fails` flag.
No, just E2E improvements.
> Flake hunting - Improves E2E clean up for internet checker

- pkg/util/liveconfig/hive.go
Fixes AKS cluster location matching in regions that return mixed case instance meta locations.
Currently the AKS cluster credentials are not matching the correct cluster in Canary due to EastUS2EUAP != eastus2euap and CentralUSEUAP != centraluseuap. This is an assumption, but we have logs with EastUS2EUAP and CentralUSEUAP and when running an `az aks list` the results show the locations are lowercase.
Tested against a Dev AKS cluster.
No.
> Liveconfig: Use case insensitive matching for the AKS cluster lookup

- .gitignore
Follow up for https://github.com/Azure/ARO-RP/pull/2519
* Adds `e2e-report.xml` into `.gitignore`
Run E2E
> Adds `e2e-report.xml` into `.gitignore`

- pkg/api/validate/dynamic/serviceprincipal_test.go
- pkg/util/clusterauthorizer/authorizer_test.go
Required to pass Microsoft Guardian tests.
Fixes
Microsoft Guardian Pipeline Analysis
pipeline failed on a MS Guardian analysis due to fake token strings.
Ran tests locally, retest in pipeline
> Update fake RefreshToken to use a randomly generated string

- pkg/deploy/assets/rp-development-predeploy.json
- pkg/deploy/assets/rp-production-predeploy.json
- pkg/deploy/generator/resources_rp.go
Fixes deploying to GovCloud until we have a method to deploy azsecpack.
Unblocks GovCloud deploys.
Tested the ARM template condition in a deployment to the Dev subscription.
No.
> Skip deploying the AKS agentpool dynamic keyvault access in GovCloud

- pkg/deploy/assets/rp-development-predeploy.json
- pkg/deploy/assets/rp-production-predeploy.json
- pkg/deploy/generator/resources_rp.go
- pkg/util/arm/types.go
- pkg/util/azureclient/apiversions.go
Fixes an issue blocking deployment to FairFax.
In the current implementation, the evaluation of the [reference to the kubeletidentity objectId](https://github.com/Azure/ARO-RP/blob/19e59aa1e6c1275d8a563952bbb68dd9fd74cbe0/pkg/deploy/assets/rp-production-predeploy.json#L329) is taking place whether [the deployment condition](https://github.com/Azure/ARO-RP/blob/19e59aa1e6c1275d8a563952bbb68dd9fd74cbe0/pkg/deploy/assets/rp-production-predeploy.json#L341) is matched or not.
This PR switches to an inner-evaluated deployment resource to overcome the issue. There wasn't support for this resource type and the [mgmt/features DeploymentPropertiesExtended struct](https://github.com/Azure/ARO-RP/blob/19e59aa1e6c1275d8a563952bbb68dd9fd74cbe0/vendor/github.com/Azure/azure-sdk-for-go/services/resources/ …
> Switch to nested inner-evaluated ARM deployments for the dynamic Keyvault access policies

- test/e2e/operator.go
Part of [WI 13667437](https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/13667437/).
This helps with troubleshooting of E2Es as it makes easier to understand what assertion within the wait code failed and why.
Run E2E
No, just E2E refactoring
> Moves ARO operator E2E tests to use `Eventually`

- .dockerignore
Dockerignore must not list any files tracked in git. 
When we build the aro container, the source tree is copied over using a dockerfile `COPY` statement. If any git-tracked files are ignored, then the source tree becomes unclean. This causes the build to append `-dirty` to version.GitCommit, which ultimately causes clusters created by this version to try to install the aro operator containers using the `-dirty` container image tag and that doesn't match what is published to ACR so those pods go into ImagePullBackOff. 
This issue is only seen when builds are done on an untagged commit or a commit with a lightweight tag rather than an annotated tag.
See also https://coreos.slack.com/archives/CCV9YF9PD/p1668806408581799
> Remove example files from .dockerignore

- pkg/monitor/cluster/arooperatorheartbeat.go
- pkg/monitor/cluster/arooperatorheartbeat_test.go
- pkg/operator/deploy/deploy.go
[Add additional logging to the ARO Operator deployment process](https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/16288833/)
> Add more logs about aro deployment state

- test/e2e/aks.go
Fixes https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/15372448/ 
Add new e2e test to cover hive kubeconfig manipulation
> Add e2e test for hive kubeconfig

- python/az/aro/azext_aro/custom.py
Fixes `az aro get-versions -l <region>`
Changes the version paging iteration to match the latest round of API changes.
Manually tested against a dedicated RP instance and created a multi-version cluster.
No.
> Modify az get-versions iteration to match the latest round of API changes

- test/e2e/aks.go
Disables AKS in a region without AKS. The list of regions is hard coded without an option to
configure. 
The reason for not configurable variant is to make the PR as small as possible and not introduce
changes in the pipeline and in the rp-config.
Fixes
> Skips AKS tests for defined regions without AKS

- pkg/util/ready/ready.go
- pkg/util/ready/ready_test.go
- test/e2e/adminapi.go
- test/e2e/adminapi_cluster_get.go
- test/e2e/adminapi_cluster_getlogs.go
- test/e2e/adminapi_cluster_list.go
- test/e2e/adminapi_cluster_update.go
- test/e2e/adminapi_kubernetesobjects.go
- test/e2e/adminapi_redeployvm.go
- test/e2e/cluster.go
Part of [WI 13667437](https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/13667437/).
This helps with troubleshooting of E2Es as it makes easier to understand what assertion within the wait code failed and why.
This is basically the same as https://github.com/Azure/ARO-RP/pull/2534, but for rest of E2Es.
Run E2E
No, just E2E refactoring
> Migrates rest of the E2Es to use `Eventually` instead of `wait.Poll*`

- pkg/cluster/adminupdate_test.go
- pkg/cluster/install.go
"Fixes a bug in the certificate PUCM process that does not take into account clusters that have not been successfully PUCM'ed since a [large infra change PR](https://github.com/Azure/ARO-RP/pull/1296) was merged in Feb 2021". 
Previous ADO Card for Certificate PUCM : https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/15581636/
"Fixes a bug in the certificate PUCM process that does not take into account clusters that have not been successfully PUCM'ed since a  [large infra change PR](https://github.com/Azure/ARO-RP/pull/1296) was merged in Feb 2021". At present fixMCSCert step failing as it could not find the Properties.APIServerProfile.IntIP entry in the Cluster Document.
Create Test Cluster without the Properties.APIServerProfile.IntIP entry in the Cluster Document and …
> Fixes a bug in the certificate PUCM process 

- pkg/api/admin/openshiftcluster.go
- pkg/api/admin/openshiftcluster_convert.go
- pkg/api/defaults.go
- pkg/api/defaults_test.go
- pkg/api/featureflags.go
- pkg/api/openshiftcluster.go
- pkg/cluster/deploystorage.go
- pkg/cluster/install.go
- pkg/cluster/networkprofile.go
- pkg/frontend/openshiftcluster_putorpatch_test.go
- pkg/installer/custominstallconfig.go
- pkg/installer/deployresources_resources.go
- pkg/installer/generateconfig.go
- pkg/installer/install.go
Removes public IP from private clusters.
We deployed a full rp service in DEV with the current changes and created a cluster.
> Public IP removal

- pkg/frontend/admin_openshiftcluster_redeployvm.go
- pkg/frontend/admin_openshiftcluster_startvm.go
- pkg/frontend/admin_openshiftcluster_stopvm.go
- pkg/frontend/admin_openshiftcluster_vmresize.go
- pkg/frontend/admin_vm_actions.go
- pkg/frontend/frontend.go
fixes a race condition introduced by https://github.com/Azure/ARO-RP/pull/2275 . This race condition can lead to adminActions overriding each others' parameters and lead to wrong VMs in wrong subscription to be redeployed for example
This is because the admin action is shared and unique (accessed by the frontend pointer). In case of concurrent use, we have no guarantee of which admin action interface we are using and thus trigger geneva actions with the wrong parameters. Catastrophic bug isn't really likely because vms will have a somewhat unique names across subs but the geneva action will fail when that rc happens. 
This just removes the adminaction field from the frontend struct so we are forced to use local variables instead and can't have that race condition anymore
Fixes
> fixed race condition in frontend

- .pipelines/e2e.yml
- test/e2e/aks.go
AKS shards start with 1
EqualFold is required because not all regions use lowercase
Fixes
> Fix AKS shard number and add equalfold

- test/e2e/aks.go
Fixes
Makes AKS tests as WIP with use of `Pending` because we cannot run them properly in INT.
We still need to fix the INT and than enable AKS test again.
> Disable AKS test as it is not working every where

- pkg/portal/portal.go
Fixes bug introduced by https://github.com/Azure/ARO-RP/pull/2344/files#diff-9d7f4b3eb6a8c6b563c82464fe86dd126cabe728955e19fed89282919358a391 because it was reading from the actual file system instead of the embedded one and was failing in canary because it ended up being ran from `/` (?) and got a permission denied 
E2E does not verify that the portal is running (portal tests are disabled because e2e are running in containers) and local testing has different permissions than actual environments. 
Portal will not work until this is merged
Fixes
> reads from embedded files instead of filesystem

- pkg/cluster/deploystorage_resources.go
Follow up to #2550  that switches to allowing AKS Pod, instead of the AKS VMSS subnet, for cluster storage access. 
During testing for the initial PR, I had manually created service endpoints for testing and this interfered with my final results. However, when standing up fresh infra to test the final ARO-Installer the manual step was obviously missing. This PR fixes that oversight.
There is a [corresponding AKS PR](https://dev.azure.com/msazure/AzureRedHatOpenShift/_git/ARO.Pipelines/pullrequest/7269811) that is also required.
Testing creating a few clusters.
No.
> Hive Install: Allow access from the AKS pod subnet

- pkg/operator/controllers/checker/internetchecker.go
- pkg/operator/controllers/checker/internetchecker_test.go
Improves internet checker test coverage.
I'm looking into splitting internet checker from other checks and noticed that test coverage can be improved: we were not checking what cnoditions controller was actually setting after the checks. Also the test now tets both master and worker roles.
Run tests.
No, just test updates.
> Improves internet checker test coverage

- pkg/util/log/log.go
`-loglevel` flag is currently doing nothing: we set it on the default logger in `logrus`, but we never use the default: we use our custom one.
As a result it is not possible to see debug logs when running `go run -tags aro ./cmd/aro -loglevel debug rp` or other commands with `-loglevel debug`.
Run commands with `-loglevel debug` and see if debug logs are being produced.
No, just a fix for a flag.
> Fixes the -loglevel flag

- cmd/aro/operator.go
- pkg/operator/controllers/alertwebhook/alertwebhook_controller.go
- pkg/operator/controllers/alertwebhook/alertwebhook_controller_test.go
- pkg/operator/controllers/banner/banner_controller.go
- pkg/operator/controllers/checker/checker_controller.go
- pkg/operator/controllers/dnsmasq/cluster_controller.go
- pkg/operator/controllers/dnsmasq/machineconfig_controller.go
- pkg/operator/controllers/dnsmasq/machineconfigpool_controller.go
- pkg/operator/controllers/genevalogging/genevalogging_controller.go
- pkg/operator/controllers/imageconfig/image_controller.go
- pkg/operator/controllers/imageconfig/image_controller_test.go
- pkg/operator/controllers/ingress/ingress_controller.go
- pkg/operator/controllers/machine/machine_controller.go
- pkg/operator/controllers/machinehealthcheck/machinehealthcheck_controller.go
- pkg/operator/controllers/machinehealthcheck/machinehealthcheck_controller_test.go
- pkg/operator/controllers/machineset/machineset_controller.go
- pkg/operator/controllers/monitoring/monitoring_controller.go
- pkg/operator/controllers/muo/muo_controller.go
- pkg/operator/controllers/muo/muo_controller_test.go
- pkg/operator/controllers/node/node_controller.go
- pkg/operator/controllers/pullsecret/pullsecret_controller.go
- pkg/operator/controllers/rbac/rbac_controller.go
- pkg/operator/controllers/routefix/routefix_controller.go
- pkg/operator/controllers/storageaccounts/storageaccount_controller.go
- pkg/operator/controllers/subnets/subnets_controller.go
- pkg/operator/controllers/workaround/workaround_controller.go
Helpful to understand whether controllers are doing anything at all.
Run [the operator locally](https://github.com/Azure/ARO-RP/tree/0aa7bf29eef4cf0a86a6b491bce2753c1b144d28/pkg/operator#how-to-run-the-operator-locally-out-of-cluster) with `-loglevel debug`.
Note: for this to actually work we need #2579 to be merged first.
> Adds debug logs to aro operator controllers

- python/az/aro/azext_aro/_validators.py
- python/az/aro/azext_aro/tests/latest/unit/test_validators.py
Update az aro extension to handle reading the pull-secret file directly without having to prefix the path with @.
The pull-secret file can still be specified with or without @ as  `--pull-secret @pull-secret.txt`, or `--pull-secret pull-secret.txt`.
https://github.com/Azure/ARO-RP/issues/2110
Fixes
The pull secret file has to be prefixed with the @ symbol rather than the file path directly. Also brought up here: https://github.com/MicrosoftDocs/azure-docs/issues/53604
Tested locally with `az aro create -g $RESOURCEGROUP --name steven-cluster-2 --vnet aro-vnet --master-subnet master-subnet --worker-subnet worker-subnet --pull-secret ~/Downloads/pull-secret`
Unit tests pass, filesystem mocking will need to be done to test reading a file in addition to json strings.
Azure docs may want to be …
> Update az aro extension to support specifying --pull-secret file without @ prefix

- pkg/util/cluster/cluster.go
Fixes https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/15727672
Previous PR to get this done with our previous stable API: https://github.com/Azure/ARO-RP/pull/2035
Updates our dev cluster create to use the new stable API that is available in all regions. The doc for this is here: https://msazure.visualstudio.com/AzureRedHatOpenShift/_wiki/wikis/ARO.wiki/240029/API-Release-Process?anchor=update-cluster-creation-for-development-with-the-new-api
> Update `pkg/util/cluster/cluster.go` to use v20220904

- pkg/operator/deploy/deploy.go
- pkg/util/dynamichelper/createorder.go
- pkg/util/dynamichelper/workloadhelper.go
This addresses some race conditions possibilities which could lead to the cluster object being created before etcd would register completely the CRD object 
https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/16571882/
Fixes
> Operator deploy fix

- pkg/hive/install.go
Adds the `ControlPlaneConfig.APIServerIPOverride` for Hive enabled installs.
The [Hive adoption process includes this setting](https://github.com/Azure/ARO-RP/blob/0e652505a1687febab818245ffd1fbf946918869/pkg/hive/resources.go#L162-L164), but it was not duplicated in the Hive install cluster deployment spec. 
Created test clusters.
No.
> Specify the APIServerIPOverride for Hive installs

- .pipelines/e2e.yml
- docs/prepare-a-shared-rp-development-environment.md
None
We have started using AKS kubeconfig in some e2e tests to test AKS connectivity/Hive/etc. In some of our bash scripts, Makefiles, and docs files we use aks.kubeconfig as the name of AKS kubeconfig file.
This change actually updates two things:
- [Prepare shared environment docs](https://github.com/Azure/ARO-RP/blob/master/docs/prepare-a-shared-rp-development-environment.md) (aka E2E infra installation docs) with steps: update a kubeconfig on the SA, and install Hive on the new AKS
- The kubeconfig filename on E2E. For some reason, the e2e AKS kubeconfig is stored in the file called e2e-aks-kubeconfig. I suggest renaming this file to aks.kubeconfig to reach some naming consistency
Green E2E is enough
> Update docs for shared rp-dev-env installation

- pkg/hive/install.go
Fixes certificate validation errors when Hive is communicating with the Cluster API server.
Hive can't communicate with the Cluster API server if we don't.
Created a test cluster.
None yet, but we need Hive debug documentation.
> Hive: Set the APIURLOverride with the internal API URL

- test/e2e/adminapi_redeployvm.go
[ADO task](https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/15682807)
Adds a random, unique suffix to the end of the names of pods deployed during the adminapi_redeployvm E2E test in order to check uptime. These pods are not deleted immediately, causing them to conflict if the test deploys a second uptime pod before the first is finished deleting.
Run the E2E test under question and ensure it still passes/fails as expected 
No (E2E flake reduction)
I have discovered additional flakiness in this test that I do not believe to be related. When running these tests against the same cluster (e.g. in a local dev environment), subsequent runs after the first passing one will fail, triggering Ginkgo's automatic retry which passes and marks the test as flaky. Further …
> Update redeployvm e2e test to use unique name for each uptime pod

- pkg/operator/controllers/clusteroperatoraro/clusteroperatoraro_controller.go
Currently `oc get co` doesn't list a version for the aro operator. This change shows the version as `1.0-<commithash>`. Might save new people some confusion over why one operator doesn't have a version number.
> Expose aro operator version

- pkg/portal/middleware/aad.go
- pkg/portal/middleware/aad_test.go
removing useless typecasting because of bad constructor
Fixes
> removing useless typecasting because of bad constructor

- pkg/operator/controllers/clusteroperatoraro/clusteroperatoraro_controller.go
- pkg/operator/controllers/previewfeature/previewfeature_controller.go
Every other controller has debug logs like this, but these two controllers were missing logs.
> Adds missing debug logs to the operator

- .pipelines/e2e.yml
- .pipelines/vars.yml
- hack/e2e/run-rp-and-e2e.sh
Follow-up PR for an issue with the must-gather feature where CI e2e clusters were getting deleted successfully, but Ev2 e2e clusters were getting left behind.
- Reverts  https://github.com/Azure/ARO-RP/pull/2538 with fixes
- Reintroduces https://github.com/Azure/ARO-RP/pull/1955
- Fixes https://issues.redhat.com/browse/ARO-1502
When must-gather CI was first introduced, it removed cluster deletion from the e2e binary and moved it to a pipeline step. This PR is almost identical, except for that rather than making any changes to the e2e binary, it passes in `E2E_DELETE_CLUSTER=false` so that only CI clusters are retained for must-gather collection, then deleted later using the pipeline.
Confirm functionality in CI (we should be OK to stop there, since we're no longer making any changes to …
> Reintroduce CI must-gathers, retain existing cluster deletion

- .pipelines/onebranch/pipeline.buildrp.official.yml
- .pipelines/onebranch/templates/template-buildrp-buildaro.yml
- .pipelines/onebranch/templates/template-buildrp-builddocker.yml
- Dockerfile.aro-multistage
- Makefile
Git has two different kinds of tags: annotated and light-weight. Our release process only supports annotated tags (`git tag -a`). If the tag is a light-weight tag then the build process will ignore it and use the git revision instead of the tag.
This change enforces the use of an annotated tag for "official" builds. A new pipeline variable `is_official_release` is passed down to `Dockerfile.aro-multistage` which, if true, runs a new `make aro-release` target. This Makefile target bails out if the tag is not specified.
Similar logic is added to the `Build_ARO` onebranch pipeline which doesn't use the Makefile.
Official release with valid tag:
```bash
$ make aro-release
go generate ./...
bindata.go
bindata.go
bindata.go
bindata.go
go build -tags aro,containers_image_openpgp,codec.safe …
```
> Require "official" builds have a valid tag.

- pkg/operator/controllers/alertwebhook/alertwebhook_controller.go
- pkg/operator/controllers/banner/banner_controller.go
- pkg/operator/controllers/checkers/clusterdnschecker/controller.go
- pkg/operator/controllers/checkers/ingresscertificatechecker/controller.go
- pkg/operator/controllers/checkers/internetchecker/controller.go
- pkg/operator/controllers/checkers/serviceprincipalchecker/controller.go
- pkg/operator/controllers/clusteroperatoraro/clusteroperatoraro_controller.go
- pkg/operator/controllers/dnsmasq/machineconfig_controller.go
- pkg/operator/controllers/dnsmasq/machineconfigpool_controller.go
- pkg/operator/controllers/genevalogging/genevalogging_controller.go
- pkg/operator/controllers/imageconfig/image_controller.go
- pkg/operator/controllers/ingress/ingress_controller.go
- pkg/operator/controllers/machine/machine_controller.go
- pkg/operator/controllers/machinehealthcheck/machinehealthcheck_controller.go
- pkg/operator/controllers/machineset/machineset_controller.go
- pkg/operator/controllers/monitoring/monitoring_controller.go
- pkg/operator/controllers/muo/muo_controller.go
- pkg/operator/controllers/node/node_controller.go
- pkg/operator/controllers/previewfeature/previewfeature_controller.go
- pkg/operator/controllers/pullsecret/pullsecret_controller.go
- pkg/operator/controllers/rbac/rbac_controller.go
- pkg/operator/controllers/routefix/routefix_controller.go
- pkg/operator/controllers/storageaccounts/storageaccount_controller.go
- pkg/operator/controllers/subnets/subnets_controller.go
- pkg/operator/controllers/workaround/workaround_controller.go
InjectClient had an `a` receiver while rest of the methods had `r` receivers.
Follow up for https://github.com/Azure/ARO-RP/pull/2605#discussion_r1067058036
> Fixes consistency of receivers in controllers
