- pkg/install/resources.go
Create bugfix:
`DisableOutboundSnat=true`
> Create bugfix 2

- docs/deploy-development-rp.md
- pkg/backend/openshiftcluster.go
- pkg/backend/subscriptions.go
- pkg/install/1-installresources.go
- pkg/install/2-removebootstrap.go
Enables heartbeat to cancel backend workers if lost lease
> Cancel backend workers and restartability 

- pkg/backend/openshiftcluster.go
- pkg/backend/subscriptions.go
- pkg/frontend/middleware/log.go
- pkg/frontend/middleware/metrics.go
- pkg/metrics/statsd/azure/metrics.go
- pkg/metrics/statsd/k8s/metrics.go
- pkg/metrics/statsd/statsd.go
> RP Metrics - backend

- pkg/api/openshiftcluster.go
- pkg/backend/openshiftcluster/update.go
- pkg/install/1-installresources.go
- pkg/install/2-removebootstrap.go
- pkg/util/restconfig/restconfig.go
I think this is going to be essential when factoring in monitoring load.
> store cluster private IP in database

- pkg/api/v20191231preview/openshiftcluster_validatedynamic.go
- pkg/backend/openshiftcluster/delete.go
- pkg/env/dev.go
- pkg/install/0-installstorage.go
- pkg/install/1-installresources.go
- pkg/util/azureclient/mgmt/resources/groups.go
- pkg/util/dns/dns.go
- pkg/util/mocks/azureclient/mgmt/resources/resources.go
remove CheckExistence API call and fix possible logic misordering in delete
standardise autorest.DetailedError error handling
> Error handling

- docs/using-az-aro.md
- Typo in cloning command
- Registration of the provider details
> WIP - Getting started review

- .github/workflows/pull_request-test-python.yaml
Fix python version is a new test runner image
> fix test python version

- .sha256sum
- pkg/api/openshiftcluster.go
- pkg/api/v20191231preview/openshiftcluster.go
- pkg/api/v20191231preview/openshiftcluster_convert.go
- pkg/api/v20191231preview/openshiftcluster_example.go
- pkg/api/v20191231preview/openshiftcluster_validatestatic.go
- pkg/api/v20191231preview/openshiftcluster_validatestatic_test.go
- pkg/client/services/preview/redhatopenshift/mgmt/2019-12-31-preview/redhatopenshift/models.go
- pkg/install/2-removebootstrap.go
- python/az/aro/azext_aro/_format.py
- python/client/azure/mgmt/redhatopenshift/v2019_12_31_preview/models/__init__.py
- python/client/azure/mgmt/redhatopenshift/v2019_12_31_preview/models/_models.py
- python/client/azure/mgmt/redhatopenshift/v2019_12_31_preview/models/_models_py3.py
- swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/preview/2019-12-31-preview/examples/OpenShiftClusters_CreateOrUpdate.json
- swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/preview/2019-12-31-preview/examples/OpenShiftClusters_Get.json
- swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/preview/2019-12-31-preview/examples/OpenShiftClusters_List.json
- swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/preview/2019-12-31-preview/examples/OpenShiftClusters_ListByResourceGroup.json
- swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/preview/2019-12-31-preview/examples/OpenShiftClusters_Update.json
- swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/preview/2019-12-31-preview/redhatopenshift.json
Move consoleURL to consoleProfile.URL
> move console to consoleProfile

- pkg/install/1-installresources.go
Fixes #8
Remove route table
Follow up from https://github.com/openshift/installer/pull/2948
> remove un-used route table

- .github/workflows/pull_request-test-go.yaml
- pkg/frontend/openshiftcluster_delete.go
- pkg/frontend/openshiftcluster_delete_test.go
- pkg/frontend/openshiftcluster_putorpatch.go
- pkg/frontend/openshiftcluster_putorpatch_test.go
new manifest is rolling out so this can be straight enabled in prod in next
release
> remove FEATURE_OPERATIONS flag

- pkg/install/2-removebootstrap.go
@m1kola hope this PR is ok with you - I didn't spot the missing error check on review.
> check error after updateConsoleBranding

- cmd/aro/monitor.go
- cmd/aro/rp.go
- hack/db/db.go
- pkg/database/database.go
- pkg/database/metrics.go
- pkg/database/openshiftclusters.go
- pkg/metrics/statsd/cosmosdb/metrics.go
- pkg/util/mocks/database/database.go
> backend cosmosdb metrics

- pkg/frontend/openshiftclustercredentials_post.go
- pkg/frontend/openshiftclustercredentials_post_test.go
@jim-minter please take a look. Is this what you meant in https://github.com/Azure/ARO-RP/pull/118#discussion_r370907552?
> Allow API version to disable credentials requests

- pkg/metrics/statsd/cosmosdb/metrics.go
Fixes: https://github.com/Azure/ARO-RP/issues/126
> cosmosdb metrics terminate early

- docs/using-az-aro.md
> docs updates from workshop

- pkg/frontend/asyncoperationresult_get_test.go
- pkg/frontend/asyncoperationsstatus_get_test.go
- pkg/frontend/openshiftcluster_delete_test.go
- pkg/frontend/openshiftcluster_get_test.go
- pkg/frontend/openshiftcluster_list_test.go
- pkg/frontend/openshiftcluster_putorpatch_test.go
- pkg/frontend/openshiftclustercredentials_post_test.go
- pkg/frontend/subscriptions_put_test.go
Make sure that a response body is valid as a whole.
Followup for https://github.com/Azure/ARO-RP/pull/124#discussion_r371757408
> Improves response body tests

- pkg/install/2-removebootstrap.go
> Adds waiting for console-operator config

- pkg/backend/openshiftcluster.go
- pkg/install/install.go
Enables to terminates phases on each phase so shutdown could be grateful
> terminate backend on each phase

- pkg/api/v20191231preview/openshiftcluster_validatestatic.go
- pkg/api/validate/format_regexps.go
Follow up for https://github.com/Azure/ARO-RP/pull/145
> Moves format regexps into pkg/api/validate

- pkg/api/openshiftcluster.go
- pkg/api/openshiftcluster_test.go
- pkg/backend/openshiftcluster.go
- pkg/database/openshiftclusters.go
fix: https://github.com/Azure/ARO-RP/issues/180
> fix asyncoperation

- pkg/api/error.go
- pkg/backend/openshiftcluster.go
- pkg/install/0-installstorage.go
- pkg/util/dns/dns.go
- pkg/util/dns/dns_test.go
Return errors from the backend
> backend errors

- pkg/util/immutable/immutable.go
- pkg/util/immutable/immutable_test.go
> allow immutable to handle time.Time

- .sha256sum
- cmd/aro/rp.go
- pkg/api/admin/openshiftcluster.go
- pkg/api/admin/openshiftcluster_convert.go
- pkg/api/admin/openshiftcluster_validatestatic.go
- pkg/api/admin/openshiftcluster_validatestatic_test.go
- pkg/api/admin/register.go
- pkg/api/openshiftcluster.go
- pkg/api/v20191231preview/openshiftcluster.go
- pkg/backend/openshiftcluster.go
- pkg/backend/subscriptions.go
- pkg/client/services/preview/redhatopenshift/mgmt/2019-12-31-preview/redhatopenshift/models.go
- pkg/frontend/openshiftcluster_putorpatch.go
- python/client/azure/mgmt/redhatopenshift/v2019_12_31_preview/models/_models.py
- python/client/azure/mgmt/redhatopenshift/v2019_12_31_preview/models/_models_py3.py
- swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/preview/2019-12-31-preview/redhatopenshift.json
Depends on:
* https://github.com/Azure/ARO-RP/pull/119
* https://github.com/Azure/ARO-RP/pull/124
* https://github.com/Azure/ARO-RP/pull/145
* https://github.com/Azure/ARO-RP/pull/183
> Adds foundation for the admin API

- pkg/api/validate/openshiftcluster_validatedynamic.go
> clientId validation

- pkg/api/error.go
- pkg/install/0-installstorage.go
- pkg/install/1-installresources.go
- pkg/install/error.go
> arm resource quota error code

- .pipelines/pr-e2e.yml
This will allow us to run `azp` command
> E2E Pipeline - Remove manual ci and pr triggers

- pkg/genevalogging/genevalogging.go
@Makdaam and I have both encountered the following error when creating a cluster:
```
INFO[...05:00]pkg/install/install.go:170 install.(*Installer).Install() running step github.com/Azure/ARO-RP/pkg/install.(*Installer).ensureGenevaLogging-fm  component=backend resource=/subscriptions/...
ERRO[...05:00]pkg/backend/openshiftcluster.go:96 backend.(*openShiftClusterBackend).handle() securitycontextconstraints.security.openshift.io "privileged" not found  component=backend resource=/subscriptions/...
```
This PR would wait until the "privileged" SCC existed before proceeding.
(This could be refactored in the future to fit the pattern in https://github.com/Azure/ARO-RP/pull/201).
> Wait for "privileged" SCC when ensuring Geneva logging during installation

- pkg/api/validate/openshiftcluster_validatedynamic.go
- pkg/util/azureclient/mgmt/network/virtualnetworks.go
- pkg/util/mocks/azureclient/mgmt/network/network.go
Adding custom dns vnet validation.
> Adding vnet validation for custom dns

- pkg/install/generate.go
- pkg/metrics/generate.go
- pkg/metrics/metrics.go
- pkg/util/azureclient/graphrbac/applications.go
- pkg/util/azureclient/graphrbac/generate.go
- pkg/util/azureclient/keyvault/base.go
- pkg/util/azureclient/keyvault/generate.go
- pkg/util/azureclient/mgmt/authorization/generate.go
- pkg/util/azureclient/mgmt/authorization/permissions.go
- pkg/util/azureclient/mgmt/dns/generate.go
- pkg/util/azureclient/mgmt/dns/recordsets.go
- pkg/util/azureclient/mgmt/documentdb/databaseaccounts.go
- pkg/util/azureclient/mgmt/documentdb/generate.go
- pkg/util/azureclient/mgmt/keyvault/generate.go
- pkg/util/azureclient/mgmt/keyvault/vaults.go
- pkg/util/azureclient/mgmt/network/generate.go
- pkg/util/azureclient/mgmt/network/interfaces.go
- pkg/util/azureclient/mgmt/redhatopenshift/generate.go
- pkg/util/azureclient/mgmt/redhatopenshift/openshiftclusters.go
- pkg/util/azureclient/mgmt/resources/deployments.go
- pkg/util/azureclient/mgmt/resources/generate.go
- pkg/util/azureclient/mgmt/storage/accounts.go
- pkg/util/azureclient/mgmt/storage/generate.go
- pkg/util/instancemetadata/generate.go
- pkg/util/instancemetadata/prod.go
> Move code generation comments to separate files

- .sha256sum
- pkg/api/operation.go
- pkg/client/services/preview/redhatopenshift/mgmt/2019-12-31-preview/redhatopenshift/models.go
- pkg/frontend/operations_get.go
- python/client/azure/mgmt/redhatopenshift/v2019_12_31_preview/models/_models.py
- python/client/azure/mgmt/redhatopenshift/v2019_12_31_preview/models/_models_py3.py
- swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/preview/2019-12-31-preview/redhatopenshift.json
Adding to operations results response to fill in missing fields
> Fix operations route

- pkg/util/tls/tls.go
closes https://github.com/Azure/ARO-RP/issues/259
> using UTC timezone for TLS certs

- .pipelines/templates/template-run-rp-and-e2e.yml
- hack/e2e/run-rp-and-e2e.sh
#246 
- Also adding a check to make sure pipeline is using correct sub to run e2e against
> FIX - Fail e2e on stderr

- pkg/env/dev.go
- pkg/env/prod.go
- pkg/genevalogging/genevalogging.go
still needs proper role configuration in MDSD
> WIP: adding Kubernetes API audit logs MDSD daemonset

- pkg/api/validate/openshiftcluster_validatedynamic_test.go
Adding a few test cases for vnet validation.
> Adding validatevnet unit test

- pkg/backend/openshiftcluster/delete.go
> Don't fail delete if the resource group does not exist

- pkg/api/admin/register.go
- pkg/api/register.go
- pkg/api/v20191231preview/openshiftcluster_validatestatic.go
- pkg/api/v20191231preview/openshiftcluster_validatestatic_test.go
- pkg/api/v20191231preview/register.go
- pkg/frontend/openshiftcluster_putorpatch.go
- pkg/frontend/openshiftcluster_putorpatch_test.go
Disallow incoming domain names of the form:
* x.<wrong-location>.aroapp.io
* x.y.<location>.aroapp.io
> more closely validate incoming domain names

- .gitignore
- .pipelines/deploy-int-env.yml
- .pipelines/templates/template-deploy-int-env.yml
- cmd/aro/deploy.go
- cmd/aro/main.go
- deploy/config.yaml.example
- deploy/generate.go
- hack/deploy/prepare-int-parameters.sh
- pkg/deploy/config.go
- pkg/deploy/config_test.go
- pkg/deploy/deploy.go
- pkg/deploy/deploy_test.go
- pkg/deploy/generator/const.go
- pkg/deploy/generator/generators.go
Add `config.yaml` for deployer tooling.
Add Config merge functionality
Add tests to test merge and field parity with templates
> Deployment tooling config file

- pkg/backend/openshiftcluster/openshiftcluster.go
> dev does not have ACRResourceID set and ParseResourceID fails

- docs/using-az-aro.md
- pkg/genevalogging/genevalogging.go
- pkg/install/disablealertmanagerwarning.go
- pkg/install/disablealertmanagerwarning_test.go
- pkg/install/install.go
implementing a no-op webhook server is a follow-up.
> hack to disable alertmanager warning for now

- .pipelines/build-and-push-images.yml
- hack/deploy/copy_artifacts.sh
Adding steps to build and push images to publish artifacts containing the deployer. So that we can  use it in the release pipeline
> Publish deployer

- .pipelines/build-and-push-images.yml
Made a small mistake on the artifact naming
> Fixing naming on artifacts

- docs/deploy-development-rp.md
- hack/monitor/monitor.go
Moved out from [PR 321](https://github.com/Azure/ARO-RP/pull/321) per feedback.
> Helper script to watch monitor output

- pkg/install/install.go
- pkg/install/removebootstrap.go
Remove ign config after install
> Remove ign config post install

- .pipelines/deploy-azure-env.yml
- .pipelines/int-release.yml
- .pipelines/prod-release.yml
- .pipelines/templates/template-job-deploy-azure-env.yml
Moving deploy to region environment logic into a template.
Adding Int and Prod releases.  
This is only deploying the region in the future it will also run e2es and chain sector deployments.
> Adding release pipelines

- .pipelines/deploy-azure-env.yml
- .pipelines/int-release.yml
- .pipelines/prod-release.yml
- .pipelines/templates/template-job-deploy-azure-env.yml
Adding release pipelines to allow us to stage rollout of new builds in prod and mirror that in INT.
Not in the PR is adding an E2E run after each deploy phase to verify the deployment.
> Release pipelines

- README.md
- docs/deploy-development-rp.md
- docs/using-az-aro.md
These are the pitfalls I ran into while trying to create my first v4 cluster (currently in progress!).
> Update docs based on first runthrough

- .pipelines/templates/template-deploy-azure-env.yml
- .pipelines/templates/template-job-deploy-azure-env.yml
During approval currently you can't see what you are approving. Trying to fixing that
> adding location to enviroment name so you can see what you are approving

- pkg/install/error.go
- pkg/install/error_test.go
- pkg/install/install.go
Seeing errors where the storage deployment fails due to stale permissions.  I have proven that the retry in this PR helps.
> retry deployments that fail due to AuthorizationFailed

- pkg/util/restconfig/restconfig.go
This is associated with https://github.com/Azure/ARO-RP/issues/389.  I've got quite a war story to tell for this one ;-)
> do not hand out a RestConfig if PrivateEndpointIP is not set

- pkg/util/clusterdata/clusterdata.go
- pkg/util/clusterdata/clusterdata_test.go
> Do not run enrichment in some provisioning states

- .pipelines/deploy-azure-env.yml
for consistency. need to update pipelines at the same time
> rename vso-deployer-build-id -> vso-deployer-pipeline-id

- pkg/frontend/middleware/validate.go
- pkg/frontend/middleware/validate_test.go
- pkg/frontend/openshiftclustercredentials_post.go
- pkg/frontend/openshiftclustercredentials_post_test.go
One of these is 404->500.  The others are 404->400s.
I've audited the remaining places where we return 404 and believe they are correct.
> fix multiple places where we were returning http.StatusNotFound and should not have been

- pkg/deploy/predeploy.go
- pkg/util/keyvault/keyvault.go
will do this step manually during pre-deployment.
> remove deployment tool automation for onecert

- cmd/aro/deploy.go
- pkg/deploy/predeploy.go
> Revert "override isCreate"

- pkg/backend/openshiftcluster.go
- pkg/frontend/frontend.go
- log errors hidden from user at level error
- log errors returned to user at level info
> Logging improvements:

- pkg/monitor/cluster/alerts.go
> blacklist UsingDeprecatedAPIExtensionsV1Beta1 alert

- pkg/database/billing.go
- pkg/util/mocks/database/database.go
Adding a continuation token to billing list all function interface and passing it through to cosmos query.
> Adding paging support to Billing list all function

- python/az/aro/azext_aro/_validators.py
An attempt to update the `pull-secret` warning message.
We should come up with a better link that explains the benefits of signing up for Red Hat support.
> Update pull-secret warning.

- cmd/aro/mirror.go
- pkg/backend/openshiftcluster/create.go
- pkg/frontend/admin_openshiftcluster_mustgather.go
- pkg/frontend/frontend.go
- pkg/frontend/kubeactions/kubeactions.go
- pkg/frontend/kubeactions/mustgather.go
- pkg/util/mocks/kubeactions/kubeactions.go
- pkg/util/portforward/dialer.go
- pkg/util/portforward/exec.go
- pkg/util/portforward/portforward.go
- pkg/util/version/version.go
Work in progress - any feedback would be appreciated. As suggested, I have started to reuse code from `oc`: https://github.com/openshift/oc/blob/release-4.3/pkg/cli/admin/mustgather/mustgather.go.
Not sure about the structure of this. It requires more code than the other current Geneva actions, so it's in its own package.
> Must Gather Geneva Action

- pkg/frontend/admin_openshiftcluster_kubernetesobjects_get.go
- pkg/frontend/admin_openshiftcluster_mustgather.go
- pkg/frontend/admin_openshiftcluster_resources_list.go
- pkg/frontend/admin_openshiftcluster_upgrade.go
- pkg/frontend/frontend.go
- pkg/frontend/frontend_test.go
otherwise all kube errors (from the admin API) become 500 internal server errors.
This just converts kube api errors into CloudErrors
> handle kubernetes errors in the frontend reply function

- pkg/env/dev.go
seems likely that this actually is necessary for development workflows
> re-add development refresh

- Gopkg.lock
- pkg/frontend/admin_openshiftcluster_kubernetesobjects.go
- pkg/frontend/admin_openshiftcluster_kubernetesobjects_test.go
- pkg/frontend/frontend.go
- pkg/frontend/kubeactions/kubeactions.go
- pkg/frontend/kubeactions/kubeactions_test.go
- pkg/util/mocks/kubeactions/kubeactions.go
- vendor/k8s.io/client-go/dynamic/fake/simple.go
geneva side: https://msazure.visualstudio.com/One/_git/Compute-ARO-GenevaActions/pullrequest/2788499?_a=overview
> Add admin oc apply for geneva actions

- pkg/api/correlation.go
- pkg/frontend/middleware/log.go
- pkg/util/log/log.go
enables us to audit log who ran a geneva action
> log x-ms-client-principal-name

- python/az/aro/azext_aro/_help.py
- python/az/aro/azext_aro/_rbac.py
- python/az/aro/azext_aro/commands.py
- python/az/aro/azext_aro/custom.py
Backports changes done in downstream in a PR https://github.com/Azure/azure-cli/pull/12793
> Backport changes from downstream

- pkg/frontend/kubeactions/kubeactions.go
- pkg/frontend/kubeactions/kubeactions_test.go
This API maintains the preferred version order, which allows us to prefer the
server-preferred version but fall back in order to other versions if necessary.
An example of where this is necessary is when querying
ImageContentSourcePolicys: at least in 4.3 these are not included in the server
preferred version, but only an older version.
> use ServerGroupsAndResources to walk dynamic groups and resources

- docs/deploy-development-rp.md
> Revert "This command is implicitly deprecated"

- python/az/aro/azext_aro/_format.py
When there are no worker profiles (cluster only has masters or we failed to get data from API server) or a worker profile does not have count (machine set was scaled to 0).
I think we will also need to update the upstream cli? And add tests.
> Fixes az aro table output

- pkg/install/deploystorage.go
- pkg/util/subnet/const.go
- pkg/util/subnet/subnet.go
- pkg/util/subnet/subnet_test.go
> Replace hardcoded NSG suffixes with constants

- pkg/deploy/predeploy.go
Fixes: https://github.com/Azure/ARO-RP/issues/538
> add suffix for global deploy resources

- pkg/util/heartbeat/heartbeat.go
We wait for 2 minutes before emitting a heartbeat metric.  This ensures that there will be a gap in the metric if we crash or restart.
> wait for 2 minutes before emitting heartbeat

- cmd/aro/rp.go
- pkg/frontend/admin_openshiftcluster_kubernetesobjects_test.go
- pkg/frontend/admin_openshiftcluster_list_test.go
- pkg/frontend/admin_openshiftcluster_resources_list_test.go
- pkg/frontend/admin_openshiftcluster_restartvm.go
- pkg/frontend/admin_openshiftcluster_restartvm_test.go
- pkg/frontend/admin_openshiftcluster_vmreboot.go
- pkg/frontend/admin_openshiftcluster_vmreboot_test.go
- pkg/frontend/asyncoperationresult_get_test.go
- pkg/frontend/asyncoperationsstatus_get_test.go
- pkg/frontend/frontend.go
- pkg/frontend/openshiftcluster_delete_test.go
- pkg/frontend/openshiftcluster_get_test.go
- pkg/frontend/openshiftcluster_list_test.go
- pkg/frontend/openshiftcluster_putorpatch_test.go
- pkg/frontend/openshiftclustercredentials_post_test.go
- pkg/frontend/security_test.go
- pkg/frontend/subscriptions_put_test.go
- pkg/frontend/validate.go
- pkg/util/azureclient/mgmt/compute/virtualmachines_addons.go
- pkg/util/mocks/azureclient/mgmt/compute/compute.go
work item: https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/6969068/
client PR: https://msazure.visualstudio.com/One/_git/Compute-ARO-GenevaActions/pullrequest/2825637
> add admin vm restart operation

- pkg/api/validate/openshiftcluster_validatedynamic.go
Got the following false error on deploy: "Deployment failed. The resource provider does not have Contributor permission on vnet '/subscriptions/225e02bc-43d0-43d1-a01a-17e584a4ef69/resourceGroups/v4-eastus2/providers/Microsoft.Network/virtualNetworks/vnet'."
Work around it.  Loop for 2 minutes trying for success on permissions check, and only give up after that.  (Ugh).
> more RP permission check changes

- pkg/frontend/kubeactions/kubeactions.go
- pkg/frontend/kubeactions/kubeactions_test.go
Note: punted on "Convert kube api errors to CloudErrors within the kubeaction module" - needs more thought
> handle errors in findGVR()

- .pipelines/prod-release.yml
Updating the prod-release.yml to do a staged release across all regions.
> Updating staged release pipeline

- pkg/install/deploystorage.go
fixes: https://github.com/Azure/ARO-RP/issues/561
> Propagate vnet error message

- .pipelines/bvte2e.yml
Introduce RP E2E and Billing E2E, Billing E2E PIPELINE should be called after 4 hours waiting
> Introduce RP E2E and Billing E2E

- .pipelines/e2e-with-billing.yml
- .pipelines/templates/template-clean-e2e-db.yml
- .pipelines/templates/template-clean-e2e-deps.yml
- .pipelines/templates/template-deploy-e2e-db.yml
- .pipelines/templates/template-run-rp-and-e2e.yml
- hack/e2e/run-rp-and-e2e.sh
- pkg/install/deploystorage.go
It is used in a storage account container name, and these must be lower case.
> require infra id to be in lower case

- pkg/install/gatherlogs.go
- pkg/install/install.go
POC for failure log gatherer for failed installs. 
fixes: https://github.com/Azure/ARO-RP/issues/560
> Add gather logs

- pkg/api/error.go
- pkg/install/error.go
- pkg/install/error_test.go
- pkg/install/install.go
- pkg/install/install_test.go
> Return deployment errors to end user

- .pipelines/e2e-loop.yml
> Add e2e loop pipeline

- hack/kubeadminkubeconfig/get.go
- hack/kubeadminkubeconfig/kubetoken.go
> Add a retry loop to kubeadminkubeconfig

- pkg/install/deploystorage.go
- pkg/util/aad/aad.go
Fixes https://github.com/Azure/ARO-RP/issues/602
> Adds re-tries to the install

- .pipelines/deploy-azure-env.yml
Require one-off deploys to use RP-PROD environment.
> deploy to RP-PROD environment

- pkg/api/validate/openshiftcluster_validatedynamic.go
- pkg/env/dev.go
- pkg/install/install.go
> add RefreshFPAuthorizer

- python/az/aro/azext_aro/_params.py
- python/az/aro/azext_aro/_validators.py
> [WIP] Replace custom int validator in az aro

- .pipelines/ci.yml
- .pipelines/e2e-with-billing.yml
this is a CI fix + yaml formatting (mostly whitespace) change
> require make test-python not to change any repo files

- Gopkg.lock
- cgmanifest.json
- docs/upstream-differences.md
- vendor/github.com/openshift/installer/pkg/asset/tls/tls.go
Rebase installer for https://bugzilla.redhat.com/show_bug.cgi?id=1831760
> Rebase installer 

- .pipelines/deploy-azure-env.yml
- .pipelines/int-release.yml
- .pipelines/prod-release.yml
- .pipelines/templates/template-job-deploy-azure-env.yml
Add Billing E2E into RP release pipeline
> Add Billing E2E into RP release pipeline

- docs/az-aro-python-development.md
introduced the brief guide how to work
with aro subcommand on az tool
> Add brief python az aro howto

- pkg/api/v20191231preview/openshiftcluster_validatestatic_test.go
- pkg/api/v20200430/openshiftcluster_validatestatic_test.go
Now we run tests for static validation for updates too.
Fixes #413
> Improves static validation tests

- pkg/frontend/admin_openshiftcluster_resources_list.go
- pkg/frontend/admin_openshiftcluster_resources_list_test.go
- pkg/util/azureclient/mgmt/compute/virtualmachines.go
- pkg/util/mocks/azureclient/mgmt/compute/compute.go
add enricher for geneva arm resources.
fixes: https://github.com/Azure/ARO-RP/issues/613
> Enirch vm status

- pkg/frontend/kubeactions/kubeactions.go
- pkg/frontend/kubeactions/kubeactions_test.go
fixes https://github.com/Azure/ARO-RP/issues/596
> Add a better message when the groupKind matches multiple

- pkg/api/correlation.go
- pkg/backend/openshiftcluster.go
- pkg/database/openshiftclusters.go
- pkg/frontend/middleware/log.go
> Improve cluster creation metric

- cmd/aro/mirror.go
- pkg/mirror/graph.go
- pkg/mirror/version_test.go
Mirror all images based on the lower limit.
> Mirror without max limit

- .pipelines/deploy-azure-env.yml
- .pipelines/prod-release.yml
- .pipelines/templates/template-job-deploy-azure-env.yml
Require build IDs for prod deployments.  @JackQuincy ptal?
> latch build IDs for prod deployments

- Makefile
- operator/config/manager/kustomization.yaml
- operator/config/output/crd.yaml
- operator/config/output/resources.yaml
RP will need the final kubernetes manifests during install process, so we have to keep them in source control.
> [aro-operator] Makefile updates and source control kustsomize outputs

- python/az/aro/azext_aro/_help.py
PR to fix function with the wrong flag in the error message to keep in sync 
- https://github.com/Azure/azure-cli/pull/13439
> Synchronize with Azure/azure-cli upstream

- python/az/aro/azext_aro/_aad.py
Fixes https://github.com/Azure/ARO-RP/issues/535
> Add retries to create_service_principal

- pkg/api/validate/openshiftcluster_validatedynamic.go
- pkg/api/validate/openshiftcluster_validatedynamic_test.go
- pkg/api/validate/quota.go
- pkg/api/validate/quota_test.go
- pkg/backend/openshiftcluster/create.go
- pkg/backend/openshiftcluster/openshiftcluster.go
- pkg/backend/openshiftcluster/update.go
- pkg/install/deploystorage.go
- pkg/install/install.go
- pkg/util/azureerrors/error.go
- pkg/util/azureerrors/error_test.go
Fixes https://github.com/Azure/ARO-RP/issues/618
[View diffs with whitespace ignored](https://github.com/Azure/ARO-RP/pull/632/files?diff=unified&w=1)
> Guard more against AuthorizationFailed on create (w/ refactoring)

- pkg/api/error.go
- pkg/api/validate/openshiftcluster_validatedynamic.go
- pkg/api/validate/openshiftcluster_validatedynamic_test.go
- pkg/api/validate/quota.go
- pkg/api/validate/quota_test.go
- pkg/backend/openshiftcluster/adminupdate.go
- pkg/backend/openshiftcluster/create.go
- pkg/backend/openshiftcluster/openshiftcluster.go
- pkg/backend/openshiftcluster/update.go
- pkg/install/deploystorage.go
- pkg/install/install.go
- pkg/util/azureerrors/error.go
- pkg/util/azureerrors/error_test.go
An attempt to validate routetable permissions on vnets.
ref: #425
> Adding routetable permission checking.

- Gopkg.lock
- pkg/install/install.go
- pkg/install/start_vms.go
- pkg/install/start_vms_test.go
- pkg/util/azureclient/mgmt/compute/virtualmachines_addons.go
- pkg/util/mocks/azureclient/mgmt/compute/compute.go
- vendor/golang.org/x/sync/errgroup/errgroup.go
> Adds a step to start VMs during admin upgrade

- hack/e2e/run-rp-and-e2e.sh
- pkg/backend/openshiftcluster/create.go
Fix location format used in the installer.
Fixes: https://github.com/Azure/ARO-RP/issues/729
> Fix location format

- python/az/aro/azext_aro/_params.py
> [python]Add allowed values to ingress/apiserver visibility

- pkg/env/dev.go
- pkg/env/env.go
- pkg/env/prod.go
- pkg/env/test.go
- pkg/install/install.go
closes https://github.com/Azure/ARO-RP/issues/718
> Adding the refreshAuthorizer to prod

- pkg/util/aad/aad.go
> Improves token refresh retries

- hack/kubeadminkubeconfig/kubetoken.go
- pkg/api/admin/register.go
- pkg/backend/openshiftcluster/openshiftcluster.go
- pkg/database/extensions.go
- pkg/deploy/generator/resources.go
- pkg/frontend/admin_openshiftcluster_list_test.go
- pkg/install/consolebranding_test.go
- pkg/metrics/statsd/k8s/metrics.go
- pkg/util/billing/billing.go
- pkg/util/clusterdata/worker_profiles_task.go
some fixes from staticcheck.io for now
ref https://github.com/Azure/ARO-RP/issues/765
> fixes from staticcheck tool

- pkg/deploy/predeploy.go
- pkg/util/azureclient/keyvault/base.go
- pkg/util/mocks/azureclient/keyvault/keyvault.go
this is preparation for when mdm/mdsd certs are autogenerated by key vault.
> don't copy certificates in deployment tool

- python/az/aro/linter_exclusions.yml
fixes https://github.com/Azure/ARO-RP/issues/766
> add python/az/aro/linter_exclusions.yml

- Makefile
- hack/ifreload/.gitignore
- hack/ifreload/Dockerfile.build
- hack/ifreload/Dockerfile.ifreload
- hack/ifreload/Dockerfile.tools
- hack/ifreload/Makefile
- hack/ifreload/ifreload-dryrun.yaml
- hack/ifreload/ifreload.c
- hack/ifreload/ifreload.yaml
workaround the kernel issue we're seeing
> add ifreload tool

- pkg/ifreload/ifreload.go
- pkg/install/ifreload.go
- pkg/install/install.go
depends on https://github.com/Azure/ARO-RP/pull/772
> integrate ifreload tool

- docs/az-aro-python-development.md
> [docs]Add contributing section to az aro python development

- .pipelines/e2e-with-billing-all-regions.yml
RP E2E has passed in Southafricanorth. This PR will add this region in daily e2e
https://msazure.visualstudio.com/AzureRedHatOpenShift/_build/results?buildId=31630412&view=logs&s=5b8cfc99-6a16-5af6-dabe-8bcd0be8fed8&j=a7030b29-0362-50ed-dadb-f72f5e63a55b
> add south africa north

- .pipelines/mirror-images.yml
Fix image mirror due to limit on public agents.
> Image-Mirror fix

- pkg/api/admin/openshiftcluster.go
- pkg/api/admin/openshiftcluster_convert.go
- pkg/api/admin/openshiftcluster_validatestatic_test.go
Add registryProfile to the admin api
Fix: #685 
> Add RegistryProfile to admin API

- hack/ssh-agent.sh
> Nit SSH-agent fix

- Dockerfile.routefix
- Makefile
- pkg/install/install.go
- pkg/install/routefix.go
- pkg/routefix/routefix.go
This is a workaround for clusters which hit https://bugzilla.redhat.com/show_bug.cgi?id=1849736.
> work around mtu 1450 in route exception table

- hack/e2e/run-rp-and-e2e.sh
This reverts commit 4133c38ca5935ad074cbe4182b1273ba99e65c6a.
Reverts the revert :) 
fixes: https://github.com/Azure/ARO-RP/issues/752 
Tests if we can handle upper-lower letters in location field
Part of e2e
No
> Re-add location uppercase test

- pkg/frontend/middleware/log.go
This sets X-Ms-Client-Request-Id if requested (we currently ignore it).
Added a check within a unittest.
No.
> Sets X-Ms-Client-Request-Id if requested

- .pipelines/clean-subscription.yml
Clean subscriptions
Enable purge in non-dry mode
Run in dry mode to see if world is still spinning around.
> Enable purge

- pkg/install/condition.go
- pkg/install/condition_test.go
Fixes https://dev.azure.com/msazure/AzureRedHatOpenShift/_workitems/edit/7519638/
This PR changes the way we check if operators are ready after cluster creation. With 4.4 there's a unified way to check if a cluster operator is available.
E2E tests will verify if the installation progresses. The logic of checking if operators are available hasn't changed, only the method.
No docs changes, code got a bit simpler in conditions.go.
> Changed installer operator checks to cluster operator checks

- test/e2e/adminapi.go
- test/e2e/adminapi_cluster_get.go
- test/e2e/adminapi_cluster_list.go
- test/e2e/adminapi_cluster_update.go
There is one todo item waiting for #859 to be merged.
Partially fixes [Work item #6098209](https://dev.azure.com/msazure/AzureRedHatOpenShift/_workitems/edit/6098209/)
Adds more admin API tests.
PR only includes tests.
No, PR only includes tests.
> Adds E2E tests for admin API: list clusters

- pkg/util/billing/billing.go
Fixes: N/A
Standardizes a variable name to enhance readability of repository.
Renames all occurrences of a variable used within a single function; no testing is required.
No, just cleaning up.
> use standard name subscriptionDoc

- pkg/genevalogging/genevalogging.go
- pkg/ifreload/ifreload.go
- pkg/routefix/routefix.go
> apply projectv1.ProjectNodeSelector to namespaces at upgrade

- pkg/backend/subscriptions.go
At the time of writing, subscription docs are only enqueued to enable cascading delete, but for safety let's double-check our state before actually deleting anything in case that assumption ever changes.
> add extra subscription deletion check

- test/e2e/adminapi_resources.go
Fixes [a new E2E bug](https://msazure.visualstudio.com/AzureRedHatOpenShift/_build/results?buildId=33157989&view=logs&j=10f66467-59e5-53bc-0c8a-42cc89770de4&t=cc311011-c8c8-5cb4-274c-19f32b3aecb1&l=757) caused by https://github.com/Azure/ARO-RP/pull/893.
Fixes a new bug causing all E2Es to fail due to the addition of VNet to the admin resource list endpoint.
Run E2E successfully.
> E2E VNet Resource List Fix

- hack/devtools/deploy-shared-env.sh
Fixes one of the vectors how our dev got purged.
> Add persist tag

- test/e2e/adminapi_resources.go
Correcting approach in https://github.com/Azure/ARO-RP/pull/900
> don't assume that RG name starts with aro-

- cmd/aro/rp.go
- pkg/api/v20201231preview/generate.go
- pkg/api/v20201231preview/openshiftcluster.go
- pkg/api/v20201231preview/openshiftcluster_convert.go
- pkg/api/v20201231preview/openshiftcluster_example.go
- pkg/api/v20201231preview/openshiftcluster_marshal.go
- pkg/api/v20201231preview/openshiftcluster_validatestatic.go
- pkg/api/v20201231preview/openshiftcluster_validatestatic_test.go
- pkg/api/v20201231preview/openshiftclustercredentials.go
- pkg/api/v20201231preview/openshiftclustercredentials_convert.go
- pkg/api/v20201231preview/openshiftclustercredentials_example.go
- pkg/api/v20201231preview/register.go
- swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/stable/2020-12-31-preview/examples/OpenShiftClusters_CreateOrUpdate.json
- swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/stable/2020-12-31-preview/examples/OpenShiftClusters_Delete.json
- swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/stable/2020-12-31-preview/examples/OpenShiftClusters_Get.json
- swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/stable/2020-12-31-preview/examples/OpenShiftClusters_List.json
- swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/stable/2020-12-31-preview/examples/OpenShiftClusters_ListByResourceGroup.json
- swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/stable/2020-12-31-preview/examples/OpenShiftClusters_ListCredentials.json
- swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/stable/2020-12-31-preview/examples/OpenShiftClusters_Update.json
- swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/stable/2020-12-31-preview/examples/Operations_List.json
- swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/stable/2020-12-31-preview/redhatopenshift.json
Fixes: https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/7508558
Introduce preview API for ARO-RP. This enables adding new features exposed via API.
Currently, the API is the same as released stable API v20200430. No tests are included at this time.
No documentation yet, as this API is a plain copy of stable API.
> Add preview API to ARO-RP

- pkg/frontend/kubeactions/mustgather.go
Fixes https://github.com/Azure/ARO-RP/issues/912
Waits for the existence of the default service account before creating the must-gather pod.
E2E must gather test (`test/e2e/adminapi_mustgather.go`)
No, fixes a race condition
> [WIP] Must gather: wait for default service account to exist

- linter_exclusions.yml
Fixes unit test failure. Upstream `azdev` added new linter rules
> fix python linter

- .pipelines/prod-release.yml
Adds canary regions to prod release
Do a prod rollout
Not yet
> Add canary to prod release

- .pipelines/prod-release.yml
Fixes staging for prod deploy. Adds missing dependsOn stanza
> Add missing dependsOn for prod

- .pipelines/mirror-images.yml
Needed for debug cluster.
Ability to run this on an ad-hoc basis
> Add ability to sync from custom build

- pkg/swagger/swagger.go
Updated swagger generation to current api version
> Change api version in swagger generation

- pkg/util/status/clusterversionoperator_status.go
Add explaining comment for hotfix regarding bug https://github.com/petrkotas/ARO-RP/pull/new/add-comment
None needed
None needed
> Add explaining comment for CVO fix

- cmd/aro/deploy.go
- pkg/deploy/config.go
- pkg/deploy/config_test.go
- pkg/deploy/deploy.go
- pkg/deploy/deploy_test.go
- pkg/deploy/predeploy.go
**What this PR does**
Enable skipping the empty fields the
Configuration fields via nil value check.
Fix: #838 
**Comment**
still need better tests
/cc @mjudeikis
> Change template configuration to pointers

- hack/clean/clean.go
> Purge denylist

- pkg/env/dev.go
Part of https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/7914937
In a situation where you are using env.Dev + go test (e.g. my database integration tests that can talk to cosmosdb), you will be unable to read the certificates it loads due to the current working directory being changed to a temporary one for test isolation. This uses the module's code path to determine the source directory of the RP.
It lets me run the tests :)
N/A
> Work around test runners changing the current directory

- .pipelines/e2e-with-billing-all-regions.yml
- .pipelines/prod-release.yml
Add CentralIndia to regions
GA Central India
> Add CentralIndia

- cmd/aro/rp.go
- pkg/backend/backend.go
- pkg/backend/openshiftcluster.go
- pkg/backend/openshiftcluster/adminupdate.go
- pkg/backend/openshiftcluster/create.go
- pkg/backend/openshiftcluster/openshiftcluster.go
- pkg/cluster/cluster.go
each call to encryption.NewXChaCha20Poly1305 causes a key vault lookup, which
is excessive
> don't call encryption.NewXChaCha20Poly1305 in cluster.New

- test/e2e/adminapi_redeployvm.go
Should fix one of the flakes seen here: https://msazure.visualstudio.com/AzureRedHatOpenShift/_build/results?buildId=34564762&view=logs&j=10f66467-59e5-53bc-0c8a-42cc89770de4&t=f00aaa95-0643-5e60-2886-48bbeb9c10f0
Currently we don't wait for all nodes to be ready after testing redeploy.  If this test runs before the scale test, the latter can immediately fail.
Run e2e
No.
> flake: wait for nodes to go ready after redeploy admin action check

- .pipelines/e2e-with-billing-all-regions.yml
- .pipelines/prod-release.yml
Fixes https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/7065267/ and https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/7065209/
Adding 2 new regions to "Deploy ALL Regions" and billing e2e tests.
N/A
N/A
> adding uaenorth and eastasia to pipelines

- .pipelines/templates/template-prod-e2e-steps.yml
Should fix E2E failure during builds of the RP.
> Add checkout for e2e in builds

- test/e2e/operator.go
Fixes flake seen in https://msazure.visualstudio.com/AzureRedHatOpenShift/_build/results?buildId=34564762&view=logs&j=10f66467-59e5-53bc-0c8a-42cc89770de4&t=f00aaa95-0643-5e60-2886-48bbeb9c10f0
The above flake happened because two controllers made concurrent modifications during the test.  The updatedObjects part of the test is ugly but useful.  Ideally we might fix this flake by somehow having the operator indicate that all controllers are synced before starting testing, but for now as a hack, exclude other namespaces / non-namespaced objects from the test by using a filter.
E2E test
No.
> hack: filter updateObjects test by namespace to avoid flaking on concurrent changes to other objects by other controllers

- hack/devtools/deploy-shared-env.sh
To align with ci count in the production
> Increase ci vmss count

- .github/CODEOWNERS
:partying_face: :balloon: :wave: :fallen_leaf: :man_technologist: :partying_face: :birthday:
> @asalkeld Leaving party!

- pkg/env/prod.go
> fix rp panic in eastus2euap

- pkg/operator/controllers/checker/checker_controller.go
- pkg/operator/controllers/pullsecret/pullsecret_controller.go
Fix a logic error causing e2es to fail currently
> don't call For multiple times on a controller-runtime Builder

- .github/workflows/maintenance.md
trying GitHub actions to mark needs-rebase - don't know if this will work
> try GitHub actions to mark needs-rebase

- docs/authorizers.md
- pkg/env/dev.go
- pkg/env/env.go
- pkg/env/int.go
- pkg/env/prod.go
- pkg/util/keyvault/keyvault.go
Fixes [7730098](https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/7730098)
- Adds doc which explains the different authorizers used in RP 
- Standardizes one name used in a few places
None - just adds comments and renames a few variables to be consistent.
This PR contains the documentation
> Add doc explaining authorizers; rename a few variables

- test/e2e/scalenodes.go
> be tolerant while waiting for nodes in e2e

- test/e2e/adminapi_kubernetesobjects.go
> increase deletion timeout

- .pipelines/prod-release.yml
fix pipeline overrun from last week
> add missing succeededOrFailed

- pkg/cluster/install.go
remove duplicate i.deployResourceTemplate invocation added in #860
pretty sure this was no more than a typo @hawkowl?
> remove duplicate i.deployResourceTemplate invocation added in #860

- test/e2e/operator.go
give more time for internet e2e test
> give more time for internet e2e test

- pkg/cluster/deploystorage.go
Fixes [8218896](https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/8218896)
If cluster creation fails due to RequestDisallowedByPolicy, the customer is in the dark and doesn't know what to do to fix it -- they just see InternalServerError. We should return the policy error to them.
For example, a policy might require resource groups to all have certain tags. In this case, they would need to create two resource groups with those tags and specify them both in the az aro create command. To help them arrive at this conclusion, presenting them with their own policies would be a good idea and it would save SRE time.
No tests - just returns a more detailed error to user in one situation
Might be worth updating official ARO documentation with troubleshooting steps, at least …
> Return RequestDisallowedByPolicy errors to user

- pkg/frontend/admin_openshiftcluster_kubernetesobjects_test.go
- pkg/frontend/validate.go
prevent access to oauth objects via geneva actions
> prevent access to oauth objects via geneva actions

- .pipelines/build-and-push-images.yml
- .pipelines/deploy-dev-env.yml
- .pipelines/e2e.yml
- .pipelines/templates/template-az-cli-login.yml
- .pipelines/templates/template-az-cli-logout.yml
- .pipelines/templates/template-clean-subscription.yml
- .pipelines/templates/template-deploy-azure-env.yml
- .pipelines/templates/template-deploy-shared-env.yml
- .pipelines/templates/template-prod-e2e-steps.yml
make sure we always run `az logout` after `az login` in CI to help avoid unwittingly leaking credentials across jobs
> add az logout template

- .pipelines/templates/template-prod-e2e-steps.yml
Fixes a typo in path. (minor fix)
Wrong template import path, e2e doesn't work due to it.
Run E2E, see if pipeline works.
No docs needed, tech fix.
> correcting path in E2E pipeline

- pkg/deploy/predeploy.go
> Fix typo in location 

- pkg/deploy/upgrade.go
storage accounts must be lowercase
> lower-case rpVersion to rpversion

- cmd/aro/main.go
> enable pprof on localhost

- pkg/deploy/deploy.go
remove unused client
@Makdaam @mjudeikis
> remove unused client

- hack/e2e/run-rp-and-e2e.sh
This is a bit of a hack, but this code should be going away soon anyway.
cf https://github.com/Azure/azure-cli/issues/14767
> retry `az ad sp create-for-rbac` if it fails

- python/az/aro/azext_aro/_rbac.py
workaround e2e failure https://msazure.visualstudio.com/AzureRedHatOpenShift/_build/results?buildId=35850482&view=logs&j=ea6eb09a-9147-5082-5104-9a8b4fde10b0&t=03eeb979-cfc7-50a1-1612-b7c5cb6b4789
> retry hash conflict ValidationError in python

- .gitignore
When working with INT, E2E, dev, I need multiple secrets folders. Tidy up :)
> add secrets* to .gitignore

- pkg/operator/controllers/workaround/systemreserved.go
- pkg/operator/controllers/workaround/systemreserved_test.go
- pkg/util/dynamichelper/dynamichelper.go
- pkg/util/dynamichelper/dynamichelper_test.go
Fixes: 8636074
Adds hardEviction to nodes
Locally run busy nodes and see
N/A
> Add hardEviction

- python/az/aro/azext_aro/_rbac.py
- python/az/aro/azext_aro/custom.py
> Revert "Fix permissions on cluster deletion in az cli"

- pkg/monitor/cluster/clusterversions.go
- pkg/monitor/cluster/clusterversions_test.go
Fixes https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/8573067/ 
Introduce cluster baseline version metric. The metric signals whether the cluster lags behind
upgrade stream with its version.
Metric adds baselineVersion as additional dimension to the existing clusterVersion metric.
This dimension is emited only when the cluster requires attention: the version is behind its upgrade stream.
Added unit test covering baseline computation. Added unit test testing the metric emit.
VSTS ticket https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/8573067/
> Add baselineversion metric

- pkg/api/admin/openshiftcluster.go
- pkg/api/admin/openshiftcluster_convert.go
- pkg/api/admin/openshiftcluster_validatestatic_test.go
- pkg/api/openshiftcluster.go
- pkg/cluster/install.go
- pkg/cluster/install_test.go
- pkg/frontend/openshiftcluster_putorpatch.go
- pkg/frontend/openshiftcluster_putorpatch_test.go
@hawkowl you missed this bit ;-)
> add CreatedBy to admin API

- pkg/util/keyvault/keyvault.go
RFC 5280 requires that the common name be <= 64 characters.  Also see https://docs.digicert.com/manage-certificates/public-certificates-data-entries-that/#64character-maximum-limit-violation .  The above does not prevent having longer DNS names in the subject alternative names field.  Key vault does not allow a certificate subject with an empty common name.  So, in the case where the domain name is too long, we use a reserved domain name which cannot be allocated by an end user as the common name.
Fixes #1120
> don't request certificates with long common names

- pkg/deploy/predeploy.go
Fixes https://github.com/Azure/ARO-RP/issues/1081
retry on global deployments when multiple concurrent deployments are running 
With :fire: 
No
> Add retry for global deployment

- .pipelines/int-release.yml
- .pipelines/templates/template-job-deploy-azure-env.yml
Fixes an unset parameter that's not really "optional".
> optional is not an option in vsts

- .pipelines/int-release.yml
- .pipelines/templates/template-job-deploy-azure-env.yml
> Revert "optional is not an option in vsts"

- pkg/util/cluster/cluster.go
Fix nightly breakage.  Can be reverted after 4.5 is rolled out.
> mend fixupNSGs to support 4.4 and 4.5 clusters in PROD

- pkg/util/azureclient/mgmt/authorization/roleassignments_addons.go
- pkg/util/cluster/cluster.go
- pkg/util/mocks/azureclient/mgmt/authorization/authorization.go
> restrict deleteRoleAssignments to owning resource group

- .pipelines/int-release.yml
- .pipelines/mirror-images.yml
- .pipelines/templates/template-job-deploy-azure-env.yml
s/master/latest
Better word choice and more descriptive.
> changing master to latest as it better describes what's being run.

- pkg/api/validate/openshiftcluster_validatedynamic.go
- pkg/api/validate/openshiftcluster_validatedynamic_test.go
I don't think anyone's ever hit this, but I spotted the validation was missing.
> validate vnet location matches cluster location

- pkg/util/ready/ready.go
- test/e2e/cluster.go
Stop using a naked pod for the pod storage test - we hit node rotations and the test flakes.  Use a stateful set and up the timeout.
> make pod storage test less flaky

- pkg/cluster/install.go
- pkg/cluster/tls.go
- pkg/util/azureclient/keyvault/base.go
- pkg/util/keyvault/keyvault.go
- pkg/util/mocks/azureclient/keyvault/keyvault.go
- pkg/util/mocks/keyvault/keyvault.go
I've validated manually that all certs are upgraded
> remove certificate policy upgrade code, all certs are upgraded

- python/az/aro/azext_aro/_rbac.py
- python/az/aro/azext_aro/custom.py
This reverts commit 45baf2f5b92f1b7e17919856131fe4bc7838e260.
Reopening to continue on discussion in #1011.
> Revert "Revert "Fix permissions on cluster deletion in az cli""

- .sha256sum
- pkg/api/v20191231preview/openshiftcluster.go
- pkg/api/v20191231preview/openshiftcluster_validatestatic.go
- pkg/api/v20191231preview/openshiftcluster_validatestatic_test.go
- pkg/api/v20191231preview/openshiftclustercredentials.go
- pkg/api/v20200430/openshiftcluster.go
- pkg/api/v20200430/openshiftcluster_validatestatic.go
- pkg/api/v20200430/openshiftcluster_validatestatic_test.go
- pkg/api/v20200430/openshiftclustercredentials.go
- pkg/api/v20201031preview/openshiftcluster.go
- pkg/api/v20201031preview/openshiftcluster_validatestatic.go
- pkg/api/v20201031preview/openshiftcluster_validatestatic_test.go
- pkg/api/v20201031preview/openshiftclustercredentials.go
- pkg/client/services/redhatopenshift/mgmt/2020-04-30/redhatopenshift/models.go
- pkg/client/services/redhatopenshift/mgmt/2020-10-31-preview/redhatopenshift/models.go
- python/client/azure/mgmt/redhatopenshift/v2020_04_30/models/_models.py
- python/client/azure/mgmt/redhatopenshift/v2020_04_30/models/_models_py3.py
- python/client/azure/mgmt/redhatopenshift/v2020_10_31_preview/models/_models.py
- python/client/azure/mgmt/redhatopenshift/v2020_10_31_preview/models/_models_py3.py
- swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/stable/2020-04-30/redhatopenshift.json
- swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/stable/2020-10-31-preview/redhatopenshift.json
Increase the default worker profile count on Create to 50
> Make workers count unbound 

- pkg/util/version/stream.go
- pkg/util/version/stream_test.go
- pkg/util/version/version.go
> handle hotfix upgrades

- swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/stable/2020-04-30/redhatopenshift.json
Align swagger spec with generator and API
> Align swagger - 2020-04-30

- .pipelines/templates/template-clean-subscription.yml
- cmd/aro/deploy.go
- cmd/aro/mirror.go
- hack/clean/clean.go
- pkg/env/core.go
- pkg/util/instancemetadata/dev.go
- pkg/util/instancemetadata/instancemetadata.go
- pkg/util/purge/purge.go
- test/e2e/setup.go
Fies failed int and image mirror: 
Fixes: https://msazure.visualstudio.com/AzureRedHatOpenShift/_build/results?buildId=37125126&view=logs&j=3c7d1bfc-207c-57c7-bfba-8d4b44a0467d&t=1acb40ae-22aa-5025-303e-cfb82f77661f
https://msazure.visualstudio.com/AzureRedHatOpenShift/_build/results?buildId=37125123&view=logs&j=406f28f7-259e-5bfd-e153-dd013342e83f&t=5ea0ef72-2b7c-5817-344e-070cc4795af5
> Fix deployment and mirror

- python/az/aro/azext_aro/_validators.py
- python/az/aro/azext_aro/azext_metadata.json
- python/az/aro/azext_aro/custom.py
[8920206](https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/8920206/)
The way error handling guidelines in upstream az-cli has [changed](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).  Before upstreaming other az-cli changes, these errors must be changed to the newer ones.
Standard unit testing
No
> Update error handling per new az-cli upstream guidelines

- .github/CODEOWNERS
- pkg/api/validate/openshiftcluster_validatedynamic.go
- pkg/api/validate/openshiftcluster_validatedynamic_test.go
- python/az/aro/azext_aro/custom.py
* az aro: don't honour AZURE_FP_CLIENT_ID when RP_MODE is unset
* update RP error message
* remove ehashman from CODEOWNERS
> Minor fixes

- python/az/aro/azext_aro/_aad.py
Reconcile more of az aro extension with azure-cli
Reconcile more of az aro extension with azure-cli
Python unit tests
No
> Reconcile more of az aro extension with azure-cli

- pkg/api/admin/openshiftcluster.go
Returns arch version via Admin action to help with scripting and insights.
> Return arch version to admin

- pkg/mirror/graph.go
Fix broken mirroring pipelines
> fix mirror: upstream cincinnati changed image prefix

- .pipelines/templates/template-deploy-shared-env.yml
- docs/prepare-a-shared-rp-development-environment.md
- hack/devtools/deploy-shared-env.sh
> small fixes found deploying dev env to government cloud

- pkg/portal/kubeconfig/proxy.go
- pkg/portal/kubeconfig/proxy_test.go
> add nil kubeconfig check to portal

- hack/devtools/deploy-shared-env.sh
- pkg/env/core.go
- pkg/util/cluster/cluster.go
- pkg/util/tls/marshal.go
Partially fixes [8644408](https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/8644408)
Misc fixes to move towards ARO in AzureUSGovernment cloud
Run existing unit and E2E tests
No
> Works towards AzureUSGovernment enablement

- pkg/cluster/deploystorage.go
- pkg/util/aad/aad.go
- pkg/util/cluster/aad.go
Should fix a nightly E2E failure I saw
> retry createServicePrincipal when needed

- docs/prepare-a-shared-rp-development-environment.md
- hack/devtools/deploy-shared-env.sh
Fixes our docs regards the certs updates
Because we broke int :)
> Update cert docs

- Makefile
Looking into CI issues with Python
> Updates pyenv with the latest pip

- docs/prepare-a-shared-rp-development-environment.md
Fixes docs
Doc fixes only
Yes, in this PR.
> Shared RP Dev Env Doc Fixes

- pkg/deploy/upgrade.go
- pkg/frontend/frontend.go
- pkg/frontend/ready_get.go
- pkg/frontend/security_test.go
- pkg/monitor/monitor.go
We need to work out a monitoring alternative to handle the functionality removed in commit 2.  Don't merge until we've got it.
> Remove some sleeps

- pkg/operator/deploy/deploy.go
- test/e2e/operator.go
> disable PersistentPrometheus

- pkg/api/validate/dynamic.go
Recent failures. I suspect azure being slow.
https://msazure.visualstudio.com/AzureRedHatOpenShift/_build/results?buildId=39263962&view=logs&s=602abd16-0dc6-5e79-6702-0d1aa3f2fbca&j=d87a2e09-c6ef-5d96-4472-efb2a5350117
https://msazure.visualstudio.com/AzureRedHatOpenShift/_build/results?buildId=39263962&view=logs&s=602abd16-0dc6-5e79-6702-0d1aa3f2fbca&j=c52c4f47-0644-5533-2e1d-fa2b7edb92c3
https://msazure.visualstudio.com/AzureRedHatOpenShift/_build/results?buildId=39244048&view=logs&s=602abd16-0dc6-5e79-6702-0d1aa3f2fbca&j=d87a2e09-c6ef-5d96-4472-efb2a5350117
> bump routetable validate timeout

- cmd/aro/monitor.go
- cmd/aro/portal.go
- hack/db/db.go
- pkg/api/validate/dynamic.go
- pkg/api/validate/openshiftcluster_validatedynamic.go
- pkg/api/validate/quota.go
- pkg/deploy/generator/const.go
- pkg/deploy/generator/resources.go
- pkg/deploy/generator/templates.go
- pkg/env/env.go
- pkg/env/prod.go
use env.Core instead of env.Interface in pkg/api/validate
move *KeyVaultSuffix to env
> Minor code transformations

- pkg/util/azureclient/debug.go
Add debug azure logger. 
Number of times I had to copy this code is lost.
> Add logger for future debugging 

- pkg/deploy/predeploy.go
- pkg/util/cluster/cluster.go
attempt to work around an error seen in our e2es
> add retry in fixupNSGs

- pkg/util/version/const.go
> bump to 4.4.33

- pkg/api/validate/openshiftcluster_validatedynamic.go
- pkg/api/validate/quota.go
- pkg/cluster/cluster.go
- pkg/cluster/install.go
- pkg/cluster/serviceprincipal.go
- pkg/cluster/validate.go
- pkg/util/aad/aad.go
Fixes our ability to deal with Cluster SP client related steps
This will enable us better control CSP related clients, 
Sadly not much. Code we abstracting is hard to test so we want to put it away for now :)
No
> Add step to initialize SP clients in the install

- pkg/mirror/mirror.go
increase retries and wait a little in response to some PROD mirroring failures
> mirror: try harder

- .pipelines/e2e-with-billing-all-regions.yml
- .pipelines/prod-release.yml
ARM manifest deployment in progress behind feature flag, can merge this
> enable brazilsoutheast, indiasouth

- pkg/cluster/install.go
change order of steps to reduce race condition probability
> Step order change

- pkg/cluster/ipaddresses.go
- pkg/cluster/ipaddresses_test.go
> fix router IP address panic 

- pkg/frontend/adminactions/kubeactions.go
- pkg/monitor/cluster/arooperatorheartbeat.go
- pkg/monitor/cluster/cache.go
- pkg/monitor/cluster/cluster.go
- pkg/monitor/cluster/clusterversions.go
- pkg/monitor/cluster/daemonsetstatuses.go
- pkg/monitor/cluster/deploymentstatuses.go
- pkg/monitor/cluster/jobconditions.go
- pkg/monitor/cluster/machineconfigpoolconditions.go
- pkg/monitor/cluster/podconditions.go
- pkg/monitor/cluster/replicasetstatuses.go
- pkg/monitor/cluster/statefulsetstatuses.go
- pkg/util/clusterdata/ingress_profiles_task.go
- pkg/util/clusterdata/worker_profiles_task.go
Should fix BBM OOM kills seen due to too many ReplicaSet objects on a managed cluster.  Also a frontend OOM kill when trying to list the objects via Geneva action :-(
By inspection (view PR with whitespace diff off).
No.
> Paginate in monitor and frontend (Geneva actions)

- pkg/operator/controllers/alertwebhook/alertwebhook_controller.go
- pkg/operator/controllers/checker/checker_controller.go
- pkg/operator/controllers/dnsmasq/cluster_controller.go
- pkg/operator/controllers/genevalogging/genevalogging_controller.go
- pkg/operator/controllers/monitoring/monitoring_controller.go
- pkg/operator/controllers/pullsecret/pullsecret_controller.go
- pkg/operator/controllers/rbac/rbac_controller.go
- pkg/operator/controllers/routefix/routefix_controller.go
> Simplifies event filtering in the operator

- pkg/portal/ssh/proxy.go
- pkg/proxy/proxy.go
a couple of potential possible leaks - should be safe to merge
> bug fix: correct connection close behaviour

- docs/updating-dependencies.md
Add vendorind and dependency update documentation with
vendoring process of ARO-RP.
None, doc update.
It is documentation itself.
> Add dependency update documentation

- pkg/operator/apis/aro.openshift.io/v1alpha1/cluster_types.go
- pkg/operator/controllers/condition.go
- test/e2e/operator.go
PR is part of work done on 
fixing https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/8749451/
Refactors the code linked to `setStaticStatus` to clear up the confusion about its use.
Moreover minor refactor of tests to simplify future conditions changes.
This PR is part of the PR: #1347, it is split to simplify review process.
> Refactor setting static status to enable future condition appending

- .github/CODEOWNERS
Clean owners file.
In case of issues we need to be able to merge.
> Clean owners file

- pkg/monitor/cluster/prometheusalerts.go
https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/9311775/
Quick win on alerting: disable ImagePruningDisabled alert sending to Geneva (plus small correct with alerts/count
ImagePruningDisabled alert is currently firing (noisily) for clusters created before 4.5 and then upgraded to 4.5+. This alert fires when imagepruning job is suspended (which is the default case for clusters created before 4.5 but then upgraded). 
- Are there unit tests? apparently unit testing prometheus alerts in ARO codebase was not done in the past and not easy
- Are there integration/e2e tests? No
- If it is not possible to write automated tests, explain why and document how
to manually test and verify the feature.
Should be possible to test manually in theory, starting a local monitor process, …
> ignore ImagePruningDisabled alert

- cmd/aro/mirror.go
easily separable PR of #1377.  Convenience PR - no-op in PROD, can just be merged
> sync additional geneva/rhel images on single-shot mode to make it easier to stand up an ACR

- hack/clean/clean.go
don't mess with clusters in RGs managed by a production RP. Although the production deny assignment will prevent us from breaking most things, that does not include us potentially detaching the cluster's NSG from the vnet, thus breaking inbound access to the cluster.
> purger: ignore managed resource groups

- pkg/deploy/predeploy.go
> fix broken ACRReplicaDisabled logic

- cmd/aro/operator.go
- go.mod
- go.sum
- pkg/operator/controllers/clusteroperatoraro/clusteroperatoraro_controller.go
- pkg/operator/controllers/const.go
- pkg/util/scheme/scheme.go
- vendor/github.com/openshift/library-go/LICENSE
- vendor/github.com/openshift/library-go/pkg/config/clusteroperator/v1helpers/status.go
- vendor/modules.txt
Work item [№9264594](https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/9264594/).
We want to block upgrades when there are issues with the cluster.
**Note:** this will not block patch releases.
> Skeleton for blocking cluster updates via clusteroperator status

- linter_exclusions.yml
- pkg/util/aad/aad.go
- pkg/util/azureerrors/error.go
- pkg/util/refreshable/refreshable.go
- python/az/aro/azext_aro/_aad.py
- python/az/aro/azext_aro/_params.py
- python/az/aro/azext_aro/_validators.py
- python/az/aro/azext_aro/custom.py
- python/az/aro/linter_exclusions.yml
Fixes: https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/9148852
First part of the story.
It will enable us to pass credentials changes into API server. 
API server will have to be changed to accept those. 
This is out of scope for this PR
Rotation on CLI is https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/7609645 
Review review review...
Yes, docs how to use it.
> CLI Credential rotation

- go.mod
- go.sum
- vendor/github.com/openshift/installer/pkg/aro/dnsmasq/dnsmasq.go
- vendor/modules.txt
Fixes cases where we get multiple IP;s from `hostname -I`
Production issue
Tests will show :)
No
> Fix IP address resolution

- python/az/aro/azext_aro/__init__.py
- python/az/aro/azext_aro/_validators.py
Fixes issues with PyLint in CI. This is a test PR to trigger tests. DO NOT MERGE.
> DO NOT MERGE - test commit for CI pylint

- README.md
Updates README for repository structure with addition to the clusteroperator controller and the  serviceprincipalchecker in the checker controller 
None 
Updated with this PR
> Update README with clusteroperatoraro controller and serviceprincipal checker in checker controller

- docs/deployment-model.md
add deployment model documentation
> add deployment model documentation

- docs/deploy-development-rp.md
N/A, no associated ADO item or issue
Adds full package name `python-setuptools` in code blocks to prerequisite steps.
Not needed, docs change.
No
> Formatting fix for deploy-development-rp.md

- pkg/cluster/delete.go
Relates to PR https://github.com/Azure/ARO-RP/pull/1447
Retry logic on delete for E2E failures
Testing using e2e pipelines
Comments in code
> Adding retry logic to delete

- .github/CODEOWNERS
> Remove @jim-minter

- cmd/aro/deploy.go
Partially hacks around https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/9909648 
It enabled us to use managed identity metadata in EV2 where env variables are not set.
we should set `AZURE_EV2=true` for this to work. Otherwise old behavior stays 
Test in prod
Not yet
> Workaround EV2 for GovCloud

- pkg/deploy/predeploy.go
Fixes hardcoded global rp location.  Use the RP config instead.
> Fix Hardcoded Global RP Location

- pkg/env/prod.go
Fixes https://github.com/Azure/ARO-RP/issues/1515
Azure API stopped returning metadata. Stopgap solution until we find out right way to do this.
No
No
> Fix SKUs issue 

- pkg/cluster/delete.go
This reverts commit 278e59131d68dfc1068937d58099f36bc99db248, reversing
changes made to 060007680842a5e80ba56d7a67c1054fda717b83.
> Revert "Merge pull request #1483 from swiencki/retryDelete"

- README.md
No associated issue or ADO item.
Adds a brief description of the new azurensg operator controller to our README.md.
N/A, documentation change.
N/A
> Add azurensg controller to README.md

- .github/CODEOWNERS
Add owner for approvals and merged
> Add @m1kola

- pkg/portal/cluster_test.go
- pkg/portal/middleware/aad.go
- pkg/portal/middleware/aad_test.go
- pkg/portal/portal.go
- pkg/portal/security_test.go
Fixes https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/10191797
The existing REST API does redirects when not authorised, which means that it's difficult to make a more front-end based interface over these APIs.
It does not change the portal UI.
Existing tests + manual testing of the portal.
N/A
> Admin Portal 2.0 -- RESTify the existing API

- docs/deploy-development-rp.md
A copy-paste-ish example documenting how to perform an adminUpdate on a dev RP against a dev cluster
> document cmd to trigger adminupdate with dev rp && dev cluster

- pkg/cluster/delete.go
Fixes https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/9744005/
Customers have created clusters without using AZ CLI and have created the cluster resource groups prior to submitting a PUT request into ARM to create an ARO cluster. This results in the cluster resource group not being owned by the RP. In this circumstance we do not want the RP to blindly delete (and likely does not have permissions on) resources in this customers cluster resource group that they created.
As a side effect of this PR I have modified non production clusters to have a proper ManagedBy field set. Prior to this, all non production clusters ManagedBy field was `ManagedBy = nil`, and the purger operated on deleting clusters older than `X` amount of days that have `ManagedBy = nil || ManagedBy = …
> Conditional Delete when CRG ManagedBy != OpenShiftCluster.Id

- pkg/cluster/delete.go
Fixes dev cluster deletion which got broken in #1541
> Fixes dev cluster deletion

- .pipelines/templates/template-prod-e2e-steps.yml
Fixes SP ref for Production public cloud
I suspect App id is wrong in public cloud.
by :fire: 
No
> change SP for prod

- pkg/cluster/delete.go
- pkg/util/azureerrors/error.go
Fixes situation where create failed early in validation and RG does not even exists. 
:fire: 
No
> ResourceGroupNotFound flake

- pkg/api/validate/dynamic/dynamic_test.go
- pkg/api/validate/dynamic/provider_test.go
- pkg/frontend/openshiftcluster_putorpatch_test.go
- pkg/util/dns/dns_test.go
* Moves gomock.NewController(t) call into subtests, where possible
* Adds missing t.Run(tt.name, ...) calls
Run unit tests in CI
> Unit test improvements

- pkg/portal/security_test.go
Fixes nothing
Calls out a todo on a data race condition only present in our unit tests.  
n/a
no
> Security Test Data Race

- pkg/api/validate/dynamic/dynamic_test.go
> Replaces func() with context.CancelFunc in tests

- pkg/cluster/delete.go
Just addresses minor things from https://github.com/Azure/ARO-RP/pull/1541#pullrequestreview-697020905
@bryanro92 please take a look.
> Cluster deletion refactoring

- pkg/cluster/generateconfig.go
- pkg/env/env.go
- pkg/env/prod.go
- pkg/util/computeskus/computeskus.go
- pkg/util/computeskus/computeskus_test.go
- pkg/util/mocks/env/env.go
Part of work item [№9586080](https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/9586080/).
This is a prerequisite for Server-Side Encryption and Encryption at host validations PR https://github.com/Azure/ARO-RP/pull/1595.
Existing unit tests and e2e tests should cover this refactoring.
> Refactors the way we work with compute SKUs

- pkg/monitor/cluster/arooperatorconditions.go
- pkg/monitor/cluster/clusterversionconditions.go
- pkg/monitor/cluster/machineconfigpool.go
- test/e2e/adminapi_redeployvm.go
Reduce useless logging in monitor
Reduce noise. 
No
no
> Reduce logging

- pkg/cluster/fixssh.go
- pkg/cluster/fixssh_test.go
Fixes ICM 250423613
workarounds partially https://bugzilla.redhat.com/show_bug.cgi?id=1882490
If customer deleted master it will get re-created with different nic name (see bz for more info). If this happens we have following things:
1. Master is not in the LB anymore (not the scope of this PR)
2. fixSSH breaks with unknown NIC name (this pr)
Unit tests
No
> Add fixSSH fallback

- pkg/operator/README.md
This is the followup to the conversation we had recently on why separate master/worker deployments are necessary in the operator. I'm happy to make any additional edits/adds here, if there are suggestions.
Just for clarity / legibility.
N/A, docs change.
N/A.
> Add operator readme section with deployment info

- pkg/cluster/deploystorage.go
- pkg/cluster/install.go
- pkg/cluster/kubeconfig.go
> move kubeconfig in deploystorage to dedicated step

- Makefile
We have failing CI due to upstream issue: https://github.com/Azure/azure-cli/issues/18950
See if CI is green
Work item to revert this once https://github.com/Azure/azure-cli/issues/18950 fixed: [№10448709](https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/10448709).
> Temporary remove azdev from tests

- pkg/operator/controllers/machine/machine_controller_test.go
Fixes https://github.com/Azure/ARO-RP/issues/1605 
Currently the machine controller test repeats a lot of code and doesn't have the best coverage. This cleans things up and improves coverage. Thanks @nilsanderselde for the assist.
`make test-go`
`go test -v`
`go test -coverprofile machine.html`
No
> Fix up Machine controller tests

- .pipelines/e2e-with-billing-all-regions.yml
Add Norway West so we can see in the tests
Its rolling out in ARM so should be good to merge
with :fire: 
No
> Add norway west for tests

- Makefile
This reverts PR #1642 (commit c91f75874911c41a3c87c76b40860808cd2f51c3)
> Revert "Temporary remove azdev from tests"

- pkg/operator/controllers/machine/machine_controller_test.go
Nits clean repetitiveness 
Remove one function 
no
no
> Nits tests update

- hack/validate-imports/validate-imports.go
- pkg/cluster/fixmcscert_test.go
- pkg/cluster/fixmcsuserdata_test.go
- pkg/cluster/storageclass_test.go
- pkg/frontend/adminactions/upgrade_test.go
- pkg/monitor/cluster/machineconfigpool_test.go
- pkg/operator/controllers/azurensg/subnetnsg.go
- pkg/operator/controllers/azurensg/subnetnsg_test.go
- pkg/operator/controllers/dnsmasq/cluster_controller.go
- pkg/operator/controllers/genevalogging/genevalogging.go
- pkg/operator/controllers/machine/machine_controller_test.go
- pkg/operator/controllers/machineset/machineset_controller_test.go
- pkg/operator/controllers/pullsecret/pullsecret_controller_test.go
- pkg/operator/controllers/rbac/rbac_controller.go
- pkg/operator/controllers/routefix/routefix.go
- pkg/operator/controllers/workaround/systemreserved.go
- pkg/operator/controllers/workaround/systemreserved_test.go
- pkg/operator/deploy/deploy.go
- pkg/util/clusterdata/worker_profiles_task_test.go
- pkg/util/dynamichelper/createorder.go
- pkg/util/dynamichelper/createorder_test.go
- pkg/util/dynamichelper/discovery/cache_fallback_discovery_client.go
- pkg/util/dynamichelper/dynamichelper.go
- pkg/util/dynamichelper/dynamichelper_test.go
- pkg/util/dynamichelper/workloadhelper.go
- pkg/util/dynamichelper/workloadhelper_test.go
- pkg/util/ready/ready_test.go
Breaking out of a minor fix in another PR
Updates kubernetes's runtime import to kruntime to mirror.
Is part of testing
N/A
> Change kubernetes's runtime import name to kruntime

- pkg/cluster/tls.go
Fixes regression in the certs
Wrong namespace was specified 
:fire: 
No
> Fix regression 

- .pipelines/prod-release.yml
Add missing norwaywest to pipelines
> add  norwaywest

- deploy/generate.go
- pkg/api/admin/generate.go
- pkg/api/generate.go
- pkg/api/v20200430/generate.go
- pkg/api/v20210901preview/generate.go
- pkg/database/cosmosdb/generate.go
Superficial changes for consistency
Puts generate comments in a standard spot across the repo.
Noop
No
> standardize placement of generate command

- test/e2e/adminapi_redeployvm.go
> Disable redeploy VM tests

- docs/prepare-a-shared-rp-development-environment.md
Simple documentation update to use the new AAD group in Azure for the development subscription
Fixes
> Update documentation with the new AAD group

- README.md
doc update
noop
this is a doc update from #1663
> docs: README - rename azurensg -> subnets

- .pipelines/build-and-push-fluentbit.yml
- .pipelines/build-and-push-images.yml
- .pipelines/e2e.yml
- .pipelines/templates/template-push-images-to-acr.yml
Fluentbit image is stale. We need way to build it in prod and int fast. This should do
Automate the build
Test in pipelines
No
> fluentbit pipeline

- python/az/aro/azext_aro/_aad.py
- python/az/aro/azext_aro/_validators.py
- python/az/aro/azext_aro/custom.py
Fixes ADO-12526877
changed %-strings to f-strings as requested by linter
test-python - no new functionality
N/A - fixing linter complaints
> Fixing Python CI

- cmd/aro/operator.go
Fixes N/A
Remove the http server and utilizes builtin http
health probes in manager. This reduces the amount of custom code in the codebase.
> Move health probe to manager

- pkg/operator/controllers/subnets/subnets_controller.go
- pkg/util/clusterauthorizer/authorizer.go
Moves more boilerplate code into NewAzRefreshableAuthorizer
> Refactors clusterauthorizer

- pkg/deploy/devconfig.go
- pkg/util/version/const.go
as title says
recent changes were made and this is required for dev deploys to get latest configs
deployed it, e2e, :fire: 
I created a story for that, https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/12651598, ideally this could be automated
> update config version, abstract gateway devconfig to version const.go

- pkg/operator/controllers/dnsmasq/machineconfig_controller.go
- pkg/operator/controllers/dnsmasq/machineconfigpool_controller.go
Fixes a bug in our code where we apply dnsmasq config even if the reconciler feature flag is disabled.  
Fix bugs
Need to test still, but this is a bug
This needs unit tests too.  
Nope
> Don't reconcile the DNSMasq Stuffs if It's Disabled

- .github/CODEOWNERS
Fixes
Add pkotas as codeowner.
> other: add pkotas as codeowner

- docs/deploy-full-rp-service-in-dev.md
- pkg/deploy/devconfig.go
Fixes some doc & RP var gaps in spinning up a full service RP
No, these are the doc updates.
> Update docs and required dev-config params

- pkg/operator/controllers/genevalogging/const.go
I forget the ICM number
This fixes the config to not use a large amount of memory on Fluentbit 1.8.x. It does not include changing the Fluentbit version.
Tested on shared cluster:
N/A
> Fix fluentbit 1.8 memory usage

- docs/deploy-development-rp.md
Fixes https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/12838475/
Documents the procedure on how to make AdminAction API call(s)
to a localrp running a Dev Cluster to perform below actions.,
1. List Clusters
2. List Azure Resources
3. PUCM
4. Cluster Upgrade
5. Get Cluster Details
6. View Serial Console logs of a VM
> document on usage of how to make adminaction API calls to localrp

- pkg/frontend/operations_get.go
Fixes - WI TBD, RBAC operation not documented in api.
It adds a human readable operation description to be used in Azure RBAC. For the new listAdminCredentials endpoint.
The operations returned by the endpoint include the new one.
N/A
> adding description for the listadmincredentials action

- .pipelines/templates/template-job-deploy-azure-env.yml
The original path is not working as it is blocked for writing,
Using the pipeline default instead
> Fix: Broken pull path

- .pipelines/templates/template-job-deploy-azure-env.yml
The checkout behaves differently when checking out single repository.
It checkout to /s
> Fix: Broken checkout code path

- .pipelines/prod-release.yml
Pipeline params for prod pipeline was not consistent so I can't deploy.  
Run prod pipeline
No
> Update prod pipeline params to be consistent

- .pipelines/onebranch/pipeline.bootstrapper.official.yml
- .pipelines/onebranch/pipeline.bootstrapper.pullrequest.yml
- .pipelines/onebranch/pipeline.buildrp.official.yml
- .pipelines/onebranch/pipeline.buildrp.pullrequest.yml
- .pipelines/onebranch/pipeline.logging.geneva.bootstrapper.pullrequest.yml
- .pipelines/onebranch/pipeline.logging.geneva.pullrequest.yml
- .pipelines/onebranch/pipeline.logging.kusto.pullrequest.yml
Fixes: https://dev.azure.com/msazure/AzureRedHatOpenShift/_workitems/edit/12997379/
Related: https://dev.azure.com/msazure/AzureRedHatOpenShift/_workitems/edit/12932704
This is a requirement driven by Microsoft
N/A
N/A
> Enable SBOM on all OneBranch pipelines

- README.md
- cmd/aro/operator.go
- pkg/api/defaults.go
- pkg/operator/controllers/const.go
- pkg/operator/controllers/imageconfig/image_controller.go
- pkg/operator/controllers/imageconfig/image_controller_test.go
Signed-off-by: Karan.Magdani <kmagdani@redhat.com>
Fixes https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/9947373/
This PR introduces a controller that checks changes to image.config & ensures that required registries are not blocked.
Added Unit tests. In my opinion if E2E is required it can be covered as a separate PR
N/A?
> imageconfig controller

- pkg/deploy/devconfig.go
Fixes https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/13111550/
(ref #1917 point 3)
Properly generates ACR domain names for fluentbit based on [other configuration](https://github.com/Azure/ARO-RP/blob/master/docs/deploy-full-rp-service-in-dev.md#deploying-an-int-like-development-rp)
N/A - local dev configuration file
N/A
> Fixing bug where incorrect ACR domain name was being generated

- .pipelines/build-and-push-images-tagged.yml
Fixes
existing service connection does not meet requirement
for the github release
> fix: fix service connection to the github

- .pipelines/build-and-push-images-tagged.yml
> ADO Pipelines make no sense

- .pipelines/build-and-push-images-tagged.yml
Fixes ADO pipeline issue with Makefile recursive variable.  
Fix tagged pipelines
Run and see if it works.
no
> Ensure TAG environment var is consistent case

- .pipelines/int-release-tag.yml
- .pipelines/prod-release-tag.yml
- .pipelines/templates/template-job-deploy-azure-env-tag.yml
Fixes incorrect directory path for template references in pipelines.  
pipelines won't work without this.  
Run it
no
> Update correct directory path for pipeline template files

- .github/CODEOWNERS
> add fl to owners :-)

- cmd/aro/operator.go
- pkg/operator/controllers/imageconfig/image_controller.go
- pkg/operator/controllers/imageconfig/image_controller_test.go
Followup PR for remaining feedback from #1766 (some of the comments are hidden by GitHub UI).
This PR itself is mostly about improving unit tests. Better coverage added for one case in `getCloudAwareRegistries`.
No, just bug fixes and test improvements.
> Follow up PR on image config controller feedback

- .pipelines/prod-release-tag.yml
Fixes N/A
Adds norwaywest to the tagged pipeline.
Norwaywest was missing from the pipeline due to merge order (branch was split before norwaywest was rolled out).
Not applicable.
> Adding norwaywest to deploy from tag Pipeline.

- .pipelines/deploy-azure-env-tag.yml
- .pipelines/prod-release-tag.yml
Fixes prod single region release pipeline
$Title
Run it as a one-off
N/A
> Include variable groups for prod single region release

- .pipelines/mirror-aro-to-int.yml
> fix: provide the correct dependent pipeline

- .pipelines/mirror-aro-to-int.yml
> fix: replace parameter with variable

- pkg/api/error.go
None, just came across it when I was reading the code
Fixes
CloudErrorsCodes are not changing (at least not during runtime), so making
them const prevents from accidentally modifying them at runtime.
It should be covered by exisiting tests. 
No
> Changed CloudErrorCodes from vars to consts.

- docs/deploy-development-rp.md
> Fix typo in deploy-development-rp doc

- docs/prepare-your-dev-environment.md
* Removes mention of Python virtualenv as it comes by default with Python 3
* Updates macOS docs to make sure that steps work for Intel and ARM macs
* Markdown formatting fixes
> Updates dev env docs

- pkg/api/openshiftcluster.go
fix a wrong path in the comments
Fixes
> updated path to quota file

- pkg/api/validate/dynamic/quota.go
This is a redesign of the quota computations, which was absolutely horrendous. 
Fixes
Was not a really good design 
Should be covered by existing tests. If tests pass it should have kept the same behavior. 
No
> redesigned the quota computation to something understandable

- test/e2e/fips.go
Fixes 12385409
This PR updates FIPs e2e test to use the 2022-04-01 API.  The e2e test will retrieve the cluster document with the new API and check if FIPs is enabled or disabled.  Then it will assert the expected machine configs are either present or absent.
- Are there integration/e2e tests? yes
No
> Update FIPs e2e test for 2022-04-01 API

- pkg/util/cluster/cluster.go
Cluster creation process after the API release
> Cluster create after api 2022-04-01

- .github/CODEOWNERS
Should be fairly self-explanatory :)
> Add David Newman to CODEOWNERS

- docs/deploy-full-rp-service-in-dev.md
Clarifies and re-orders some items in the doc.
- Adds additional notes
- Reorders mirroring step before keyvault step
- Removes redundant `deploy your cluster` section
- Fixes `Create the cluster` section
> Add improvements to `deploy-full-rp-service-in-dev.md` doc

- docs/keyvaults.md
Documents our keyvault production usage as well as what is contained within each keyvault and why. 
N/A - documentation only
> Add documentation outlining our keyvaults, certificates, and secrets

- .pipelines/e2e-with-billing-all-regions.yml
- .pipelines/prod-release-tag.yml
- .pipelines/prod-release.yml
Work items per region:
- [australiacentral](https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/14209523)
- [australiacentral2](https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/14209565)
- [swedencentral](https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/14216349)
Part of the [new region rollout](https://msazure.visualstudio.com/AzureRedHatOpenShift/_wiki/wikis/ARO.wiki/59387/New-region-rollout?anchor=update-rp-pipelines) process.
N/A : This is a pipeline change.
Yes - see process documentation and work items above.
> Add new ARO regions to pipelines

- .pipelines/templates/template-prod-e2e-steps.yml
Fixes https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/14638167
Fix typo in E2E pipeline script.
CI pipeline should pass.
No docs update needed.
> Typo in pipeline script

- docs/deploy-development-rp.md
It is better to explicitly call out CLUSTER=<cluster-name>, as in the azure portal we see dev clusters created with
name `cluster`.
> Minor change in deploy-dev-rp.md

- pkg/cluster/gatewayprivateendpoint.go
Update gateway arm template deployment name and log message
Fixes https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/14657615
existing unit/e2e, just minor text/string change
I am updating egress lockdown enabling wiki and this fix makes it more clear that the private endpoint was deployed
> Update gateway arm template deployment name and log message

- test/e2e/adminapi_cluster_getlogs.go
Hopefully fixes an e2e flake
Reduces flakiness
E2E test
N/A
> attempt to make getpodlogs e2e test a bit more reliable

- pkg/operator/controllers/muo/muo_controller.go
Fixes an issue found in M2 testing
Listens to changes in the pull secret so that when a RH pull secret is added, OCM connectivity is enabled.
Will have to manually test.
fix, N/A
> Listen to the pullsecret in the MUO Operator

- pkg/operator/deploy/deploy.go
- pkg/operator/deploy/deploy_test.go
- pkg/operator/deploy/staticresources/master/deployment.yaml.tmpl
- pkg/operator/deploy/staticresources/worker/deployment.yaml.tmpl
Improved the operator deployment process so we can use proper templating instead of custom  (needed for ocm pull secret validation). (needed for https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/13933226/)
Fixes
already covered by existing tests
> operator deployment improvement

- test/e2e/operator.go
helps debug a flake
E2E test
N/A
> Add some logging for the e2e cluster conditions check

- .sha256sum
- Makefile
- cmd/aro/rp.go
- pkg/api/v20220904/generate.go
- pkg/api/v20220904/openshiftcluster.go
- pkg/api/v20220904/openshiftcluster_convert.go
- pkg/api/v20220904/openshiftcluster_example.go
- pkg/api/v20220904/openshiftcluster_marshal.go
- pkg/api/v20220904/openshiftcluster_validatestatic.go
- pkg/api/v20220904/openshiftcluster_validatestatic_test.go
- pkg/api/v20220904/openshiftclusteradminkubeconfig.go
- pkg/api/v20220904/openshiftclusteradminkubeconfig_convert.go
- pkg/api/v20220904/openshiftclusteradminkubeconfig_example.go
- pkg/api/v20220904/openshiftclustercredentials.go
- pkg/api/v20220904/openshiftclustercredentials_convert.go
- pkg/api/v20220904/openshiftclustercredentials_example.go
- pkg/api/v20220904/register.go
- pkg/swagger/generator.go
- swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/stable/2022-09-04/examples/OpenShiftClusters_CreateOrUpdate.json
- swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/stable/2022-09-04/examples/OpenShiftClusters_Delete.json
- swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/stable/2022-09-04/examples/OpenShiftClusters_Get.json
- swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/stable/2022-09-04/examples/OpenShiftClusters_List.json
- swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/stable/2022-09-04/examples/OpenShiftClusters_ListAdminCredentials.json
- swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/stable/2022-09-04/examples/OpenShiftClusters_ListByResourceGroup.json
- swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/stable/2022-09-04/examples/OpenShiftClusters_ListCredentials.json
- swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/stable/2022-09-04/examples/OpenShiftClusters_Update.json
- swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/stable/2022-09-04/examples/Operations_List.json
- swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/stable/2022-09-04/redhatopenshift.json
Fixes https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/14904549
Creates the framework to be used for the new API version. Other developers can begin to use this and build upon it.
There is nothing net new in this PR (besides the API version), it is just a copy of our previous version
unit test, e2e
will communicate out to team
> New API Version

- pkg/installer/generateconfig.go
Fixes issue calling `m.doc` which doesn't exist, it is `m.oc` at this point resulting in ci failing right now
unit,ci,e2e
n/a
> Fix generateconfig

- pkg/hive/manager.go
Do not return an error when there is no cluster namespace in the Hive AKS cluster.
Code path is disabled at the moment. Existing E2E should indicate a regression, if any.
No. Small change in a disabled code.
> Hive cluster manager: do not error deletion on 404

- pkg/cluster/clusterserviceprincipal.go
Fixes name of deployment logged so it is more clear
> update deployment name/logged arm template deployed

- docs/deploy-development-rp.md
Added the curl call to redeploy VM of dev cluster
using local RP.
Fixes
> Doc: add step to Re-deploy VM of a dev cluster

- docs/deploy-development-rp.md
updates the docs to add CURL calls to start, Stop and
resize VM of a dev cluster using local-rp
> Doc: Add step to Stop/Start/resize for a dev cluster VM

- pkg/cluster/gatherlogs.go
- pkg/monitor/cluster/cluster.go
slight refactor to use of FriendlyName function
> slight refactor to use of FriendlyName function

- docs/prepare-a-shared-rp-development-environment.md
- hack/devtools/deploy-shared-env.sh
#2168 
Apply changes required for MS Graph.  These commands are currently failing because they refer to a now nonexistent field name.
Tested by rebuilding the local RP.  The rebuild was successful.
Docs update are included.
> Update changes required for Microsoft Graph

- docs/prepare-a-shared-rp-development-environment.md
Fixes the group name in our docs
The old group name was under the old tenant, we are now under a new tenant in our dev subscription
n/a
this is the docs
> docs: update aad group name

- .github/workflows/codeql-analysis.yml
- .github/workflows/codeql-config.yml
Reverts Azure/ARO-RP#2276
It didn't work. :(
> Revert "Add codeql configuration to prevent scanning vendor directory"

- pkg/frontend/adminactions/azureactions.go
Redeploying a VM with an ephemeral OS disk will result in a error message,
stating that the VM has an ephemeral OS disk and cannot be redeployed.
If a VM that has an ephemeral OS disk is redeployed it will never become ready,
due to the fact that the VM's OS is re-provisioned and
the cluster machine approver will not allow the "new" machine
to join the cluster again.
Fixes : https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/14751454/
> Prevent AdminAction redeploy if VM has an ephemeral OS disk

- pkg/monitor/cluster/podconditions.go
- vendor/k8s.io/kubernetes/pkg/kubelet/events/event.go
- vendor/modules.txt
Fixes https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/14233929/
> make monitor Ignore preempted completed pods

- pkg/util/restconfig/restconfig_test.go
While working on https://github.com/openshift/hive/pull/1817 I came up with a test wihch is very similar to what we need in RP codebase.
This PR add a new test
No, it is just a test
> Adds an unit test covering DialContext

- pkg/hive/manager.go
This enables unit testing with fake client-go clients
> Makes clusterManager use client interfaces (to enable unit testing)

- pkg/cluster/hive.go
- pkg/monitor/cluster/hiveregistrationstatus.go
> Fixes a typo in TODO(hive) comments

- pkg/cluster/delete.go
It is [User story 10295993](https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/10295993/)
Somewhen in the past, the ARO team decided to log every error that occur while deleting the resource group.
So now we have enough logs, and there are two kinds of errors we don't handle: 202 – context deadline exceeded; 409, it happened only once – Storage Account was in creating state somehow, so we got conflict status code.
Both cases are kinda cloud errors, therefore the result should be `500, InternalServerError`. 
So this PR does not change error handling logic, but logging has been deleted.
> stop loggin failed RG deletion

- pkg/cluster/hive_test.go
Fixes https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/14962351/
Unit testing
No. Tech debt.
> Add hive createnamespace tests

- hack/hive-generate-config.sh
[Work item 15033872](https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/15033872/)
New version includes support for log decoration with extra fields.
For more details see:
* https://github.com/Azure/ARO-RP/pull/2284
* https://github.com/openshift/hive/pull/1828
> Updates hive image

- pkg/cluster/storageaccounts.go
- pkg/operator/controllers/storageaccounts/storageaccounts.go
Fixes https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/14743726
N/A
N/A
> Fix panic on AdminUpdate for clusters with custom storage

- hack/clean/clean.go
> Cleanup hack/clean.go

- go.mod
- pkg/cluster/storageaccounts.go
An import went missing because git didn't flag anything :)
> Fix some drift from multiple merges

- docs/upstream-differences.md
N/A
Adds more clarity to docs.
> Updating docs for applying patches to installer-aro

- test/e2e/operator.go
Fixes e2e test failures in USGovCloud environments. [#15119913](https://msazure.visualstudio.com/AzureRedHatOpenShift/_boards/board/t/Chainsaw/Stories/?workitem=15119913)
Fixes a previously hard-coded string that was causing test failures.
Run test in USGovCloud environment. Test now re-implements cloud aware logic from controller so confidence is high that it will work correctly.
N/A
> re-implement cloud aware function for e2e test

- pkg/cluster/hive_test.go
https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/14962351/
unit tests for hiveEnsureResources
No
> added hiveEnsureResources unit tests

- pkg/cluster/hive_test.go
https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/14962351/
unit tests for hiveDeleteResources func
No
> Added hiveDeleteResources unit tests

- pkg/cluster/deploystorage.go
- pkg/cluster/deploystorage_test.go
Fixes [this](https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/15272241/)
Currently, if we PUCM a cluster with tags set on the cluster resource group, it will remove them.  We do allow tagging of the clsuter resource group, so we shouldn't be removing these.  
Unit tests & tested locally. 
no,
> Persist tags on ensureResourceGroup

- pkg/deploy/config.go
Fixes bug introduced by https://github.com/Azure/ARO-RP/pull/2266/files
Properly formats RSA public key format
Needs to be tested during ongoing INT deployments
No
> fixing private key formatting

- .github/workflows/ci-go.yml
- Dockerfile.ci
- hack/ci-utils/build.sh
- hack/git-utils/isClean.sh
https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/14705826/
Moves units tests to github actions so we can see the results without having to connect to wvd or a vm.
> added github action for go ci

- pkg/frontend/admin_openshiftcluster_redeployvm.go
- pkg/frontend/admin_openshiftcluster_startvm.go
- pkg/frontend/admin_openshiftcluster_stopvm.go
- pkg/frontend/admin_openshiftcluster_vmresize.go
- pkg/frontend/admin_openshiftcluster_vmsizelist.go
- pkg/frontend/admin_vm_actions.go
- pkg/frontend/frontend.go
Remove a  lot of repeated code in our VM actions.
Unit tests were already in place.
> DRY implementation to our admin_vm_actions

- .github/CODEOWNERS
Add's ARO team leads to OWNERS
> Add ARO Team leads to Owners

- pkg/util/liveconfig/dev.go
- pkg/util/liveconfig/hive.go
- pkg/util/liveconfig/manager.go
Fixes comments from https://github.com/Azure/ARO-RP/pull/2325
Addresses comments made from merged PR.
N/A
No.
> clean up naming in liveconfig

- pkg/util/namespace/namespace.go
- pkg/util/namespace/namespace_test.go
Signed-off-by: Karan <kmagdani@redhat.com>
No Work item, minor change
We should be able to view logs for openshift-cluster-version namespace. 
Unit test added
N/A
> include openshift-cluster-version in monitoring

- test/e2e/adminapi_drainnode.go
This PR addresses [Bug 15410721](https://dev.azure.com/msazure/AzureRedHatOpenShift/_workitems/edit/15410721) which resolves a recurring flake in the drain node E2E tests. For example - https://msazure.visualstudio.com/AzureRedHatOpenShift/_build/results?buildId=59442207&view=logs&j=3965c7ea-79de-5618-9d9a-42b627bfb354&t=4810cc2a-45e4-5107-9a11-ae0073a144ef 
This PR addresses a recurring "flake" in the drain node E2E tests - Tests will fail if there are only daemon set pods running on the target worker node, because the number of pods targeted for deletion will be 0.
The CI E2E tests that run for this PR will run the modified E2E test.
No - there is no explicit documentation for E2E tests.
> Drain Node E2E Test Fix

- pkg/cluster/cluster.go
- pkg/cluster/hive.go
- pkg/cluster/hive_test.go
- pkg/cluster/install.go
- pkg/hive/install.go
- pkg/hive/manager.go
- pkg/hive/manager_test.go
- pkg/hive/resources.go
- pkg/hive/resources_test.go
- pkg/util/liveconfig/dev.go
- pkg/util/liveconfig/hive.go
- pkg/util/liveconfig/manager.go
- pkg/util/mocks/hive/hive.go
- test/util/testliveconfig/liveconfig.go
Part of M5 work
Proof of concept for adding ClusterDocument to trigger the installer, currently a WIP and proof of concept
> [M5] Initial storage of ClusterDocument in Hive

- pkg/proxy/proxy.go
We were seeing panics in the gateway for some reasons. (see icm 331749411). 
fixes the panic
> added type cast success check in gateway proxy

- docs/deploy-development-rp.md
Corrected typo in the development guide, for a better reading experience.
Fixes a typo in the development guide.
Updates development guide
N/A
Updated GitHub Doc.
> [Doc] Corrected typo, Resize Master Node section

- .pipelines/e2e.yml
- docs/prepare-a-shared-rp-development-environment.md
- hack/devtools/deploy-shared-env.sh
- hack/e2e/run-rp-and-e2e.sh
- pkg/cluster/nsg.go
- pkg/deploy/assets/aks-development.json
- pkg/util/azureclient/mgmt/network/virtualnetworkpeerings.go
- pkg/util/azureclient/mgmt/network/virtualnetworkpeerings_addons.go
- pkg/util/cluster/cluster.go
- pkg/util/mocks/azureclient/mgmt/network/network.go
Signed-off-by: Karan <kmagdani@redhat.com>
Fixes https://dev.azure.com/msazure/AzureRedHatOpenShift/_boards/board/t/Chainsaw/Stories/?workitem=15123283
This PR enables VPN support on our CI-E2E Pipelines. The pipeline connects to a vpn before creating private clusters and  running end to end tests. This will facilitate running pipelines when SimplySecure V2 is enabled on our subscriptions
> CI E2E in SimplySecure

- hack/fakecluster/fakecluster.go
- hack/gendiscoverycache/gendiscoverycache.go
- hack/gendiscoverycache/main.go
- hack/genkey/genkey.go
- hack/licenses/main.go
- hack/tunnel/tunnel.go
- pkg/swagger/examples.go
- pkg/swagger/swagger.go
- test/e2e/adminapi.go
Follow up to #2414 to prepare for golangci-lint upgrade (https://go.dev/doc/go1.16#ioutil)
Also related to #2423
> ioutil removal

- cmd/aro/rp.go
- docs/feature-flags.md
- pkg/database/clustermanager.go
- pkg/deploy/devconfig.go
- pkg/env/env.go
- pkg/env/zz_generated_feature_enumer.go
- pkg/frontend/clustermanager_delete.go
- pkg/frontend/clustermanager_delete_test.go
- pkg/frontend/clustermanager_get.go
- pkg/frontend/clustermanager_get_test.go
- pkg/frontend/clustermanager_putorpatch.go
- pkg/frontend/clustermanager_putorpatch_test.go
- pkg/frontend/frontend.go
- pkg/frontend/frontend_test.go
- pkg/frontend/security_test.go
- pkg/frontend/shared_test.go
- pkg/util/arm/resources.go
- test/database/clustermanager.go
- test/database/fixtures.go
- test/database/inmemory.go
Fixes https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/15529572/
Building on #2332, add relevant test cases.
Make tests pass.
No
> Add unit tests for OCM frontend routes

- pkg/cluster/deploystorage.go
- pkg/cluster/deploystorage_test.go
Don't "GET" a resource group unless it already exists.  
Fixes TODO
https://github.com/Azure/ARO-RP/pull/2328/files#diff-fc2ecaea9c3fb03887bc89a5290dd452dc919a651168e73a3b3a83a25d8ff525R48
Test in prod because that's the only place to accurately test this.  We also need to PUCM an existing cluster to ensure we can still "GET" an existing resource group.
> workaround - FPSP Role Assignment Doesn't Have Get

- test/e2e/operator.go
Splits ARO operator E2Es into steps. This is helpful from several perspectives:
* Documenting what we do in our E2E tests
* Makes it bit easier to narrow down the area of failure
CI runs E2E
No, just E2E improvements
> Splits operator E2E tests into steps

- .github/workflows/golint.yml
- .golangci.yml
waiting on #2423
updates golangci-lint to a newer version.
> upgrade golangci-litn, removed deadcode linter, duplicate of unused

- test/e2e/aro.go
Refactors E2E test which verifies ARO attributes
E2E run
No, just E2E refactoring.
> Refactors E2E test which verifies ARO attributes

- test/e2e/aro.go
- test/e2e/fips.go
Follow up for https://github.com/Azure/ARO-RP/pull/2441#discussion_r990036871
Related to [WI 13667437](https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/13667437)
> Removes duplication in E2E

- docs/deploy-full-rp-service-in-dev.md
Fixes missing documentation
Adds missing documentation in the full-service RP doc
I ran it manually
these are the docs :shrug:
> Update docs for deploying the full-service RP in a dev environment :writing_hand: 

- test/e2e/adminapi.go
- test/e2e/adminapi_cluster_get.go
- test/e2e/adminapi_cluster_list.go
- test/e2e/adminapi_cluster_update.go
- test/e2e/adminapi_redeployvm.go
- test/e2e/adminapi_resources.go
Splits RP Admin API E2Es into steps (similar to #2441 and to #2430)
Run E2E
No, just E2E improvements
> Admin API E2E fixups

- .github/CODEOWNERS
> added facchettos to owners

- .github/CODEOWNERS
> add cadenmarchese to owners

- .github/workflows/ci-go.yml
- hack/ci-utils/isClean.sh
https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/12358638/
> added vendor check step

- test/e2e/setup.go
> Selenium fix

- .github/workflows/npm-audit.yml
- hack/github-actions/npm_audit.sh
[ADO CARD](https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/16018120)
Adds `npm audit` to portal v2 at minimal cost to time (~20s) or process per pull request to ensure that we are ALWAYS aware if our production facing admin portal contains vulnerabilities.
Created PR and tested GitHub Action.
No. Standard internal CI/CD implementation.
> Add npm audit GitHub Action for portal/v2

- test/e2e/setup.go
Removes an unused parameter and an unnecessary function in test/e2e/setup.go.
Tests already exist.
N/A
> remove unused param and unnecessary function in E2E setup

- python/az/aro/azext_aro/custom.py
[Work Item- Add Network Contributor permissions on az aro update](https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/14957600) 
Added network contributor to NAT gateway on az aro update.
> Add network contributor to NAT gateway

- .golangci.yml
- pkg/api/v20220401/openshiftcluster_example.go
- pkg/api/v20220904/openshiftcluster_example.go
- pkg/api/validate/dynamic/quota.go
- pkg/frontend/admin_openshiftcluster_vmresize_test.go
- pkg/frontend/openshiftversions_list.go
- pkg/monitor/cluster/arooperatorconditions.go
- pkg/monitor/cluster/machineconfigpool_test.go
- pkg/monitor/cluster/prometheusalerts.go
- pkg/monitor/worker.go
- pkg/util/conditions/condition.go
- pkg/util/keyvault/keyvault.go
- test/util/deterministicuuid/deterministicuuid.go
Adds a new linter which will ensure we don't use useless conversions which are making the code less clear
> added more linter

- Makefile
> bump fluentbit image version to latest in makefile

- .pipelines/e2e.yml
- Makefile
Part of [WI 13667437](https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/13667437/).
So we can see trends and more easily identify most frequently failing tests.
Run E2E pipeline
No, CI updates.
> Adds junit report to E2E

- .pipelines/ci.yml
Fixes CI so all other pipelines turn green
Allow CI to pass for everyone.
This PR - if CI passes we're good.
N/A
> Fix CI linting - install vendored binaries

- .pipelines/e2e.yml
> Fix kubeconfig var name

- pkg/hive/manager.go
- pkg/hive/manager_test.go
Fixes https://dev.azure.com/msazure/AzureRedHatOpenShift/_workitems/edit/15728844
Currently the Hive manager is only checking for `spec.Installed`, but this does not check for any failure conditions and results in all failures taking 60 minutes to return. This PR adds a single failure condition, Provision Failed, but scaffolding has been put in place making it trivial to add any additional error conditions in the future.
Tested cluster installation failure propagation in a dedicated RP instance.
No.
> Hive: exit if we enter ProvisionFailed status

- pkg/metrics/statsd/statsd.go
Modifies a comment updating a broken link to Microsoft docs.
N/A
N/A
> docs: update outdated statsd link

- test/e2e/setup.go
changes to that message weren't needed in #2495 
Fixes
> corrected message as it is used elsewhere too

- pkg/operator/controllers/checkers/clusterdnschecker/checker.go
- pkg/operator/controllers/checkers/internetchecker/checker.go
- pkg/operator/controllers/checkers/serviceprincipalchecker/checker.go
- pkg/operator/controllers/checkers/serviceprincipalchecker/checker_test.go
Addresses some feedback from #2584, #2588, #2589
> Follow up for checker controller split

- docs/monitoring.md
- pkg/backend/openshiftcluster.go
- pkg/monitor/worker.go
https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/12371799/
[Google doc](https://docs.google.com/document/d/1x6VPMWaD_hADHB3UOsksSwc7dJAuzbd5LhekFXgRXkc/edit?usp=sharing)
`docs/monitoring.md`
> Ensure monitor captures the deletion

- cmd/aro/mirror.go
Routine update
Bumps the synced version of MUO.
Should be fine, this gets the image synced for testing.
N/A
> Update to new MUO image

- .pipelines/onebranch/templates/template-buildrp-buildaro.yml
Fixes logic causing the pullrequest pipeline to fail
> Onebranch template-buildrp-buildaro: fix logic

- .pipelines/ci.yml
- .pipelines/templates/template-checkout.yml
Fixes https://issues.redhat.com/browse/ARO-1401 maybe
> Switch CI to running on 1ES

- pkg/frontend/asyncoperations.go
- pkg/frontend/clustermanager_get.go
- pkg/frontend/clustermanager_putorpatch.go
- pkg/frontend/openshiftcluster_delete.go
- pkg/frontend/openshiftcluster_putorpatch.go
Some light refactoring to decouple functions from `mux.Vars()` as we are going to remove gorilla 
some preparation work for https://issues.redhat.com/browse/ARO-1724
Fixes
> decoupling functions from mux.Vars() in frontend

- test/e2e/aks.go
- test/e2e/hive_manager.go
- test/e2e/setup.go
https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/15583619/
E2E tests for hive clusterManager in pkg/hive/manager.go
No
Tested manually. Checked that namespaces have been created and deleted.
> Test hive CreateNamespace in e2e

- python/az/aro/azext_aro/custom.py
https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/12670363/
> Keynotfound empty subnet sp rotation

- .pipelines/ci.yml
Amending #2624  to use the final pool
Should pass because it is tests :)
> Run CI on the 1es-aro-ci-pool pool

- pkg/dbtoken/refresher.go
Fixes https://issues.redhat.com/browse/ARO-1714
Small fix to a metric name that was added in previous release.
Just a rename to an unused metric. Nothing to test.
> fixed metric name for consistency

- cmd/aro/mirror.go
Need the Mariner container for #2520 
Updates image mirroring, adds Mariner
Shouldn't need any
N/A
> Bump image mirror tags

- .github/CODEOWNERS
> Add Ulrich Schlueter to  CODEOWNERS

- pkg/dbtoken/server.go
- pkg/dbtoken/server_test.go
this is part of the effort to get rid of the deprecated gorilla library
https://issues.redhat.com/browse/ARO-1731
Fixes
It should pass existing tests (bar the one that I modified because there is no segregation on methods in servemux)
> replaced deprecated gorilla with standard library

- .gitignore
- .pipelines/e2e.yml
- .pipelines/templates/template-push-images-to-acr.yml
- .pipelines/vars.yml
- Dockerfile.aro-e2e
- Makefile
- hack/ci-utils/extractaro.sh
- hack/e2e/run-rp-and-e2e.sh
- hack/get-admin-kubeconfig.sh
- pkg/hive/install.go
- pkg/proxy/dialer.go
- test/e2e/setup.go
Fixes https://issues.redhat.com/browse/ARO-1390
Ports E2E to use 1ES.
It is tests :) It might not work perfectly (e.g. when it crashes), but we can make incremental updates as needed.
N/A
> Migrate E2E to 1ES pool

- test/e2e/aks.go
Fixes
Provide updated list of regions without working AKS.
> Update the list of AKS denied regions

- test/e2e/setup.go
Fixes flag in https://github.com/Azure/ARO-RP/pull/2670
only run hive test in local development mode
> only run hive test in local development mode

- pkg/api/register.go
- pkg/frontend/asyncoperationresult_get.go
- pkg/frontend/clustermanager_delete.go
- pkg/frontend/clustermanager_get.go
- pkg/frontend/clustermanager_putorpatch.go
- pkg/frontend/clustermanager_type.go
- pkg/frontend/clustermanager_type_test.go
- pkg/frontend/frontend.go
- pkg/frontend/middleware/authenticated.go
- pkg/frontend/middleware/log.go
- pkg/frontend/middleware/metrics.go
- pkg/frontend/middleware/validate.go
- pkg/frontend/middleware/validate_test.go
- pkg/frontend/openshiftcluster_get.go
- pkg/frontend/openshiftcluster_list.go
- pkg/frontend/openshiftcluster_putorpatch.go
- pkg/frontend/openshiftclustercredentials_post.go
- pkg/frontend/openshiftclusterkubeconfigcredentials_post.go
- pkg/frontend/openshiftversions_list.go
- pkg/frontend/operations_get.go
https://issues.redhat.com/browse/ARO-1728 
this is a start to decouple the middlewares from gorilla, which is needed to remove it completely and replace it with another router
Fixes
> decoupled middlewares and frontend from gorilla for apiversion

- pkg/frontend/admin_openshiftcluster_approvecsr.go
- pkg/frontend/admin_openshiftcluster_cordonnode.go
- pkg/frontend/admin_openshiftcluster_drainnode.go
- pkg/frontend/admin_openshiftcluster_kubernetesobjects.go
- pkg/frontend/admin_openshiftcluster_kubernetespods_logs.go
- pkg/frontend/admin_openshiftcluster_reconcilefailednic.go
- pkg/frontend/admin_openshiftcluster_resources_list.go
- pkg/frontend/admin_openshiftcluster_serialconsole.go
- pkg/frontend/admin_openshiftcluster_upgrade.go
- pkg/frontend/admin_openshiftcluster_vmsizelist.go
- pkg/frontend/admin_vm_actions.go
- pkg/frontend/clustermanager_putorpatch.go
- pkg/frontend/openshiftcluster_applensdetectors.go
- pkg/frontend/openshiftcluster_get.go
- pkg/frontend/openshiftclustercredentials_post.go
cleaning up the frontend before gorilla deprecation
Fixes
> Frontend cleanup

- test/e2e/aks.go
Fixes a formatting discrepancy on master after running `make validate-go`
> fix formatting issue

- pkg/api/openshiftcluster.go
- pkg/api/validate/vm.go
https://issues.redhat.com/browse/ARO-1295
Fixes
Added new instance types.
refer: https://learn.microsoft.com/en-us/azure/openshift/support-policies-v4
> Added new instance type

- hack/hive-config/cluster-image-sets/4.10.15.yaml
- hack/hive-dev-install.sh
According to @darthhexx we don't use this CR, so I'm removing it so we don't confuse the team :rocket:
> Remove unused clusterimageset

- .github/workflows/ci-go.yml
- .github/workflows/golint.yml
- .pipelines/ci.yml
- .pipelines/onebranch/pipeline.buildrp.official.yml
- .pipelines/onebranch/pipeline.buildrp.pullrequest.yml
- Dockerfile.aro-e2e
- Dockerfile.aro-multistage
- Dockerfile.ci
- docs/prepare-a-shared-rp-development-environment.md
- docs/prepare-your-dev-environment.md
- docs/updating-dependencies.md
- go.mod
- hack/update-go-module-dependencies.sh
Fixes https://issues.redhat.com/browse/ARO-2127 
Update go to 1.18
> Update go version to 1.18

- pkg/operator/controllers/clusteroperatoraro/clusteroperatoraro_controller.go
Conflict indicates that we acted on a stale date. Abort reconciliation and requeue.
> Removes RetryOnConflict from operator controllers

- .github/CODEOWNERS
> Removes m1kola from CODEOWNERS

- pkg/portal/portal.go
cleans up the portal rest definition
Fixes
> portal rest clean up

- pkg/api/validate/dynamic/serviceprincipal_test.go
- pkg/util/clusterauthorizer/authorizer_test.go
Fixes a problem in our code golang-lint is erroring on . 
above 
let the CI run
> Fix code to make golang-lint happy 

- cmd/aro/update_ocp_versions.go
- pkg/util/version/const.go
Fixes
Adds 4.11 version to the aro update-versions.
> Add 4.11 latest version to update-version

- test/e2e/cluster.go
- test/e2e/disk_encryption.go
Fixes e2e tests when running against 4.11 clusters
default storage classes changed in 4.11, from managed-premium -> managed-csi.  This change checks the cluster version from the cluster document and sets the default storage class.
Ran e2e tests against 4.11 cluster.
No
> fix e2e tests when running against 4.11 clusters

- docs/adding-new-instance-types.md
Fixes
Outlines the process for adding new instance types to RP and testing the changes. Meant to improve our own ability to test and support new VM sizes and unify the knowledge a bit.
Adapted from an old PR (https://github.com/Azure/ARO-RP/pull/1751)
> New document for adding new instance types to RP

- docs/prepare-your-dev-environment.md
Fixes
Quick nit to add the extra steps needed to get a working dev setup on a RHEL box.
> add extra steps for RHEL machines

- pkg/portal/cluster_test.go
- pkg/portal/http_test.go
- pkg/portal/kubeconfig/kubeconfig.go
- pkg/portal/kubeconfig/kubeconfig_test.go
- pkg/portal/kubeconfig/proxy.go
- pkg/portal/kubeconfig/proxy_test.go
- pkg/portal/portal.go
- pkg/portal/prometheus/prometheus.go
- pkg/portal/prometheus/proxy.go
- pkg/portal/prometheus/proxy_test.go
- pkg/portal/regions_test.go
- pkg/portal/ssh/proxy.go
- pkg/portal/ssh/proxy_test.go
- pkg/portal/ssh/ssh.go
- pkg/portal/ssh/ssh_test.go
some rework of portal before removing gorilla
this centralizes the route definitions in the portal.go file instead of having some extra route definitions added to the routers from other packages. 
Fixes
> clean up of portal

- .pipelines/templates/template-clean-subscription.yml
> Fix Purge MSFT CI Subscription

- docs/disk-encryption-set.md
This option was removed in azure-cli 2.41.0, for more context see:
https://learn.microsoft.com/en-us/azure/key-vault/general/soft-delete-change
> remove --enable-soft-delete option

- pkg/api/validate/dynamic/dynamic.go
Additional logging for CheckAccess API (authz)
> New branch for addl checkAccess logging

- pkg/deploy/deploy.go
- pkg/deploy/vmsscleaner/clean.go
- pkg/deploy/vmsscleaner/clean_test.go
- pkg/util/azureclient/mgmt/compute/virtualmachinesscalesets_addons.go
- pkg/util/mocks/azureclient/mgmt/compute/compute.go
- pkg/util/mocks/vmsscleaner/vmsscleaner.go
this revert recent deploy changes as it may impact gateway availability and we need to make sure there will be no service interuption
Fixes
> Gateway deploy fix revert

- pkg/cluster/version.go
Fixes logical differences between frontend & backend handling the default version
We need to support the default version no matter what.  This is because if a customer does not specify a version, we set the default version.  So we cannot disable it as it would provide a poor experience.  
Create a default version cluster when a record for it does not exist in cosmosdb.  
Probably, but don't think we have existing documentation on this.
> Reconcile differences between frontend & backend default version behavior

- pkg/deploy/assets/aks-development.json
Fixes https://issues.redhat.com/browse/ARO-1947
Update K8s version in AKS-Dev template so shared env has same k8s version as production clusters.
Locally tested
No
> Update Kubernetes Version in AKS-Development template

- .pipelines/e2e.yml
- Makefile
Reverts Azure/ARO-RP#2796
Should fix an issue with our e2e pipelines. https://redhat-internal.slack.com/archives/C02ULBRS68M/p1680722136075439
> Revert "Update Makefile to not allow unset variables"

- pkg/deploy/assets/env-development.json
- pkg/deploy/generator/resources_dev.go
Uses a smaller dev proxy instance type for local development.  Cost savings yay
Deployed the instance type to dev.
> Update dev proxy instance type

- pkg/monitor/cluster/debugpods.go
- pkg/monitor/cluster/debugpods_test.go
https://issues.redhat.com/browse/ARO-2650
events `v1beta1` are being removed in kubernetes 1.25. This updates the events we are using in the debugpod monitor.  
Fixes
see above
existing tests should be passing still
> updated event version to v1 in debug pod monitor

- pkg/api/validate/vm.go
Came across this comment, updating it for a better reading experience
Fixes
updating for a better reading experience
N/A
> Nitpick update vm.go

- cmd/aro/mirror.go
Fixes an extra space
mirror it
negative
> removes extra space in hive image tag

- pkg/util/steps/refreshing.go
see https://redhat-internal.slack.com/archives/C02ULBRS68M/p1683248585884089 and #2896
Fixes
> fix refresher

- pkg/api/validate/dynamic/dynamic.go
- pkg/util/steps/refreshing.go
https://github.com/Azure/ARO-RP/pull/2896 but smaller
> Minimal refreshing for SP checks

- pkg/monitor/cluster/cluster.go
- pkg/monitor/cluster/nsgreconciliations.go
- pkg/operator/controllers/subnets/subnet_controller_test.go
- pkg/operator/controllers/subnets/subnet_nsg.go
- pkg/operator/controllers/subnets/subnets_controller.go
- test/e2e/operator.go
https://issues.redhat.com/browse/ARO-2113
We wanna have a metric that shows if the subnet nsg controller is in the infinite loop. You can find more details in the JIRA ticket description.
E2Es (are updated in this PR)
> Capture subnet reconciliations

- pkg/api/validate/dynamic/dynamic.go
Fixes incorrect reporting of lack of resource provider permissions due to not waiting for ARM to replicate role assignments.
e2e
> Update timeout on check permissions to >5 min for ARM RA cache

- pkg/util/clusterdata/worker_profile_test.go
https://issues.redhat.com/browse/ARO-2739
Refactored the existing tests for worker profile enrichment so that the tests are more legible and maintainable.
test-go
No documentation needs to be updated for this PR as the code was refactored.
> Worker profiles enrichment refactored tests

- pkg/frontend/admin_supportedvmsizes_list_test.go
Jira: https://issues.redhat.com/browse/ARO-2883
> Test cases for GA SupportedVMSizes

- pkg/api/validate/vm.go
Fixes a typo identified by @niontive
> Fix VMSize bug introduced in #2713

- Dockerfile.guardrails
- Makefile
JIRA: https://issues.redhat.com/browse/ARO-2392
> Guardrails image Dockerfile

- pkg/deploy/assets/rp-production.json
- pkg/deploy/generator/templates_rp.go
Fixes a deployment issue where the checkAccess RP config var isn't set resulting in the deployment failing.  
Deploy to FF INT
No
> Set a default value for checkaccess

- pkg/frontend/adminactions/azureactions.go
- pkg/util/azureclient/applens/applens.go
- pkg/util/azureclient/applens/applens_client.go
- pkg/util/azureclient/applens/applens_client_test.go
- pkg/util/azureclient/applens/applens_detector_request_options.go
https://issues.redhat.com/browse/ARO-1756
Changed AppLens code to wrap response in required ARM envelope
> Wrap AppLens resp in required envelope

- pkg/env/armhelper.go
Our local development workflow lays down a role assignment on creation of the cluster resource group to mimic ARM's magical [S2S Resource Group Scoped Authorization](https://armwiki.azurewebsites.net/rbac/authorization/ResourceGroupScopedServicetoServiceAuthorization.html?q=s2s)  
We no longer use client secret in this, so continue using certificate based credentials to lay down this role assignment for development mode.  
Remove stale/old code.  
E2e will cover everything
nope
> Remove AZURE_ARM_CLIENT_SECRET helper 

- .github/CODEOWNERS
added myself to codeowners as per discussed
NA
NA
NA
> added myself to codeowners

- .github/CODEOWNERS
> Adding myself to code owners

- .pipelines/e2e.yml
- Makefile
- hack/e2e/run-rp-and-e2e.sh
- test/e2e/admin_portal.go
- test/e2e/setup.go
> Run the admin portal e2e in podman

- pkg/backend/openshiftcluster.go
- pkg/util/log/log.go
JIRA: https://issues.redhat.com/browse/ARO-3309
Fixes
> Add field ClusterDeploymentNamespace in ServiceLogs

- cmd/aro/update_ocp_versions.go
Small followup to https://github.com/Azure/ARO-RP/pull/3009 to address a nit called out in code review.
Split off a new function so the environment variable name `INSTALLER_IMAGE_DIGESTS` only has to be specified once.
[[ARO-3523] Move the ARO-Installer Image Digests to RP-Config](https://issues.redhat.com/browse/ARO-3523)
> update_ocp_versions: Code cleanup

- pkg/operator/controllers/dnsmasq/cluster_controller.go
- pkg/operator/controllers/dnsmasq/cluster_controller_test.go
jira: https://issues.redhat.com/browse/ARO-3186
Fixes
> Propagate errors of ARO DNSMasqCluster controller to ARO Operator

- .pipelines/e2e.yml
- hack/get-admin-kubeconfig.sh
Fixes the CI must-gather - a continuation of https://github.com/Azure/ARO-RP/pull/3038
> Fix e2e must gather

- pkg/util/clusterdata/clusterdata.go
- pkg/util/clusterdata/clusterdata_test.go
setdefault was forgotten during the redesign of the enrichers
Fixes
> added setdefault

- .pipelines/ci.yml
- .pipelines/onebranch/pipeline.buildrp.official.yml
- .pipelines/onebranch/templates/template-buildrp-buildaro.yml
Attempted fix for [ARO-3957](https://issues.redhat.com/browse/ARO-3957)
Uses CodeQL3000 OneBranch tasks instead of custom CodeQL step
TBD
No
> Use CodeQL3000 tasks in OneBranch pipeline

- pkg/cluster/acrtoken.go
Fixes https://issues.redhat.com/browse/ARO-3897
Currently, the RegistryProfile in the cluster doc, which stores the original ACR token credentials, is left unchanged when we run PUCM to rotate the ACR token. Because of this, a incomplete PUCM or OperatorUpdate will overwrite the new token password in the cluster with the old one, and depending on that old password's validity, can break clusters from pulling from our prod ACR until another full PUCM is run.
This PR patches the cluster doc with the new RegistryProfile before continuing on to rotate the token in-cluster.
Steps taken to test:
- Added a quick hack to print the token password on GetCluster (we don't currently return it):
```
if oc.Properties.RegistryProfiles != nil {
out.Properties.RegistryProfiles = make([]RegistryProfile, …
```
> Update RegistryProfile with new ACR token password once rotated

- pkg/deploy/predeploy.go
Jira - https://issues.redhat.com/browse/ARO-3999
Fixes 
Includes a aro-portal and aro-monitor restart in the predeploy steps
Tested the change(restart) by creating a full RP
No
> add aro-monitor and aro-portal restart to predeploy steps

- pkg/cluster/loadbalancerprofile_test.go
Fixes N/A
Fixes a discovered flake around the tests for load balancer profiles.
The test `managed ip cleanup errors are propagated when cleanup fails` deletes two load balancers using gomock. This action order is not guaranteed, so the error messages can be either order. (ie: uuid1 and then uuid2, or uuid2 and then uuid1)
Unit tests were updated to be less flaky.
No, test flake clean up.
> Reduce flakes in TestLoadBalancerProfile()

- python/az/aro/azext_aro/__init__.py
- python/az/aro/azext_aro/_aad.py
- python/az/aro/azext_aro/_client_factory.py
- python/az/aro/azext_aro/_dynamic_validators.py
- python/az/aro/azext_aro/_params.py
- python/az/aro/azext_aro/_validators.py
- python/az/aro/azext_aro/custom.py
N/A
Small, nitpicky changes to our `az aro` extension code to better align it with upstream and reduce the diffs between the two
Ensure everything works as expected (no functionality changes should be present as a part of this)
AzureCLI extension and upstreaming documentation pages will need to reduce/change the documented diffs within them
> Reduce diffs between our `az aro` extension and the upstream Azure CLI command

- pkg/frontend/validate.go
- pkg/frontend/validate_test.go
Fixes https://issues.redhat.com/browse/ARO-4245
> add group for metrics to allow for top nodes to exectute

- docs/prepare-your-dev-environment.md
Fixes: N/A - doc improvement
Add required packages for debian based dev setup.
Doc update
> Add required debian packages to docs

- pkg/frontend/admin_openshiftcluster_etcdcertificaterenew.go
- pkg/frontend/admin_openshiftcluster_etcdcertificaterenew_test.go
- pkg/frontend/frontend.go
JIRA: https://issues.redhat.com/browse/ARO-3989
KCS[1]: https://access.redhat.com/solutions/7025431
The Geneva Action applies the KCS[1] with extra validations and tries recovery incase of issue.
Fixes
> GenevaAction for etcd Certificate Renewal

- .pipelines/e2e.yml
- test/e2e/admin_portal.go
- test/e2e/setup.go
Fixes the e2e failures happening because of the admin portal
> Get to the bottom of the e2e admin portal failure

- pkg/frontend/admin_openshiftcluster_kubernetesobjects_test.go
None
Adds additional unit tests to the admin API to ensure that we validate we don't allow access to customer objects on get/create/update/delete k8s objects so that we don't regress these functions in the future.
No
> Add customer data regression tests for get/create/update/delete k8s admin api

- docs/operators.md
- docs/prepare-your-dev-environment.md
N/A
This PR updates the documentation around the operator and Fedora 37. I found some issues with the docs while creating a new controller for ARO-3112.
N/A
No. This is to update the developer docs. 😄
> Update documentation for testing the ARO operator

- pkg/util/azureclient/mgmt/redhatopenshift/2023-07-01-preview/redhatopenshift/openshiftclusters.go
- pkg/util/azureclient/mgmt/redhatopenshift/2023-07-01-preview/redhatopenshift/openshiftclusters_addons.go
- pkg/util/azureclient/mgmt/redhatopenshift/2023-07-01-preview/redhatopenshift/operations.go
- pkg/util/azureclient/mgmt/redhatopenshift/2023-07-01-preview/redhatopenshift/operations_addons.go
- test/e2e/setup.go
- test/e2e/update.go
Fixes https://issues.redhat.com/browse/ARO-4178
This PR adds e2e tests for increasing and decreasing load balancer managed outbound IPs
e2e tests
N/A
> Add e2e tests for multiple ips per loadbalancer

- pkg/cluster/install.go
https://issues.redhat.com/browse/ARO-4404
A long discussion is here https://redhat-internal.slack.com/archives/C02ULBRS68M/p1697570801196159?thread_ts=1695641115.974799&cid=C02ULBRS68M
None
None
> Additional Waiting for API Server to become ready

- .github/CODEOWNERS
> removed facchettos from codeowners

- pkg/deploy/assets/aks-development.json
- python/az/aro/azext_aro/_params.py
Fixes: 
- https://issues.redhat.com/browse/ARO-4576
- https://issues.redhat.com/browse/ARO-4514
- Update the aro-rp az aro extension (_params.py) with defaults
- Update K8s version in development.
- Existing E2E tests
No
> Add defaults and update k8s dev version

- pkg/monitor/cluster/arooperatorconditions.go
- pkg/monitor/cluster/arooperatorconditions_test.go
- pkg/monitor/cluster/clusteroperatorconditions.go
- pkg/monitor/cluster/prometheusalerts.go
Fixes https://issues.redhat.com/browse/ARO-4187
Cleans up a significant amount of useless metrics from the monitor.
Added some tests
N/A
> Clean up some of the monitor emitting metrics 

- docs/deploy-development-rp.md
Fixes [ARO-2718](https://issues.redhat.com/browse/ARO-2718)
This Pull Request updates our development RP documentation to include the Etcd Recovery admin endpoint.
NA
ADO Documentation has been updated.
- Updated
- https://msazure.visualstudio.com/AzureRedHatOpenShift/_wiki/wikis/ARO.wiki/253699/Replace-a-Master-Node-VM
- https://msazure.visualstudio.com/AzureRedHatOpenShift/_wiki/wikis/ARO.wiki/64663/Current-known-and-outstanding-issues?anchor=apiserver-errors-due-to-broken-etcd
- New Documents
- https://msazure.visualstudio.com/AzureRedHatOpenShift/_wiki/wikis/ARO.wiki/610309/Etcd-Recovery-Single-Master-Etcd-Recovery-Standard-Operating-Procedure?anchor=overview
> Update RP Documentatation with Etcd Recovery URL

- .github/workflows/ci-go.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/golint.yml
- .golangci.yml
- pkg/cluster/loadbalancerprofile_test.go
- pkg/containerinstall/install_test.go
- pkg/dbtoken/server.go
- pkg/metrics/statsd/metrics.go
- pkg/monitor/cluster/podconditions_test.go
- pkg/portal/cluster_test.go
- pkg/portal/regions_test.go
- pkg/portal/security_test.go
- pkg/util/arm/types.go
- pkg/util/dynamichelper/dynamichelper_test.go
- pkg/util/installer/certs.go
- pkg/util/pem/pem_test.go
- pkg/util/pullsecret/extract_test.go
- test/e2e/admin_portal.go
- test/e2e/adminapi_drainnode.go
- test/e2e/adminapi_redeployvm.go
- test/e2e/disk_encryption.go
- test/e2e/list.go
- test/e2e/monitor.go
- test/e2e/operations.go
- test/e2e/operator.go
- test/e2e/update.go
- test/util/kubeadminkubeconfig/kubetoken.go
mostly just some little nits that annoy me :)
CI
cleanups
> Add some more golangci-lint linters and fix the issues they find

- pkg/operator/controllers/genevalogging/const.go
- pkg/operator/controllers/genevalogging/genevalogging_test.go
- pkg/operator/controllers/genevalogging/staticfiles/fluent.conf
- pkg/operator/controllers/genevalogging/staticfiles/parsers.conf
Small cleanup, non-functional change
Wrote some tests to double check I didn't break anything
N/A
> Move genevalogging operator controller files into separate .confs with goembed

- pkg/util/graph/adapter.go
workaround an issue with gzip that has shown up again
run CI
> disable gzip compression as a workaround

- pkg/monitor/azure/nsg/nsg.go
- pkg/monitor/azure/nsg/nsg_test.go
Fixes the comments mentioned in #3324 
Refactoring the logic to address the comments mentioned in the original PR.
Unit tests. 
No.
> Refactoring per comments in #3324

- Makefile
- docs/shared-cluster.md
- hack/clean/clean.go
- hack/shared-cluster.sh
When replacing the shared-cluster I noticed that we have some scripts and docs related to the shared-cluster that are stale now.
This PR just tidies up the secrets around the shared-cluster.
I could recreate the shared-cluster to test it but I think it's probably okay.
Note:
I don't have access to a B-account so there might be some style guides etc that I'm missing so get pedantic and let me know if there's anything like that ;)
> Update shared cluster usage

- pkg/cluster/condition.go
- pkg/cluster/condition_test.go
Small PR to remove an some old code and its tests that aren't being used anywhere anymore. I just spotted it while doing something else.
> Remove unused old code

- cmd/aro/mirror.go
Fixes [ARO-5059](https://issues.redhat.com/browse/ARO-5059)
Fixes
1. Removes quay.io/app-sre/hive:9dd47f8bfa
1. Adds quay.io/app-sre/hive:5fbe0d158ba9
E2E tests
N/A
> Mirror hive revender images

- pkg/api/v20230701preview/openshiftcluster_validatestatic.go
- pkg/api/v20231122/openshiftcluster_validatestatic.go
Follow-up nit fixes for [ARO-5484](https://issues.redhat.com/browse/ARO-5484)
Simplifies architecture version handling in API static validation for multiple public IPs-releases (20231122 and 20230701preview)
- Unit tests continue to pass 
No
> Follow-up fixes from #3406

- pkg/cluster/deploybaseresources.go
- pkg/cluster/deploybaseresources_test.go
- pkg/cluster/install.go
- pkg/util/steps/refreshing.go
fixes a thing I encountered trying to do local testing
Makes the NSG attaching code robust to authentication failures as well as the "not ready" bug
fixes local dev for me
N/A
> Fix failures provisioning a cluster in dev due to NSG attaching

- hack/shared-cluster.sh
This PR contains:
- a small fix I had to do when rebuilding the shared cluster
- some extra log lines I added
TODO:
> Fix shared_cluster.sh

- pkg/backend/openshiftcluster.go
- pkg/frontend/frontend.go
- pkg/util/log/log.go
- pkg/util/log/log_test.go
This PR is a small refactor that comes out of a pairing session with myself and @sankur-codes. The originating PR is [here](https://github.com/Azure/ARO-RP/pull/3396).
I've added some unit tests.
Nope
> Refactor result type

- pkg/backend/openshiftcluster.go
- pkg/frontend/frontend.go
- pkg/util/log/log.go
- pkg/util/log/log_test.go
Reverts Azure/ARO-RP#3410.
Mistake spotted. I'll open a new PR to update the tests and then a subsequent PR to implement this refactor again
> Revert "Refactor result type"

- pkg/util/azureclient/environments.go
Urgent update the AppLens tenant.
AppLens will be enforcing AAD Auth in AME on March 13th.
N/A -- Config update.
N/A
> Update applens tenant

- test/e2e/helpers.go
This is a small PR to improve the readability of E2E test output by using the GinkgoHelper(). I noticed this feature while doing https://issues.redhat.com/browse/ARO-5321. The details are [here](https://onsi.github.io/ginkgo/#the-offset-decorator) but the tl;dr is we get more informative/clearer stack traces if there is an error in the helpers.
The current E2E tests.
Is there any documentation that needs to be updated for this PR?
No. I think having this in the existing helpers is enough documentation.
> Add the GinkgoHelper

- portal/v2/package-lock.json
This PR is the result of running `npm audit fix` locally. This was done after seeing errors in the `npm-audit-fix` job in 2 PRs [here](https://github.com/Azure/ARO-RP/actions/runs/8293190421/job/22695825917?pr=3427#logs) and [here](https://github.com/Azure/ARO-RP/actions/runs/8286146606/job/22675462452?pr=3458)
> Run npm audit fix

- cmd/aro/mirror.go
Fixes
https://issues.redhat.com/browse/ARO-6456
The logs from the mirroring command are huge. Ev2 pipelines and Ev2 Portal trim the output from the mirroring command and errors mirroring images at the beginning of the execution are lost and not observable.
The mirroring function doesn't immediately fail and return an error if an image cannot be mirrored, it just prints it in the log. This is by design, to continue mirroring any other remaining images without returning if there is a failure.
However, if one or more images fail to be mirrored, we just return a "failed to mirror" error to the calling function, instead of a collection of failed images/errors. The log is trimmed by Ev2 due to its big size, and we lose visibility of what failed.
Ev2 pipeline is currently failing and we can't …
> Return image mirroring errors to calling function

- pkg/backend/openshiftcluster.go
- pkg/backend/openshiftcluster_test.go
- pkg/frontend/frontend.go
- pkg/util/log/log.go
- pkg/util/log/log_test.go
This PR is a small refactor that comes out of a pairing session with myself and @sankur-codes. The originating PR is [here](https://github.com/Azure/ARO-RP/pull/3396).
I've added some unit tests.
Nope
> Refactor the ResultType

- pkg/util/steps/runner.go
- pkg/util/steps/runner_test.go
Fixes
https://issues.redhat.com/browse/ARO-5325
Propagate error to user.
Updated runner_test.go 
No, tech debt.
Unit test.
> ARO-5325: Propagate install error to user

- .github/CODEOWNERS
> remove dofinn from codeowners

- Makefile
> Update MARINER_VERSION to 20240425

- hack/shared-cluster.sh
Small PR that just fixes the application of the tag
> Correctly wrap bash assignment

- docs/prepare-your-dev-environment.md
ENV var ARO_PODMAN_SOCKET is incorrect in docs/prepare-your-dev-environment.md
remove a forward slash in ENV var ARO_PODMAN_SOCKET
I tested to create a dev cluster
N/A
N/A
> remove a forward slash in ENV var ARO_PODMAN_SOCKET

- cmd/aro/mirror.go
- go.mod
- go.sum
- vendor/github.com/go-logr/logr/README.md
- vendor/github.com/go-logr/logr/funcr/funcr.go
- vendor/modules.txt
[ARO-5062](https://issues.redhat.com/browse/ARO-5062)
Fixes
Keep Hive updated to mitigate vulnerabilities.
@slawande2 has tested this by creating a cluster with this hive commit in a full service dev rp environment.
Updated [ARO Wiki](https://msazure.visualstudio.com/AzureRedHatOpenShift/_wiki/wikis/ARO.wiki/635070/Hive-Deploy-ARO-Pipelines) with `make ci-rp` step.
Cluster creation during E2E of Hive deployment will ensure hive functions.
> Revender hive to commit d7ead609f495785360aeea7c318f28fe82f9bcbf

- pkg/cluster/loadbalancerprofile.go
- pkg/cluster/loadbalancerprofile_test.go
- pkg/util/uuid/fake/fake_uuid.go
- pkg/validate/openshiftcluster_validatedynamic.go
Fixes https://issues.redhat.com/browse/ARO-5251
Follow up for PR #3095
- Change dynamic validation to use FP SP
- Refactors IP Creation/Deletion and adds concurrency to create/update, IPs are now deleted and created in parallel which speeds up the update process. 
E2E tests
Existing unit tests
No
> Multi ip per load balancer followup 

- pkg/deploy/assets/aks-development.json
While trying to deploy AKS on step 8 as mentioned in https://github.com/Azure/ARO-RP/blob/master/docs/deploy-full-rp-service-in-dev.md, I got an error from the default Kubernetes version which is not supported (and not modified in run time).
**The suggested fix is a workaround.**
Fixes a possible bug when using `deploy_aks_dev` function from _hack/devtools/deploy-shared-env.sh_
Update the default Kubernetes version as it was asked by the `deploy_aks_dev` function from _hack/devtools/deploy-shared-env.sh_. 
Error :
```
➜  ARO-RP git:(master) deploy_aks_dev
########## Deploying aks-development in RG root-aro-eastus ##########
ERROR: {"code": "InvalidTemplateDeployment", "message": "The template deployment 'aks-development' is not valid according to the validation procedure. The tracking id …
```
> Use newer default Kubernetes version

- hack/devtools/msi.sh
> Add script to create mock MSI object

- docs/deploy-full-rp-service-in-dev.md
n/a
Adds doc on how to rotate certificates on a vnet gateway created as part of the full RP env setup. I've had to do it a few times so I figured it would be useful to document it upstream.
n/a, docs issue.
> Add doc on rotating full RP env VPN certs

- hack/devtools/platform_msi.sh
> Assign federated credential role to cluster msi

- pkg/frontend/openshiftcluster_preflightvalidation.go
Fixes CI failures on https://github.com/Azure/ARO-RP/actions/runs/9992357721/job/27617159964
> Fix missing database refactor on preflight validation in frontend

- Makefile
- test/e2e/ocp_cluster.go
- test/e2e/setup.go
Fixes https://issues.redhat.com/browse/ARO-7343, https://issues.redhat.com/browse/ARO-7344, https://issues.redhat.com/browse/ARO-7351.
This PR automates some of smoke tests which we always run when we release the new OCP version installer or gap analysis.
With this change, we can run smoke tests by running `E2E_LABEL=smoke make test-e2e`.
Run locally to check the functionality.
Run e2e to confirm that this test doesn't interfere the existing e2e tests. 
Run locally.
Run e2e on CI.
> Smoke test automation for some basic checks

- python/az/aro/azext_aro/__init__.py
- python/az/aro/azext_aro/_aad.py
- python/az/aro/azext_aro/_actions.py
- python/az/aro/azext_aro/_client_factory.py
- python/az/aro/azext_aro/_dynamic_validators.py
- python/az/aro/azext_aro/_params.py
- python/az/aro/azext_aro/_rbac.py
- python/az/aro/azext_aro/_validators.py
- python/az/aro/azext_aro/azext_metadata.json
- python/az/aro/azext_aro/commands.py
- python/az/aro/azext_aro/custom.py
- python/az/aro/azext_aro/tests/latest/unit/test_validators.py
- python/az/aro/setup.py
Fixes [ARO-6453](https://issues.redhat.com/browse/ARO-6453)
Fixes [ARO-4398](https://issues.redhat.com/browse/ARO-4398)
Implements functionality into the `az aro` extension to allow creating ARO clusters with a set of managed identities, instead of a service principal. 
As a consequence, this PR also includes changes to update the version of the `az aro` extension, as well as changes to upgrade the used ARO SDK/API to v20240812preview. 
- Example invocation:
```sh
az aro create \
--subscription ${SUBSCRIPTION_ID} \
--resource-group ${CLUSTER_RESOURCE_GROUP} \
--name azcli-testcluster \
--version 4.14.16 
--vnet aro-vnet --master-subnet master-subnet --worker-subnet worker-subnet \ 
--enable-managed-identity \
--assign-platform-workload-identity foo asdf \ …
```
> WI/MI CLI Phase 1 - Base API functionality

- docs/deploy-development-rp.md
- hack/devtools/local_dev_env.sh
- hack/devtools/msi.sh
Fixes https://issues.redhat.com/browse/ARO-8986
Create a service principal for local development so we can mock cluster MSI
Local testing
Yes
> Add scripts for creating and persisting mock cluster MSI

- test/e2e/helpers.go
- test/e2e/ocp_machine.go
Fixes https://issues.redhat.com/browse/ARO-7349
This PR adds test checking if it can scale up and down machine, and newly created node is available.
Running `E2E_LABEL=smoke make test-e2e` locally
no
This is a test. not production feature.
> Add machine scaling smoke test

- test/e2e/ocp_loadbalancer.go
- test/e2e/setup.go
- test/e2e/static_resources/loadbalancer.yaml
- test/util/dynamic/dynamic.go
- vendor/k8s.io/client-go/discovery/cached/memory/memcache.go
- vendor/modules.txt
Fixes https://issues.redhat.com/browse/ARO-7350
This PR adds the test checking whether it can create a load balancer and the service is reachable.
Run `E2E_LABEL=smoke make test-e2e` locally.
N/A
This is a test. not production feature.
> Add load balancer smoke test

- docs/deploy-development-rp.md
Small PR that just adds a note on using `oc` with a dev cluster. AFAIK this is institutional knowledge but I'm writing it down.
> Add note on using oc with dev clusters

- pkg/backend/openshiftcluster.go
This is to ensure EndLease always gets called, including cases when a panic is encountered.
[ARO-9241](https://issues.redhat.com/browse/ARO-9241)
Fixes
In the event that a panic occurs within `endLease()`, we want to ensure that `ocb.dbOpenShiftClusters.EndLease()` is always called.
Run a local RP and induce a panic during a cluster operation.
No.
Local testing.
> Add panic recovery within endLease

- docs/deploy-development-rp.md
- docs/hive.md
1. Minor document mistake, updated duplicate **australiaeast** value with **eastus**
2. Removed **$**, if someone copy and run it directly. Gives an error `bash: $: command not found`
No JIRA created for this
None
None
None
> Minor document changes

- test/e2e/static_resources/loadbalancer.yaml
Fixes https://issues.redhat.com/browse/ARO-7350
This is a followup of #3717 .
Apparently the image `nginx` is not compliant to MSFT security advisory.
https://msazure.visualstudio.com/AzureRedHatOpenShift/_build/results?buildId=99367257&view=logs&j=10f66467-59e5-53bc-0c8a-42cc89770de4&t=22254a09-0937-5b6f-413f-542ad48300e2&l=28
I followed the warning and modified tests accordingly.
Run tests locally.
N/A
Check CI status.
> change load balancer image in smoke test

- docs/testing.md
Fixes part of https://issues.redhat.com/browse/ARO-6771
This PR adds document about how to run smoke tests.
doc fix, N/A
doc fix, N/A
doc fix, N/A
> Add smoke tests doc

- docs/testing.md
Fixes https://issues.redhat.com/browse/ARO-7341 https://issues.redhat.com/browse/ARO-8847
This PR adds documents about how to run e2e tests to private clusters and upgraded clusters.
I tested them locally.
This is a doc update.
This is about how to test and not a production function.
> add smoke test documents

- pkg/backend/backend.go
- pkg/backend/openshiftcluster.go
- pkg/backend/openshiftcluster_test.go
Fixes https://issues.redhat.com/browse/ARO-9966
Test time comparisons:
- before: ✓  pkg/backend (20.075s)
- after: ✓  pkg/backend (79ms)
make unit-test-go
N/A
No code changes, just a refactor to make code testable.
> Fix slow tests in /pkg/backend

- .pipelines/ci.yml
- Makefile
- docs/admin-portal.md
Fixes feedback/concerns raised by the wider ARO team.
Loki is committed to enhancing our build and release process by moving local testing and validation closer to a production-like state. While we believe this approach will effectively address current issues, we respect individual preferences and will not mandate its use. Loki will continue to elevate our CI and containerized builds, ensuring top-tier local execution. Our CI/CD roadmap will continue to focus on containerized builds and validation for both PR validation and production builds, because our current architecture runs containers in production as defined in these build processes.
TL;DR - you now need to opt into the new, containerized build process locally. There is a clear distinction and naming consistency between local …
> Separate Makefile targets for local vs containerized

- Dockerfile.ci-rp
Minor change replaced as with AS
Fixing warning message `WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 8)`
None
None
None
> Docker file change replace as with AS

- docs/deploy-development-rp.md
- docs/prepare-your-dev-environment.md
Steps to resolve known/often issues when deploying dev RP environments.
Consolidate and visibility of resolutions resolution steps.
> Steps to resolve recurrent issues

- .pipelines/onebranch/templates/template-buildrp-buildaro.yml
Fixes an oversight in #3719 
Makes the build work again, hopefully
Build pipeline fixes, so the build pipeline should be able to test for it
N/A
N/A
> Fix make aro build in onebranch

- .pipelines/clean-subscription.yml
- .pipelines/templates/template-clean-subscription.yml
Fixes subscription cleaning that was broken in #3719
> Fix cleaning the gratis subscription

- .github/CODEOWNERS
> Add fahlmant as code owner

- pkg/api/admin/openshiftcluster.go
- pkg/api/openshiftcluster.go
- pkg/api/validate/vm.go
Addresses requests made in https://issues.redhat.com/browse/ARO-7187 and https://issues.redhat.com/browse/ARO-7816
Fixes
Provides DDS Family SKU support for control planes
<!--
Local testing and resizing was accepted by the cluster, but will need more validation based on this PR. 
Yes, we need to update our supported SKUs publicly if accepted.
Resize target is available and successful
> adding DDS family sku support

- cmd/aro/rp.go
- docs/deploy-development-rp.md
- pkg/backend/backend.go
- pkg/backend/openshiftcluster_test.go
> Clean up unused contexts

- cmd/aro/update_role_sets.go
Fixes No Jira
Similarly to https://github.com/Azure/ARO-RP/pull/3648/files, update update_role_sets to not use master key / AEAD auth and use database.NewDatabaseClientFromEnv instead.
Tested it with a local RP + go run ./cmd/aro update-role-sets to confirm the role sets are updated in cosmosdb.
> Update cosmosdb auth used by update_role_sets.go

- pkg/cluster/correct_cert_issuer.go
- pkg/cluster/delete.go
- pkg/cluster/tls.go
Uses constants / functions where possible.  
Making a change in one place should update it everywhere.  
CI/E2e
no
🙏
> Use constant / function names everywhere possible

- README.md
No JIRA for this task
Added/Updated new useful links as suggested and discussed on [#forum-aro](https://redhat-internal.slack.com/archives/CCV9YF9PD/p1724822722034539
)
None
None
None
> Updated Useful Links section

- pkg/api/admin/openshiftcluster.go
Hotfix.
Details are here: https://redhat-internal.slack.com/archives/C07UY4A7HM1/p1730882723923239
> Make PreconfiguredNSG mutable

- docs/deploy-development-rp.md
add reminder that dev clusters don't show up in ARM
> add reminder that dev clusters don't show up in ARM

- cmd/aro/mirror.go
- pkg/cluster/deploybaseresources_additional_test.go
> Fix image syncing

- pkg/util/steps/runner.go
- pkg/util/steps/runner_test.go
Fixes https://issues.redhat.com/browse/ARO-12795
This PR adds error handling from MSGraph, so that it can return meaningful error message to users.
When the application is deleted just before the cluster creation, it gets `error status code received from the API`.
By adding the error handling, it returns 400 error with the error message from MSGraph.
Reproducible code is in https://github.com/Azure/ARO-RP/tree/temp/aro-12792 . Running the hack script will reproduce the issue.
Running the hack script in https://github.com/Azure/ARO-RP/tree/temp/aro-12792.
unit test
N/A
Running the hack script in https://github.com/Azure/ARO-RP/tree/temp/aro-12792.
> [ARO-12792] Fix CIF - ServerError - error status code received from the API

- pkg/util/keyvault/keyvault.go
- pkg/util/keyvault/keyvault_test.go
Part of [ARO-11589](https://issues.redhat.com/browse/ARO-11589)
This PR makes the error from keyvault more structurized and easy to debug.
This will be useful to investigate the error from keyvault, and think about the error handling.
Sometimes even though the certificate operation is in progress, polling the certificate operation fails. 
It fails when it gets error from internal certificate issuer service, in that case the keyvault API returns the certificate operation object, but its status is failed. 
This may be a retryable error (e.g. 429 error), and we should handle this properly, but with the current log, we're not sure which fields should be used to identify if it is retryable or not.
This is the error:
```
step [Action pkg/cluster.(*manager).createCertificates] encountered error: …
```
> [ARO-11589] Dump keyvault certificate error

- docs/deploy-development-rp.md
n/a
Add two closing curly braces to a `curl` command in a code block.
Submit the `curl` command against a local RP.
n/a
Documentation changes should not affect code running in production.
> fix typo in curl snippet

- .github/CODEOWNERS
I (Ace) have recently become FL for Firefly. Adding myself as codeowner as is appropriate.
> Adding ankur as codeowner

- pkg/frontend/openshiftcluster_putorpatch_test.go
https://issues.redhat.com/browse/ARO-12033
This is a follow-up on #4046 that adds a unit test case for a MIWI admin update. Note that it still doesn't fully test the changes from #4046 - we'll want an E2E test case later.
The PR is a test :D
N/A
N/A
> Add unit test case for admin PATCH-ing a workload identity cluster

- .github/workflows/ci-go.yml
- .golangci.yml
- pkg/operator/deploy/deploy.go
Fixes broken golanglint
CI is green
Fixing the linter error should result in no functional difference, e2e should pass and that should be considered sufficient.
Dev docs may need updating
CI is green or has linting failures, not failure to execute the job.
> Fixes: broken ci-go linting, and the error the linter compained about

- hack/aead/aead.go
- hack/db/db.go
- pkg/cluster/apply.go
- pkg/cluster/correct_cert_issuer.go
- pkg/cluster/correct_cert_issuer_test.go
- pkg/cluster/delete.go
- pkg/cluster/graph/manager_test.go
- pkg/cluster/tls.go
- pkg/env/armhelper.go
- pkg/env/certificateRefresher.go
- pkg/env/certificateRefresher_test.go
- pkg/env/env.go
- pkg/env/prod.go
- pkg/frontend/frontend.go
- pkg/frontend/security_test.go
- pkg/frontend/shared_test.go
- pkg/util/azureclient/azuresdk/azcertificates/helpers.go
- pkg/util/azureclient/azuresdk/azsecrets/client.go
- pkg/util/encryption/azure.go
- pkg/util/encryption/multi.go
- pkg/util/mocks/azureclient/azuresdk/azsecrets/azsecrets.go
- pkg/util/mocks/env/env.go
- pkg/util/tls/tls.go
https://issues.redhat.com/browse/ARO-4669
> *: migrate more keyvault & certificates to track2

- .github/CODEOWNERS
Fixes ARO-11774
Adding Haoran Wang as an owner to the repository
> Add Haoran Wang as an owner

- test/e2e/operator.go
Fixes [ARO-15917](https://issues.redhat.com/browse/ARO-15917)
Removes the `updatedObjects` check from the `ARO Operator - Geneva Logging` E2E test, which attempts to ensure the operator only modifies the desired number of objects. This check is a source of flakiness in the E2E suite, as it depends on scraping the ARO Operator's logs to check what objects were reported as updated/created. 
As this was the only remaining callsite of the `updatedObjects` check, this PR also removes it entirely. In the future, if we want to ensure the operator does not make any undesired changes, we should maintain explicit "operator retains desired state" checks to ensure the state of ARO Operator-managed resources is as expected, rather than scraping operator logs to ensure specific actions were logged as …
> Remove updated objects diff check from MDSD Daemonset E2E test

- cmd/aro/mirror.go
Part of ARO-16076
Bump MUO image to be mirrored.
N/A
N/A
N/A
> [ARO-16076] Bump version of MUO

- docs/prepare-your-dev-environment.md
https://issues.redhat.com/browse/ARO-16272
* Clearer structure and formatting using visual blocks like > [!NOTE], > [!TIP], > [!IMPORTANT], > [!WARNING]
* Greater emphasis on containerized development as the recommended path
* More consistent and standardized section naming
* Restructured document to follow the process in succession (prior to this steps were mis-ordered as dependencies)
* Expanded installation steps for Go and Python (with emphasis on pyenv) and tooling
* `pyenv` instructions show steps to install required version regardless of users current version (contained to the ARO-RP repo directory)
* Clearer and cleaner instructions surrounding docker/podman
* OS specific section moved to bottom and linked throughout where needed
* Expanded instructions for each OS, prior to this …
> Re-structured, expanded and cleaned prepare-your-dev-environment doc

- pkg/cluster/ipaddresses.go
Fixes [ARO-12540 Migrate mgmt/network in createAPIServerPrivateEndpoint](https://issues.redhat.com/browse/ARO-12540)
Tech debt.
Covered in UT, tested locally, will run /azp run e2e
Negative.
> ARO-12540: Migrate to armnetwork in createAPIServerPrivateEndpoint

- pkg/operator/controllers/guardrails/policies/gktemplates-src/aro-deny-privileged-namespace/src_test.rego
Fixes ARO-17017
remove the exposed pull secret
the change is constrained to the test file only
NA
NA
> remove exposed pull secret

- pkg/env/msiauthorizer.go
- pkg/util/azureclient/environments.go
Fixes ARO-15999 , maybe
Allows the RP to use Workload Identity for authentication.
Manual testing at the moment.
N/A
Needs to be manually tested.
> [ARO-15999] Initial stab at using workload identity

- pkg/frontend/adminactions/azureactions.go
- pkg/frontend/adminactions/reconcilefailednic.go
- pkg/frontend/adminactions/reconcilefailednic_test.go
Fixes https://issues.redhat.com/browse/ARO-12532
tech debt
Unit tests were amended and are passing, will run e2e in PR.
tech debt
N/A
> ARO-12532: Migrate mgmt/network in NICReconcileFailedState

- pkg/deploy/deploy.go
- pkg/deploy/deploy_rp.go
Fixes [ARO-12535](https://issues.redhat.com/browse/ARO-12535)
Tech debt
NA
NA, tech debt
No difference in logic, covered in e2e
> ARO-12535: Migrate mgmt/network in Deploy (RP)

- pkg/deploy/deploy_rp.go
Fixes [a linter error](https://github.com/Azure/ARO-RP/actions/runs/15757707594/job/44416781490?pr=4033)
Will be covered in linter and e2e
NA
Test coverage
> Remove embedded PublicIPAddress field when getting IP addresses

- pkg/api/openshiftcluster.go
- pkg/cluster/cluster.go
- pkg/cluster/deploybaseresources_additional.go
- pkg/cluster/deploybaseresources_additional_test.go
- pkg/cluster/deploybaseresources_test.go
- pkg/cluster/install.go
- pkg/cluster/ipaddresses_test.go
- pkg/cluster/validate.go
- pkg/cluster/validate_test.go
- pkg/env/env.go
- pkg/env/zz_generated_feature_enumer.go
- pkg/util/azurezones/azurezones.go
- pkg/util/azurezones/azurezones_test.go
Fixes ARO-17460
Initial pass at provisioning the PIPs with zonal support for zonal redundancy.
Will require manual testing as well as CI.
Yes, likely customer facing documentation.
Manual testing should suffice, and then the cluster install success rates.
> [ARO-17460] Support zonal IPs in cluster creation

- .github/CODEOWNERS
Adding myself and Benson, removing @petrkotas (cause he's not part of aro anymore)
> Add mrWinston and Benson to and remote petr from CODEOWNERS

- pkg/api/openshiftcluster.go
- pkg/cluster/validate.go
- pkg/cluster/validate_test.go
- pkg/util/azurezones/azurezones.go
- pkg/util/azurezones/azurezones_test.go
Fixes ARO-20038
Fixes a regression from #4228 
Unit tests, E2E
N/A
Identified difference in API between prod and the mocks pre-test, so this should now reflect reality
> [ARO-20038] Fix zone checking and creation code

- hack/stress/staticresources/deployment.yaml
- hack/stress/staticresources/namespace.yaml
- hack/stress/stress.go
- pkg/monitor/cluster/certificateexpirationstatuses_test.go
- pkg/monitor/cluster/cluster.go
- pkg/monitor/cluster/daemonsetstatuses.go
- pkg/monitor/cluster/daemonsetstatuses_test.go
- pkg/monitor/cluster/deploymentstatuses.go
- pkg/monitor/cluster/deploymentstatuses_test.go
- pkg/monitor/cluster/jobconditions.go
- pkg/monitor/cluster/jobconditions_test.go
- pkg/monitor/cluster/managednamespaces.go
- pkg/monitor/cluster/managednamespaces_test.go
- pkg/monitor/cluster/podconditions.go
- pkg/monitor/cluster/podconditions_test.go
- pkg/monitor/cluster/replicasetstatuses.go
- pkg/monitor/cluster/replicasetstatuses_test.go
- pkg/monitor/cluster/statefulsetstatuses.go
- pkg/monitor/cluster/statefulsetstatuses_test.go
Fixes ARO-20197
Reduces the memory usage of the monitor by avoiding querying more than we need, and by querying in smaller batches.
Unit tests, E2E, INT?
N/A
Unsure :)
> [ARO-20197] Reduce memory usage of the Monitor

- pkg/cluster/fixssh.go
Fixes https://issues.redhat.com/browse/ARO-20877
Fixes a bug introduced in the last release that causes AdminUpdate to fail for UDR clusters during the fixssh AdminUpdate step.
This adds a check for UDR clusters and stops processing before reaching the code that checks the external load balancer, which is what is causing an error for UDR clusters since the external load balancer does not exist for UDR clusters.
To be tested in Canary.
N/A
> [ARO-20877] Update FixSSH Admin Step To Fix Bug For UDR Clusters

- pkg/util/cluster/cluster.go
Fixes ARO-20778
Follow up to #4354 
The previous PR deleted failed clusters immediately after they failed. We collect diagnostics of failed clusters, these won't work if we delete the failed cluster too soon. This PR changes the deletion to only happen immediately before retry, allowing the final failure to be deleted later after diagnostics are collected.
> Reorder the cluster retry logic to preserve the final failed cluster

- pkg/util/azureclient/mgmt/redhatopenshift/2024-08-12-preview/redhatopenshift/openshiftclusters.go
- pkg/util/azureclient/mgmt/redhatopenshift/2024-08-12-preview/redhatopenshift/operations.go
- pkg/util/azureclient/mgmt/redhatopenshift/2025-07-25/redhatopenshift/openshiftclusters.go
- pkg/util/azureclient/mgmt/redhatopenshift/2025-07-25/redhatopenshift/operations.go
Fixes several critical items identified in CodeQL
https://vnext.s360.msftcloudes.com/blades/security?blade=KPI:a0f0ce42-3063-5d3b-3b47-1ff3143abdc9~SLA:3~AssignedTo:AssignedToServices~Forums:All~Program:68556099-a3e2-472e-8da0-e1d1b000eda4;65a010a5-1e3d-4777-bb89-f149470a507d~waves:All~Tab:Summary~_loc:Security&peopleBasedNodes=weinongw_team&global=@WEINONGW%2BWeinong%20Wang%20(WEINONGW)&tile=S360_ServiceTreeServiceName:Azure%20Red%20Hat%20OpenShift~SecuritySeverity:Critical~_loc:__key__Security__a0f0ce42-3063-5d3b-3b47-1ff3143abdc9
> SFI(addresses several items identified in CodeQL)

- docs/deploy-full-rp-service-in-dev.md
No JIRA
Updated Fluent-bit version in documentation
None
None
None
> Fluent-bit version update in document
